#!/usr/bin/env bash
# Regenerate cases/11-intl-shipped.js from the browser's own Intl prelude.
#
# The bare engine has no Intl at all, so cases/09-intl-clone.js measures the
# ENGINE and says nothing about the browser. The browser installs
# c/apps/browser/js_intl.c's INTL_PRELUDE, and THAT is what a page meets. This
# lifts those exact bytes out of the C source and prepends them to the same
# questions, so the shipped formatter gets compared to node like everything
# else. js_intl.c's own header says it is "an ENGLISH formatter wearing the
# Intl interface"; this measures how far the English half is right, which is
# the part a monolingual page depends on.
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
OUT="$HERE/cases/11-intl-shipped.js"

{
  echo "// GENERATED by tests/jssem/gen-intl-case.sh -- DO NOT EDIT."
  echo "// Body: tests/jssem/intl-shipped-body.js"
  echo "// Prelude: c/apps/browser/js_intl.c INTL_PRELUDE, verbatim."
  echo "("
  python3 "$HERE/extract-prelude.py" "$ROOT/c/apps/browser/js_intl.c" INTL_PRELUDE
  echo ")();"
  cat "$HERE/intl-shipped-body.js"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
