/* SPDX-License-Identifier: MIT */
#include "sema/internal.h"
#include "runtime/capability_bits.h"
#include "../../../../include/abi/logit_abi.h"

/* The LogitOS ABI is target data even when the compiler runs on macOS. Never
 * use host syscall numbers here. Keeping this translation unit independent
 * of legacy/vm.h also lets the no-VM frontend link prove the old engine is unused. */
/* Every offset fsroot/as/lib/abi.as hands to layout(), asserted against the real
 * struct by the compiler that builds this file. Both halves are generated by
 * tools/gen_abi.py, so the numbers the script uses are the target compiler's
 * opinion of the layout rather than the generator's arithmetic -- a kernel
 * struct that moves a field fails the build instead of leaving a script reading
 * the wrong bytes.
 *
 * It was legacy/abi_layout.inc, included by legacy/builtins.c, until the A2
 * engine was deleted. Kept rather than deleted with it, because abi.as is an A3
 * library and still carries those offsets. It belongs on the COMPILER side: the
 * runtime is copied into a toolchain sysroot and built with a narrow -I set that
 * does not reach include/abi, so putting it in runtime/system.c broke 137 gates
 * with 'logit_abi.h' file not found. constants.c already includes that header by
 * an explicit relative path, for the same reason.
 *
 * At FILE scope, not inside at_check_system_constant(): system_constants.def
 * below is included in the middle of an array initializer, and an earlier
 * attempt put these declarations there with it. */
#include "abi_layout.inc"

int at_check_system_constant(AtNode *node)
{
    static const struct {
        const char *name;
        int64_t value;
    } constants[] = {

#define AS_SYSTEM_CONSTANT(name, value) {#name, value},
#include "common/system_constants.def"

#undef AS_SYSTEM_CONSTANT
    };

    for (unsigned index = 0; index < sizeof constants / sizeof constants[0]; index++) {
        if (at_scope_name_equal(node->token, constants[index].name)) {
            node->kind = AN_CONSTANT;
            node->integer = (uint64_t)constants[index].value;
            return 1;
        }
    }
    return 0;
}
