# Audio CODEC test targets (c/lib/audio: WAV, FLAC, MP3).
#
# A separate fragment from tests/audio.mk on purpose. That one belongs to the
# sound-driver line (the PCM layer, the mixer, /bin/sndtest); this one belongs
# to the decoders that feed it, and the two are developed independently. Kept
# out of the shared Makefile for the reason tests/nic.mk gives: several agents
# edit it at once and a shared-file edit cannot be committed without swallowing
# theirs. Every target here is prefixed test-audio-codec-* or named after the
# format, so nothing collides with the driver line's test-audio-*.
#
# The Makefile pulls this in with one line:
#
#     -include tests/audio_codec.mk
#
# THE BAR DIFFERS BY FORMAT, ON PURPOSE, BECAUSE THE FORMATS DIFFER.
#
#   WAV and FLAC are exactly specified, so the bar is bit-exactness and the
#   tests assert equality with ffmpeg sample for sample -- no tolerance is
#   involved or allowed. FLAC additionally carries its OWN criterion: the MD5
#   of the original PCM, stored in STREAMINFO, which the decoder checks against
#   itself with no reference decoder present at all. That is the check that
#   also runs inside the guest.
#
#   MP3 reconstructs through an IMDCT and a polyphase filter bank in floating
#   point, and ISO/IEC 11172-3 does not define a bit pattern for the output.
#   Claiming bit-exactness for it would be claiming a property the format does
#   not have. ISO/IEC 11172-4 instead defines conformance as a bound on the
#   difference from a reference decoder, and test-mp3 measures against the
#   full-accuracy bound (RMS < 2^-15/sqrt(12), peak <= 2^-15, full scale 1.0)
#   using ffmpeg's mp3float as the reference. That is a differential, not a run
#   of the official ISO conformance bitstreams -- those are not
#   redistributable and are not present here -- and the test says so in its
#   own output rather than letting the distinction get lost.
#
# The corpus is generated by ffmpeg into $(BUILD) on every fresh build
# directory rather than committed, so a fixture cannot rot into agreement with
# a bug. Those targets need ffmpeg; test-audio-codec-units and
# test-audio-codec-fuzz do not.

.PHONY: test-audio-codecs test-audio-codec-units test-audio-codec-fuzz \
        test-audio-codec-negctl test-audio-codec-os test-wav test-flac test-mp3

AUDIO_CODEC_SRC := c/lib/audio/audio.c c/lib/audio/wav.c c/lib/audio/flac.c \
                   c/lib/audio/mp3.c c/lib/audio/amd5.c
AUDIO_REF       := $(BUILD)/audioref
AUDIO_STAMP     := $(AUDIO_REF)/.stamp-v5

$(AUDIO_STAMP): tests/unit/audio_gen.sh
	@bash tests/unit/audio_gen.sh $(AUDIO_REF)

# Per-module tests: the bit reader, the from-scratch cube root and 2^(e/4),
# every Huffman codebook (Kraft-complete, prefix-free, round-tripping), both
# IMDCTs against the direct formula, and the synthesis filter bank against the
# literal ISO decoder flow AND against the property it exists for -- that
# subband k passes band k and rejects everything else. A whole-file test says
# something is wrong; these say what. Needs no ffmpeg and no corpus.
test-audio-codec-units:
	@mkdir -p $(BUILD)
	@$(CC) -O2 -Wall -Wextra -Ic/lib/audio -o $(BUILD)/audio_units \
	    tests/unit/audio_units_test.c -lm
	@$(BUILD)/audio_units

# WAV at every bit depth it supports, the header writer, format sniffing by
# content rather than by file name, and the pull interface at five buffer sizes
# for all three formats -- because "decode the whole file" and "decode it 37
# frames at a time" are different code paths and a player only uses the second.
test-wav: test-audio-codec-units $(AUDIO_STAMP)
	@$(CC) -O2 -Wall -Wextra -Ic/lib/audio -o $(BUILD)/audio_test \
	    tests/unit/audio_test.c $(AUDIO_CODEC_SRC)
	@$(BUILD)/audio_test $(AUDIO_REF)

test-flac: $(AUDIO_STAMP)
	@$(CC) -O2 -Wall -Wextra -Ic/lib/audio -o $(BUILD)/flac_test \
	    tests/unit/flac_test.c c/lib/audio/flac.c c/lib/audio/amd5.c
	@$(BUILD)/flac_test $(AUDIO_REF)

test-mp3: $(AUDIO_STAMP)
	@$(CC) -O2 -Wall -Wextra -Ic/lib/audio -o $(BUILD)/mp3_test \
	    tests/unit/mp3_test.c c/lib/audio/mp3.c -lm
	@$(BUILD)/mp3_test $(AUDIO_REF)

# Audio arrives over the network and off removable disks, so every length,
# count and bit depth in it is a claim by a stranger that this code turns into
# an allocation size or an array subscript. Four phases: corrupted real files,
# structurally hostile headers, uniform noise, and the properties that must
# hold even on garbage (bounded writes, determinism, no leaks).
#   make test-audio-codec-fuzz SCALE=40 SEED=0x1234    goes deeper
#
# -fno-sanitize-recover=all is not decoration. UBSan's DEFAULT is to print the
# diagnostic and CARRY ON, so a signed overflow or a misaligned load would be
# reported on stderr and the harness would still exit 0 and print its own
# "no sanitizer report" line -- a gate that reports the opposite of what it
# found. With -fno-sanitize-recover the first UB aborts the process, which is
# the only way that line can be true. halt_on_error=1 does the same for ASan's
# few recoverable classes, and abort_on_error makes the exit status unambiguous.
SCALE ?= 6
SEED  ?= 0x243F6A8885A308D3
ASAN_FLAGS := -fsanitize=address,undefined -fno-sanitize-recover=all \
              -fno-omit-frame-pointer
ASAN_ENV   := ASAN_OPTIONS=detect_leaks=1:halt_on_error=1:abort_on_error=0 \
              UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1

test-audio-codec-fuzz:
	@mkdir -p $(BUILD)
	@$(CC) -O1 -g $(ASAN_FLAGS) -w \
	    -Ic/lib/audio -o $(BUILD)/audio_fuzz tests/unit/audio_fuzz.c $(AUDIO_CODEC_SRC)
	@$(ASAN_ENV) $(BUILD)/audio_fuzz $(SCALE) $(SEED) tests/fixtures/audio

# A soak run over several seeds. Not part of test-audio-codecs -- it takes
# minutes, not seconds -- but it is what a "the parsers are fuzzed" claim
# should be able to point at.
#   make test-audio-codec-fuzz-deep SCALE=60
test-audio-codec-fuzz-deep:
	@mkdir -p $(BUILD)
	@$(CC) -O1 -g $(ASAN_FLAGS) -w \
	    -Ic/lib/audio -o $(BUILD)/audio_fuzz tests/unit/audio_fuzz.c $(AUDIO_CODEC_SRC)
	@for s in 0x243F6A8885A308D3 0x13198A2E03707344 0xA4093822299F31D0 \
	          0x082EFA98EC4E6C89 0x452821E638D01377; do \
	    echo "--- seed $$s ---"; \
	    $(ASAN_ENV) $(BUILD)/audio_fuzz $(SCALE) $$s tests/fixtures/audio || exit 1; \
	 done

# NEGATIVE CONTROL for the fuzzer itself. A fuzz target that has never caught
# anything is indistinguishable from one wired to /dev/null, and this one
# reports "no sanitizer report" in its own output -- so the sanitizers have to
# be shown to be live. -DAUDIO_FUZZ_SABOTAGE reintroduces a one-byte
# over-read in the WAV chunk walk (the exact bug class this fuzzer exists for).
# REQUIRED TO FAIL, and required to fail with an ASan report specifically.
test-audio-codec-fuzz-negctl:
	@mkdir -p $(BUILD)
	@$(CC) -O1 -g $(ASAN_FLAGS) -w -DAUDIO_FUZZ_SABOTAGE=1 \
	    -Ic/lib/audio -o $(BUILD)/audio_fuzz_neg tests/unit/audio_fuzz.c $(AUDIO_CODEC_SRC)
	@if $(ASAN_ENV) $(BUILD)/audio_fuzz_neg 2 $(SEED) tests/fixtures/audio \
	        >$(BUILD)/audio_fuzz_neg.log 2>&1; then \
	    echo "NEGCTL-FAIL: a deliberate out-of-bounds read in the WAV chunk walk"; \
	    echo "  did not trip the fuzzer -- the sanitizers are not doing anything."; \
	    exit 1; \
	 elif grep -q 'AddressSanitizer' $(BUILD)/audio_fuzz_neg.log; then \
	    echo "negctl: the injected WAV over-read is caught by AddressSanitizer"; \
	    grep -m1 'ERROR: AddressSanitizer' $(BUILD)/audio_fuzz_neg.log | sed 's/^/       /'; \
	 else \
	    echo "NEGCTL-FAIL: the sabotaged build failed, but not with an ASan report --"; \
	    echo "  so this proves the harness noticed, not that the sanitizer did."; \
	    head -20 $(BUILD)/audio_fuzz_neg.log | sed 's/^/       /'; exit 1; \
	 fi

# THE NEGATIVE CONTROL: a gate that never fails is not a gate. Two deliberate
# faults, each a real bug class, each behind a -DAUDIO_SABOTAGE that no
# shipping build defines: MP3 with alias reduction removed (which still sounds
# like music, which is exactly why "it played" proves nothing) and FLAC with
# the mid/side parity bit dropped (audibly perfect, and not lossless). Both
# gates MUST reject them.
test-audio-codec-negctl: $(AUDIO_STAMP)
	@$(CC) -O2 -w -DAUDIO_SABOTAGE=1 -Ic/lib/audio -o $(BUILD)/mp3_sabotage \
	    tests/unit/mp3_test.c c/lib/audio/mp3.c -lm
	@if $(BUILD)/mp3_sabotage $(AUDIO_REF) >$(BUILD)/mp3_sabotage.log 2>&1; then \
	    echo "NEGCTL-FAIL: the MP3 conformance gate passed a decoder with alias"; \
	    echo "  reduction disabled, so it is not measuring the decoder."; exit 1; \
	 else \
	    echo "negctl: MP3 without alias reduction is rejected ($$(grep -c '^FAIL' $(BUILD)/mp3_sabotage.log) failing checks)"; \
	 fi
	@$(CC) -O2 -w -DAUDIO_SABOTAGE=2 -Ic/lib/audio -o $(BUILD)/flac_sabotage \
	    tests/unit/flac_test.c c/lib/audio/flac.c c/lib/audio/amd5.c
	@if $(BUILD)/flac_sabotage $(AUDIO_REF) >$(BUILD)/flac_sabotage.log 2>&1; then \
	    echo "NEGCTL-FAIL: the FLAC gate passed a decoder that drops the mid/side"; \
	    echo "  parity bit, so neither the diff nor the MD5 check is working."; exit 1; \
	 else \
	    echo "negctl: FLAC without the mid/side parity bit is rejected by both the"; \
	    echo "        ffmpeg differential and the STREAMINFO MD5"; \
	 fi

# Everything host-side, in one target.
test-audio-codecs: test-wav test-flac test-mp3 test-audio-codec-fuzz \
                   test-audio-codec-negctl

# Does any of this work on LogitOS, or only under glibc? Boots the OS, runs
# /bin/audiocheck on the wav/flac/mp3 packed into the disk image, and requires
# every CRC32 to equal the one the HOST build of the same source prints. This
# is the audio counterpart of test-video, and the only test that exercises the
# decoders against mini-libc's allocator, the 24 MiB arena, and SSE enabled by
# boot code rather than by the host ABI.
$(BUILD)/audiocheck_host: c/apps/audio/audiocheck.c $(AUDIO_CODEC_SRC) \
                          $(wildcard c/lib/audio/*.h)
	@mkdir -p $(BUILD)
	@$(CC) -O2 -Wall -Wextra -Ic/lib/audio -o $@ c/apps/audio/audiocheck.c \
	    $(AUDIO_CODEC_SRC)

test-audio-codec-os: $(ISO) $(DISK) $(BUILD)/audiocheck_host
	@bash tests/boot/run-audio-test.sh $(ISO) $(DISK) $(BUILD)/audiocheck_host
