# --- JS engine semantics, differential against node --------------------------
#
# node is the ORACLE. Each case in tests/jssem/cases/ is a program that PRINTS;
# the two stdouts are diffed byte for byte. That is the c/apps/libc gate shape
# and its stated reason applies word for word here: it gives every operation a
# REFERENCE instead of a hand-written expectation that only records what its
# author already believed. A hand-written assertion about what toString(2)
# should do records a belief; a byte diff against node records the truth.
#
#   make test-jssem       host QuickJS, browser flags, vs node
#   make test-jssem-os    /bin/jssem ON THE MACHINE, the run that counts
#
# THE HOST BINARY IS NOT THE BROWSER. `test-jssem` links $(QJS_SRC) for
# arm64/darwin against the system libc; browser.aex links the same sources
# through $(JS_CF) for x86_64-elf against mini-libc with -DLOGIT_OS
# -DCONFIG_STACK_CHECK -DNDEBUG, and at least one intrinsic (Atomics) differs
# between those two engines already. So the host target here is the iteration
# loop and `test-jssem-os` is the evidence: /bin/jssem is linked from
# $(ENGINE_OBJ), the literal object files $(BUILD)/browser.elf links.
#
# NEITHER target installs queueMicrotask or structuredClone. Those live in
# c/apps/browser/js_platform.c, not in the engine, so a row here that says
# `structuredClone is not defined` is a fact about the bare engine and NOT a
# fact about the browser -- confirm that class in a page before repeating it.
# The same trap caught Intl: cases/09-intl-clone.js reports no Intl at all,
# which is true of the engine and FALSE of the browser, because
# c/apps/browser/js_intl.c installs a prelude. cases/11-intl-shipped.js is
# generated by gen-intl-case.sh, which lifts those exact bytes out of the C
# source and asks the same questions of them -- verbatim, because retyping the
# polyfill would measure a copy of it.
#
# cases/ is shared with another line's Proxy/descriptor cases. Both sets are
# plain files driven by the same runner and neither knows about the other.
#
# THE CONTROL is tests/jssem/cases/99-control.js and it is a control in the
# strict sense of rule 5: the harness gives the two sides a different value for
# one variable on purpose, so a run in which 99-control comes back SAME is a
# run in which the harness compared nothing, and run-objweak.sh says so and
# fails. Three neighbouring rows in the same file must still agree, which is
# what distinguishes "the control fired" from "everything differs".

JSSEM_DIR    := tests/jssem
JSSEM_CASES  := $(sort $(wildcard $(JSSEM_DIR)/cases/*.js))
JSSEM_PATHS  := $(foreach f,$(JSSEM_CASES),/jssem/$(notdir $(f)))

# --- host: the same QuickJS sources, the browser's -D set --------------------
$(BUILD)/js_sem_probe: tests/unit/js_sem_probe.c $(QJS_SRC)
	@mkdir -p $(BUILD)
	@$(CC) -O1 -w $(JS_INC) -DCONFIG_VERSION='"logit-2024"' \
	    -DLOGIT_OS -DCONFIG_STACK_CHECK -DNDEBUG -o $@ \
	    tests/unit/js_sem_probe.c $(QJS_SRC) -lm

test-jssem: $(BUILD)/js_sem_probe
	@bash $(JSSEM_DIR)/run-objweak.sh $(BUILD)/js_sem_probe $(BUILD)/jssem-out

# --- guest: /bin/jssem, linked from the browser's own engine objects ---------
JSSEM_PACK := $(BUILD)/jssem.aex:/bin/jssem \
              $(foreach f,$(JSSEM_CASES),$(f):/jssem/$(notdir $(f)))
$(DISK): $(BUILD)/jssem.aex $(JSSEM_CASES)

$(BUILD)/jssemobj/malloc_big.o: c/apps/libc/src/malloc.c
	@mkdir -p $(dir $@)
	$(CC) $(UCFLAGS) -DARENA_SIZE=67108864u -c $< -o $@

$(BUILD)/jssem.elf: $(ENGINE_OBJ) $(BUILD)/jsobj/tests/unit/js_sem_probe.o \
                    $(BUILD)/jssemobj/malloc_big.o $(APPDIR)/crt0_cli.asm
	@mkdir -p $(BUILD)/apps
	$(ASM) -f elf64 $(APPDIR)/crt0_cli.asm -o $(BUILD)/apps/jssem.crt0c.o
	$(LD) -nostdlib -e _start -Ttext=0x50000000 -o $@ --start-group \
	    $(BUILD)/apps/jssem.crt0c.o $(BUILD)/jsobj/tests/unit/js_sem_probe.o \
	    $(ENGINE_OBJ) $(BUILD)/jssemobj/malloc_big.o --end-group

$(BUILD)/jssem.aex: $(BUILD)/jssem.elf tools/mkaex.py
	python3 tools/mkaex.py $(BUILD)/jssem.elf $@ jssem - '?' 150 150 150

test-jssem-os: $(ISO) $(DISK)
	@bash $(JSSEM_DIR)/run-guest.sh $(ISO) $(DISK) $(JSSEM_PATHS)

.PHONY: test-jssem test-jssem-os
