# tcc 0.9.27 as a LogitOS program, and the kernel's acceptance of the bare ELF
# it emits. NOT included by the Makefile -- the `-include tests/*.mk` list
# there belongs to another line -- so every target here is reached as
#
#     make -f Makefile -f tests/tcc.mk test-tcc-build
#     make -f Makefile -f tests/tcc.mk test-elf-exec
#
# and the one-line `-include tests/tcc.mk` beside its ninety siblings is the
# ask to whoever owns the Makefile. Everything below reuses that file's
# variables -- $(UCFLAGS), $(LIBC_OBJS), $(LIBM_OBJ), $(APPDIR), $(ASM),
# $(LD), $(CC), $(DISK), $(ISO), and tests/exec.mk's EXEC_* -- rather than
# retyping a flag list, because a retyped list is how tools/lmshape.c carried
# a wrong link line for as long as the file existed.
#
# WHAT IS BUILT
#   $(TCC_OUT)/tcc.aex      tcc for the device: the x86_64 TUs upstream's own
#                           Makefile compiles, MINUS tccrun.c (the -run JIT,
#                           which needs <sys/ucontext.h> and an executable
#                           heap; a batch compiler never calls it), against
#                           mini-libc + musl libm + crt0_cli at 0x50000000,
#                           wrapped by tools/mkaex.py like /bin/as.
#   $(TCC_OUT)/host/tcc     the SAME patched source built for the host, with
#                           the same -DTCC_LOGIT, so it is a cross-tcc for
#                           LogitOS: same link base, same static default, same
#                           paths. It links the hello below exactly as the
#                           device tcc will link a program.
#   $(TCC_OUT)/host-stock/tcc  the same source WITHOUT -DTCC_LOGIT: stock
#                           defaults, 0x400000 and a dynamic link with
#                           PT_INTERP. The negative control's toolchain.
#   $(TCC_OUT)/hello-elf    tests/unit/tcc_hello.c linked by host/tcc with our
#                           crt0 and libc -- a BARE ELF, never wrapped. What
#                           test-elf-exec executes on the device.
#   $(TCC_OUT)/hello-bad    the same, -Wl,-Ttext=0x400000: the stock base. The
#                           kernel must refuse it by name, not fault.
#   $(TCC_OUT)/hello-dyn    the same program linked by host-stock/tcc at the
#                           right base: PT_INTERP + .dynamic present. The
#                           readelf check must fail on it.
#
# WHAT config.h WOULD HAVE SAID is written as flags (TCC_DEFS) and an EMPTY
# generated config.h, so the build is reproducible from the tree and no
# ./configure output is checked in or depended on. The LogitOS defaults
# themselves (link base, paths, static, no interpreter, __logit__, -shared
# refused, chmod of the output) live IN the vendored source under TCC_LOGIT,
# each argued beside its value -- third_party/tcc/{tcc.h,x86_64-link.c,
# libtcc.c,tcc.c,tccelf.c}.
#
# THE PATHS THIS tcc IS BUILT TO FIND, for the sysroot line to populate:
#   /usr/include            CONFIG_TCC_SYSINCLUDEPATHS (then {B}/include)
#   /usr/lib                CONFIG_TCC_LIBPATHS   -> -lc finds /usr/lib/libc.a
#   /usr/lib                CONFIG_TCC_CRTPREFIX  -> crt1.o crti.o crtn.o
#   /usr/lib/tcc            CONFIG_TCCDIR ({B})   -> /usr/lib/tcc/libtcc1.a
#                                                    /usr/lib/tcc/include/*.h
# A default `tcc hello.c -o hello` adds, in this order: crt1.o, crti.o, the
# user's files, -lc, libtcc1.a, crtn.o. `-nostdlib` skips all six.

.PHONY: test-tcc-build test-tcc-build-negctl test-elf-exec

TCC_SRCDIR := third_party/tcc
TCC_OUT    := $(BUILD)/tcc
# Upstream Makefile: X86_64_FILES = CORE_FILES x86_64-gen.c x86_64-link.c
# i386-asm.c, with tcctools.c #included by tcc.c. tccrun.c dropped, see above.
TCC_TUS    := tcc libtcc tccpp tccgen tccelf tccasm x86_64-gen x86_64-link i386-asm
TCC_OBJ    := $(patsubst %,$(TCC_OUT)/obj/%.o,$(TCC_TUS))
TCC_HDRS   := $(wildcard $(TCC_SRCDIR)/*.h) $(wildcard $(TCC_SRCDIR)/*.def) \
              $(TCC_SRCDIR)/tcctools.c
# config.h, as flags. TCC_TARGET_X86_64 picks the code generator;
# CONFIG_TCC_STATIC drops dlopen(); TCC_VERSION is what `tcc -v` prints and
# what __TINYC__ is derived from; TCC_LOGIT is every LogitOS default at once.
TCC_DEFS   := -DTCC_TARGET_X86_64 -DCONFIG_TCC_STATIC -DTCC_VERSION='"0.9.27"'
TCC_LOGIT_DEFS := $(TCC_DEFS) -DTCC_LOGIT

# --- the device binary --------------------------------------------------------
$(TCC_OUT)/config.h:
	@mkdir -p $(TCC_OUT)
	@printf '/* generated by tests/tcc.mk: deliberately empty. Every define\n * ./configure would have written here is on the compile line (TCC_DEFS)\n * or argued in the vendored source under TCC_LOGIT. */\n' > $@

# -I$(TCC_SRCDIR) -I$(TCC_OUT) come BEFORE $(UCFLAGS) so tcc's own elf.h,
# stab.h and the empty config.h win over anything of the same basename in
# the flat $(INCDIRS) scan (c/kernel/exec/elf.h is the one that collides).
# -std=gnu11 -w after UCFLAGS overrides its -std=c11 -Wall -Wextra: this is
# 2017 GNU C and its warnings are upstream's to fix.
$(TCC_OUT)/obj/%.o: $(TCC_SRCDIR)/%.c $(TCC_HDRS) $(TCC_OUT)/config.h
	@mkdir -p $(dir $@)
	$(CC) -I$(TCC_SRCDIR) -I$(TCC_OUT) $(UCFLAGS) -std=gnu11 -w -DONE_SOURCE=0 \
	    $(TCC_LOGIT_DEFS) -c $< -o $@

$(TCC_OUT)/crt0_cli.o: $(APPDIR)/crt0_cli.asm
	@mkdir -p $(TCC_OUT)
	$(ASM) -f elf64 $< -o $@

$(TCC_OUT)/tcc.elf: $(TCC_OBJ) $(LIBC_OBJS) $(LIBM_OBJ) $(TCC_OUT)/crt0_cli.o
	$(LD) -nostdlib -e _start -Ttext=0x50000000 -o $@ \
	    $(TCC_OUT)/crt0_cli.o $(TCC_OBJ) $(LIBC_OBJS) $(LIBM_OBJ)

$(TCC_OUT)/tcc.aex: $(TCC_OUT)/tcc.elf tools/mkaex.py
	python3 tools/mkaex.py $< $@ tcc - 'C' 150 150 150 --category dev

# --- the host cross-tcc, and the stock one for the control ---------------------
# ONE_SOURCE=1 is upstream's own single-TU build (tcc.c pulls everything in),
# which is why one compile line produces the whole compiler. No -ldl: with
# CONFIG_TCC_STATIC the dl* names are tccrun.c's stubs, and the LOGIT build
# does not compile tccrun.c at all.
$(TCC_OUT)/host/tcc: $(wildcard $(TCC_SRCDIR)/*.c) $(TCC_HDRS) $(TCC_OUT)/config.h
	@mkdir -p $(dir $@)
	$(CC) -O2 -w -DONE_SOURCE=1 $(TCC_LOGIT_DEFS) -I$(TCC_SRCDIR) -I$(TCC_OUT) \
	    $(TCC_SRCDIR)/tcc.c -o $@ -lm

$(TCC_OUT)/host-stock/tcc: $(wildcard $(TCC_SRCDIR)/*.c) $(TCC_HDRS) $(TCC_OUT)/config.h
	@mkdir -p $(dir $@)
	$(CC) -O2 -w -DONE_SOURCE=1 $(TCC_DEFS) -I$(TCC_SRCDIR) -I$(TCC_OUT) \
	    $(TCC_SRCDIR)/tcc.c -o $@ -lm

# --- hello, linked BY tcc against our libc ---------------------------------------
# Archives rather than the object list: tcc links a named object WHOLE, and
# pulls from an archive only what resolves an undefined symbol -- which is how
# the device tcc will consume /usr/lib/libc.a, so it is the shape to test.
# (And a whole-object link of mini-libc would pull pthread.o, whose `__thread`
# sentinel is an R_X86_64_TPOFF32 this tcc has no case for.)
$(TCC_OUT)/libc.a: $(LIBC_OBJS)
	@mkdir -p $(TCC_OUT)
	@rm -f $@
	ar rcs $@ $(LIBC_OBJS)
$(TCC_OUT)/libm.a: $(LIBM_OBJ)
	@mkdir -p $(TCC_OUT)
	@rm -f $@
	ar rcs $@ $(LIBM_OBJ)

# -nostdinc -nostdlib: the host has no /usr/include of ours and tcc must not
# reach for the host's. tcc's own include/ supplies stdarg.h/stddef.h (its
# va_list is compiler-specific); everything else is mini-libc's headers.
TCC_XFLAGS := -nostdinc -nostdlib -I$(TCC_SRCDIR)/include \
              -Ic/apps/libc/include/uonly -Ic/apps/libc/include
TCC_HELLO_IN := $(TCC_OUT)/crt0_cli.o tests/unit/tcc_hello.c $(TCC_OUT)/libc.a $(TCC_OUT)/libm.a

$(TCC_OUT)/hello-elf: $(TCC_OUT)/host/tcc $(TCC_HELLO_IN)
	$(TCC_OUT)/host/tcc $(TCC_XFLAGS) -o $@ $(TCC_HELLO_IN)
$(TCC_OUT)/hello-bad: $(TCC_OUT)/host/tcc $(TCC_HELLO_IN)
	$(TCC_OUT)/host/tcc $(TCC_XFLAGS) -Wl,-Ttext=0x400000 -o $@ $(TCC_HELLO_IN)
$(TCC_OUT)/hello-dyn: $(TCC_OUT)/host-stock/tcc $(TCC_HELLO_IN)
	$(TCC_OUT)/host-stock/tcc $(TCC_XFLAGS) -Wl,-Ttext=0x50000000 -o $@ $(TCC_HELLO_IN)

# --- test-tcc-build (host) ----------------------------------------------------
# tcc.aex links; readelf on tcc's OWN image and on the hello tcc linked shows
# ET_EXEC x86-64, no PT_INTERP, no PT_DYNAMIC, entry and every PT_LOAD inside
# the private user region. Then the two controls, each required to fail the
# same script on EXACTLY the checks it was built to fail:
#   hello-bad   entry + PT_LOAD range      2 FAIL lines
#   hello-dyn   PT_INTERP + PT_DYNAMIC     2 FAIL lines
# and the kernel-side control below, as a prerequisite (the tree's convention:
# a control named on a `ci-host:` line instead runs never).
test-tcc-build: test-tcc-build-negctl
test-tcc-build: $(TCC_OUT)/tcc.aex $(TCC_OUT)/hello-elf $(TCC_OUT)/hello-bad $(TCC_OUT)/hello-dyn
	@echo "tcc: $$(stat -c%s $(TCC_OUT)/tcc.elf) bytes of ELF, $$(stat -c%s $(TCC_OUT)/tcc.aex) bytes of .aex"
	@bash tests/unit/tcc_elfcheck.sh $(TCC_OUT)/tcc.elf
	@bash tests/unit/tcc_elfcheck.sh $(TCC_OUT)/hello-elf
	@if bash tests/unit/tcc_elfcheck.sh $(TCC_OUT)/hello-bad > $(TCC_OUT)/negctl_bad.log 2>&1; then \
	    echo "FAIL: hello linked at 0x400000 PASSED the ELF check -- the check does not measure the link base"; exit 1; fi
	@n=$$(grep -c '^  FAIL' $(TCC_OUT)/negctl_bad.log); [ "$$n" -eq 2 ] || \
	    { echo "FAIL: the 0x400000 control failed $$n checks, expected exactly 2 (entry, PT_LOAD range):"; cat $(TCC_OUT)/negctl_bad.log; exit 1; }
	@grep -q 'FAIL: entry' $(TCC_OUT)/negctl_bad.log || { echo "FAIL: the 0x400000 control did not fail on the ENTRY check"; exit 1; }
	@echo "  ok: control -- the same hello at 0x400000 fails exactly the 2 range checks"
	@if bash tests/unit/tcc_elfcheck.sh $(TCC_OUT)/hello-dyn > $(TCC_OUT)/negctl_dyn.log 2>&1; then \
	    echo "FAIL: a stock-tcc dynamic link PASSED the ELF check -- the check does not see PT_INTERP"; exit 1; fi
	@n=$$(grep -c '^  FAIL' $(TCC_OUT)/negctl_dyn.log); [ "$$n" -eq 2 ] || \
	    { echo "FAIL: the dynamic control failed $$n checks, expected exactly 2 (INTERP, DYNAMIC):"; cat $(TCC_OUT)/negctl_dyn.log; exit 1; }
	@grep -q 'FAIL: no PT_INTERP' $(TCC_OUT)/negctl_dyn.log || { echo "FAIL: the dynamic control did not fail on PT_INTERP"; exit 1; }
	@echo "  ok: control -- stock tcc's default link fails exactly the 2 dynamic checks"
	@echo "PASS: tcc.aex links, its output is a static ET_EXEC in the private user region, and both controls fail where they should"

# --- test-tcc-build-negctl: the kernel half, on the host -------------------------
# aex.c's bare-ELF pre-check with its 64-byte verdict removed (the plausible
# "elf.c checks it later anyway" version). tests/unit/exec_test.c's bare-ELF
# refusal cases must go red -- exactly 4 lines: the 0x4000b0 refusal, its
# "out loud" companion, aex_info()'s verdict, and EM_386 -- while acceptance
# of a good bare ELF stays green, or the control broke the feature rather
# than the check. Built the way tests/exec.mk builds its own controls.
test-tcc-build-negctl: $(EXEC_SEEDS) $(EXEC_FIXTURES)
	@mkdir -p $(TCC_OUT)
	@$(CC) -O1 -g -w $(EXEC_INC) -DAEX_NEGCTL_NOHDR -o $(TCC_OUT)/exec_test_nohdr \
	    tests/unit/exec_test.c $(EXEC_SRC)
	@if $(EXEC_ENV) $(TCC_OUT)/exec_test_nohdr $(EXEC_SEEDS) > $(TCC_OUT)/negctl_nohdr.log 2>&1; then \
	    echo "FAIL: the no-header-check control PASSED -- the battery does not measure the bare-ELF verdict"; exit 1; fi
	@n=$$(grep -c '^FAIL' $(TCC_OUT)/negctl_nohdr.log); [ "$$n" -eq 4 ] || \
	    { echo "FAIL: the control reddened $$n checks, expected exactly 4:"; grep '^FAIL' $(TCC_OUT)/negctl_nohdr.log; exit 1; }
	@grep -q '^FAIL: a bare ELF whose entry is 0x4000b0' $(TCC_OUT)/negctl_nohdr.log || \
	    { echo "FAIL: the control did not redden the 0x4000b0 refusal"; exit 1; }
	@grep -q '^ok: a bare ELF (the reference file' $(TCC_OUT)/negctl_nohdr.log || \
	    { echo "FAIL: the control broke bare-ELF acceptance itself, not just the verdict"; exit 1; }
	@echo "  ok: control -- without the 64-byte verdict, exactly the 4 refusal checks go red and acceptance stays green"

# --- test-elf-exec (device) --------------------------------------------------
# Its OWN disk image: the Makefile's $(DISK) file list, taken from `make -n`
# (continuations joined -- see tests/boot/mk-tcc-disk.py) plus the files
# under test.
#
# $(DISK) is deliberately NOT a prerequisite. It pulls in every app in the
# tree, and on 2026-08-21 an unrelated app's link (h2check, a new ssh TU
# missing its crypto objects) turned this gate red for a reason that had
# nothing to do with tcc or the loader. `make -n` still yields the file list
# whether or not the image is current, and mk-tcc-disk.py refuses -- naming
# the file -- if an input it lists does not exist; `make build/disk.img` is
# then the fix, run once, by hand.
$(TCC_OUT)/disk.img: $(TCC_OUT)/tcc.aex $(TCC_OUT)/tcc.elf $(TCC_OUT)/hello-elf \
                     $(TCC_OUT)/hello-bad tests/boot/mk-tcc-disk.py tools/mkfs.py \
                     tests/unit/tcc_bare.c tests/unit/tcc_hello.c
	@$(MAKE) -f Makefile -n -W tools/mkfs.py $(DISK) > $(TCC_OUT)/disk.mk-n
	@python3 tests/boot/mk-tcc-disk.py . $(TCC_OUT)/disk.mk-n $@ \
	    $(TCC_OUT)/tcc.aex:/bin/tcc \
	    $(TCC_OUT)/tcc.elf:/bin/tcc-elf \
	    $(TCC_OUT)/hello-elf:/bin/hello-elf \
	    $(TCC_OUT)/hello-bad:/bin/hello-bad \
	    tests/unit/tcc_bare.c:/src/bare.c \
	    tests/unit/tcc_hello.c:/src/hello.c

test-elf-exec: $(ISO) $(TCC_OUT)/disk.img
	@bash tests/boot/run-tcc-test.sh $(ISO) $(TCC_OUT)/disk.img

# --- test-tcc-identity (device): the compiler on the device IS the host's ----
# tests/boot/run-tcc-identity.sh: the same hello_id.c (no includes) and the
# same tccpp.c (3,903 lines, 11 mini-libc headers + 3 of tcc's own, against a
# snapshot of workflow 2's build/sysroot) are compiled to OBJECTS by
# /bin/tcc on the device and by $(TCC_OUT)/host/tcc on the host, and the .o
# files must be BYTE-IDENTICAL -- the .o comes back off the (non -snapshot)
# image via the harness's embedded LogitFS reader. The gate carries its own
# negative control (one -D on one side must change the bytes) and prints the
# device compile wall times (TCG, and KVM when /dev/kvm exists) plus a host
# LD_PRELOAD open() census, because no kernel VFS open counter exists to ask.
.PHONY: test-tcc-identity
test-tcc-identity: $(TCC_OUT)/tcc.aex $(TCC_OUT)/host/tcc $(ISO) \
                   tests/boot/run-tcc-identity.sh tests/boot/mk-tcc-disk.py
	@bash tests/boot/run-tcc-identity.sh $(ISO)
