#include "mlkem.h"
#include "keccak.h"

/* ML-KEM-768, FIPS 203. Integer only, no libc, no allocation: every buffer is
 * a caller's or an automatic.
 *
 * ARITHMETIC. All of it is derived in build/tlsx/derive.py and gen_zetas.py and
 * every constant below was machine-checked before it was typed, because this is
 * the layer where implementations go wrong silently:
 *
 *   q = 3329 = 2^8 * 13. The 2-adic valuation of q-1 is 8, so Z_q has a
 *   primitive 256th root of unity and NOT a 512th one. X^256+1 therefore does
 *   NOT split into linear factors -- it splits into 128 quadratics. That single
 *   fact is why this NTT is 7 layers and not 8, and why pointwise
 *   multiplication is a degree-2 base case (basemul) rather than a scalar
 *   product. An implementation that assumes a full NTT produces plausible
 *   garbage and no error.
 *
 *   ZETA = 17 is the smallest primitive 256th root mod q (and the only one
 *   below 40); 17^128 = 3328 = -1 confirms the order is exactly 256.
 *
 *   Montgomery R = 2^16, QINV = q^-1 mod 2^16 = 62209 = -3327 as int16.
 *   montgomery_reduce(a) = a*R^-1 mod q.
 *
 *   Barrett V = round(2^26/q) = 20159. barrett_reduce was checked over ALL
 *   65536 int16 inputs: correct mod q in every case, output always within
 *   [-1664, 1664] = +-q/2. Exhaustive, not sampled -- the input range is small
 *   enough that there is no excuse for a spot check.
 *
 * WHY MONTGOMERY AND NOT PLAIN MODULAR REDUCTION. The alternative is a %
 * operator per coefficient multiply; there are 256*7 butterflies in a single
 * NTT and three NTTs per operation. On this target % is a hardware divide,
 * which is both slow and (on several x86 microarchitectures) operand-dependent
 * in latency -- a timing signal over secret polynomial coefficients.
 * Montgomery is a multiply and a shift, always.
 *
 * CONSTANT TIME. The secret-dependent paths are: SamplePolyCBD (bit counting,
 * branch-free), the NTT and basemul (multiply/add only), compress/decompress in
 * K-PKE.Decrypt (multiply-shift, magic constants derived and verified
 * exhaustively in gen_compress.py so no hardware divide appears), and the
 * ciphertext comparison plus select in Decaps (ct_diff/select below, no
 * branch). Rejection sampling in SampleNTT is variable-time BY DESIGN and that
 * is safe: it runs on rho, which is public -- it is transmitted in the clear as
 * part of ek. Making it constant-time would cost real work to protect a value
 * the attacker already has.
 *
 * STACK. K-PKE.Encrypt is the deepest frame and Decaps calls it for the
 * re-encryption. The kernel thread kstack is 32 KiB (CLAUDE.md M11 note) and
 * the TLS path is already described there as stack-heavy, so this was measured
 * rather than assumed -- see the -fstack-usage numbers in the report. The
 * matrix is generated a ROW at a time in encrypt and never held whole,
 * precisely to keep the re-encryption inside Decaps inside that budget.
 */

#define N     256
#define Q     3329
#define K     3
#define ETA1  2
#define ETA2  2
#define DU    10
#define DV    4

#define QINV  (-3327)            /* q^-1 mod 2^16, as int16 */
#define BARV  20159              /* round(2^26 / q) */

/* Single division magic for every compress width used here (d <= 11):
 * floor(n/q) == (n*CDIV_M) >> CDIV_S, verified for ALL n in [0, 6817408],
 * which covers the largest argument any Compress_d can produce (d=11:
 * 3328<<11 + q/2 = 6817408). One constant rather than a table indexed by d,
 * because a table would need the same proof per entry and buy nothing. */
#define CDIV_M  2580335u
#define CDIV_S  33

typedef struct { int16_t c[N]; } poly;
typedef struct { poly v[K]; } polyvec;

/* zetas[i] = zeta^brv7(i) * 2^16 mod+- q, zeta = 17. Generated by
 * build/tlsx/gen_zetas.py, which also PROVES the table by running an NTT
 * multiply against a schoolbook multiply in Z_q[X]/(X^256+1) -- 5/5 exact.
 * sum = -4863, sum|.| = 108583 (checksums to diff against, not magic). */
static const int16_t zetas[128] = {
    -1044,  -758,  -359, -1517,  1493,  1422,   287,   202,
     -171,   622,  1577,   182,   962, -1202, -1474,  1468,
      573, -1325,   264,   383,  -829,  1458, -1602,  -130,
     -681,  1017,   732,   608, -1542,   411,  -205, -1571,
     1223,   652,  -552,  1015, -1293,  1491,  -282, -1544,
      516,    -8,  -320,  -666, -1618, -1162,   126,  1469,
     -853,   -90,  -271,   830,   107, -1421,  -247,  -951,
     -398,   961, -1508,  -725,   448, -1065,   677, -1275,
    -1103,   430,   555,   843, -1251,   871,  1550,   105,
      422,   587,   177,  -235,  -291,  -460,  1574,  1653,
     -246,   778,  1159,  -147,  -777,  1483,  -602,  1119,
    -1590,   644,  -872,   349,   418,   329,  -156,   -75,
      817,  1097,   603,   610,  1322, -1285, -1465,   384,
    -1215,  -136,  1218, -1335,  -874,   220, -1187, -1659,
    -1185, -1530, -1278,   794, -1510,  -854,  -870,   478,
     -108,  -308,   996,   991,   958, -1460,  1522,  1628,
};

/* ------------------------------------------------------- small helpers */

/* No libc: this file links into the kernel and into a host test; a memcpy call
 * would resolve to a different implementation in each. */
static void cp(uint8_t *d, const uint8_t *s, int n) { for (int i = 0; i < n; i++) d[i] = s[i]; }

/* Wipe through a volatile pointer so -O2 cannot drop it as a dead store.
 * Same reasoning as crypto.h's crypto_wipe; not included from there because
 * this file must also build in the host test without the kernel's crypto.h. */
static void wipe(void *p, int n)
{
    volatile uint8_t *v = (volatile uint8_t *)p;
    while (n--) *v++ = 0;
}

/* Constant-time: 0x00 if the two buffers are equal, 0xFF if they differ
 * anywhere. Accumulates over the WHOLE buffer -- no early exit. Returning on
 * the first differing byte would leak how far a mauled ciphertext matched,
 * which over repeated queries recovers it. */
static uint8_t ct_diff(const uint8_t *a, const uint8_t *b, int n)
{
    uint8_t d = 0;
    for (int i = 0; i < n; i++) d |= (uint8_t)(a[i] ^ b[i]);
    /* 0 -> 0x00, anything else -> 0xFF, without a branch: (0-d) has the high
     * bit set for every nonzero d in 0..255, and the arithmetic shift of the
     * widened value spreads it. */
    return (uint8_t)(0u - (uint32_t)((d | (uint8_t)(0u - (uint32_t)d)) >> 7));
}

/* montgomery_reduce: a * R^-1 mod q, for |a| < q * 2^15. */
static int16_t mont(int32_t a)
{
    int16_t t = (int16_t)((int16_t)a * QINV);
    return (int16_t)((a - (int32_t)t * Q) >> 16);
}
static int16_t fqmul(int16_t a, int16_t b) { return mont((int32_t)a * b); }

/* barrett_reduce: representative of a mod q in [-q/2, q/2]. Verified over all
 * 65536 int16 inputs (derive.py). */
static int16_t barrett(int16_t a)
{
    int16_t t = (int16_t)(((int32_t)BARV * a + (1 << 25)) >> 26);
    return (int16_t)(a - (int32_t)t * Q);
}

/* Conditional add q: maps [-q, q) into [0, q). Branch-free -- the arithmetic
 * shift produces 0 or -1 from the sign bit. */
static int16_t csubq_add(int16_t a) { return (int16_t)(a + ((a >> 15) & Q)); }

/* ------------------------------------------------------------- the NTT */

static void ntt(poly *r)
{
    int k = 1;
    for (int len = 128; len >= 2; len >>= 1) {
        for (int start = 0; start < N; start += 2 * len) {
            int16_t z = zetas[k++];
            for (int j = start; j < start + len; j++) {
                int16_t t = fqmul(z, r->c[j + len]);
                r->c[j + len] = (int16_t)(r->c[j] - t);
                r->c[j]       = (int16_t)(r->c[j] + t);
            }
        }
    }
}

static void invntt(poly *r)
{
    /* f = 128^-1 * 2^32 mod q = 1441 (gen_zetas.py). It folds the 1/128 of the
     * inverse transform and the Montgomery factor the butterflies leave behind
     * into ONE multiply -- the alternative, a separate division by 128, does
     * not exist in this ring without another modular inverse per coefficient. */
    const int16_t f = 1441;
    int k = 127;
    for (int len = 2; len <= 128; len <<= 1) {
        for (int start = 0; start < N; start += 2 * len) {
            int16_t z = zetas[k--];
            for (int j = start; j < start + len; j++) {
                int16_t t = r->c[j];
                r->c[j]       = barrett((int16_t)(t + r->c[j + len]));
                r->c[j + len] = (int16_t)(r->c[j + len] - t);
                r->c[j + len] = fqmul(z, r->c[j + len]);
            }
        }
    }
    for (int j = 0; j < N; j++) r->c[j] = fqmul(r->c[j], f);
}

/* Degree-2 base case: (a0 + a1 X)(b0 + b1 X) mod (X^2 - zeta). This is the
 * "incomplete NTT" consequence noted at the top -- there is no 512th root, so
 * the quotient ring does not reduce further than quadratics. */
static void basemul(int16_t r[2], const int16_t a[2], const int16_t b[2], int16_t zeta)
{
    r[0] = fqmul(a[1], b[1]);
    r[0] = fqmul(r[0], zeta);
    r[0] = (int16_t)(r[0] + fqmul(a[0], b[0]));
    r[1] = fqmul(a[0], b[1]);
    r[1] = (int16_t)(r[1] + fqmul(a[1], b[0]));
}

static void poly_basemul(poly *r, const poly *a, const poly *b)
{
    for (int i = 0; i < N / 4; i++) {
        basemul(&r->c[4*i],   &a->c[4*i],   &b->c[4*i],    zetas[64 + i]);
        basemul(&r->c[4*i+2], &a->c[4*i+2], &b->c[4*i+2], (int16_t)-zetas[64 + i]);
    }
}

static void poly_add(poly *r, const poly *a, const poly *b)
{ for (int i = 0; i < N; i++) r->c[i] = (int16_t)(a->c[i] + b->c[i]); }
static void poly_sub(poly *r, const poly *a, const poly *b)
{ for (int i = 0; i < N; i++) r->c[i] = (int16_t)(a->c[i] - b->c[i]); }
static void poly_reduce(poly *r)
{ for (int i = 0; i < N; i++) r->c[i] = barrett(r->c[i]); }
static void poly_tomont(poly *r)
{
    /* R^2 mod q = 1353 (derive.py), so fqmul(x, 1353) = x*R mod q. Needed where
     * a value must gain the Montgomery factor that basemul removed. */
    const int16_t f = 1353;
    for (int i = 0; i < N; i++) r->c[i] = fqmul(r->c[i], f);
}

/* ------------------------------------------------------ encode / decode */

/* Compress_d then pack, and unpack then Decompress_d (FIPS 203 4.7 / 4.2.1).
 * The division by q is the derived multiply-shift, never the % operator: this
 * runs on secret data in K-PKE.Decrypt. */
static uint32_t compress(int16_t x, int d)
{
    uint32_t u = (uint32_t)csubq_add(barrett(x));       /* into [0, q) */
    uint32_t n = (u << d) + Q / 2;
    uint32_t t = (uint32_t)(((uint64_t)n * CDIV_M) >> CDIV_S);
    return t & ((1u << d) - 1u);
}
static int16_t decompress(uint32_t y, int d)
{
    return (int16_t)(((uint32_t)Q * y + (1u << (d - 1))) >> d);
}

/* Bit-packer: 256 values of d bits, little-endian bit order within the stream,
 * exactly ByteEncode_d. Written as a bit accumulator rather than the usual
 * per-width special cases, because those special cases are where off-by-one
 * packing bugs live and there are four widths here (1, 4, 10, 12). */
static void pack(uint8_t *out, const uint16_t *v, int d)
{
    uint32_t acc = 0; int nbits = 0, o = 0;
    for (int i = 0; i < N; i++) {
        acc |= (uint32_t)(v[i] & ((1u << d) - 1u)) << nbits;
        nbits += d;
        while (nbits >= 8) { out[o++] = (uint8_t)acc; acc >>= 8; nbits -= 8; }
    }
}
static void unpack(uint16_t *v, const uint8_t *in, int d)
{
    uint32_t acc = 0; int nbits = 0, o = 0;
    for (int i = 0; i < N; i++) {
        while (nbits < d) { acc |= (uint32_t)in[o++] << nbits; nbits += 8; }
        v[i] = (uint16_t)(acc & ((1u << d) - 1u));
        acc >>= d; nbits -= d;
    }
}

static void poly_tobytes(uint8_t r[384], const poly *a)
{
    uint16_t t[N];
    for (int i = 0; i < N; i++) t[i] = (uint16_t)csubq_add(barrett(a->c[i]));
    pack(r, t, 12);
}
static void poly_frombytes(poly *r, const uint8_t a[384])
{
    uint16_t t[N];
    unpack(t, a, 12);
    for (int i = 0; i < N; i++) r->c[i] = (int16_t)t[i];
}

static void poly_compress(uint8_t *r, const poly *a, int d)
{
    uint16_t t[N];
    for (int i = 0; i < N; i++) t[i] = (uint16_t)compress(a->c[i], d);
    pack(r, t, d);
}
static void poly_decompress(poly *r, const uint8_t *a, int d)
{
    uint16_t t[N];
    unpack(t, a, d);
    for (int i = 0; i < N; i++) r->c[i] = decompress(t[i], d);
}

/* --------------------------------------------------------- sampling */

/* SampleNTT, FIPS 203 Alg.7. Rejection sampling from SHAKE128.
 *
 * THIS MUST BE EXACTLY THE SPEC RULE OR THE PUBLIC KEYS DIFFER AND NOTHING
 * WORKS, WITH NO ERROR ANYWHERE -- the handshake simply computes two different
 * shared secrets and fails at the Finished MAC hundreds of lines away. Two
 * details carry that:
 *   - THREE bytes yield TWO candidates: d1 = C0 + 256*(C1 mod 16) and
 *     d2 = floor(C1/16) + 16*C2. Taking the nibbles the other way round is the
 *     classic wrong version and it still produces a uniform-looking polynomial.
 *   - BOTH candidates are tested; d2 is used only if it is < q AND ctr < 256.
 *     Skipping d2 whenever d1 was accepted, or breaking out of a block early,
 *     changes the stream position and therefore every later coefficient.
 * Variable-time by design: the input rho is public (it is sent inside ek). */
static void sample_ntt(poly *a, const uint8_t seed[32], uint8_t i, uint8_t j)
{
    struct shake xof;
    uint8_t buf[168];
    int ctr = 0, pos = 168;

    shake128_init(&xof);
    shake_absorb(&xof, seed, 32);
    { uint8_t ij[2]; ij[0] = i; ij[1] = j; shake_absorb(&xof, ij, 2); }
    shake_finalize(&xof);

    while (ctr < N) {
        if (pos > 168 - 3) { shake_squeeze(&xof, buf, 168); pos = 0; }
#ifdef MLKEM_CTL_NIBBLE_SWAP
        /* NEGATIVE CONTROL: the nibbles of the middle byte taken the other way
         * round. Still uniform, still terminates, still yields a well-formed
         * key -- and interoperates with nothing. */
        uint16_t d1 = (uint16_t)((buf[pos] << 4) | (buf[pos+1] >> 4));
        uint16_t d2 = (uint16_t)(((buf[pos+1] & 0x0F) << 8) | buf[pos+2]);
#else
        uint16_t d1 = (uint16_t)(buf[pos] | ((uint16_t)(buf[pos+1] & 0x0F) << 8));
        uint16_t d2 = (uint16_t)((buf[pos+1] >> 4) | ((uint16_t)buf[pos+2] << 4));
#endif
        pos += 3;
        if (d1 < Q)              a->c[ctr++] = (int16_t)d1;
#ifndef MLKEM_CTL_SKIP_D2
        /* NEGATIVE CONTROL (-DMLKEM_CTL_SKIP_D2): drop the second candidate.
         * The polynomial is still uniform and the loop still terminates -- only
         * the XOF stream position differs, so every coefficient after the first
         * rejection is wrong. */
        if (d2 < Q && ctr < N)   a->c[ctr++] = (int16_t)d2;
#else
        (void)d2;
#endif
    }
}

/* SamplePolyCBD_eta, FIPS 203 Alg.8, for eta = 2 (both ETA1 and ETA2 are 2 at
 * this parameter set, so there is one function and not two). Input is 64*eta =
 * 128 bytes. Branch-free bit counting: the input is secret. */
static void cbd2(poly *r, const uint8_t buf[128])
{
    for (int i = 0; i < N / 8; i++) {
        uint32_t t = (uint32_t)buf[4*i] | ((uint32_t)buf[4*i+1] << 8)
                   | ((uint32_t)buf[4*i+2] << 16) | ((uint32_t)buf[4*i+3] << 24);
        /* Sum adjacent bit pairs in parallel: each 2-bit field of d holds the
         * population count of the corresponding 2 bits of t. */
        uint32_t d = (t & 0x55555555u) + ((t >> 1) & 0x55555555u);
        for (int k = 0; k < 8; k++) {
            int16_t x = (int16_t)((d >> (4 * k))     & 0x3);
            int16_t y = (int16_t)((d >> (4 * k + 2)) & 0x3);
            r->c[8 * i + k] = (int16_t)(x - y);
        }
    }
}

/* PRF_eta(s, b) = SHAKE256(s || b, 64*eta), FIPS 203 4.1. */
static void prf(uint8_t *out, int outlen, const uint8_t s[32], uint8_t b)
{
    struct shake sh;
    shake256_init(&sh);
    shake_absorb(&sh, s, 32);
    shake_absorb(&sh, &b, 1);
    shake_finalize(&sh);
    shake_squeeze(&sh, out, (size_t)outlen);
}
static void poly_cbd_eta(poly *r, const uint8_t s[32], uint8_t nonce)
{
    uint8_t buf[64 * ETA1];
    prf(buf, (int)sizeof buf, s, nonce);
    cbd2(r, buf);
    wipe(buf, (int)sizeof buf);
}

/* --------------------------------------------------------- vector ops */

static void polyvec_ntt(polyvec *v)
{ for (int i = 0; i < K; i++) { ntt(&v->v[i]); poly_reduce(&v->v[i]); } }

/* <a, b> in the NTT domain, accumulated then reduced once. The result carries
 * an extra R^-1 from basemul; callers that need it removed say so with
 * poly_tomont, which keeps the Montgomery bookkeeping in one visible place
 * instead of scattering conversions through the algorithm. */
static void polyvec_dot(poly *r, const poly *a, const polyvec *b)
{
    poly t;
    poly_basemul(r, &a[0], &b->v[0]);
    for (int i = 1; i < K; i++) { poly_basemul(&t, &a[i], &b->v[i]); poly_add(r, r, &t); }
    poly_reduce(r);
}

/* --------------------------------------------------------------- K-PKE */

/* A[i][j] = SampleNTT(rho || j || i). NOTE THE BYTE ORDER: the transposed flag
 * swaps which index is absorbed first, and getting it backwards produces a
 * perfectly valid-looking keypair that no peer can interoperate with -- there
 * is no error, only a Finished MAC failure much later. FIPS 203 Alg.13 line 4
 * absorbs (j, i) for A; Alg.14 line 4 uses A-transpose, i.e. (i, j). */
static void gen_matrix_row(poly a[K], const uint8_t rho[32], int i, int transposed)
{
    for (int j = 0; j < K; j++) {
#ifdef MLKEM_CTL_NO_TRANSPOSE
        /* NEGATIVE CONTROL: ignore the transpose. keygen and encrypt then agree
         * with each other, so OUR OWN round trip still succeeds -- which is
         * precisely why a self-test cannot see this defect and openssl can. */
        (void)transposed; sample_ntt(&a[j], rho, (uint8_t)j, (uint8_t)i);
#else
        if (transposed) sample_ntt(&a[j], rho, (uint8_t)i, (uint8_t)j);
        else            sample_ntt(&a[j], rho, (uint8_t)j, (uint8_t)i);
#endif
    }
}

static void pke_keygen(const uint8_t d[32], uint8_t ek[MLKEM768_EK], uint8_t dkpke[384 * K])
{
    uint8_t g[64], rho[32], sigma[32];
    polyvec s, e, t;
    poly row[K], tmp;

    /* G(d || k) -- the trailing domain-separation byte k is in the FINAL
     * FIPS 203 and was NOT in the Kyber round-3 submission this grew from.
     * Omitting it yields a self-consistent implementation that disagrees with
     * every real one, which is exactly the failure the openssl gate exists to
     * catch and a self-test never would. */
    {
        uint8_t in[33];
        cp(in, d, 32); in[32] = (uint8_t)K;
#ifdef MLKEM_CTL_NO_DOMAIN_BYTE
        /* NEGATIVE CONTROL: G(d) instead of G(d || k). This is the Kyber
         * round-3 behaviour, i.e. what a faithful port of older reference code
         * produces -- entirely self-consistent, interoperable with nothing. */
        sha3_512(g, in, 32);
#else
        sha3_512(g, in, 33);
#endif
        wipe(in, (int)sizeof in);
    }
    cp(rho, g, 32); cp(sigma, g + 32, 32);

    uint8_t nonce = 0;
    for (int i = 0; i < K; i++) poly_cbd_eta(&s.v[i], sigma, nonce++);
    for (int i = 0; i < K; i++) poly_cbd_eta(&e.v[i], sigma, nonce++);
    polyvec_ntt(&s);
    polyvec_ntt(&e);

    for (int i = 0; i < K; i++) {
        gen_matrix_row(row, rho, i, 0);
        polyvec_dot(&tmp, row, &s);
        poly_tomont(&tmp);                       /* undo the R^-1 basemul left */
        poly_add(&t.v[i], &tmp, &e.v[i]);
        poly_reduce(&t.v[i]);
    }

    for (int i = 0; i < K; i++) poly_tobytes(ek + 384 * i, &t.v[i]);
    cp(ek + 384 * K, rho, 32);
    for (int i = 0; i < K; i++) poly_tobytes(dkpke + 384 * i, &s.v[i]);

    wipe(g, (int)sizeof g); wipe(sigma, (int)sizeof sigma);
    wipe(&s, (int)sizeof s); wipe(&e, (int)sizeof e);
}

static void pke_encrypt(const uint8_t ek[MLKEM768_EK], const uint8_t m[32],
                        const uint8_t r[32], uint8_t ct[MLKEM768_CT])
{
    polyvec tvec, y;
    /* v doubles as the per-row scratch inside the u loop (it is not written for
     * real until after that loop), and e2 is reused to hold mu once it has been
     * folded into v. Two polynomials saved, 1,024 B off the deepest stack
     * chain, and no lifetime overlaps -- see the two comments at the use sites.
     * Named locals for both would read better; on this stack budget they do not
     * fit, and the alternative of a scratch pool is more machinery than a
     * 256-entry array deserves. */
    poly row[K], u, v, e2;
    const uint8_t *rho = ek + 384 * K;

    for (int i = 0; i < K; i++) poly_frombytes(&tvec.v[i], ek + 384 * i);

    uint8_t nonce = 0;
    for (int i = 0; i < K; i++) poly_cbd_eta(&y.v[i], r, nonce++);
    polyvec_ntt(&y);

    /* u = NTT^-1(A^T . y) + e1. The matrix row is generated inside the loop and
     * never held whole: Decaps re-runs this whole function and the kernel stack
     * is 32 KiB, so 4.6 KiB of matrix used once per row is not worth keeping.
     * Costs nothing in time -- each row is consumed immediately. */
    for (int i = 0; i < K; i++) {
        gen_matrix_row(row, rho, i, 1);
        polyvec_dot(&v, row, &y);                /* v as scratch: see decl */
        invntt(&v);
        poly_cbd_eta(&u, r, nonce++);            /* e1[i] */
        poly_add(&u, &v, &u);
        poly_reduce(&u);
        poly_compress(ct + (32 * DU) * i, &u, DU);
    }

    poly_cbd_eta(&e2, r, nonce++);
    polyvec_dot(&v, tvec.v, &y);
    invntt(&v);

    poly_add(&v, &v, &e2);

    /* mu = Decompress_1(ByteDecode_1(m)) -- a message bit becomes 0 or
     * round(q/2), which is exactly what Decompress_1 computes. Reuses e2's
     * storage: e2 was consumed by the add on the line above and is dead. */
    poly_decompress(&e2, m, 1);
    poly_add(&v, &v, &e2);
    poly_reduce(&v);
    poly_compress(ct + 32 * DU * K, &v, DV);

    wipe(&y, (int)sizeof y); wipe(&e2, (int)sizeof e2);
}

/* noinline is load-bearing, not a hint. Decaps calls decrypt and then encrypt,
 * one after the other -- but decrypt is static and called once, so the compiler
 * inlines it, and its ~4 KiB of polynomials then stays LIVE in the Decaps frame
 * while Encrypt runs beneath it. Measured with -fstack-usage: the deepest chain
 * was 15.6 KiB of a 32 KiB kernel thread stack, on the code path CLAUDE.md
 * already records overflowing a stack once (M11: the TLS redirect path went
 * into the page tables). Forcing the frame to be released before the
 * re-encryption starts costs one call instruction. Measured after:
 *   step_recv_sh 1576 + tls_compute_shared 136 + decaps 1336
 *   + pke_encrypt 6840 + poly_cbd_eta 504 + keccakf1600 424  =  10,816 B
 * against 15.6 KiB before, on a 32 KiB stack.
 * The alternative -- hoisting the buffers into the caller and passing them in
 * -- makes the peak the same but spreads decrypt's working set across two
 * functions, where the next person to add a local re-creates the problem. */
__attribute__((noinline))
static void pke_decrypt(const uint8_t dkpke[384 * K], const uint8_t ct[MLKEM768_CT],
                        uint8_t m[32])
{
    polyvec u, s;
    poly v, w;

    for (int i = 0; i < K; i++) poly_decompress(&u.v[i], ct + (32 * DU) * i, DU);
    poly_decompress(&v, ct + 32 * DU * K, DV);
    for (int i = 0; i < K; i++) poly_frombytes(&s.v[i], dkpke + 384 * i);

    polyvec_ntt(&u);
    polyvec_dot(&w, s.v, &u);
    invntt(&w);
    poly_sub(&w, &v, &w);
    poly_reduce(&w);
    poly_compress(m, &w, 1);

    wipe(&s, (int)sizeof s); wipe(&w, (int)sizeof w);
}

/* ------------------------------------------------------------- ML-KEM */

void mlkem768_keygen_derand(const uint8_t d[32], const uint8_t z[32],
                            uint8_t ek[MLKEM768_EK], uint8_t dk[MLKEM768_DK])
{
    pke_keygen(d, ek, dk);                                   /* dk[0 : 384k] */
    cp(dk + 384 * K, ek, MLKEM768_EK);                       /* || ek */
    sha3_256(dk + 384 * K + MLKEM768_EK, ek, MLKEM768_EK);   /* || H(ek) */
    cp(dk + 384 * K + MLKEM768_EK + 32, z, 32);              /* || z */
}

/* FIPS 203 7.2 modulus check: every 12-bit coefficient of ByteDecode12(ek) must
 * be < q, equivalently ByteEncode12(ByteDecode12(ek)) == ek. Without it an
 * attacker can produce many distinct byte strings that decode to one key, which
 * breaks the binding that H(ek) inside dk is relied on for. Checked on the
 * DECODED values rather than by re-encoding and comparing: the same test for a
 * third of the work. */
static int ek_modulus_ok(const uint8_t ek[MLKEM768_EK])
{
    uint16_t t[N];
    for (int i = 0; i < K; i++) {
        unpack(t, ek + 384 * i, 12);
        for (int j = 0; j < N; j++) if (t[j] >= Q) return 0;
    }
    return 1;
}

int mlkem768_encaps_derand(const uint8_t ek[MLKEM768_EK], const uint8_t m[32],
                           uint8_t ct[MLKEM768_CT], uint8_t ss[MLKEM768_SS])
{
    uint8_t g[64], in[64];
    if (!ek_modulus_ok(ek)) return -1;

    cp(in, m, 32);
    sha3_256(in + 32, ek, MLKEM768_EK);       /* H(ek) */
    sha3_512(g, in, 64);                      /* (K, r) = G(m || H(ek)) */

    pke_encrypt(ek, m, g + 32, ct);
    cp(ss, g, 32);

    wipe(g, (int)sizeof g); wipe(in, (int)sizeof in);
    return 0;
}

void mlkem768_decaps(const uint8_t dk[MLKEM768_DK], const uint8_t ct[MLKEM768_CT],
                     uint8_t ss[MLKEM768_SS])
{
    const uint8_t *dkpke = dk;
    const uint8_t *ek    = dk + 384 * K;
    const uint8_t *h     = dk + 384 * K + MLKEM768_EK;
    const uint8_t *z     = dk + 384 * K + MLKEM768_EK + 32;

    uint8_t mprime[32], g[64], in[64], kbar[32];
    uint8_t ct2[MLKEM768_CT];

    pke_decrypt(dkpke, ct, mprime);

    cp(in, mprime, 32);
    cp(in + 32, h, 32);
    sha3_512(g, in, 64);                      /* (K', r') = G(m2 || h) */

    /* Kbar = J(z || ct) = SHAKE256(z || ct, 32). Computed ALWAYS, not only on
     * failure -- computing it under an if would make the timing say which
     * branch ran, which is the oracle this construction exists to close. */
    {
        struct shake sh;
        shake256_init(&sh);
        shake_absorb(&sh, z, 32);
        shake_absorb(&sh, ct, MLKEM768_CT);
        shake_finalize(&sh);
        shake_squeeze(&sh, kbar, 32);
    }

    pke_encrypt(ek, mprime, g + 32, ct2);     /* re-encrypt */

    /* IMPLICIT REJECTION (FIPS 203 Alg.18 line 9). mask = 0xFF when the
     * ciphertext did NOT re-encrypt to itself, and the shared secret becomes
     * the pseudorandom Kbar. No branch, no error return: see mlkem.h for why an
     * error return here would be a decryption oracle. */
#ifdef MLKEM_CTL_NO_IMPLICIT_REJECT
    /* NEGATIVE CONTROL: hand back K2 unconditionally, i.e. never reject. Every
     * HONEST ciphertext still decapsulates correctly, so the keygen/encaps/
     * decaps checks stay green and ONLY the corrupted-ciphertext checks move.
     * That precision is the point -- it shows those checks are testing the
     * rejection rather than riding on the rest of the algorithm working. */
    (void)ct2; (void)ct_diff;
    uint8_t mask = 0x00;
#else
    uint8_t mask = ct_diff(ct, ct2, MLKEM768_CT);
#endif
    for (int i = 0; i < 32; i++)
        ss[i] = (uint8_t)((g[i] & (uint8_t)~mask) | (kbar[i] & mask));

    wipe(mprime, (int)sizeof mprime); wipe(g, (int)sizeof g);
    wipe(in, (int)sizeof in); wipe(kbar, (int)sizeof kbar); wipe(ct2, (int)sizeof ct2);
}
