#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate a deterministic, relocation-free PSL table; no network at build time."""
import argparse
import hashlib
import pathlib
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'tools/psl/public_suffix_list.dat'
DEST = ROOT / 'c/net/http/cookie_psl.inc'


def generate():
    raw = SOURCE.read_bytes()
    text = raw.decode('utf-8')
    if '// ===BEGIN ICANN DOMAINS===' not in text or '// ===BEGIN PRIVATE DOMAINS===' not in text:
        raise ValueError('PSL must include both ICANN and PRIVATE sections')
    rules = set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('//'):
            continue
        kind = '='
        if line.startswith('!'):
            kind, line = '!', line[1:]
        elif line.startswith('*.'):
            kind, line = '*', line[2:]
        # The upstream list is normalized U-label data. Encode Unicode labels
        # directly as A-labels: Python's builtin IDNA2003 would map sharp-s to
        # 'ss', silently changing a PSL boundary under modern IDNA/UTS46 URLs.
        labels = []
        for label in unicodedata.normalize('NFC', line.lower()).split('.'):
            if not label or '*' in label or '!' in label:
                raise ValueError('invalid PSL label: ' + repr(label))
            label = label if label.isascii() else 'xn--' + label.encode('punycode').decode('ascii')
            if len(label) > 63 or any(c not in 'abcdefghijklmnopqrstuvwxyz0123456789-_' for c in label):
                raise ValueError('invalid A-label: ' + repr(label))
            labels.append(label)
        rules.add(kind + '.'.join(labels))
    rules = sorted(rules)
    if len(rules) < 9000:
        raise ValueError('PSL unexpectedly short')
    version = next(x[3:] for x in text.splitlines() if x.startswith('// VERSION:'))
    commit = next(x[3:] for x in text.splitlines() if x.startswith('// COMMIT:'))
    lines = ['/* SPDX-License-Identifier: MPL-2.0',
             ' * GENERATED by tools/psl/generate.py; do not edit.',
             ' * Derived from tools/psl/public_suffix_list.dat (Mozilla Public License 2.0).',
             ' * ' + version, ' * ' + commit,
             ' * SHA256: ' + hashlib.sha256(raw).hexdigest(), ' */',
             'static const char cookie_psl_data[] =']
    offsets, offset = [], 0
    for rule in rules:
        lines.append('    "' + rule + '\\0"')
        offsets.append(offset)
        offset += len(rule) + 1
    lines[-1] += ';'
    lines.append('static const uint32_t cookie_psl_offsets[] = {')
    for pos in range(0, len(offsets), 12):
        lines.append('    ' + ', '.join(str(x) for x in offsets[pos:pos+12]) + ',')
    lines.extend(['};', '#define COOKIE_PSL_COUNT ' + str(len(rules)), ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate()
    if args.check:
        if DEST.read_text() != result:
            raise SystemExit('cookie PSL generated data is stale; run tools/psl/generate.py')
        print('cookie PSL snapshot and generated data agree')
    else:
        DEST.write_text(result)
        print('generated', DEST)
