#ifndef LOGIT_SCRIPT_H
#define LOGIT_SCRIPT_H

#include <stdint.h>

/* Script and Joining_Type properties, run segmentation, and Arabic joining.
 *
 * This is the half of shaping that needs no font: it answers "which script is
 * this character, which way does it run, and which of the four Arabic joining
 * forms does it take here". c/lib/text/shape.c consumes the answers; nothing
 * here opens a font file.
 *
 * The property tables are generated by tests/unit/bidi_gen.py from the UCD
 * (Scripts.txt, extracted/DerivedJoiningType.txt) into script_data.inc.
 *
 * Zero allocation, zero global state, no libc -- callable from the kernel, from
 * ring 3, and from several threads at once.
 */

/* Scripts the shaper names. The order is fixed by bidi_gen.py's SCRIPTS list;
 * anything the UCD calls something else collapses to SC_UNKNOWN, which is the
 * honest answer -- we do not claim to shape what we do not name. */
enum {
    SC_UNKNOWN = 0, SC_COMMON, SC_INHERITED, SC_LATIN, SC_GREEK, SC_CYRILLIC,
    SC_ARABIC, SC_HEBREW, SC_SYRIAC, SC_THAANA, SC_NKO, SC_DEVANAGARI,
    SC_BENGALI, SC_GURMUKHI, SC_GUJARATI, SC_ORIYA, SC_TAMIL, SC_TELUGU,
    SC_KANNADA, SC_MALAYALAM, SC_SINHALA, SC_THAI, SC_LAO, SC_TIBETAN,
    SC_MYANMAR, SC_KHMER, SC_HANGUL, SC_HAN, SC_HIRAGANA, SC_KATAKANA,
    SC_ARMENIAN, SC_GEORGIAN, SC_ETHIOPIC, SC_MONGOLIAN, SC_NSCRIPT
};

/* Joining_Type. The order is fixed by bidi_gen.py's JOINING list. */
enum { JOIN_U = 0, JOIN_C, JOIN_D, JOIN_R, JOIN_L, JOIN_T };

/* The Arabic joining forms, numbered in the order the OpenType features are
 * applied (isol, fina, fin2, fin3, medi, med2, init). shape.c uses the value as
 * an index into that feature array, so the numbering is load bearing.
 * fin2/fin3/med2 exist only for Syriac. */
enum { AJ_ISOL = 0, AJ_FINA, AJ_FIN2, AJ_FIN3, AJ_MEDI, AJ_MED2, AJ_INIT,
       AJ_NONE, AJ_NFORM = AJ_NONE };

/* Script of a code point (SC_*). */
int script_of(uint32_t cp);

/* Joining_Type of a code point (JOIN_*). */
int script_joining_type(uint32_t cp);

/* Does this script run right to left?  Answers for the scripts we name; a
 * script we do not name is left to right. */
int script_is_rtl(int script);

/* The OpenType script tag, e.g. FONT_TAG('a','r','a','b'). SC_COMMON /
 * SC_INHERITED / SC_UNKNOWN yield 'DFLT'; shape.c falls back through
 * 'DFLT' -> 'dflt' -> 'latn' when the font does not carry the tag. */
uint32_t script_ot_tag(int script);

/* Does this script need the cursive-joining (Arabic-family) shaper?  Arabic,
 * Syriac, N'Ko and Mongolian do; everything else we name uses the plain path.
 * Indic/Khmer/Myanmar reordering is NOT implemented and this returns 0 for
 * them, so they get the plain path and are shaped incorrectly -- named as a
 * gap rather than silently wrong. */
int script_is_cursive(int script);

/* ------------------------------------------------------------------ runs -- */

struct text_run {
    int start, len;      /* code point indices into the input */
    int script;          /* SC_* */
    int rtl;             /* 0/1, from the bidi level when levels are supplied */
    int level;           /* bidi level, or 0 */
    int vis;             /* scratch: shape_line's visual order key */
    int font;            /* whatever the caller's fontsel returned */
};

/* Split `cps` into runs of one script, one direction and one font.
 *
 *   levels   per-code-point bidi levels from bidi_resolve(), or NULL for "all
 *            level 0". A level change always starts a new run.
 *   fontsel  called per code point to choose a font index, or NULL for "one
 *            font". A font change always starts a new run.
 *
 * Common and Inherited characters extend the run they are in; a run that has
 * seen nothing but Common/Inherited adopts the first real script that follows.
 * Runs come back in LOGICAL order -- reordering them is bidi_reorder's job.
 *
 * Returns the number of runs the text has, which may exceed `cap`; only `cap`
 * were written. */
int script_runs(const uint32_t *cps, int n, const uint8_t *levels,
                int (*fontsel)(uint32_t cp, void *ctx), void *ctx,
                struct text_run *out, int cap);

/* --------------------------------------------------------- Arabic joining -- */

/* Per-code-point joining form (AJ_*), by the state machine of UAX #9's
 * companion, the Arabic cursive joining rules -- the same table HarfBuzz uses,
 * including the two Syriac joining groups (Alaph, Dalath/Rish) that need their
 * own states. Transparent characters (marks) get AJ_NONE.
 *
 * `forms` receives n bytes. */
void script_arabic_joining(const uint32_t *cps, int n, uint8_t *forms);

#endif /* LOGIT_SCRIPT_H */
