/* matmul.c -- the operation an inference pass is mostly made of.
 *
 * WHY THE LOOPS LOOK LIKE THIS, and every reason is a measured property of
 * this machine rather than a habit carried in from elsewhere.
 *
 * FOUR LANES, NOT FOUR SCALARS -- and the difference is the whole of this
 * file's performance history, so it is written out rather than summarised.
 *
 * A single running sum makes every iteration wait for the previous add to
 * retire, so the loop ran at one add per ADDSS latency instead of one per
 * cycle. Four independent partial sums break that chain. That reasoning was
 * right; the SHAPE it was written in was wrong, and the assembly said so:
 *
 *   `float s0,s1,s2,s3;` with s_l += row[j+l]*x[j+l], j += 4
 *   -> clang 21 emits, per 8 elements: 4 movups, 2 mulps, 4 addps, and
 *      FOUR shufps, keeping the four sums as TWO 2-lane vectors (the final
 *      fold reads only lanes 0 and 1). Half the register is idle and the
 *      shuffles are pure overhead.
 *
 * Two plain-C attempts to fix it, both measured, both rejected:
 *
 *   `float s = 0; for (j..k) s += row[j]*x[j];` -- the "just delete the four
 *   accumulators" answer. It compiles to ZERO mulps: a serial f32 reduction
 *   may not be reassociated without -ffast-math, so the vectoriser is not
 *   permitted to touch it and the loop is fully scalar. Slower, not faster.
 *
 *   `float s[4]` with an inner l-loop -- byte-for-byte the SAME bad output as
 *   the four scalars, four shufps and all.
 *
 * So the four lanes are stated as one register, in SSE2 intrinsics. Two
 * spellings of that were compiled and DIFFED at the device target
 * (--target=x86_64-elf -ffreestanding -msse -msse2 -O2): <emmintrin.h> and a
 * GNU `vector_size(16)` typedef produce an IDENTICAL instruction stream, so
 * the choice is not a performance decision. The intrinsics are used because
 * `_mm_loadu_ps` SAYS unaligned at the load, where the vector-typedef form
 * carries it as an `aligned(4)` attribute on the type -- and dropping that
 * attribute does not slow the code down, it emits movaps and FAULTS on the
 * first weight row that is not 16-aligned. A trap that is spelled out at every
 * use beats one parked in a typedef.
 *
 * SSE2 AND NOTHING ABOVE, stated once: no AVX on this target, no FMA, and no
 * runtime dispatch pretending otherwise. Four f32 lanes is the whole machine.
 * <emmintrin.h> is a compiler-provided header and needs no libc, which is why
 * it is available in a -ffreestanding -nostdlib build (verified, not assumed).
 *
 * THE ARITHMETIC IS UNCHANGED, BIT FOR BIT, and that is what let this land.
 * Lane l accumulates exactly the elements old s_l did (j+l for j = 0,4,8,...),
 * in the same order, and the fold is the same (s0+s1)+(s2+s3). So the model's
 * generated bytes do not move -- which is the gate this line is held to, and
 * not something a "faster matvec" gets to spend.
 *
 *   measured, 29-matvec mix of one token (823,296 MACs), i7-14700KF, clang -O2:
 *     four scalars   267,423 cycles   0.325 cyc/MAC
 *     four lanes     171,604 cycles   0.208 cyc/MAC     1.56x
 *
 * REJECTED, WITH ITS NUMBER: two vector accumulators over 8 elements per
 * iteration measures 159,691 cycles (0.194 cyc/MAC, a further 7%). It is not
 * taken because lane l would then sum blocks 0,8,16,... and 4,12,20,...
 * separately before folding -- a different summation order, so different last
 * bits, so different generated bytes. 7% of a kernel is not worth spending the
 * one property that makes a change here checkable.
 *
 * ROW-MAJOR AND CONTIGUOUS ALONG k. Both operands of the dot product walk
 * forward through memory. For the quantised path that matters more than the
 * arithmetic does: a matvec reads the whole weight matrix once and does two
 * operations per byte, so it is bound by memory bandwidth and not by the
 * multiplier. That is also the entire argument for int8 -- it is four times
 * less to read, and on this machine the read is the cost.
 */
#include <emmintrin.h>
#include "nn.h"

/* The horizontal fold, written once so the two matvecs below cannot drift
 * apart in the one place where the ORDER of the additions is observable.
 *
 * `_mm_loadu_ps(p)` puts p[i] in lane i, so lane i of the accumulator holds
 * exactly the indices the old scalar s_i held (j with j%4 == i). Folding them
 * as (s0+s1)+(s2+s3) is what the four scalar accumulators did. A left-to-right
 * ((s0+s1)+s2)+s3 would be equally defensible and would move the last bits of
 * every logit in the model, so the order is pinned here rather than left to
 * whichever reduction a future reader finds natural. */
static inline float nn_v4_sum(__m128 a)
{
    float s[4];
    _mm_storeu_ps(s, a);
    return (s[0] + s[1]) + (s[2] + s[3]);
}

void nn_matvec_f32(float *y, const float *w, const float *x, int n, int k)
{
    if (!y || !w || !x || n <= 0 || k <= 0) return;
    for (int i = 0; i < n; i++) {
        const float *row = w + (size_t)i * k;
        __m128 acc = _mm_setzero_ps();
        int j = 0;
        for (; j + 3 < k; j += 4)
            acc = _mm_add_ps(acc, _mm_mul_ps(_mm_loadu_ps(row + j),
                                             _mm_loadu_ps(x + j)));
        float s = nn_v4_sum(acc);
        /* The tail is the same left-to-right scalar sum the four-accumulator
         * version ended with, appended to the same fold -- so a k that is not
         * a multiple of 4 (w2 is [dim, 344] and 344 is, but a future hidden
         * size need not be) lands on the identical value. */
        for (; j < k; j++) s += row[j] * x[j];
        y[i] = s;
    }
}

void nn_matvec_q8(float *y, const int8_t *q, const float *scale,
                  const float *x, int n, int k)
{
    if (!y || !q || !scale || !x || n <= 0 || k <= 0) return;
    for (int i = 0; i < n; i++) {
        const int8_t *row = q + (size_t)i * k;
        /* The int8 weight is widened to float and multiplied by the f32
         * activation, then the ROW's scale is applied once at the end.
         *
         * THE ACCUMULATION STAYS IN FLOAT, and the reason is a gate rather
         * than a preference. An int32 accumulation would be exact, but it
         * needs the ACTIVATIONS quantised too -- a second quantisation, with
         * its own per-token scale and its own error, on the one tensor that
         * changes every token. That error lands on lm_infer_test's "q8 and
         * f32 differ by the quantisation error and no more", whose bound is
         * derived from the WEIGHT quantisation alone; passing it would mean
         * widening the bound, which is not a faster kernel, it is a weaker
         * check. (nn.h's dtype note claimed this loop already accumulated in
         * integer. It never did, and the sentence is corrected there.)
         *
         * It was never the accuracy standing between this kernel and its
         * speed anyway -- it was the WIDENING, done one value at a time:
         *
         *   29-matvec mix of one token (823,296 MACs), i7-14700KF, clang -O2:
         *     scalar convert + four scalar sums   1,118,820 cyc  1.359/MAC
         *     four lanes, four values widened
         *       per iteration                       275,126 cyc  0.334/MAC
         *                                                        4.06x
         *
         * The brace initialiser below is enough to get it: clang lowers it to
         * SSE2's sign-extend idiom -- movd, punpcklbw, punpcklwd, psrad $24,
         * cvtdq2ps -- four values per pass. SSE4.1 does it in one instruction
         * (pmovsxbd) and this target does not have SSE4.1, so that sequence is
         * the floor, and no intrinsic would improve on what the compiler
         * already emits.
         *
         * WORTH KNOWING BEFORE REACHING FOR Q8 FOR SPEED: even fixed, this
         * kernel is 0.334 cyc/MAC against the f32 path's 0.208. Reading four
         * times less memory buys nothing at the reference model's size,
         * because those weights already sit in cache -- the widening is pure
         * added work. Q8 earns its place on the argument nn.h actually makes,
         * which is that a model MUST FIT in 512 MiB, and not on throughput. */
        __m128 acc = _mm_setzero_ps();
        int j = 0;
        for (; j + 3 < k; j += 4) {
            /* _mm_setr_ps, not _mm_set_ps: setr takes its arguments in LANE
             * order and set takes them reversed. Both compile, both look
             * right, and the reversed one silently pairs weight j+3 with
             * activation j+0 -- a matvec that returns plausible numbers for
             * the wrong reason. The memcmp gate against the pre-change kernel
             * is what would catch it, and it is cheaper not to write it. */
            __m128 wv = _mm_setr_ps((float)row[j + 0], (float)row[j + 1],
                                    (float)row[j + 2], (float)row[j + 3]);
            acc = _mm_add_ps(acc, _mm_mul_ps(wv, _mm_loadu_ps(x + j)));
        }
        float s = nn_v4_sum(acc);
        for (; j < k; j++) s += (float)row[j] * x[j];
        y[i] = s * scale[i];
    }
}

void nn_matmul_f32(float *c, const float *a, const float *b, int m, int k, int n)
{
    if (!c || !a || !b || m <= 0 || k <= 0 || n <= 0) return;
    /* i-k-j, not i-j-k. The naive ordering walks B down a column, which is a
     * stride of n floats per step and a cache miss per element once n is
     * large. This one keeps both B and C moving forward along a row, at the
     * cost of writing C k times instead of once -- which is a good trade
     * whenever k is smaller than the cache, and is every shape in a
     * transformer. */
    for (int i = 0; i < m; i++) {
        float *crow = c + (size_t)i * n;
        for (int j = 0; j < n; j++) crow[j] = 0.0f;
        const float *arow = a + (size_t)i * k;
        for (int p = 0; p < k; p++) {
            float av = arow[p];
            if (av == 0.0f) continue;          /* the padding rows of a batch */
            const float *brow = b + (size_t)p * n;
            for (int j = 0; j < n; j++) crow[j] += av * brow[j];
        }
    }
}

void nn_quantize_q8(int8_t *q, float *scale, const float *w, int n, int k)
{
    if (!q || !scale || !w || n <= 0 || k <= 0) return;
    for (int i = 0; i < n; i++) {
        const float *row = w + (size_t)i * k;
        float amax = 0.0f;
        for (int j = 0; j < k; j++) {
            float a = row[j] < 0.0f ? -row[j] : row[j];
            if (a > amax) amax = a;
        }
        /* An all-zero row gets scale 0 and reconstructs EXACTLY, because every
         * value in it is zero. Dividing by amax here would be a division by
         * zero producing inf or NaN scales that then poison a whole output
         * channel -- and an all-zero row is not exotic: it is what a pruned or
         * an unused embedding slot looks like. */
        float s = amax > 0.0f ? amax / 127.0f : 0.0f;
        scale[i] = s;
        float inv = s > 0.0f ? 1.0f / s : 0.0f;
        int8_t *qr = q + (size_t)i * k;
        for (int j = 0; j < k; j++) {
            float v = row[j] * inv;
            /* Round half away from zero, then clamp. The clamp is not
             * defensive dressing: rounding amax*inv gives exactly 127.0 in
             * exact arithmetic and can give 127.0000008 after two f32
             * roundings, which truncates to 127 but would be 128 -- an
             * overflow to -128 -- under a different rounding. */
            int r = (int)(v < 0.0f ? v - 0.5f : v + 0.5f);
            if (r > 127) r = 127;
            if (r < -127) r = -127;
            qr[j] = (int8_t)r;
        }
    }
}

void nn_dequantize_q8(float *w, const int8_t *q, const float *scale,
                      int n, int k)
{
    if (!w || !q || !scale || n <= 0 || k <= 0) return;
    for (int i = 0; i < n; i++) {
        float s = scale[i];
        const int8_t *qr = q + (size_t)i * k;
        float *wr = w + (size_t)i * k;
        for (int j = 0; j < k; j++) wr[j] = (float)qr[j] * s;
    }
}
