#ifndef LOGIT_AES_GCM_SIV_H
#define LOGIT_AES_GCM_SIV_H

#include <stdint.h>

/* AES-GCM-SIV (RFC 8452): a nonce-misuse-resistant AEAD.
 *
 * NOT WIRED INTO ANYTHING. No consumer in this tree calls these functions --
 * see the header of aes_gcm_siv.c for why that is deliberate. This file is a
 * library primitive, gated by tests/unit/aes_gcm_siv_test.c against RFC 8452
 * Appendix C (50 official vectors: C.1 AES-128 x24, C.2 AES-256 x24, C.3
 * counter-wrap x2) plus the standalone POLYVAL example in section 7.
 *
 * WHY THIS AND NOT JUST AES-GCM. AES-GCM's authentication key derives its
 * strength entirely from the nonce never repeating under one key: repeat a
 * nonce and the attacker recovers the GHASH authentication key outright,
 * which is total forgery, not "one leaked bit". GCM-SIV's tag is a
 * deterministic function of (key, nonce, plaintext, aad) via POLYVAL -- so a
 * repeated (key, nonce) pair with the SAME plaintext produces the same
 * ciphertext (a real but bounded leak: an observer learns the two messages
 * were equal), and a repeated pair with DIFFERENT plaintexts produces
 * unrelated ciphertexts and gives the attacker nothing more. That is the
 * property named "nonce misuse resistant". Anywhere a nonce is derived
 * (hashed, counted per-key-not-globally, generated by a process that might
 * repeat) rather than guaranteed unique by a single counter, this is the
 * primitive to reach for instead of GCM. */

/* POLYVAL (RFC 8452 section 3): the authenticator GCM-SIV is built from.
 * S_0 = 0; S_j = dot(S_{j-1} + X_j, H) for j = 1..s, where the X_j are the
 * `nblocks` consecutive 16-byte field elements at `blocks`. Exported (rather
 * than kept static) specifically so the standalone worked example in RFC
 * 8452 section 7 can be asserted directly: calling polyval(b, a, 1, out)
 * computes exactly dot(a, b) with S_0=0, X_1=a, H=b -- the one-block case of
 * the general iteration IS the worked example, so no separate "dot" entry
 * point is needed to test it.
 *
 * POLYVAL IS NOT GHASH, and the difference is a byte-order mirror plus a
 * trailing *x -- see aes_gcm_siv.c's top comment before reaching for GCM's
 * gf_mul (aes_backend.h) here. This function has its own field arithmetic. */
void polyval(const uint8_t H[16], const uint8_t *blocks, int nblocks, uint8_t out[16]);

/* AEAD_AES_128_GCM_SIV / AEAD_AES_256_GCM_SIV (RFC 8452 section 6). `nonce`
 * is always 96 bits, as GCM-SIV defines no other length -- unlike AES-GCM,
 * which is a footgun this construction was partly designed to remove. `ct`
 * and `pt` may alias `pt`/`ct` respectively (both are consumed left-to-right,
 * 16 bytes of keystream at a time, same as the CTR helpers elsewhere in this
 * directory). Negative lengths return without writing anything, the same
 * convention aesgcm.c and chacha20poly1305.c use. */
void aes128_gcm_siv_seal(const uint8_t key[16], const uint8_t nonce[12],
                         const uint8_t *aad, int aadlen,
                         const uint8_t *pt, int len, uint8_t *ct, uint8_t tag[16]);
/* Returns 0 and writes `pt` only if the tag verifies; returns -1 and writes
 * NOTHING otherwise -- decryption never hands back unauthenticated
 * plaintext, the same rule aesgcm.c's gcm_open documents. */
int  aes128_gcm_siv_open(const uint8_t key[16], const uint8_t nonce[12],
                         const uint8_t *aad, int aadlen,
                         const uint8_t *ct, int len, const uint8_t tag[16], uint8_t *pt);

void aes256_gcm_siv_seal(const uint8_t key[32], const uint8_t nonce[12],
                         const uint8_t *aad, int aadlen,
                         const uint8_t *pt, int len, uint8_t *ct, uint8_t tag[16]);
int  aes256_gcm_siv_open(const uint8_t key[32], const uint8_t nonce[12],
                         const uint8_t *aad, int aadlen,
                         const uint8_t *ct, int len, const uint8_t tag[16], uint8_t *pt);

#endif /* LOGIT_AES_GCM_SIV_H */
