/* GENERATED by tools/gen_abi.py from include/abi/logit_calls.abi -- DO NOT EDIT.
 *
 * The kernel side of the packed syscall arguments. fsroot/as/lib/abi.as packs
 * these fields; these macros unpack them, and both come from the same three
 * numbers in the .abi file -- so where a field lives is written once.
 * c/kernel/gui/wm.c unpacks through these macros, which makes the convention
 * single-sourced end to end rather than merely generated on one side. */
#ifndef LOGIT_PACK_H
#define LOGIT_PACK_H


/* SYS_GUI_CREATE arg b: w<<16 | h */
#define LOGIT_GUI_CREATE_B_W(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_CREATE_B_H(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_RECT arg a: x<<16 | y */
#define LOGIT_GUI_RECT_A_X(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_RECT_A_Y(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_RECT arg b: w<<16 | h */
#define LOGIT_GUI_RECT_B_W(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_RECT_B_H(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_TEXT arg a: x<<16 | y */
#define LOGIT_GUI_TEXT_A_X(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_TEXT_A_Y(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_TEXT_MONO arg a: x<<16 | y */
#define LOGIT_GUI_TEXT_MONO_A_X(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_TEXT_MONO_A_Y(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_TEXT_MONO arg b: cell<<24 | color */
#define LOGIT_GUI_TEXT_MONO_B_CELL(v) ((int)(((unsigned long long)(v) >> 24) & 0xFFULL))
#define LOGIT_GUI_TEXT_MONO_B_COLOR(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFFFULL))

/* SYS_GUI_ICON arg a: x<<16 | y */
#define LOGIT_GUI_ICON_A_X(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_ICON_A_Y(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_ICON arg b: id<<16 | px */
#define LOGIT_GUI_ICON_B_ID(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_ICON_B_PX(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_RRECT arg a: x<<16 | y */
#define LOGIT_GUI_RRECT_A_X(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_RRECT_A_Y(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_RRECT arg b: w<<16 | h */
#define LOGIT_GUI_RRECT_B_W(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_RRECT_B_H(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_RRECT arg c: radius<<24 | color */
#define LOGIT_GUI_RRECT_C_RADIUS(v) ((int)(((unsigned long long)(v) >> 24) & 0xFFULL))
#define LOGIT_GUI_RRECT_C_COLOR(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFFFULL))

/* SYS_GUI_GLASS arg a: x<<16 | y */
#define LOGIT_GUI_GLASS_A_X(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_GLASS_A_Y(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_GLASS arg b: w<<16 | h */
#define LOGIT_GUI_GLASS_B_W(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_GLASS_B_H(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_GLASS arg c: radius<<32 | tr<<24 | tg<<16 | tb<<8 | ta */
#define LOGIT_GUI_GLASS_C_RADIUS(v) ((int)(((unsigned long long)(v) >> 32) & 0xFFULL))
#define LOGIT_GUI_GLASS_C_TR(v) ((int)(((unsigned long long)(v) >> 24) & 0xFFULL))
#define LOGIT_GUI_GLASS_C_TG(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFULL))
#define LOGIT_GUI_GLASS_C_TB(v) ((int)(((unsigned long long)(v) >> 8) & 0xFFULL))
#define LOGIT_GUI_GLASS_C_TA(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFULL))

/* SYS_GUI_CLIP arg a: x<<16 | y */
#define LOGIT_GUI_CLIP_A_X(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_CLIP_A_Y(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_CLIP arg b: w<<16 | h */
#define LOGIT_GUI_CLIP_B_W(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_CLIP_B_H(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_GUI_WIN_MIN arg a: w<<16 | h */
#define LOGIT_GUI_WIN_MIN_A_W(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_GUI_WIN_MIN_A_H(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_SOCK_OPEN arg b: port<<16 | flags */
#define LOGIT_SOCK_OPEN_B_PORT(v) ((int)(((unsigned long long)(v) >> 16) & 0xFFFFULL))
#define LOGIT_SOCK_OPEN_B_FLAGS(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFULL))

/* SYS_TEXT_MEASURE arg c: px<<1 | mono */
#define LOGIT_TEXT_MEASURE_C_PX(v) ((int)(((unsigned long long)(v) >> 1) & 0x7FFFFFFFULL))
#define LOGIT_TEXT_MEASURE_C_MONO(v) ((int)(((unsigned long long)(v) >> 0) & 0x1ULL))

/* SYS_FUTEX arg b: timeout<<32 | val */
#define LOGIT_FUTEX_B_TIMEOUT(v) ((int)(((unsigned long long)(v) >> 32) & 0xFFFFFFFFULL))
#define LOGIT_FUTEX_B_VAL(v) ((int)(((unsigned long long)(v) >> 0) & 0xFFFFFFFFULL))

#endif /* LOGIT_PACK_H */
