/* js_cssom.c -- the CSSOM: CSSOM-View geometry, document.styleSheets, the CSS
 * namespace object, matchMedia, and the FontFaceSet stub.
 *
 * WHY THIS FILE EXISTS, in the form of a measurement rather than a wish. A WPT
 * run over the vendored corpus reports 1,926 files under css/ that never
 * completed the harness -- 88% of every harness death in the whole corpus, and
 * 28% of every CSS test file we have. A file that dies reports nothing, so
 * every subtest inside it is invisible and the CSS denominator is a fiction.
 *
 * Reading WHY a sample of them died, rather than assuming, produced a ranked
 * table (in build/cssom/, regenerated by `make wpt-cssom-rank`). The
 * assumption going in was that they die inside the CSSOM -- getComputedStyle,
 * cssRules, setProperty. That assumption was mostly WRONG, and the table is
 * the useful part of this work whether or not the code is. The two entries
 * this file is aimed at:
 *
 *   1049  the harness completed with ZERO subtests
 *          -- of which ~765 are `<body onload="checkLayout('.target')">`.
 *             The load event fires on the WINDOW; `<body onload>` is a WINDOW
 *             handler, not a body one; nothing here reflected it. So
 *             checkLayout was never called, no test() was ever registered,
 *             and the file timed out empty. Once it IS called it immediately
 *             needs offsetWidth, offsetTop, clientWidth, scrollWidth and
 *             getBoundingClientRect -- and of those, only the last existed.
 *     57  `CSS is not defined` -- no CSS namespace object at all, so a
 *          feature detect (`CSS.supports(...)`) threw on line one.
 *     10  `cannot read property 'cssRules' of undefined` -- document.styleSheets.
 *
 * (The ranking at the time also had 165 files on `document.fonts.ready`. The
 * web-API line fixed that one concurrently; see the note on SHIM_FONTS. It is
 * not in this file's numbers.)
 *
 * WHAT IS HONEST ABOUT THE GEOMETRY, said before the code and not after.
 * layout.c produces a FLAT display list, not a box tree. An element's border
 * box is recovered from it two ways: EXACTLY, when layout emitted the
 * element's own IT_RECT (any background or border does that), and otherwise as
 * the union of the boxes its subtree painted -- which is the INK extent, so a
 * background-less <div> reports the width of its widest line rather than its
 * containing block's width. That is the same compromise js_dom.c's
 * getBoundingClientRect already documents, for the same reason: making layout
 * emit an invisible rect per element would cost a display-list entry for every
 * node on every page to serve a call most pages never make. It is recorded
 * here as a KNOWN WRONG ANSWER for a class of elements, not as a rounding
 * error.
 *
 * And the numbers are only as good as the last layout. A real browser flushes
 * a pending reflow on any of these reads; so does this (see flush_layout) --
 * but only when layout.c is linked. The host WPT runner links neither layout.c
 * nor a font backend, so there every box is 0x0 and the revived check-layout
 * files complete and then FAIL. That is strictly better than dying, because a
 * failing subtest is IN the denominator and a dead file is not. It is not the
 * same as passing. Do not read a revived file as a fixed one.
 */

#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "quickjs.h"
#include "dom.h"
#include "css.h"
/* The real struct, not a hand-copied prefix of it. The first attempt declared
 * a five-int-and-a-pointer struct to avoid pulling img.h in behind layout.h,
 * and it read the display list at the WRONG STRIDE -- the prefix was right and
 * sizeof was not, which is a class of bug a prefix declaration invites and
 * cannot be reviewed out of. */
#include "layout.h"
#include "js_dom.h"
#include "js_cssom.h"

/* layout.c is linked into the browser and into the CSS audit, and is NOT
 * linked into the host WPT runner or the DOM unit tests. Weak, exactly as
 * js_dom.c declares the same two, so this file builds and behaves in both. */
extern void  layout_page(struct node *root, int canvas_w) __attribute__((__weak__));
extern int   layout_count(void) __attribute__((__weak__));
extern const struct item *layout_items(void) __attribute__((__weak__));

/* ==========================================================================
 * From a JSValue back to a struct node
 *
 * js_dom.c's node_of() is static and js_dom.c is another line's file, so the
 * mapping is rebuilt from the other end: a node that has ever been wrapped
 * stores its JSObject* in the weak `jsw` slot, so the wrapper a script holds
 * identifies its node uniquely. The walk is over the document, which would be
 * O(nodes) per property read -- hence the one-entry cache in front of it,
 * which is enough because the access pattern is invariably
 * `el.offsetWidth; el.offsetHeight; el.offsetTop` on the same element.
 * ========================================================================== */

static struct node *g_cache_node;
static void        *g_cache_ptr;

static struct node *find_by_jsw(struct node *n, void *p)
{
    for (; n; n = n->next) {
        if (n->jsw == p) return n;
        if (n->first_child) {
            struct node *r = find_by_jsw(n->first_child, p);
            if (r) return r;
        }
    }
    return 0;
}

static struct node *node_from(JSValueConst v)
{
    if (!JS_IsObject(v)) return 0;
    void *p = JS_VALUE_GET_PTR(v);
    if (p && p == g_cache_ptr && g_cache_node && g_cache_node->jsw == p)
        return g_cache_node;
    struct node *root = js_dom_root();
    if (!root) return 0;
    struct node *r = (root->jsw == p) ? root : find_by_jsw(root->first_child, p);
    if (r) { g_cache_ptr = p; g_cache_node = r; }
    return r;
}

/* The wrapper js_dom.c already made for a node, or null. This file must never
 * mint a wrapper of its own: two wrappers for one node makes
 * `el.offsetParent === document.body` false, which is worse than answering
 * null. A page reaches an element through the DOM before measuring it, and
 * that is what wraps it. */
static JSValue wrapper_of(JSContext *ctx, struct node *n)
{
    (void)ctx;
    if (!n || !n->jsw) return JS_NULL;
    return JS_DupValue(ctx, JS_MKPTR(JS_TAG_OBJECT, n->jsw));
}

/* ==========================================================================
 * Reflow on read
 *
 * A geometry read is the one place a browser is REQUIRED to make layout
 * current -- "forced synchronous layout" is the name of the performance
 * problem, and it is a problem precisely because the answer would otherwise be
 * stale.
 *
 * Two guards keep the flush from being a disaster. It runs only when layout.c
 * is linked at all, and only when there is either no display list yet or the
 * DOM has been mutated since the last one. js_dom_dirty() is the EMBEDDER's
 * flag: this reads it and never clears it, because browser.c owns the clear
 * and stealing it would make the browser skip its own re-style. The
 * `g_saw_dirty` edge is what stops a hundred reads inside one dirty episode
 * costing a hundred reflows: one per episode, then quiet.
 *
 * js_cssom_layouts() counts them so a test can assert BOTH directions -- that
 * mutate-then-measure did re-lay-out, and that measure-measure-measure did
 * not. A counter says that deterministically; a timing assertion would not.
 *
 * WHAT A REFLOW IS, is the embedder's business and not this file's. A style
 * mutation changes the STYLE ATTRIBUTE; the boxes only move once the cascade
 * has run again, and the cascade needs the document's stylesheet set -- which
 * browser.c assembles (external sheets, var() expansion, the css_extra post
 * pass) and this file has no access to. So the embedder registers what a
 * reflow means, and the fallback with nobody registered is layout alone.
 *
 * That fallback is a REAL limitation, not a formality: with no hook, geometry
 * after an el.style write reflects the previous cascade. It is stated here
 * rather than hidden because a wrong number is worse than a missing one, and
 * because "we re-laid-out" reads as "we re-styled" if nobody writes it down.
 * ========================================================================== */

static int g_layouts;
static int g_saw_dirty;
static void (*g_reflow)(void);
int js_cssom_layouts(void) { return g_layouts; }
void js_cssom_set_reflow(void (*fn)(void)) { g_reflow = fn; }

static int have_layout(void)
{
#ifdef CSSOM_NEGCTL_NOGEOM
    /* THE OTHER NEGATIVE CONTROL (tests/cssom.mk). Every accessor is still
     * installed and every one answers 0 -- which is not a hypothetical, it is
     * exactly the state a build with layout.c unlinked is in, and therefore
     * exactly the state the host WPT runner is in. `make test-cssom-negctl`
     * requires the suite to FAIL here, and that is what proves the geometry
     * assertions are reading real boxes rather than agreeing 0 == 0. */
    return 0;
#endif
    return &layout_count != 0 && &layout_items != 0 && &layout_page != 0;
}

static void flush_layout(void)
{
    if (!have_layout()) return;
    struct node *root = js_dom_root();
    if (!root) return;
    int dirty = js_dom_dirty();
    int need = (layout_count() <= 0) || (dirty && !g_saw_dirty);
    g_saw_dirty = dirty;
    if (!need) return;
    g_layouts++;
    if (g_reflow) { g_reflow(); return; }
    int w = css_media_width();
    layout_page(root, w > 0 ? w : 800);
}

/* ==========================================================================
 * An element's boxes, out of the flat display list
 * ========================================================================== */

static int in_subtree(const struct node *root, const struct node *n)
{
    for (; n; n = n->parent) if (n == root) return 1;
    return 0;
}

static const struct item *items(int *n)
{
    *n = 0;
    if (!have_layout()) return 0;
    int c = layout_count();
    if (c <= 0) return 0;
    *n = c;
    return (const struct item *)layout_items();
}

/* The BORDER box. Exact when layout drew the element itself; the subtree ink
 * union otherwise -- see the file header for why that second case is a known
 * wrong answer rather than an approximation. Returns 0 when the element
 * produced no box at all, which the CSSOM reports as zero everywhere. */
static int border_box(struct node *el, int *ox, int *oy, int *ow, int *oh)
{
    *ox = *oy = *ow = *oh = 0;
    if (!el) return 0;
    int n = 0;
    const struct item *it = items(&n);
    if (!it) return 0;
    for (int i = 0; i < n; i++)
        if (it[i].node == el && it[i].type == IT_RECT) {
            *ox = it[i].x; *oy = it[i].y; *ow = it[i].w; *oh = it[i].h;
            return 1;
        }
    int x0 = 0, y0 = 0, x1 = 0, y1 = 0, got = 0;
    for (int i = 0; i < n; i++) {
        if (!it[i].node || !in_subtree(el, it[i].node)) continue;
        int ax = it[i].x, ay = it[i].y, bx = ax + it[i].w, by = ay + it[i].h;
        if (!got) { x0 = ax; y0 = ay; x1 = bx; y1 = by; got = 1; continue; }
        if (ax < x0) x0 = ax;
        if (ay < y0) y0 = ay;
        if (bx > x1) x1 = bx;
        if (by > y1) y1 = by;
    }
    if (!got) return 0;
    *ox = x0; *oy = y0; *ow = x1 - x0; *oh = y1 - y0;
    return 1;
}

/* The SCROLLABLE overflow area, as the subtree ink union. */
static int overflow_box(struct node *el, int *ow, int *oh)
{
    *ow = *oh = 0;
    int n = 0;
    const struct item *it = items(&n);
    if (!it) return 0;
    int x0 = 0, y0 = 0, x1 = 0, y1 = 0, got = 0;
    for (int i = 0; i < n; i++) {
        if (!it[i].node || !in_subtree(el, it[i].node)) continue;
        int ax = it[i].x, ay = it[i].y, bx = ax + it[i].w, by = ay + it[i].h;
        if (!got) { x0 = ax; y0 = ay; x1 = bx; y1 = by; got = 1; continue; }
        if (ax < x0) x0 = ax;
        if (ay < y0) y0 = ay;
        if (bx > x1) x1 = bx;
        if (by > y1) y1 = by;
    }
    if (!got) return 0;
    *ow = x1 - x0; *oh = y1 - y0;
    return 1;
}

static const struct cstyle *sty(const struct node *n)
{ return (n && n->style) ? (const struct cstyle *)n->style : 0; }

/* Border widths separate the border box from the padding box. cstyle keeps
 * them in CSS shorthand order: top, right, bottom, left. */
static void borders(const struct node *n, int *t, int *r, int *b, int *l)
{
    const struct cstyle *c = sty(n);
    *t = *r = *b = *l = 0;
    if (!c) return;
    *t = c->border_w[0]; *r = c->border_w[1]; *b = c->border_w[2]; *l = c->border_w[3];
}

static int is_tag(const struct node *n, const char *t)
{ return n && n->type == N_ELEM && n->tag && !strcmp(n->tag, t); }

static int has_box(struct node *el)
{ int x, y, w, h; return border_box(el, &x, &y, &w, &h); }

/* offsetParent: the nearest positioned ancestor, else the body. Null for the
 * body, for the root element, for a fixed-position box and for anything with
 * no box at all. */
static struct node *offset_parent(struct node *el)
{
    if (!el || el->type != N_ELEM) return 0;
    if (is_tag(el, "body") || is_tag(el, "html")) return 0;
    if (!has_box(el)) return 0;
    const struct cstyle *c = sty(el);
    if (c && c->position == POS_FIXED) return 0;
    struct node *body = 0;
    for (struct node *p = el->parent; p; p = p->parent) {
        if (p->type != N_ELEM) continue;
        if (is_tag(p, "body")) { body = p; break; }
        const struct cstyle *pc = sty(p);
        if (pc && pc->position != POS_STATIC) return p;
    }
    return body;
}

/* ==========================================================================
 * DOMRect / DOMRectReadOnly / DOMRectList
 * ========================================================================== */

static JSValue rect_toJSON(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{ (void)argc; (void)argv; return JS_DupValue(ctx, t); }

static JSValue make_rect(JSContext *ctx, double x, double y, double w, double h)
{
    JSValue r = JS_NewObject(ctx);
    if (JS_IsException(r)) return r;
    /* A negative width or height is legal in a DOMRect and means the box is
     * expressed from its far edge; left/top/right/bottom normalise it. That is
     * what `new DOMRect(0, 0, -10, -10)` is checking, and it is the one part
     * of DOMRect with any behaviour in it at all. */
    double l  = w < 0 ? x + w : x, rt = w < 0 ? x : x + w;
    double tp = h < 0 ? y + h : y, bt = h < 0 ? y : y + h;
    JS_SetPropertyStr(ctx, r, "x",      JS_NewFloat64(ctx, x));
    JS_SetPropertyStr(ctx, r, "y",      JS_NewFloat64(ctx, y));
    JS_SetPropertyStr(ctx, r, "width",  JS_NewFloat64(ctx, w));
    JS_SetPropertyStr(ctx, r, "height", JS_NewFloat64(ctx, h));
    JS_SetPropertyStr(ctx, r, "left",   JS_NewFloat64(ctx, l));
    JS_SetPropertyStr(ctx, r, "top",    JS_NewFloat64(ctx, tp));
    JS_SetPropertyStr(ctx, r, "right",  JS_NewFloat64(ctx, rt));
    JS_SetPropertyStr(ctx, r, "bottom", JS_NewFloat64(ctx, bt));
    JS_SetPropertyStr(ctx, r, "toJSON", JS_NewCFunction(ctx, rect_toJSON, "toJSON", 0));
    return r;
}

static JSValue js_DOMRect(JSContext *ctx, JSValueConst nt, int argc, JSValueConst *argv)
{
    (void)nt;
    double v[4] = { 0, 0, 0, 0 };
    for (int i = 0; i < 4 && i < argc; i++)
        if (JS_ToFloat64(ctx, &v[i], argv[i]) < 0) return JS_EXCEPTION;
    return make_rect(ctx, v[0], v[1], v[2], v[3]);
}

/* item(i) for the array-like DOMRectList getClientRects returns. */
static JSValue list_item(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    int32_t i = 0;
    if (argc < 1 || JS_ToInt32(ctx, &i, argv[0]) < 0) return JS_NULL;
    if (i < 0) return JS_NULL;
    JSValue v = JS_GetPropertyUint32(ctx, t, (uint32_t)i);
    if (JS_IsUndefined(v)) { JS_FreeValue(ctx, v); return JS_NULL; }
    return v;
}

/* ==========================================================================
 * The Element geometry accessors
 *
 * One getter with a `magic` selector rather than thirteen near-identical C
 * functions: thirteen would be thirteen places for the flush to be forgotten.
 * ========================================================================== */

enum {
    G_OFFSET_W = 0, G_OFFSET_H, G_OFFSET_L, G_OFFSET_T,
    G_CLIENT_W, G_CLIENT_H, G_CLIENT_L, G_CLIENT_T,
    G_SCROLL_W, G_SCROLL_H
};

static JSValue el_geom(JSContext *ctx, JSValueConst t, int magic)
{
    struct node *el = node_from(t);
    if (!el || el->type != N_ELEM) return JS_NewInt32(ctx, 0);
    flush_layout();
    int x, y, w, h;
    if (!border_box(el, &x, &y, &w, &h)) return JS_NewInt32(ctx, 0);
    int bt, br, bb, bl;
    borders(el, &bt, &br, &bb, &bl);
    int cw = w - bl - br, ch = h - bt - bb;
    if (cw < 0) cw = 0;
    if (ch < 0) ch = 0;
    switch (magic) {
    case G_OFFSET_W: return JS_NewInt32(ctx, w);
    case G_OFFSET_H: return JS_NewInt32(ctx, h);
    case G_OFFSET_L:
    case G_OFFSET_T: {
        /* Relative to the offsetParent's PADDING edge, per the CSSOM: its
         * border box inset by its own border. With no offsetParent the
         * reference is the initial containing block, i.e. the document. */
        struct node *op = offset_parent(el);
        int px = 0, py = 0;
        if (op) {
            int ox, oy, ow, oh, ot, orr, ob, ol;
            if (border_box(op, &ox, &oy, &ow, &oh)) {
                borders(op, &ot, &orr, &ob, &ol);
                px = ox + ol; py = oy + ot;
            }
        }
        return JS_NewInt32(ctx, magic == G_OFFSET_L ? x - px : y - py);
    }
    case G_CLIENT_W: return JS_NewInt32(ctx, cw);
    case G_CLIENT_H: return JS_NewInt32(ctx, ch);
    case G_CLIENT_L: return JS_NewInt32(ctx, bl);
    case G_CLIENT_T: return JS_NewInt32(ctx, bt);
    case G_SCROLL_W:
    case G_SCROLL_H: {
        int sw = 0, sh = 0;
        overflow_box(el, &sw, &sh);
        int v = (magic == G_SCROLL_W) ? (sw > cw ? sw : cw) : (sh > ch ? sh : ch);
        return JS_NewInt32(ctx, v);
    }
    }
    return JS_NewInt32(ctx, 0);
}

/* offsetParent, as the number of parentNode HOPS from the element -- not as
 * the element itself.
 *
 * The wrapper is the reason. This file must never mint a second JS wrapper for
 * a node (two wrappers makes `el.offsetParent === document.body` false, which
 * is worse than answering nothing), and js_dom.c's wrapper cache is only
 * populated for nodes a script has already reached. An ancestor that nobody
 * has touched has no wrapper, so returning it from C means returning null --
 * which is what the first version did, and it made the property useless in
 * exactly the common case.
 *
 * A hop count has no such problem: the JS accessor above walks .parentNode,
 * and every step of that walk goes through js_dom.c's own wrapper cache, so
 * the object that comes back is THE object. -1 means null. */
static JSValue el_offsetParentHops(JSContext *ctx, JSValueConst t,
                                   int argc, JSValueConst *argv)
{
    (void)argc;
    struct node *el = argc > 0 ? node_from(argv[0]) : node_from(t);
    if (!el) return JS_NewInt32(ctx, -1);
    flush_layout();
    struct node *op = offset_parent(el);
    if (!op) return JS_NewInt32(ctx, -1);
    int hops = 0;
    for (struct node *p = el->parent; p; p = p->parent) {
        hops++;
        if (p == op) return JS_NewInt32(ctx, hops);
    }
    return JS_NewInt32(ctx, -1);
}

/* scrollTop / scrollLeft. Nothing in this engine scrolls a SUB-box: the
 * browser scrolls the whole page, in browser.c. So these read 0 and a write
 * moves nothing -- but the written value is REMEMBERED, because a page that
 * sets scrollTop and reads it back expecting its own value is common and a
 * silent 0 sends it into a retry loop. Kept in a side table rather than a
 * field on struct node: this is per-page-session state that a handful of
 * elements in a whole corpus ever touch, and struct node is paid for by every
 * node on every page. */
struct scrollent { struct node *n; uint32_t serial; int top, left; };
static struct scrollent *g_scroll;
static int g_scrolln, g_scrollcap;

static struct scrollent *scroll_for(struct node *n, int create)
{
    for (int i = 0; i < g_scrolln; i++)
        if (g_scroll[i].n == n && g_scroll[i].serial == n->serial) return &g_scroll[i];
    if (!create) return 0;
    if (g_scrolln == g_scrollcap) {
        int cap = g_scrollcap ? g_scrollcap * 2 : 8;
        struct scrollent *p = realloc(g_scroll, (size_t)cap * sizeof *p);
        if (!p) return 0;
        g_scroll = p; g_scrollcap = cap;
    }
    struct scrollent *e = &g_scroll[g_scrolln++];
    e->n = n; e->serial = n->serial; e->top = e->left = 0;
    return e;
}

static JSValue el_scroll_get(JSContext *ctx, JSValueConst t, int magic)
{
    struct node *el = node_from(t);
    if (!el) return JS_NewInt32(ctx, 0);
    struct scrollent *e = scroll_for(el, 0);
    return JS_NewInt32(ctx, e ? (magic ? e->left : e->top) : 0);
}

static JSValue el_scroll_set(JSContext *ctx, JSValueConst t, JSValueConst v, int magic)
{
    struct node *el = node_from(t);
    if (!el) return JS_UNDEFINED;
    double d = 0;
    if (JS_ToFloat64(ctx, &d, v) < 0) return JS_EXCEPTION;
    if (d < 0) d = 0;
    struct scrollent *e = scroll_for(el, 1);
    if (e) { if (magic) e->left = (int)d; else e->top = (int)d; }
    return JS_UNDEFINED;
}

static JSValue el_getBoundingClientRect(JSContext *ctx, JSValueConst t,
                                        int argc, JSValueConst *argv)
{
    (void)argc; (void)argv;
    struct node *el = node_from(t);
    flush_layout();
    int x = 0, y = 0, w = 0, h = 0;
    if (el) border_box(el, &x, &y, &w, &h);
    return make_rect(ctx, x, y, w, h);
}

/* getClientRects(): one rect per FRAGMENT. This engine has real fragments -- a
 * wrapped inline paints one IT_TEXT per line -- so an inline element returns
 * several and a block returns one, which makes the length mean something
 * rather than always being 1. */
static JSValue el_getClientRects(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    (void)argc; (void)argv;
    struct node *el = node_from(t);
    flush_layout();
    JSValue arr = JS_NewArray(ctx);
    if (JS_IsException(arr)) return arr;
    uint32_t k = 0;
    int n = 0;
    const struct item *it = items(&n);
    if (el && it)
        for (int i = 0; i < n; i++) {
            if (!it[i].node || !in_subtree(el, it[i].node)) continue;
            if (it[i].w == 0 && it[i].h == 0) continue;
            JS_SetPropertyUint32(ctx, arr, k++,
                make_rect(ctx, it[i].x, it[i].y, it[i].w, it[i].h));
        }
    /* A DOMRectList is an array-like with item(), not an Array. The difference
     * is invisible to every use of it in the corpus (`.length`, `[0]`,
     * `item(0)`), and an Array additionally supports the spread and for..of
     * that the newer tests use on it. */
    JS_SetPropertyStr(ctx, arr, "item", JS_NewCFunction(ctx, list_item, "item", 1));
    return arr;
}

/* ==========================================================================
 * The CSS namespace object
 * ========================================================================== */

static JSValue js_CSS_supports(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    (void)t;
    if (argc <= 0) return JS_FALSE;
    if (argc >= 2) {
        const char *p = JS_ToCString(ctx, argv[0]);
        const char *v = JS_ToCString(ctx, argv[1]);
        int ok = (p && v) ? css_supports_decl(p, -1, v, -1) : 0;
        if (p) JS_FreeCString(ctx, p);
        if (v) JS_FreeCString(ctx, v);
        return JS_NewBool(ctx, ok);
    }
    /* The one-argument form takes a <supports-condition>: a parenthesised
     * declaration, or several joined by and/or/not. Only the single
     * parenthesised declaration is answered; a compound condition answers
     * false rather than guessing, and false is the direction that makes a page
     * take its baseline branch instead of one this engine cannot render. */
    const char *s = JS_ToCString(ctx, argv[0]);
    if (!s) return JS_FALSE;
    const char *p = s;
    while (*p == ' ' || *p == '\t' || *p == '\n') p++;
    int ok = 0;
    if (*p == '(') {
        const char *e = p + strlen(p);
        while (e > p && (e[-1] == ' ' || e[-1] == '\t' || e[-1] == '\n')) e--;
        if (e > p && e[-1] == ')') {
            const char *body = p + 1, *end = e - 1;
            /* A nested '(' at depth 0 of the body means this is a compound
             * condition, not one declaration: `(a:b) and (c:d)`. */
            int depth = 0, compound = 0;
            const char *colon = 0;
            for (const char *q = body; q < end; q++) {
                if (*q == '(') { if (depth == 0) compound = 1; depth++; }
                else if (*q == ')') depth--;
                else if (*q == ':' && depth == 0 && !colon) colon = q;
            }
            if (colon && !compound)
                ok = css_supports_decl(body, (int)(colon - body),
                                       colon + 1, (int)(end - colon - 1));
        }
    }
    JS_FreeCString(ctx, s);
    return JS_NewBool(ctx, ok);
}

/* CSS.escape(), CSSOM "serialize an identifier", byte for byte. Its whole
 * purpose is to be pasted into a selector, and a near-miss produces a selector
 * that silently matches nothing -- so this is the algorithm, not an
 * approximation of it. */
static JSValue js_CSS_escape(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    (void)t;
    if (argc < 1) return JS_ThrowTypeError(ctx, "CSS.escape requires an argument");
    size_t len = 0;
    const char *s = JS_ToCStringLen(ctx, &len, argv[0]);
    if (!s) return JS_EXCEPTION;
    char *out = malloc(len * 8 + 8);
    if (!out) { JS_FreeCString(ctx, s); return JS_ThrowOutOfMemory(ctx); }
    size_t o = 0;
    static const char HEX[] = "0123456789abcdef";
    for (size_t i = 0; i < len; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == 0) { memcpy(out + o, "\xEF\xBF\xBD", 3); o += 3; continue; }
        int esc_hex =
            (c <= 0x1F) || c == 0x7F ||
            (i == 0 && c >= '0' && c <= '9') ||
            (i == 1 && c >= '0' && c <= '9' && s[0] == '-');
        if (esc_hex) {
            out[o++] = '\\';
            /* Lowercase hex, no leading zeros, one trailing space. */
            if (c >= 0x10) out[o++] = HEX[(c >> 4) & 0xF];
            out[o++] = HEX[c & 0xF];
            out[o++] = ' ';
            continue;
        }
        if (i == 0 && c == '-' && len == 1) { out[o++] = '\\'; out[o++] = '-'; continue; }
        if (c >= 0x80 || c == '-' || c == '_' ||
            (c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) {
            out[o++] = (char)c; continue;
        }
        out[o++] = '\\'; out[o++] = (char)c;
    }
    JSValue r = JS_NewStringLen(ctx, out, o);
    free(out);
    JS_FreeCString(ctx, s);
    return r;
}

/* ==========================================================================
 * matchMedia
 *
 * js_webapi.c ships one with a scanner of its own, and css.h names that as a
 * KNOWN DIVERGENCE: two evaluators for one question do not fail by being
 * approximate, they fail by DISAGREEING -- a page whose @media block LibCSS
 * declined can still take the JS branch that assumes it applied. This one is
 * the cascade's own evaluator (css_media_matches, which IS LibCSS's matcher),
 * and it is installed after js_webapi's so it wins. Overwriting the binding
 * rather than editing their file is what closes the divergence without
 * touching a file this line does not own.
 *
 * The listener surface is present and inert: nothing here changes viewport or
 * colour scheme after load, so a `change` event has no producer. Present
 * because a page that calls addListener on undefined dies, and inert because
 * inventing a fire would be worse than not firing.
 * ========================================================================== */

static JSValue mql_noop(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{ (void)ctx; (void)t; (void)argc; (void)argv; return JS_UNDEFINED; }

static JSValue js_matchMedia(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    (void)t;
    const char *q = argc > 0 ? JS_ToCString(ctx, argv[0]) : 0;
    int m = q ? css_media_matches(q, -1) : 0;
    JSValue o = JS_NewObject(ctx);
    if (JS_IsException(o)) { if (q) JS_FreeCString(ctx, q); return o; }
    JS_SetPropertyStr(ctx, o, "media",   JS_NewString(ctx, q ? q : ""));
    JS_SetPropertyStr(ctx, o, "matches", JS_NewBool(ctx, m));
    JS_SetPropertyStr(ctx, o, "onchange", JS_NULL);
    JS_SetPropertyStr(ctx, o, "addListener",         JS_NewCFunction(ctx, mql_noop, "addListener", 1));
    JS_SetPropertyStr(ctx, o, "removeListener",      JS_NewCFunction(ctx, mql_noop, "removeListener", 1));
    JS_SetPropertyStr(ctx, o, "addEventListener",    JS_NewCFunction(ctx, mql_noop, "addEventListener", 2));
    JS_SetPropertyStr(ctx, o, "removeEventListener", JS_NewCFunction(ctx, mql_noop, "removeEventListener", 2));
    JS_SetPropertyStr(ctx, o, "dispatchEvent",       JS_NewCFunction(ctx, mql_noop, "dispatchEvent", 1));
    if (q) JS_FreeCString(ctx, q);
    return o;
}

/* ==========================================================================
 * document.styleSheets and the CSSRule tree
 *
 * THE SOURCE TEXT IS THE MODEL, and that is a decision worth defending
 * because css.h is emphatic that a second CSS scanner is how this engine gets
 * two answers to one question. It does not apply here, and the reason is that
 * this asks a DIFFERENT question. The cascade's question is "what wins", and
 * LibCSS owns it. The CSSOM's question is "what does the author's sheet SAY"
 * -- selectorText, cssText, rule order, the untouched value bytes -- and
 * LibCSS deliberately throws all of that away when it compiles a sheet: it
 * keeps a selector as a compiled chain, not as the string the author wrote,
 * so a CSSOM built on it could not answer `.cssRules[0].selectorText` at all.
 *
 * So this splits the sheet's TEXT into rules and never decides anything about
 * cascade or specificity. The one place the two could drift -- insertRule and
 * deleteRule -- is closed by writing the modified sheet back into the <style>
 * element's text, so the next cascade parses exactly what the CSSOM reports.
 * ========================================================================== */

struct sbuf { char *p; size_t len, cap; };

static void sb_push(struct sbuf *b, const char *s, size_t n)
{
    if (b->len + n + 1 > b->cap) {
        size_t cap = b->cap ? b->cap * 2 : 128;
        while (cap < b->len + n + 1) cap *= 2;
        char *p = realloc(b->p, cap);
        if (!p) return;
        b->p = p; b->cap = cap;
    }
    if (!b->p) return;
    memcpy(b->p + b->len, s, n);
    b->len += n;
    b->p[b->len] = 0;
}

/* Skip a CSS comment or a quoted string starting at s[i]; returns the index
 * just past it, or i unchanged. Rule splitting that does not do this cuts a
 * sheet in half on a `{` inside content: "{". */
static size_t skip_atom(const char *s, size_t n, size_t i)
{
    if (i + 1 < n && s[i] == '/' && s[i + 1] == '*') {
        i += 2;
        while (i + 1 < n && !(s[i] == '*' && s[i + 1] == '/')) i++;
        return (i + 1 < n) ? i + 2 : n;
    }
    if (s[i] == '"' || s[i] == '\'') {
        char q = s[i++];
        while (i < n && s[i] != q) { if (s[i] == '\\' && i + 1 < n) i++; i++; }
        return (i < n) ? i + 1 : n;
    }
    return i;
}

static void trim(const char **s, size_t *n)
{
    while (*n && (**s == ' ' || **s == '\t' || **s == '\n' || **s == '\r' || **s == '\f'))
        { (*s)++; (*n)--; }
    while (*n) {
        char c = (*s)[*n - 1];
        if (c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f') (*n)--;
        else break;
    }
}

/* CSSRule.type, the legacy numeric constants. Kept because every test in the
 * corpus that touches rule types reads `.type`, not the interface name. */
enum {
    R_STYLE = 1, R_CHARSET = 2, R_IMPORT = 3, R_MEDIA = 4, R_FONT_FACE = 5,
    R_PAGE = 6, R_KEYFRAMES = 7, R_KEYFRAME = 8, R_NAMESPACE = 10,
    R_COUNTER_STYLE = 11, R_SUPPORTS = 12
};

static int at_rule_type(const char *p, size_t n)
{
    /* p points just past '@'; n is the whole prelude length from there. */
    size_t k = 0;
    while (k < n && ((p[k] >= 'a' && p[k] <= 'z') || (p[k] >= 'A' && p[k] <= 'Z') ||
                     p[k] == '-')) k++;
    if (k == 5 && !strncmp(p, "media", 5)) return R_MEDIA;
    if (k == 6 && !strncmp(p, "import", 6)) return R_IMPORT;
    if (k == 9 && !strncmp(p, "font-face", 9)) return R_FONT_FACE;
    if (k == 9 && !strncmp(p, "keyframes", 9)) return R_KEYFRAMES;
    if (k == 4 && !strncmp(p, "page", 4)) return R_PAGE;
    if (k == 7 && !strncmp(p, "charset", 7)) return R_CHARSET;
    if (k == 8 && !strncmp(p, "supports", 8)) return R_SUPPORTS;
    if (k == 9 && !strncmp(p, "namespace", 9)) return R_NAMESPACE;
    if (k == 13 && !strncmp(p, "counter-style", 13)) return R_COUNTER_STYLE;
    return 0;
}

static JSValue build_rules(JSContext *ctx, const char *s, size_t n, JSValueConst parent);

/* A declaration block as a CSSStyleDeclaration.
 *
 * This is a SECOND CSSStyleDeclaration implementation -- js_dom.c has one for
 * element.style and getComputedStyle. They are not merged because js_dom.c's
 * is backed by a NODE (the style content attribute, so inline priority is kept
 * for free) and this one is backed by a text span inside a stylesheet, which
 * has no node at all. Merging them would mean either giving js_dom.c's class a
 * second backing mode from outside the file that owns it, or giving a rule a
 * fake node. The duplication is the smaller cost, and it is bounded: the
 * READ side is shared by neither and the SERIALISATION both produce is the
 * declaration text as written, so they cannot disagree about a value. */
static JSValue make_decl(JSContext *ctx, const char *s, size_t n);

/* ---- one rule ---- */
static JSValue make_rule(JSContext *ctx, int type,
                         const char *pre, size_t prelen,
                         const char *blk, size_t blklen,
                         const char *whole, size_t wholelen)
{
    JSValue r = JS_NewObject(ctx);
    if (JS_IsException(r)) return r;
    JS_SetPropertyStr(ctx, r, "type", JS_NewInt32(ctx, type));
    JS_SetPropertyStr(ctx, r, "cssText", JS_NewStringLen(ctx, whole, wholelen));
    JS_SetPropertyStr(ctx, r, "parentRule", JS_NULL);
    switch (type) {
    case R_STYLE:
        JS_SetPropertyStr(ctx, r, "selectorText", JS_NewStringLen(ctx, pre, prelen));
        JS_SetPropertyStr(ctx, r, "style", make_decl(ctx, blk, blklen));
        break;
    case R_MEDIA:
    case R_SUPPORTS: {
        /* The condition is the prelude minus the at-keyword. */
        const char *c = pre; size_t cn = prelen;
        while (cn && *c != ' ' && *c != '\t' && *c != '(') { c++; cn--; }
        trim(&c, &cn);
        JS_SetPropertyStr(ctx, r, "conditionText", JS_NewStringLen(ctx, c, cn));
        if (type == R_MEDIA) {
            JSValue ml = JS_NewArray(ctx);
            JS_SetPropertyUint32(ctx, ml, 0, JS_NewStringLen(ctx, c, cn));
            JS_SetPropertyStr(ctx, ml, "mediaText", JS_NewStringLen(ctx, c, cn));
            JS_SetPropertyStr(ctx, r, "media", ml);
            /* The verdict from the cascade's own evaluator, so a script can
             * ask whether this block is live without a second matcher. */
            JS_SetPropertyStr(ctx, r, "matches",
                              JS_NewBool(ctx, css_media_matches(c, (int)cn)));
        }
        JS_SetPropertyStr(ctx, r, "cssRules", build_rules(ctx, blk, blklen, r));
        break;
    }
    case R_KEYFRAMES: {
        const char *c = pre; size_t cn = prelen;
        while (cn && *c != ' ' && *c != '\t') { c++; cn--; }
        trim(&c, &cn);
        JS_SetPropertyStr(ctx, r, "name", JS_NewStringLen(ctx, c, cn));
        JS_SetPropertyStr(ctx, r, "cssRules", build_rules(ctx, blk, blklen, r));
        break;
    }
    case R_FONT_FACE:
    case R_PAGE:
    case R_COUNTER_STYLE:
        JS_SetPropertyStr(ctx, r, "style", make_decl(ctx, blk, blklen));
        break;
    case R_IMPORT: {
        const char *c = pre; size_t cn = prelen;
        while (cn && *c != ' ' && *c != '\t') { c++; cn--; }
        trim(&c, &cn);
        /* Strip url(...) / quotes down to the href, which is the only part of
         * an @import a script ever reads. The sheet itself is null: nothing
         * here fetches an imported sheet, and a fabricated empty CSSStyleSheet
         * would claim it had. */
        if (cn > 4 && !strncmp(c, "url(", 4)) { c += 4; cn -= 4; if (cn && c[cn-1] == ')') cn--; }
        trim(&c, &cn);
        if (cn >= 2 && (*c == '"' || *c == '\'') && c[cn-1] == *c) { c++; cn -= 2; }
        JS_SetPropertyStr(ctx, r, "href", JS_NewStringLen(ctx, c, cn));
        JS_SetPropertyStr(ctx, r, "styleSheet", JS_NULL);
        break;
    }
    default:
        break;
    }
    if (type == R_KEYFRAME)
        JS_SetPropertyStr(ctx, r, "keyText", JS_NewStringLen(ctx, pre, prelen));
    return r;
}

/* Split `s` into rules. `parent` is the enclosing CSSMediaRule/@keyframes, or
 * JS_NULL at the top level. */
static JSValue build_rules(JSContext *ctx, const char *s, size_t n, JSValueConst parent)
{
    JSValue arr = JS_NewArray(ctx);
    if (JS_IsException(arr)) return arr;
    uint32_t k = 0;
    size_t i = 0;
    int inside_keyframes = 0;
    if (JS_IsObject(parent)) {
        JSValue ty = JS_GetPropertyStr(ctx, parent, "type");
        int32_t t = 0; JS_ToInt32(ctx, &t, ty); JS_FreeValue(ctx, ty);
        inside_keyframes = (t == R_KEYFRAMES);
    }
    while (i < n) {
        size_t j = skip_atom(s, n, i);
        if (j != i) { i = j; continue; }
        if (s[i] == ' ' || s[i] == '\t' || s[i] == '\n' || s[i] == '\r' || s[i] == '\f'
            || s[i] == ';') { i++; continue; }
        size_t start = i, brace = 0;
        int depth = 0, found = 0;
        while (i < n) {
            size_t sk = skip_atom(s, n, i);
            if (sk != i) { i = sk; continue; }
            if (s[i] == '{') { if (!depth) { brace = i; found = 1; } depth++; i++; continue; }
            if (s[i] == '}') { depth--; i++; if (depth <= 0) break; continue; }
            if (s[i] == ';' && !depth) { i++; break; }   /* @import / @charset */
            i++;
        }
        size_t end = i;
        if (!found) {
            /* A statement at-rule: @import url(x); */
            const char *pre = s + start; size_t prelen = end - start;
            if (prelen && pre[prelen - 1] == ';') prelen--;
            trim(&pre, &prelen);
            if (prelen && *pre == '@') {
                int ty = at_rule_type(pre + 1, prelen - 1);
                if (ty) {
                    JSValue r = make_rule(ctx, ty, pre, prelen, "", 0, s + start, end - start);
                    if (JS_IsObject(parent)) JS_SetPropertyStr(ctx, r, "parentRule", JS_DupValue(ctx, parent));
                    JS_SetPropertyUint32(ctx, arr, k++, r);
                }
            }
            continue;
        }
        const char *pre = s + start; size_t prelen = brace - start;
        trim(&pre, &prelen);
        const char *blk = s + brace + 1;
        size_t blkend = (end > brace + 1 && s[end - 1] == '}') ? end - 1 : end;
        size_t blklen = blkend > brace + 1 ? blkend - (brace + 1) : 0;
        int ty;
        if (prelen && *pre == '@') {
            ty = at_rule_type(pre + 1, prelen - 1);
            if (!ty) continue;                     /* an at-rule we do not model */
        } else {
            ty = inside_keyframes ? R_KEYFRAME : R_STYLE;
        }
        JSValue r = make_rule(ctx, ty, pre, prelen, blk, blklen, s + start, end - start);
        if (JS_IsObject(parent)) JS_SetPropertyStr(ctx, r, "parentRule", JS_DupValue(ctx, parent));
        JS_SetPropertyUint32(ctx, arr, k++, r);
    }
    JS_SetPropertyStr(ctx, arr, "item", JS_NewCFunction(ctx, list_item, "item", 1));
    return arr;
}

/* ---- the declaration block ----
 *
 * Backed by the block TEXT, parsed on construction into name/value pairs.
 * Eager rather than lazy because a rule's block is tens of bytes and the
 * lazy form would have to re-scan on every read; js_dom.c's inline
 * declaration is lazy for the opposite reason (a page animating an element
 * rewrites its style attribute every frame). */
struct decl { char *name; char *value; int important; };

/* CSS property names are ASCII case-insensitive, so the lookup key is
 * lowercased on both sides -- getPropertyValue('BACKGROUND-COLOR') has to
 * resolve, which is the same rule js_dom.c's sty_find() follows for the
 * inline declaration. */
static char *lower_key(JSContext *ctx, JSValueConst v)
{
    size_t n = 0;
    const char *s = JS_ToCStringLen(ctx, &n, v);
    if (!s) return 0;
    char *k = malloc(n + 1);
    if (k) {
        for (size_t i = 0; i < n; i++)
            k[i] = (s[i] >= 'A' && s[i] <= 'Z') ? (char)(s[i] + 32) : s[i];
        k[n] = 0;
    }
    JS_FreeCString(ctx, s);
    return k;
}

static JSValue decl_getPropertyValue(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    if (argc < 1) return JS_NewString(ctx, "");
    char *k = lower_key(ctx, argv[0]);
    if (!k) return JS_NewString(ctx, "");
    JSValue map = JS_GetPropertyStr(ctx, t, "__m");
    JSValue got = JS_GetPropertyStr(ctx, map, k);
    JS_FreeValue(ctx, map);
    free(k);
    if (JS_IsString(got)) return got;
    JS_FreeValue(ctx, got);
    return JS_NewString(ctx, "");
}

static JSValue decl_getPropertyPriority(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    if (argc < 1) return JS_NewString(ctx, "");
    char *k = lower_key(ctx, argv[0]);
    if (!k) return JS_NewString(ctx, "");
    JSValue map = JS_GetPropertyStr(ctx, t, "__p");
    JSValue got = JS_GetPropertyStr(ctx, map, k);
    JS_FreeValue(ctx, map);
    free(k);
    int imp = JS_ToBool(ctx, got);
    JS_FreeValue(ctx, got);
    return JS_NewString(ctx, imp ? "important" : "");
}

static JSValue make_decl(JSContext *ctx, const char *s, size_t n)
{
    JSValue o = JS_NewObject(ctx);
    if (JS_IsException(o)) return o;
    JSValue map = JS_NewObject(ctx);
    JSValue imp = JS_NewObject(ctx);
    struct sbuf text = { 0, 0, 0 };
    uint32_t k = 0;
    size_t i = 0;
    while (i < n) {
        size_t j = skip_atom(s, n, i);
        if (j != i) { i = j; continue; }
        size_t start = i;
        int depth = 0;
        while (i < n) {
            size_t sk = skip_atom(s, n, i);
            if (sk != i) { i = sk; continue; }
            if (s[i] == '(') depth++;
            else if (s[i] == ')') depth--;
            else if (s[i] == ';' && depth <= 0) break;
            i++;
        }
        const char *d = s + start; size_t dn = i - start;
        if (i < n) i++;                                     /* step over the ';' */
        trim(&d, &dn);
        if (!dn) continue;
        size_t c = 0;
        while (c < dn && d[c] != ':') c++;
        if (c >= dn) continue;
        const char *nm = d; size_t nl = c;
        const char *vl = d + c + 1; size_t vln = dn - c - 1;
        trim(&nm, &nl); trim(&vl, &vln);
        if (!nl || !vln) continue;
        int important = 0;
        if (vln >= 10) {
            size_t b = vln - 10;
            if (vl[b] == '!' &&
                !strncmp(vl + b + 1, "important", 9)) {
                important = 1;
                while (b && (vl[b-1] == ' ' || vl[b-1] == '\t')) b--;
                vln = b;
            }
        }
        char *key = malloc(nl + 1);
        char *val = malloc(vln + 1);
        if (!key || !val) { free(key); free(val); continue; }
        for (size_t q = 0; q < nl; q++)
            key[q] = (nm[q] >= 'A' && nm[q] <= 'Z') ? (char)(nm[q] + 32) : nm[q];
        key[nl] = 0;
        memcpy(val, vl, vln); val[vln] = 0;
        JS_SetPropertyStr(ctx, map, key, JS_NewStringLen(ctx, val, vln));
        if (important) JS_SetPropertyStr(ctx, imp, key, JS_TRUE);
        JS_SetPropertyUint32(ctx, o, k++, JS_NewStringLen(ctx, key, nl));
        if (text.len) sb_push(&text, " ", 1);
        sb_push(&text, key, nl);
        sb_push(&text, ": ", 2);
        sb_push(&text, val, vln);
        if (important) sb_push(&text, " !important", 11);
        sb_push(&text, ";", 1);
        free(key); free(val);
    }
    JS_SetPropertyStr(ctx, o, "__m", map);
    JS_SetPropertyStr(ctx, o, "__p", imp);
    JS_SetPropertyStr(ctx, o, "length", JS_NewInt32(ctx, (int)k));
    JS_SetPropertyStr(ctx, o, "cssText",
                      JS_NewStringLen(ctx, text.p ? text.p : "", text.len));
    JS_SetPropertyStr(ctx, o, "getPropertyValue",
                      JS_NewCFunction(ctx, decl_getPropertyValue, "getPropertyValue", 1));
    JS_SetPropertyStr(ctx, o, "getPropertyPriority",
                      JS_NewCFunction(ctx, decl_getPropertyPriority, "getPropertyPriority", 1));
    JS_SetPropertyStr(ctx, o, "item", JS_NewCFunction(ctx, list_item, "item", 1));
    free(text.p);
    return o;
}

/* ---- the sheet's source text ---- */
static void collect_text(struct node *n, struct sbuf *b)
{
    for (struct node *c = n->first_child; c; c = c->next) {
        if (c->type == N_TEXT && c->text) sb_push(b, c->text, (size_t)c->textlen);
        if (c->first_child) collect_text(c, b);
    }
}

static void find_style_elements(struct node *n, struct node **out, int *cnt, int max)
{
    for (; n; n = n->next) {
        if (n->type == N_ELEM && n->tag && !strcmp(n->tag, "style") && *cnt < max)
            out[(*cnt)++] = n;
        if (n->first_child) find_style_elements(n->first_child, out, cnt, max);
    }
}

/* Write a modified sheet back into its <style> element, so the CASCADE sees
 * what the CSSOM reports. Without this, insertRule would be a lie that only
 * showed up two frames later as a page that does not match its own
 * document.styleSheets. */
static void sheet_write_back(struct node *style, const char *text, size_t len)
{
    if (!style || style->type != N_ELEM) return;
    dom_destroy_children(style);
    struct node *t = dom_create_text(style->doc, text, (int)len);
    if (t) dom_append_child(style, t);
}

/* Which <style> a CSSStyleSheet object writes back to.
 *
 * The sheet object carries an INDEX into this table, not a node pointer --
 * a JS property cannot hold one. So the table has to stay valid for as long as
 * any sheet object a script kept a reference to, which is the whole page: it
 * is appended to and never shrunk, and each entry carries the node's `serial`
 * so a slot recycled out of the DOM's free list can never be written through a
 * stale sheet object. (Rebuilding the table per read, which is what the first
 * version did, made a held sheet's insertRule write into whichever <style>
 * happened to land at its old index.) */
struct sheetref { struct node *style; uint32_t serial; };
static struct sheetref *g_sheets;
static int g_nsheets;

static JSValue sheet_serialize(JSContext *ctx, JSValueConst rules)
{
    struct sbuf b = { 0, 0, 0 };
    JSValue lenv = JS_GetPropertyStr(ctx, rules, "length");
    uint32_t n = 0; JS_ToUint32(ctx, &n, lenv); JS_FreeValue(ctx, lenv);
    for (uint32_t i = 0; i < n; i++) {
        JSValue r = JS_GetPropertyUint32(ctx, rules, i);
        JSValue t = JS_GetPropertyStr(ctx, r, "cssText");
        const char *s = JS_ToCString(ctx, t);
        if (s) { sb_push(&b, s, strlen(s)); sb_push(&b, "\n", 1); JS_FreeCString(ctx, s); }
        JS_FreeValue(ctx, t); JS_FreeValue(ctx, r);
    }
    JSValue out = JS_NewStringLen(ctx, b.p ? b.p : "", b.len);
    free(b.p);
    return out;
}

static JSValue sheet_insertRule(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    if (argc < 1) return JS_ThrowTypeError(ctx, "insertRule requires a rule");
    JSValue rules = JS_GetPropertyStr(ctx, t, "cssRules");
    JSValue lenv = JS_GetPropertyStr(ctx, rules, "length");
    uint32_t n = 0; JS_ToUint32(ctx, &n, lenv); JS_FreeValue(ctx, lenv);
    int32_t idx = 0;
    if (argc >= 2 && JS_ToInt32(ctx, &idx, argv[1]) < 0) { JS_FreeValue(ctx, rules); return JS_EXCEPTION; }
    if (idx < 0 || (uint32_t)idx > n) {
        JS_FreeValue(ctx, rules);
        return JS_ThrowRangeError(ctx, "insertRule: index %d out of range", (int)idx);
    }
    size_t sl = 0;
    const char *src = JS_ToCStringLen(ctx, &sl, argv[0]);
    if (!src) { JS_FreeValue(ctx, rules); return JS_EXCEPTION; }
    JSValue nr = build_rules(ctx, src, sl, JS_NULL);
    JS_FreeCString(ctx, src);
    JSValue first = JS_GetPropertyUint32(ctx, nr, 0);
    JS_FreeValue(ctx, nr);
    if (!JS_IsObject(first)) {
        JS_FreeValue(ctx, first); JS_FreeValue(ctx, rules);
        return JS_ThrowSyntaxError(ctx, "insertRule: not a rule");
    }
    /* Shift up, then place. */
    for (uint32_t i = n; i > (uint32_t)idx; i--) {
        JSValue v = JS_GetPropertyUint32(ctx, rules, i - 1);
        JS_SetPropertyUint32(ctx, rules, i, v);
    }
    JS_SetPropertyUint32(ctx, rules, (uint32_t)idx, first);
    JSValue txt = sheet_serialize(ctx, rules);
    JS_FreeValue(ctx, rules);
    size_t tl = 0;
    const char *ts = JS_ToCStringLen(ctx, &tl, txt);
    JSValue owner = JS_GetPropertyStr(ctx, t, "__sx");
    int32_t si = -1; JS_ToInt32(ctx, &si, owner); JS_FreeValue(ctx, owner);
    if (ts && si >= 0 && si < g_nsheets &&
        g_sheets[si].style && g_sheets[si].style->serial == g_sheets[si].serial)
        sheet_write_back(g_sheets[si].style, ts, tl);
    if (ts) JS_FreeCString(ctx, ts);
    JS_FreeValue(ctx, txt);
    return JS_NewInt32(ctx, idx);
}

static JSValue sheet_deleteRule(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    JSValue rules = JS_GetPropertyStr(ctx, t, "cssRules");
    JSValue lenv = JS_GetPropertyStr(ctx, rules, "length");
    uint32_t n = 0; JS_ToUint32(ctx, &n, lenv); JS_FreeValue(ctx, lenv);
    int32_t idx = 0;
    if (argc >= 1 && JS_ToInt32(ctx, &idx, argv[0]) < 0) { JS_FreeValue(ctx, rules); return JS_EXCEPTION; }
    if (idx < 0 || (uint32_t)idx >= n) {
        JS_FreeValue(ctx, rules);
        return JS_ThrowRangeError(ctx, "deleteRule: index %d out of range", (int)idx);
    }
    for (uint32_t i = (uint32_t)idx; i + 1 < n; i++) {
        JSValue v = JS_GetPropertyUint32(ctx, rules, i + 1);
        JS_SetPropertyUint32(ctx, rules, i, v);
    }
    JS_SetPropertyStr(ctx, rules, "length", JS_NewInt32(ctx, (int)n - 1));
    JSValue txt = sheet_serialize(ctx, rules);
    JS_FreeValue(ctx, rules);
    size_t tl = 0;
    const char *ts = JS_ToCStringLen(ctx, &tl, txt);
    JSValue owner = JS_GetPropertyStr(ctx, t, "__sx");
    int32_t si = -1; JS_ToInt32(ctx, &si, owner); JS_FreeValue(ctx, owner);
    if (ts && si >= 0 && si < g_nsheets &&
        g_sheets[si].style && g_sheets[si].style->serial == g_sheets[si].serial)
        sheet_write_back(g_sheets[si].style, ts, tl);
    if (ts) JS_FreeCString(ctx, ts);
    JS_FreeValue(ctx, txt);
    return JS_UNDEFINED;
}

/* document.styleSheets.
 *
 * CACHED, AND THE CACHE IS PART OF THE CONTRACT, not an optimisation. The
 * CSSOM says document.styleSheets is the same StyleSheetList every time, and
 * `sheet.rules === sheet.cssRules` -- a getter that rebuilds is not merely
 * slower, it makes both of those FALSE, and the second one is what the corpus
 * checks. (That is how this was found: everything else passed and the identity
 * assertion did not.)
 *
 * The key is the concatenated source of every <style> in the document, so a
 * <style> inserted, removed or rewritten -- including by our own insertRule,
 * which writes back -- produces a new list, and nothing else does. A full
 * compare rather than a hash: a hash collision here does not fail loudly, it
 * serves the previous document's rules. This is the same reasoning, and the
 * same trade, that css_engine.c's author_sheet cache is built on. */
static JSValue g_sheetlist = JS_UNDEFINED;   /* JS_UNDEFINED == no cache yet */
static char   *g_sheetsrc;
static size_t  g_sheetsrclen;

static JSValue doc_styleSheets(JSContext *ctx, JSValueConst t)
{
    (void)t;
    struct node *root = js_dom_root();
    JSValue list = JS_UNDEFINED;
    if (!root) return JS_NewArray(ctx);

    enum { MAXS = 64 };
    static struct node *found[MAXS];
    int cnt = 0;
    find_style_elements(root->first_child, found, &cnt, MAXS);

    struct sbuf all = { 0, 0, 0 };
    for (int i = 0; i < cnt; i++) { collect_text(found[i], &all); sb_push(&all, "\1", 1); }
    if (!JS_IsUndefined(g_sheetlist) && g_sheetsrclen == all.len &&
        (all.len == 0 || memcmp(g_sheetsrc, all.p ? all.p : "", all.len) == 0)) {
        free(all.p);
        return JS_DupValue(ctx, g_sheetlist);
    }
    JS_FreeValue(ctx, g_sheetlist);
    g_sheetlist = JS_UNDEFINED;
    free(g_sheetsrc);
    g_sheetsrc = all.p; g_sheetsrclen = all.len;   /* the buffer is kept, not freed */

    list = JS_NewArray(ctx);
    if (JS_IsException(list)) return list;

    /* Appended to, never rebuilt -- see the note on struct sheetref. */
    int base = g_nsheets;
    if (cnt) {
        struct sheetref *p = realloc(g_sheets, (size_t)(base + cnt) * sizeof *p);
        if (p) { g_sheets = p; g_nsheets = base + cnt; }
    }

    for (int i = 0; i < cnt; i++) {
        int sx = base + i;
        if (g_sheets && sx < g_nsheets)
            { g_sheets[sx].style = found[i]; g_sheets[sx].serial = found[i]->serial; }
        struct sbuf src = { 0, 0, 0 };
        collect_text(found[i], &src);
        JSValue sh = JS_NewObject(ctx);
        JSValue rules = build_rules(ctx, src.p ? src.p : "", src.len, JS_NULL);
        JS_SetPropertyStr(ctx, sh, "cssRules", JS_DupValue(ctx, rules));
        /* `rules` is the old IE name and is still what a great deal of code
         * reaches for first; it is the same list, not a copy. */
        JS_SetPropertyStr(ctx, sh, "rules", rules);
        JS_SetPropertyStr(ctx, sh, "type", JS_NewString(ctx, "text/css"));
        JS_SetPropertyStr(ctx, sh, "href", JS_NULL);
        JS_SetPropertyStr(ctx, sh, "title", JS_NULL);
        JS_SetPropertyStr(ctx, sh, "disabled", JS_FALSE);
        JS_SetPropertyStr(ctx, sh, "parentStyleSheet", JS_NULL);
        JS_SetPropertyStr(ctx, sh, "ownerRule", JS_NULL);
        JS_SetPropertyStr(ctx, sh, "ownerNode", wrapper_of(ctx, found[i]));
        JS_SetPropertyStr(ctx, sh, "__sx", JS_NewInt32(ctx, sx));
        JS_SetPropertyStr(ctx, sh, "insertRule",
                          JS_NewCFunction(ctx, sheet_insertRule, "insertRule", 2));
        JS_SetPropertyStr(ctx, sh, "deleteRule",
                          JS_NewCFunction(ctx, sheet_deleteRule, "deleteRule", 1));
        /* addRule/removeRule: the pre-standard spellings, still in the corpus. */
        JS_SetPropertyStr(ctx, sh, "removeRule",
                          JS_NewCFunction(ctx, sheet_deleteRule, "removeRule", 1));
        JS_SetPropertyUint32(ctx, list, (uint32_t)i, sh);
        free(src.p);
    }
    JS_SetPropertyStr(ctx, list, "item", JS_NewCFunction(ctx, list_item, "item", 1));
    g_sheetlist = JS_DupValue(ctx, list);
    return list;
}

/* ==========================================================================
 * The JS-side shims
 *
 * Written as source rather than as C bindings where the thing being built is
 * plain object plumbing with no engine state behind it. The rule used: if it
 * has to reach the DOM, the cascade or the display list, it is C above; if it
 * is a shape a script expects to find, it is here.
 * ========================================================================== */

/* `<body onload=...>` is a handler on the WINDOW.
 *
 * This is the single largest cause of dead CSS files in the corpus (~765 of
 * 1,926) and it is not a CSSOM bug at all -- it is the HTML spec's
 * "Windows event handlers" special case: onload, onresize, onscroll and their
 * neighbours, written as content attributes on <body>, are handlers on the
 * Window, not on the body element. js_dom.c compiles an on<type> content
 * attribute when an event dispatches TO that node; the load event dispatches
 * to the window, so the body's attribute was never reached and a file whose
 * whole test body is `<body onload="checkLayout('.target')">` registered no
 * tests and timed out empty.
 *
 * It lives here rather than in js_dom.c because js_dom.c is another line's
 * file and this is purely additive: a window listener, registered at install
 * time (so before any page script's own), that pulls the attribute off the
 * body and runs it.
 *
 * TWO GUARDS AGAINST DOUBLE-FIRING, because the DOM line may well implement
 * this properly later and two calls to checkLayout is not a smaller bug than
 * zero: it skips a type whose window handler is ALREADY a function (a real
 * implementation would have reflected it there), and it runs each type at most
 * once per page.
 */
static const char *SHIM_BODY_HANDLERS =
"(function(G){\n"
"  var TYPES = ['load','unload','beforeunload','resize','scroll','error','blur',\n"
"               'focus','hashchange','languagechange','message','offline','online',\n"
"               'pagehide','pageshow','popstate','rejectionhandled','storage',\n"
"               'unhandledrejection'];\n"
"  var ran = Object.create(null);\n"
"  TYPES.forEach(function (ty) {\n"
"    G.addEventListener(ty, function (ev) {\n"
"      if (ran[ty]) return;\n"
"      if (typeof G['on' + ty] === 'function') return;   /* someone reflected it */\n"
"      var d = G.document;\n"
"      var b = d && (d.body || d.documentElement);\n"
"      if (!b || !b.getAttribute) return;\n"
"      var src = b.getAttribute('on' + ty);\n"
"      if (!src) return;\n"
"      ran[ty] = true;\n"
"      var f;\n"
"      try { f = new Function('event', src); }\n"
"      catch (e) { return; }\n"
"      f.call(b, ev);\n"
"    });\n"
"  });\n"
"})(globalThis);\n";

/* document.fonts (CSS Font Loading) and FontFace.
 *
 * CREDIT WHERE IT IS DUE, because the numbers in this file's header would
 * otherwise claim it: 165 corpus files died on `document.fonts.ready` when the
 * ranking that motivated this file was taken, and the web-API line landed a
 * document.fonts in js_webapi.c (a413491) while this was being written. Theirs
 * is the one the browser gets -- this shim installs ONLY if the property is
 * absent, which in the shipping build it is not. It is not dead code: the CSS
 * host tests and any runner that links js_cssom.c without js_webapi.c get
 * theirs from here. But this line did not fix those 165 files and does not
 * count them.
 *
 * The shape either way: `document.fonts.ready.then(() => { ...the test... })`
 * is a GATE in front of the test, not the thing under test.
 *
 * Everything here resolves immediately and reports loaded, which is the truth
 * for this engine: fonts come off the LogitFS disk at text_init() and there is
 * no asynchronous font fetch to wait for. check() answering true is the one
 * claim that is not the truth -- it says any font is available -- and it is
 * made deliberately, because the alternative answer (false) sends a page down
 * a fallback path when the fallback IS what it would get anyway.
 */
static const char *SHIM_FONTS =
"(function (G) {\n"
"  var D = G.document;\n"
"  if (!D || D.fonts) return;\n"
"  var faces = [];\n"
"  var set = {\n"
"    status: 'loaded',\n"
"    get size() { return faces.length; },\n"
"    check: function () { return true; },\n"
"    load: function () { return Promise.resolve([]); },\n"
"    add: function (f) { if (faces.indexOf(f) < 0) faces.push(f); return set; },\n"
"    delete: function (f) { var i = faces.indexOf(f);\n"
"                           if (i < 0) return false; faces.splice(i, 1); return true; },\n"
"    clear: function () { faces.length = 0; },\n"
"    has: function (f) { return faces.indexOf(f) >= 0; },\n"
"    forEach: function (cb, th) { faces.forEach(function (f) { cb.call(th, f, f, set); }); },\n"
"    values: function () { return faces[Symbol.iterator](); },\n"
"    keys: function () { return faces[Symbol.iterator](); },\n"
"    entries: function () { return faces.map(function (f) { return [f, f]; })[Symbol.iterator](); },\n"
"    addEventListener: function () {}, removeEventListener: function () {},\n"
"    dispatchEvent: function () { return true; },\n"
"    onloading: null, onloadingdone: null, onloadingerror: null\n"
"  };\n"
"  set[Symbol.iterator] = function () { return faces[Symbol.iterator](); };\n"
"  set.ready = Promise.resolve(set);\n"
"  Object.defineProperty(D, 'fonts', { get: function () { return set; }, configurable: true });\n"
"  if (!G.FontFace) {\n"
"    G.FontFace = function FontFace(family, source, desc) {\n"
"      if (!(this instanceof FontFace)) throw new TypeError('FontFace is a constructor');\n"
"      desc = desc || {};\n"
"      this.family = String(family);\n"
"      this.style = desc.style || 'normal';\n"
"      this.weight = desc.weight || 'normal';\n"
"      this.stretch = desc.stretch || 'normal';\n"
"      this.unicodeRange = desc.unicodeRange || 'U+0-10FFFF';\n"
"      this.variant = desc.variant || 'normal';\n"
"      this.featureSettings = desc.featureSettings || 'normal';\n"
"      this.variationSettings = desc.variationSettings || 'normal';\n"
"      this.display = desc.display || 'auto';\n"
"      this.ascentOverride = desc.ascentOverride || 'normal';\n"
"      this.descentOverride = desc.descentOverride || 'normal';\n"
"      this.lineGapOverride = desc.lineGapOverride || 'normal';\n"
"      this.sizeAdjust = desc.sizeAdjust || '100%';\n"
"      this.status = 'loaded';\n"
"      this._source = source;\n"
"      this.loaded = Promise.resolve(this);\n"
"    };\n"
"    G.FontFace.prototype.load = function () { return Promise.resolve(this); };\n"
"  }\n"
"})(globalThis);\n";

/* ==========================================================================
 * Install
 * ========================================================================== */

static int g_installed;

static void def_getset(JSContext *ctx, JSValueConst proto, const char *name,
                       JSValue (*get)(JSContext *, JSValueConst, int),
                       JSValue (*set)(JSContext *, JSValueConst, JSValueConst, int),
                       int magic)
{
    JSAtom a = JS_NewAtom(ctx, name);
    JSValue g = JS_NewCFunction2(ctx, (JSCFunction *)get, name, 0,
                                 JS_CFUNC_getter_magic, magic);
    JSValue s = set ? JS_NewCFunction2(ctx, (JSCFunction *)set, name, 1,
                                       JS_CFUNC_setter_magic, magic)
                    : JS_UNDEFINED;
    JS_DefinePropertyGetSet(ctx, proto, a, g, s, JS_PROP_CONFIGURABLE);
    JS_FreeAtom(ctx, a);
}

void js_cssom_install(JSContext *ctx)
{
    if (!ctx) return;
    g_installed = 1;
    g_cache_node = 0; g_cache_ptr = 0;
    g_scrolln = 0;
    g_saw_dirty = 0;
    g_sheetlist = JS_UNDEFINED;
    free(g_sheetsrc); g_sheetsrc = 0; g_sheetsrclen = 0;

    JSValue g = JS_GetGlobalObject(ctx);

    /* The Element prototype. `Element` is the one js_dom.c publishes when its
     * interface hierarchy is built; the createElement fallback is for a build
     * with JSDOM_NO_INTERFACE_HIERARCHY, which is exactly what the WPT
     * negative control uses -- so without the fallback the negative control
     * would fail for the wrong reason. */
    static const char *GETPROTO =
        "(typeof Element !== 'undefined' && Element.prototype) ||"
        " Object.getPrototypeOf(document.createElement('div'))";
    JSValue proto = JS_Eval(ctx, GETPROTO, strlen(GETPROTO), "<cssom>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(proto)) { JS_FreeValue(ctx, JS_GetException(ctx)); proto = JS_NULL; }

    if (JS_IsObject(proto)) {
        def_getset(ctx, proto, "offsetWidth",  el_geom, 0, G_OFFSET_W);
        def_getset(ctx, proto, "offsetHeight", el_geom, 0, G_OFFSET_H);
        def_getset(ctx, proto, "offsetLeft",   el_geom, 0, G_OFFSET_L);
        def_getset(ctx, proto, "offsetTop",    el_geom, 0, G_OFFSET_T);
        def_getset(ctx, proto, "clientWidth",  el_geom, 0, G_CLIENT_W);
        def_getset(ctx, proto, "clientHeight", el_geom, 0, G_CLIENT_H);
        def_getset(ctx, proto, "clientLeft",   el_geom, 0, G_CLIENT_L);
        def_getset(ctx, proto, "clientTop",    el_geom, 0, G_CLIENT_T);
        def_getset(ctx, proto, "scrollWidth",  el_geom, 0, G_SCROLL_W);
        def_getset(ctx, proto, "scrollHeight", el_geom, 0, G_SCROLL_H);
        def_getset(ctx, proto, "scrollTop",  el_scroll_get, el_scroll_set, 0);
        def_getset(ctx, proto, "scrollLeft", el_scroll_get, el_scroll_set, 1);
        JS_SetPropertyStr(ctx, proto, "__cssomOffsetParentHops",
            JS_NewCFunction(ctx, el_offsetParentHops, "__cssomOffsetParentHops", 1));
        {
            /* Defined in JS so the walk goes through js_dom.c's wrapper cache
             * -- see the comment on el_offsetParentHops. */
            static const char *OP =
                "Object.defineProperty(("
                "  (typeof Element !== 'undefined' && Element.prototype) ||"
                "  Object.getPrototypeOf(document.createElement('div'))),"
                " 'offsetParent', { configurable: true, get: function () {"
                "   var n = this.__cssomOffsetParentHops(this);"
                "   if (n < 0) return null;"
                "   var p = this;"
                "   while (n-- > 0 && p) p = p.parentNode;"
                "   return p || null;"
                " } });";
            JSValue v = JS_Eval(ctx, OP, strlen(OP), "<cssom offsetParent>",
                                JS_EVAL_TYPE_GLOBAL);
            if (JS_IsException(v)) JS_FreeValue(ctx, JS_GetException(ctx));
            JS_FreeValue(ctx, v);
        }
        /* REPLACES js_dom.c's getBoundingClientRect. Same display list, two
         * differences that matter: this one flushes a pending layout first,
         * and it prefers the element's OWN painted rect over the subtree ink
         * union when layout emitted one. */
        JS_SetPropertyStr(ctx, proto, "getBoundingClientRect",
            JS_NewCFunction(ctx, el_getBoundingClientRect, "getBoundingClientRect", 0));
        JS_SetPropertyStr(ctx, proto, "getClientRects",
            JS_NewCFunction(ctx, el_getClientRects, "getClientRects", 0));
    }
    JS_FreeValue(ctx, proto);

    /* The CSS namespace object. */
    JSValue css = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, css, "supports", JS_NewCFunction(ctx, js_CSS_supports, "supports", 2));
    JS_SetPropertyStr(ctx, css, "escape",   JS_NewCFunction(ctx, js_CSS_escape, "escape", 1));
    JS_SetPropertyStr(ctx, g, "CSS", css);

    JS_SetPropertyStr(ctx, g, "DOMRect",
        JS_NewCFunction2(ctx, js_DOMRect, "DOMRect", 4, JS_CFUNC_constructor, 0));
    JS_SetPropertyStr(ctx, g, "DOMRectReadOnly",
        JS_NewCFunction2(ctx, js_DOMRect, "DOMRectReadOnly", 4, JS_CFUNC_constructor, 0));

    /* Wins over js_webapi.c's: see the note above js_matchMedia. */
    JS_SetPropertyStr(ctx, g, "matchMedia",
        JS_NewCFunction(ctx, js_matchMedia, "matchMedia", 1));

    /* document.styleSheets */
    JSValue doc = JS_GetPropertyStr(ctx, g, "document");
    if (JS_IsObject(doc)) {
        JSAtom a = JS_NewAtom(ctx, "styleSheets");
        JS_DefinePropertyGetSet(ctx, doc, a,
            JS_NewCFunction2(ctx, (JSCFunction *)doc_styleSheets, "styleSheets", 0,
                             JS_CFUNC_getter, 0),
            JS_UNDEFINED, JS_PROP_CONFIGURABLE);
        JS_FreeAtom(ctx, a);
    }
    JS_FreeValue(ctx, doc);
    JS_FreeValue(ctx, g);

    JSValue r;
    r = JS_Eval(ctx, SHIM_FONTS, strlen(SHIM_FONTS), "<cssom fonts>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(r)) JS_FreeValue(ctx, JS_GetException(ctx));
    JS_FreeValue(ctx, r);
    r = JS_Eval(ctx, SHIM_BODY_HANDLERS, strlen(SHIM_BODY_HANDLERS),
                "<cssom body handlers>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(r)) JS_FreeValue(ctx, JS_GetException(ctx));
    JS_FreeValue(ctx, r);
}

void js_cssom_close(JSContext *ctx)
{
    if (!g_installed) return;
    g_installed = 0;
    g_cache_node = 0; g_cache_ptr = 0;
    free(g_scroll); g_scroll = 0; g_scrolln = g_scrollcap = 0;
    free(g_sheets); g_sheets = 0; g_nsheets = 0;
    /* The cached StyleSheetList holds a live GC reference; JS_FreeRuntime
     * asserts on one that outlives the context, which is why this is a close
     * hook and not just a static that gets forgotten at exit. */
    if (ctx) JS_FreeValue(ctx, g_sheetlist);
    g_sheetlist = JS_UNDEFINED;
    free(g_sheetsrc); g_sheetsrc = 0; g_sheetsrclen = 0;
}
