/* c/apps/browser/js_idb.c -- IndexedDB: a coherent, session-scoped subset.
 *
 * js_platform.h used to argue, correctly, that indexedDB should stay absent
 * until the bar below could be met: "every IDBRequest this build can
 * produce, on every path including the ones left unimplemented, terminates
 * in success or a thrown/fired error -- never silently pending." This file
 * is the implementation that meets it, and the structural argument for WHY
 * it meets it is worth stating before the code, because the code is long.
 *
 * THE ONE INVARIANT EVERYTHING ELSE IS BUILT AROUND: scheduleSettle() (below)
 * is the ONLY way an IDBRequest is ever produced. It (1) creates the request
 * object, (2) schedules its settle-task on G.setTimeout -- the SAME timer
 * queue js_page.c's g_timers already is, which js_page_pending() already
 * reports -- BEFORE running any implementation code, with a DEFAULT PAYLOAD
 * that is an error (an UnknownError DOMException), and only THEN (3) runs
 * the operation and overwrites the payload if it completes normally. A
 * request therefore cannot leave this file without a settle-task already on
 * the queue; there is no method here that returns an IDBRequest without
 * going through it. If a future edit adds a code path that forgets to
 * compute a result, the default payload fires error instead of hanging.
 *
 * A request created inside an aborting/aborted transaction is forced to the
 * error path (AbortError) at fire time regardless of what its own operation
 * computed (fireSettle checks txn._finished first) -- so "the transaction
 * aborted between this request creation and its settle-task running" is not
 * a third state, it collapses into the same error path.
 *
 * WHAT IS DELIBERATELY NOT HERE, refused rather than half-built (see
 * js_platform.h and the workflow scope note for the corpus counts):
 *   - Durability across a page load / reboot. In-memory only, scoped to one
 *     JSContext -- the SAME durability localStorage already has on this
 *     machine (js_webapi.c g_stores is a bare array with no file backing).
 *     There is no VFS positional write to build real durability on (CLAUDE.md
 *     structural gap #3), and a store that survives sometimes is worse than
 *     one that honestly does not, so this does not pretend to.
 *   - Blob/File as a stored value: put()/add() with one THROWS DataCloneError
 *     SYNCHRONOUSLY, at the call, the same shape as c/apps/libc ENOSYS rule
 *     -- refuse by name rather than hand back a request that resolves to
 *     something silently wrong.
 *   - IDBIndex.getAllRecords / IDBObjectStore.getAllRecords. Left undefined;
 *     feature detection reports false, correctly.
 *   - Worker / iframe scope. THIS SENTENCE USED TO READ "there are no workers
 *     and no nested browsing contexts in this tree", and it went stale the
 *     same day it was written: c/apps/browser/js_worker.c landed on
 *     2026-08-28 and builds a SECOND JSRuntime/JSContext with its own global
 *     (worker_install_globals), which this file is never invited to install
 *     into. The CONCLUSION is unchanged and still deliberate -- inside a
 *     Worker, `typeof indexedDB === 'undefined'`, which is the correct
 *     feature-detect answer for a scope where it genuinely is not there --
 *     but the reason is now a choice rather than an absence, so it has to be
 *     stated as one. Two things follow, and the next person to widen this
 *     should know both: (1) values do not cross JSRuntimes, so a shared
 *     store would need the structuredClone boundary at every call, not a
 *     pointer; (2) IndexedDB's whole point in a Worker is that the two scopes
 *     see the SAME database, and a per-worker store that silently did not
 *     would be present-and-wrong -- the exact failure this file exists to
 *     avoid. Absent is the right answer until that is built properly.
 *
 * SCOPE CHOICES WORTH NAMING, each a documented simplification rather than a
 * silent deviation:
 *   - The actual data operation for every request runs SYNCHRONOUSLY at call
 *     time (single JS thread, nothing else can mutate the store between the
 *     call and the deferred event); only the firing of success/error is
 *     deferred. This also makes cross-request ordering trivially correct:
 *     js_page.c timer loop fires same-tick, zero-delay timers in creation
 *     order (ascending seq), so requests settle in the order they were
 *     made, which is what most of the corpus assumes.
 *   - A transaction auto-commits via a task that reschedules itself while
 *     requests are still outstanding (txn._reqCount > 0) and commits once it
 *     reaches zero -- an idle transaction commits rather than lingering,
 *     without needing to model the spec synchronous-task activity window
 *     precisely. The cost, stated rather than hidden: TransactionInactiveError
 *     is enforced only once a transaction has actually finished, not for the
 *     spec narrower between-tasks window -- this build is MORE permissive
 *     than spec there, never silently less (a request that would have to
 *     throw synchronously in a real browser instead gets accepted and still
 *     terminates correctly here).
 *   - Event propagation does not implement generic DOM bubbling (the
 *     constructible EventTarget this stands on has none -- see js_events.c).
 *     request -> transaction -> connection propagation for unhandled errors
 *     is done as distinct, freshly-built events at each level rather than one
 *     event re-dispatched with a walked target, which is observationally the
 *     same for a non-composed leaf target and is what this corpus needs.
 *   - Cursors recompute their full candidate list from the store/index on
 *     every openCursor/continue/advance call rather than maintaining a live
 *     iterator. O(records) per step, correct by construction (no stale
 *     iterator state to get wrong), and fine at this scale -- the corpus
 *     stores hold tens of records, not millions.
 *
 * Install AFTER js_events_install (needs the real, constructible
 * EventTarget) and after js_platform_install (needs G.DOMException and
 * G.structuredClone). See js_idb.h.
 */

#include "js_idb.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *IDB_JS =
"(function (G) {\n"
"if (G.indexedDB) return;\n"
"if (typeof G.EventTarget !== 'function') return;\n"
"if (typeof G.DOMException !== 'function') return;\n"
"if (typeof G.structuredClone !== 'function') return;\n"
"if (typeof G.Event !== 'function') return;\n"
"if (typeof G.setTimeout !== 'function') return;\n"
"\n"
"function named(f, n, len) {\n"
"  try { Object.defineProperty(f, 'name', { value: n, configurable: true }); } catch (e) {}\n"
"  try { Object.defineProperty(f, 'length', { value: len, configurable: true }); } catch (e) {}\n"
"  return f;\n"
"}\n"
"function derr(msg, name) { return new G.DOMException(msg, name); }\n"
"\n"
/* ==== the total key order (spec 6.1: number < date < string < binary <
 * array, arrays compared element-wise then by length) ===================== */
"function keyTypeRank(k) {\n"
"  if (typeof k === 'number') return isNaN(k) ? -1 : 0;\n"
"  if (k instanceof Date) return isNaN(k.getTime()) ? -1 : 1;\n"
"  if (typeof k === 'string') return 2;\n"
"  if (k instanceof ArrayBuffer || (G.ArrayBuffer && G.ArrayBuffer.isView && G.ArrayBuffer.isView(k))) return 3;\n"
"  if (Array.isArray(k)) return 4;\n"
"  return -1;\n"
"}\n"
"function isValidKey(k, seen) {\n"
"  var r = keyTypeRank(k);\n"
"  if (r < 0) return false;\n"
"  if (r === 4) {\n"
"    seen = seen || [];\n"
"    if (seen.indexOf(k) >= 0) return false;\n"
"    seen = seen.concat([k]);\n"
"    for (var i = 0; i < k.length; i++) if (!isValidKey(k[i], seen)) return false;\n"
"  }\n"
"  return true;\n"
"}\n"
"function normalizeKeyOrThrow(k) {\n"
"  if (k && k.__isRange) throw derr('the parameter is not a valid key', 'DataError');\n"
"  if (!isValidKey(k)) throw derr('the parameter is not a valid key', 'DataError');\n"
"  return k;\n"
"}\n"
"function keyBytes(k) {\n"
"  if (k instanceof ArrayBuffer) return new Uint8Array(k);\n"
"  return new Uint8Array(k.buffer, k.byteOffset, k.byteLength);\n"
"}\n"
"function cmpBytes(a, b) {\n"
"  var n = Math.min(a.length, b.length);\n"
"  for (var i = 0; i < n; i++) if (a[i] !== b[i]) return a[i] < b[i] ? -1 : 1;\n"
"  return a.length < b.length ? -1 : a.length > b.length ? 1 : 0;\n"
"}\n"
"function compareKeys(a, b) {\n"
"  var ta = keyTypeRank(a), tb = keyTypeRank(b);\n"
"  if (ta !== tb) return ta < tb ? -1 : 1;\n"
"  switch (ta) {\n"
"  case 0: return a < b ? -1 : a > b ? 1 : 0;\n"
"  case 1: { var av = a.getTime(), bv = b.getTime(); return av < bv ? -1 : av > bv ? 1 : 0; }\n"
"  case 2: return a < b ? -1 : a > b ? 1 : 0;\n"
"  case 3: return cmpBytes(keyBytes(a), keyBytes(b));\n"
"  case 4: {\n"
"    var n = Math.min(a.length, b.length);\n"
"    for (var i = 0; i < n; i++) { var c = compareKeys(a[i], b[i]); if (c) return c; }\n"
"    return a.length < b.length ? -1 : a.length > b.length ? 1 : 0;\n"
"  }\n"
"  }\n"
"  return 0;\n"
"}\n"
"\n"
/* ==== key paths ============================================================ */
"function evalSingle(value, path) {\n"
"  if (path === '') return value;\n"
"  var parts = String(path).split('.'), cur = value;\n"
"  for (var i = 0; i < parts.length; i++) {\n"
"    if (cur === null || typeof cur === 'undefined') return undefined;\n"
"    if (typeof cur !== 'object' && typeof cur !== 'string') return undefined;\n"
"    cur = cur[parts[i]];\n"
"  }\n"
"  return cur;\n"
"}\n"
"function evalKeyPath(value, path) {\n"
"  if (Array.isArray(path)) {\n"
"    var out = [];\n"
"    for (var i = 0; i < path.length; i++) {\n"
"      var v = evalSingle(value, path[i]);\n"
"      if (v === undefined) return undefined;\n"
"      out.push(v);\n"
"    }\n"
"    return out;\n"
"  }\n"
"  return evalSingle(value, path);\n"
"}\n"
"function injectKeyPath(value, path, key) {\n"
"  if (Array.isArray(path) || path === '') return;\n"
"  var parts = String(path).split('.'), cur = value;\n"
"  for (var i = 0; i < parts.length - 1; i++) {\n"
"    if (typeof cur[parts[i]] !== 'object' || cur[parts[i]] === null) cur[parts[i]] = {};\n"
"    cur = cur[parts[i]];\n"
"  }\n"
"  cur[parts[parts.length - 1]] = key;\n"
"}\n"
"\n"
/* ==== IDBKeyRange =========================================================== */
"function rangeIncludes(r, key) {\n"
"  if (r.lower !== undefined) {\n"
"    var c = compareKeys(key, r.lower);\n"
"    if (c < 0 || (c === 0 && r.lowerOpen)) return false;\n"
"  }\n"
"  if (r.upper !== undefined) {\n"
"    var c2 = compareKeys(key, r.upper);\n"
"    if (c2 > 0 || (c2 === 0 && r.upperOpen)) return false;\n"
"  }\n"
"  return true;\n"
"}\n"
"var KRCtor = named(function IDBKeyRange() { throw new TypeError('illegal constructor'); }, 'IDBKeyRange', 0);\n"
"var KRProto = KRCtor.prototype;\n"
"KRProto.constructor = KRCtor;\n"
"function makeRange(lower, upper, lowerOpen, upperOpen) {\n"
"  var r = Object.create(KRProto);\n"
"  r.lower = lower; r.upper = upper; r.lowerOpen = !!lowerOpen; r.upperOpen = !!upperOpen;\n"
"  r.__isRange = true;\n"
"  return r;\n"
"}\n"
"KRProto.includes = named(function (key) { return rangeIncludes(this, normalizeKeyOrThrow(key)); }, 'includes', 1);\n"
"KRCtor.only = named(function (v) { v = normalizeKeyOrThrow(v); return makeRange(v, v, false, false); }, 'only', 1);\n"
"KRCtor.lowerBound = named(function (v, open) { v = normalizeKeyOrThrow(v); return makeRange(v, undefined, !!open, false); }, 'lowerBound', 1);\n"
"KRCtor.upperBound = named(function (v, open) { v = normalizeKeyOrThrow(v); return makeRange(undefined, v, false, !!open); }, 'upperBound', 1);\n"
"KRCtor.bound = named(function (lo, hi, loOpen, hiOpen) {\n"
"  lo = normalizeKeyOrThrow(lo); hi = normalizeKeyOrThrow(hi);\n"
"  var c = compareKeys(lo, hi);\n"
"  if (c > 0) throw derr('the lower key bound is greater than the upper key bound', 'DataError');\n"
"  if (c === 0 && (loOpen || hiOpen)) throw derr('the lower key bound equals the upper key bound and one side is open', 'DataError');\n"
"  return makeRange(lo, hi, !!loOpen, !!hiOpen);\n"
"}, 'bound', 2);\n"
"function normalizeQuery(query, required) {\n"
"  if (query === undefined) { if (required) throw new TypeError('a key or key range parameter is required'); return undefined; }\n"
/*  getAll/count/openCursor all default their query parameter to null in the
 *  WebIDL (`optional (IDBKeyRange or any)? query = null`), so an explicit
 *  null there means the same as omitted: no filter. get()/getKey() have NO
 *  default -- an explicit null is a real, invalid key and must DataError,
 *  which is why this branch only applies when the argument was optional. */
"  if (!required && query === null) return undefined;\n"
"  if (query !== null && typeof query === 'object' && query.__isRange) return query;\n"
"  return normalizeKeyOrThrow(query);\n"
"}\n"
"function matchesQuery(q, key) {\n"
"  if (q === undefined) return true;\n"
"  if (q && q.__isRange) return rangeIncludes(q, key);\n"
"  return compareKeys(q, key) === 0;\n"
"}\n"
"\n"
/* ==== the database registry: name -> {name, version, stores, openConns,
 * waiters}, in-memory for the life of this JSContext ======================= */
"var DBS = new Map();\n"
"function addOpenConn(rec, conn) { rec.openConns.push(conn); }\n"
"function removeOpenConn(rec, conn) {\n"
"  var i = rec.openConns.indexOf(conn);\n"
"  if (i >= 0) rec.openConns.splice(i, 1);\n"
"}\n"
"function liveConns(rec) { return rec.openConns.filter(function (c) { return !c._closed; }); }\n"
"function checkWaitersForDb(rec) {\n"
"  if (liveConns(rec).length > 0) return;\n"
"  if (!rec.waiters.length) return;\n"
"  var w = rec.waiters.shift();\n"
"  if (w.kind === 'open') beginUpgrade(w.req, rec, w.targetVersion);\n"
"  else performDelete(w.req, rec);\n"
"}\n"
"\n"
/* ==== events, generic ======================================================= */
"function mkEvent(type, cancelable) { return new G.Event(type, { bubbles: false, cancelable: !!cancelable }); }\n"
"function dispatchAt(target, ev) { return target.dispatchEvent(ev); }\n"
"var VCEProto;\n"
"function mkVCE(type, oldV, newV) {\n"
"  var e = new G.Event(type, { bubbles: false, cancelable: false });\n"
"  try { Object.setPrototypeOf(e, VCEProto); } catch (q) {}\n"
"  Object.defineProperty(e, 'oldVersion', { value: oldV, enumerable: true, configurable: true });\n"
"  Object.defineProperty(e, 'newVersion', { value: newV === undefined ? null : newV, enumerable: true, configurable: true });\n"
"  return e;\n"
"}\n"
"var IVCE = named(function IDBVersionChangeEvent(type, init) {\n"
"  if (!new.target) throw new TypeError('constructor IDBVersionChangeEvent requires new');\n"
"  init = init || {};\n"
"  return mkVCE(String(type), init.oldVersion === undefined ? 0 : init.oldVersion, init.newVersion === undefined ? null : init.newVersion);\n"
"}, 'IDBVersionChangeEvent', 1);\n"
"VCEProto = Object.create(G.Event.prototype);\n"
"VCEProto.constructor = IVCE;\n"
"IVCE.prototype = VCEProto;\n"
"\n"
"function defHandler(proto, evtName, propName) {\n"
"  var slot = '_h_' + propName;\n"
"  Object.defineProperty(proto, propName, {\n"
"    configurable: true, enumerable: true,\n"
"    get: function () { return this[slot] || null; },\n"
"    set: function (v) {\n"
"      var cur = this[slot];\n"
"      if (cur) { try { this.removeEventListener(evtName, cur); } catch (q) {} }\n"
"      this[slot] = (typeof v === 'function') ? v : null;\n"
"      if (this[slot]) { try { this.addEventListener(evtName, this[slot]); } catch (q) {} }\n"
"    }\n"
"  });\n"
"}\n"
"\n"
/* ==== IDBRequest / IDBOpenDBRequest ========================================
 * makeRequest builds the bare object; scheduleSettle is the ONLY function
 * that gives one a settle-task, and it always schedules one before running
 * the caller-supplied work -- see the file header. */
"var ReqProto = Object.create(G.EventTarget.prototype);\n"
"var OpenReqProto = Object.create(ReqProto);\n"
"function makeRequest(source, txn) {\n"
"  var req = Object.create(ReqProto);\n"
"  req.readyState = 'pending'; req.result = undefined; req.error = null;\n"
"  req.source = source || null; req.transaction = txn || null;\n"
"  return req;\n"
"}\n"
"function makeOpenRequest() {\n"
"  var req = Object.create(OpenReqProto);\n"
"  req.readyState = 'pending'; req.result = undefined; req.error = null;\n"
"  req.source = null; req.transaction = null;\n"
"  return req;\n"
"}\n"
"function fireSettle(req, txn, payload) {\n"
"  if (txn) txn._reqCount--;\n"
"  req.readyState = 'done';\n"
"  if (txn && txn._finished) {\n"
"    payload = { ok: false, err: txn.error || derr('the transaction was aborted before this request completed', 'AbortError') };\n"
"  }\n"
"  if (payload.ok) {\n"
"    req.result = payload.result; req.error = null;\n"
"    dispatchAt(req, mkEvent('success', false));\n"
"  } else {\n"
"    req.result = undefined; req.error = payload.err;\n"
"    var ev = mkEvent('error', true);\n"
"    var notPrevented = dispatchAt(req, ev);\n"
"    if (notPrevented && txn && !txn._finished) abortTransaction(txn, payload.err);\n"
"  }\n"
"}\n"
/* THE invariant: schedule first, with a payload that defaults to error, THEN
 * run the caller work and overwrite it. A codepath that throws for a reason
 * this file did not anticipate still lands on 'error' -- fn is wrapped in
 * try/catch here, not by each caller. */
"function scheduleSettle(req, txn, fn) {\n"
"  var payload = { ok: false, err: derr('indexedDB: the request was not completed', 'UnknownError') };\n"
"  if (txn) txn._reqCount++;\n"
"  G.setTimeout(function () { fireSettle(req, txn, payload); }, 0);\n"
"  try {\n"
"    var r = fn();\n"
"    payload.ok = true; payload.result = r;\n"
"  } catch (e) {\n"
"    payload.ok = false;\n"
"    payload.err = (e instanceof G.DOMException) ? e : derr(String((e && e.message) || e), (e && e.name) || 'UnknownError');\n"
"  }\n"
"  return req;\n"
"}\n"
"defHandler(ReqProto, 'success', 'onsuccess');\n"
"defHandler(ReqProto, 'error', 'onerror');\n"
"defHandler(OpenReqProto, 'blocked', 'onblocked');\n"
"defHandler(OpenReqProto, 'upgradeneeded', 'onupgradeneeded');\n"
"\n"
/* ==== transactions =========================================================== */
"var TxnProto = Object.create(G.EventTarget.prototype);\n"
"function checkTxnUsable(txn) {\n"
"  if (!txn || txn._finished) throw derr('the transaction has finished', 'TransactionInactiveError');\n"
"}\n"
"function checkWritable(txn) {\n"
"  checkTxnUsable(txn);\n"
"  if (txn.mode === 'readonly') throw derr('the transaction is read-only', 'ReadOnlyError');\n"
"}\n"
"function applyUndo(u) {\n"
"  if (u.had) storePutRaw(u.store, u.key, u.prev); else storeDeleteRaw(u.store, u.key);\n"
"}\n"
"function finishTransaction(t, err) {\n"
"  if (t._finished) return;\n"
"  t._finished = true;\n"
"  var idx = t._conn._liveTxns.indexOf(t);\n"
"  if (idx >= 0) t._conn._liveTxns.splice(idx, 1);\n"
"  if (err) {\n"
"    for (var i = t._undo.length - 1; i >= 0; i--) applyUndo(t._undo[i]);\n"
"    t.error = err;\n"
"    dispatchAt(t, mkEvent('abort', false));\n"
"  } else {\n"
"    dispatchAt(t, mkEvent('complete', false));\n"
"  }\n"
"  if (t._finishHook) t._finishHook(!err, err);\n"
"}\n"
"function abortTransaction(t, err) { if (!t._finished) finishTransaction(t, err); }\n"
"function scheduleAutoCommit(t) {\n"
"  G.setTimeout(function () {\n"
"    if (t._finished) return;\n"
"    if (t._reqCount > 0) { scheduleAutoCommit(t); return; }\n"
"    finishTransaction(t, null);\n"
"  }, 0);\n"
"}\n"
"function makeTransaction(conn, storeNames, mode) {\n"
"  var t = Object.create(TxnProto);\n"
"  t.db = conn; t.mode = mode; t.error = null;\n"
"  t.objectStoreNames = mkStringList(storeNames);\n"
"  t._conn = conn; t._reqCount = 0; t._finished = false; t._undo = [];\n"
"  t._versionchange = (mode === 'versionchange');\n"
"  t._stores = new Map(); t._finishHook = null;\n"
"  conn._liveTxns.push(t);\n"
"  scheduleAutoCommit(t);\n"
"  return t;\n"
"}\n"
"TxnProto.objectStore = named(function (name) {\n"
"  if (this._finished) throw derr('the transaction has finished', 'InvalidStateError');\n"
"  name = String(name);\n"
"  if (this.objectStoreNames.indexOf(name) < 0) throw derr('no object store of that name in this transaction', 'NotFoundError');\n"
"  if (this._stores.has(name)) return this._stores.get(name);\n"
"  var os = makeStoreHandle(this, name);\n"
"  this._stores.set(name, os);\n"
"  return os;\n"
"}, 'objectStore', 1);\n"
"TxnProto.abort = named(function () {\n"
"  if (this._finished) throw derr('the transaction has finished', 'InvalidStateError');\n"
"  abortTransaction(this, derr('the transaction was aborted by the caller', 'AbortError'));\n"
"}, 'abort', 0);\n"
"TxnProto.commit = named(function () {\n"
"  if (this._finished) throw derr('the transaction has finished', 'InvalidStateError');\n"
"  this._committing = true;\n"
"}, 'commit', 0);\n"
"defHandler(TxnProto, 'complete', 'oncomplete');\n"
"defHandler(TxnProto, 'abort', 'onabort');\n"
"defHandler(TxnProto, 'error', 'onerror');\n"
"\n"
/* ==== the store, on disk (in memory): sorted array of {key, value},
 * a Map of indexes, autoIncrement counter ==================================== */
"function storeFindIndexPos(rec, key) {\n"
"  var i = 0;\n"
"  while (i < rec.records.length && compareKeys(rec.records[i].key, key) < 0) i++;\n"
"  return i;\n"
"}\n"
"function storeFindEntry(rec, key) {\n"
"  var i = storeFindIndexPos(rec, key);\n"
"  if (i < rec.records.length && compareKeys(rec.records[i].key, key) === 0) return rec.records[i];\n"
"  return null;\n"
"}\n"
"function storePutRaw(rec, key, value) {\n"
"  var i = storeFindIndexPos(rec, key);\n"
"  if (i < rec.records.length && compareKeys(rec.records[i].key, key) === 0) rec.records[i] = { key: key, value: value };\n"
"  else rec.records.splice(i, 0, { key: key, value: value });\n"
"}\n"
"function storeDeleteRaw(rec, key) {\n"
"  var i = storeFindIndexPos(rec, key);\n"
"  if (i < rec.records.length && compareKeys(rec.records[i].key, key) === 0) rec.records.splice(i, 1);\n"
"}\n"
"function indexEntries(storeRec, idxRec) {\n"
"  var out = [];\n"
"  storeRec.records.forEach(function (r) {\n"
"    var kv = evalKeyPath(r.value, idxRec.keyPath);\n"
"    if (kv === undefined) return;\n"
"    if (idxRec.multiEntry && Array.isArray(kv)) {\n"
"      var seen = [];\n"
"      kv.forEach(function (k) {\n"
"        if (!isValidKey(k)) return;\n"
"        for (var i = 0; i < seen.length; i++) if (compareKeys(seen[i], k) === 0) return;\n"
"        seen.push(k);\n"
"        out.push({ key: k, primary: r.key, value: r.value });\n"
"      });\n"
"    } else if (isValidKey(kv)) {\n"
"      out.push({ key: kv, primary: r.key, value: r.value });\n"
"    }\n"
"  });\n"
"  out.sort(function (a, b) { var c = compareKeys(a.key, b.key); return c ? c : compareKeys(a.primary, b.primary); });\n"
"  return out;\n"
"}\n"
"function readEntries(storeRec, idxRec) {\n"
"  return idxRec ? indexEntries(storeRec, idxRec)\n"
"    : storeRec.records.map(function (r) { return { key: r.key, primary: r.key, value: r.value }; });\n"
"}\n"
"function firstMatch(list, q) {\n"
"  for (var i = 0; i < list.length; i++) if (matchesQuery(q, list[i].key)) return list[i];\n"
"  return null;\n"
"}\n"
"function checkUniqueIndexes(rec, value, k) {\n"
"  rec.indexes.forEach(function (idx) {\n"
"    if (!idx.unique) return;\n"
"    var kv = evalKeyPath(value, idx.keyPath);\n"
"    if (kv === undefined) return;\n"
"    var mine = (idx.multiEntry && Array.isArray(kv)) ? kv.filter(isValidKey) : (isValidKey(kv) ? [kv] : []);\n"
"    if (!mine.length) return;\n"
"    rec.records.forEach(function (r) {\n"
"      if (compareKeys(r.key, k) === 0) return;\n"
"      var kv2 = evalKeyPath(r.value, idx.keyPath);\n"
"      if (kv2 === undefined) return;\n"
"      var theirs = (idx.multiEntry && Array.isArray(kv2)) ? kv2.filter(isValidKey) : (isValidKey(kv2) ? [kv2] : []);\n"
"      mine.forEach(function (m) {\n"
"        theirs.forEach(function (o) {\n"
"          if (compareKeys(m, o) === 0) throw derr('a unique index constraint was violated', 'ConstraintError');\n"
"        });\n"
"      });\n"
"    });\n"
"  });\n"
"}\n"
"\n"
/* ==== IDBObjectStore ========================================================== */
"var OSProto = {};\n"
"function makeStoreHandle(txn, name) {\n"
"  var rec = txn._conn._dbRecord.stores.get(name);\n"
"  var os = Object.create(OSProto);\n"
"  os.name = name; os.transaction = txn;\n"
"  os.keyPath = (rec.keyPath === undefined) ? null : rec.keyPath;\n"
"  os.autoIncrement = !!rec.autoIncrement;\n"
"  os._rec = rec; os._txn = txn;\n"
"  Object.defineProperty(os, 'indexNames', {\n"
"    configurable: true, enumerable: true,\n"
"    get: function () { return mkStringList(Array.from(rec.indexes.keys()).sort()); }\n"
"  });\n"
"  return os;\n"
"}\n"
"function osPut(os, value, key, noOverwrite) {\n"
"  var txn = os._txn;\n"
"  checkWritable(txn);\n"
"  if (G.Blob && value instanceof G.Blob) throw derr('a Blob or File cannot be stored by this implementation', 'DataCloneError');\n"
"  var rec = os._rec;\n"
"  var kp = rec.keyPath;\n"
"  var explicitKey = (key !== undefined);\n"
"  if (kp !== null && kp !== undefined && explicitKey)\n"
"    throw derr('the object store uses in-line keys and a key parameter was also given', 'DataError');\n"
"  if (explicitKey) key = normalizeKeyOrThrow(key);\n"
"  if (kp === null || kp === undefined) {\n"
"    if (!explicitKey && !rec.autoIncrement) throw derr('no key was given and the object store has no key generator', 'DataError');\n"
"  }\n"
"  var cloned = G.structuredClone(value);\n"
"  var req = makeRequest(os, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var k = key;\n"
"    if (kp !== null && kp !== undefined) {\n"
"      var kv = evalKeyPath(cloned, kp);\n"
"      if (kv === undefined) {\n"
"        if (!rec.autoIncrement) throw derr('evaluating the key path did not yield a value', 'DataError');\n"
"        k = rec.nextKey++;\n"
"        injectKeyPath(cloned, kp, k);\n"
"      } else {\n"
"        if (!isValidKey(kv)) throw derr('the key path did not yield a valid key', 'DataError');\n"
"        k = kv;\n"
"        if (rec.autoIncrement && typeof k === 'number' && k >= rec.nextKey) rec.nextKey = Math.floor(k) + 1;\n"
"      }\n"
"    } else if (k === undefined) {\n"
"      k = rec.nextKey++;\n"
"    } else if (rec.autoIncrement && typeof k === 'number' && k >= rec.nextKey) {\n"
"      rec.nextKey = Math.floor(k) + 1;\n"
"    }\n"
"    var existing = storeFindEntry(rec, k);\n"
"    if (noOverwrite && existing) throw derr('a key already exists in the object store', 'ConstraintError');\n"
"    checkUniqueIndexes(rec, cloned, k);\n"
"    txn._undo.push(existing ? { store: rec, key: k, had: true, prev: existing.value } : { store: rec, key: k, had: false });\n"
"    storePutRaw(rec, k, cloned);\n"
"    return k;\n"
"  });\n"
"}\n"
"OSProto.add = named(function (value, key) { return osPut(this, value, key, true); }, 'add', 1);\n"
"OSProto.put = named(function (value, key) { return osPut(this, value, key, false); }, 'put', 1);\n"
"OSProto.get = named(function (query) {\n"
"  if (arguments.length < 1) throw new TypeError('get requires 1 argument');\n"
"  var os = this, txn = os._txn; checkTxnUsable(txn);\n"
"  var q = normalizeQuery(query, true);\n"
"  var req = makeRequest(os, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var e = firstMatch(readEntries(os._rec, null), q);\n"
"    return e ? G.structuredClone(e.value) : undefined;\n"
"  });\n"
"}, 'get', 1);\n"
"OSProto.getKey = named(function (query) {\n"
"  if (arguments.length < 1) throw new TypeError('getKey requires 1 argument');\n"
"  var os = this, txn = os._txn; checkTxnUsable(txn);\n"
"  var q = normalizeQuery(query, true);\n"
"  var req = makeRequest(os, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var e = firstMatch(readEntries(os._rec, null), q);\n"
"    return e ? e.primary : undefined;\n"
"  });\n"
"}, 'getKey', 1);\n"
"function doGetAll(os, idx, query, count, wantValues) {\n"
"  var txn = idx ? idx._txn : os._txn; checkTxnUsable(txn);\n"
"  var q = normalizeQuery(query, false);\n"
"  var lim = (count === undefined || count === 0) ? Infinity : Math.floor(Number(count));\n"
"  if (!(lim > 0)) lim = 0;\n"
"  var req = makeRequest(idx || os, txn);\n"
"  var storeRec = idx ? idx._store : os._rec;\n"
"  var idxRec = idx ? idx._idx : null;\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var list = readEntries(storeRec, idxRec), out = [];\n"
"    for (var i = 0; i < list.length && out.length < lim; i++)\n"
"      if (matchesQuery(q, list[i].key)) out.push(wantValues ? G.structuredClone(list[i].value) : list[i].primary);\n"
"    return out;\n"
"  });\n"
"}\n"
"OSProto.getAll = named(function (query, count) { return doGetAll(this, null, query, count, true); }, 'getAll', 0);\n"
"OSProto.getAllKeys = named(function (query, count) { return doGetAll(this, null, query, count, false); }, 'getAllKeys', 0);\n"
"OSProto.delete = named(function (query) {\n"
"  if (arguments.length < 1) throw new TypeError('delete requires 1 argument');\n"
"  var os = this, txn = os._txn; checkWritable(txn);\n"
"  var q = normalizeQuery(query, true);\n"
"  var req = makeRequest(os, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var rec = os._rec;\n"
"    var toDelete = rec.records.filter(function (r) { return matchesQuery(q, r.key); });\n"
"    toDelete.forEach(function (r) {\n"
"      txn._undo.push({ store: rec, key: r.key, had: true, prev: r.value });\n"
"      storeDeleteRaw(rec, r.key);\n"
"    });\n"
"    return undefined;\n"
"  });\n"
"}, 'delete', 1);\n"
"OSProto.clear = named(function () {\n"
"  var os = this, txn = os._txn; checkWritable(txn);\n"
"  var req = makeRequest(os, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var rec = os._rec;\n"
"    rec.records.forEach(function (r) { txn._undo.push({ store: rec, key: r.key, had: true, prev: r.value }); });\n"
"    rec.records = [];\n"
"    return undefined;\n"
"  });\n"
"}, 'clear', 0);\n"
"function doCount(os, idx, query) {\n"
"  var txn = idx ? idx._txn : os._txn; checkTxnUsable(txn);\n"
"  var q = normalizeQuery(query, false);\n"
"  var req = makeRequest(idx || os, txn);\n"
"  var storeRec = idx ? idx._store : os._rec;\n"
"  var idxRec = idx ? idx._idx : null;\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var list = readEntries(storeRec, idxRec), n = 0;\n"
"    for (var i = 0; i < list.length; i++) if (matchesQuery(q, list[i].key)) n++;\n"
"    return n;\n"
"  });\n"
"}\n"
"OSProto.count = named(function (query) { return doCount(this, null, query); }, 'count', 0);\n"
"OSProto.createIndex = named(function (name, keyPath, options) {\n"
"  var os = this, txn = os._txn;\n"
"  if (!txn._versionchange) throw derr('createIndex is only valid inside a versionchange transaction', 'InvalidStateError');\n"
"  if (txn._finished) throw derr('the transaction has finished', 'TransactionInactiveError');\n"
"  name = String(name);\n"
"  var rec = os._rec;\n"
"  if (rec.indexes.has(name)) throw derr('an index of that name already exists', 'ConstraintError');\n"
"  if (Array.isArray(keyPath)) {\n"
"    if (options && options.multiEntry) throw derr('multiEntry is not allowed with an array key path', 'InvalidAccessError');\n"
"    keyPath = keyPath.slice();\n"
"  } else keyPath = String(keyPath);\n"
"  var idx = { name: name, keyPath: keyPath, unique: !!(options && options.unique), multiEntry: !!(options && options.multiEntry) };\n"
"  rec.records.forEach(function (r) { checkUniqueIndexAdd(idx, r); });\n"
"  rec.indexes.set(name, idx);\n"
"  return makeIndexHandle(os, name);\n"
"}, 'createIndex', 2);\n"
"function checkUniqueIndexAdd(idx, r) {\n"
"  if (!idx.unique) return;\n"
"  var kv = evalKeyPath(r.value, idx.keyPath);\n"
"  if (kv === undefined) return;\n"
"  var mine = (idx.multiEntry && Array.isArray(kv)) ? kv.filter(isValidKey) : (isValidKey(kv) ? [kv] : []);\n"
"  idx._seen = idx._seen || [];\n"
"  mine.forEach(function (k) {\n"
"    for (var i = 0; i < idx._seen.length; i++)\n"
"      if (compareKeys(idx._seen[i], k) === 0) throw derr('a unique index constraint was violated by existing data', 'ConstraintError');\n"
"    idx._seen.push(k);\n"
"  });\n"
"}\n"
"OSProto.index = named(function (name) {\n"
"  name = String(name);\n"
"  if (!this._rec.indexes.has(name)) throw derr('no index of that name', 'NotFoundError');\n"
"  return makeIndexHandle(this, name);\n"
"}, 'index', 1);\n"
"OSProto.deleteIndex = named(function (name) {\n"
"  var txn = this._txn;\n"
"  if (!txn._versionchange) throw derr('deleteIndex is only valid inside a versionchange transaction', 'InvalidStateError');\n"
"  name = String(name);\n"
"  if (!this._rec.indexes.has(name)) throw derr('no index of that name', 'NotFoundError');\n"
"  this._rec.indexes.delete(name);\n"
"}, 'deleteIndex', 1);\n"
"OSProto.openCursor = named(function (query, direction) { return openCursorGeneric(this, null, this, this._txn, query, direction, false); }, 'openCursor', 0);\n"
"OSProto.openKeyCursor = named(function (query, direction) { return openCursorGeneric(this, null, this, this._txn, query, direction, true); }, 'openKeyCursor', 0);\n"
"\n"
/* ==== IDBIndex ================================================================ */
"var IdxProto = {};\n"
"function makeIndexHandle(os, name) {\n"
"  var idx = os._rec.indexes.get(name);\n"
"  var h = Object.create(IdxProto);\n"
"  h.name = name; h.objectStore = os;\n"
"  h.keyPath = idx.keyPath; h.multiEntry = idx.multiEntry; h.unique = idx.unique;\n"
"  h._idx = idx; h._store = os._rec; h._txn = os._txn;\n"
"  return h;\n"
"}\n"
"IdxProto.get = named(function (query) {\n"
"  if (arguments.length < 1) throw new TypeError('get requires 1 argument');\n"
"  var ix = this, txn = ix._txn; checkTxnUsable(txn);\n"
"  var q = normalizeQuery(query, true);\n"
"  var req = makeRequest(ix, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var e = firstMatch(readEntries(ix._store, ix._idx), q);\n"
"    return e ? G.structuredClone(e.value) : undefined;\n"
"  });\n"
"}, 'get', 1);\n"
"IdxProto.getKey = named(function (query) {\n"
"  if (arguments.length < 1) throw new TypeError('getKey requires 1 argument');\n"
"  var ix = this, txn = ix._txn; checkTxnUsable(txn);\n"
"  var q = normalizeQuery(query, true);\n"
"  var req = makeRequest(ix, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var e = firstMatch(readEntries(ix._store, ix._idx), q);\n"
"    return e ? e.primary : undefined;\n"
"  });\n"
"}, 'getKey', 1);\n"
"IdxProto.getAll = named(function (query, count) { return doGetAll(null, this, query, count, true); }, 'getAll', 0);\n"
"IdxProto.getAllKeys = named(function (query, count) { return doGetAll(null, this, query, count, false); }, 'getAllKeys', 0);\n"
"IdxProto.count = named(function (query) { return doCount(null, this, query); }, 'count', 0);\n"
"IdxProto.openCursor = named(function (query, direction) { return openCursorGeneric(this.objectStore, this, this, this._txn, query, direction, false); }, 'openCursor', 0);\n"
"IdxProto.openKeyCursor = named(function (query, direction) { return openCursorGeneric(this.objectStore, this, this, this._txn, query, direction, true); }, 'openKeyCursor', 0);\n"
"\n"
/* ==== IDBCursor / IDBCursorWithValue ==========================================
 * Recomputed candidate list on every step -- see the file header for why. */
"var CursorProto = {};\n"
"var CursorWithValueProto = Object.create(CursorProto);\n"
"function candidateList(cur) {\n"
"  var list = cur._index ? indexEntries(cur._store, cur._index)\n"
"    : cur._store.records.map(function (r) { return { key: r.key, primary: r.key, value: r.value }; });\n"
"  if (cur._range !== undefined) list = list.filter(function (e) { return matchesQuery(cur._range, e.key); });\n"
"  if (cur.direction === 'prev' || cur.direction === 'prevunique') list = list.slice().reverse();\n"
"  return list;\n"
"}\n"
"function findPos(list, cur) {\n"
"  if (cur.key === undefined) return -1;\n"
"  for (var i = 0; i < list.length; i++)\n"
"    if (compareKeys(list[i].key, cur.key) === 0 && compareKeys(list[i].primary, cur.primaryKey) === 0) return i;\n"
"  return -1;\n"
"}\n"
"function placeCursorAt(cur, list, i) {\n"
"  var e = list[i];\n"
"  cur.key = e.key; cur.primaryKey = e.primary;\n"
"  if (!cur._keyOnly) cur.value = G.structuredClone(e.value);\n"
"  cur._gotValue = true;\n"
"  return cur;\n"
"}\n"
"function finishCursorExhausted(cur) {\n"
"  cur.key = undefined; cur.primaryKey = undefined; if (!cur._keyOnly) cur.value = undefined;\n"
"  cur._gotValue = false; cur._done = true;\n"
"  return null;\n"
"}\n"
"function advanceCursorTo(cur, explicitKey, explicitPrimary, count) {\n"
"  var list = candidateList(cur);\n"
"  var pos = findPos(list, cur);\n"
"  var i;\n"
"  if (explicitKey !== undefined) {\n"
"    var reverse = (cur.direction === 'prev' || cur.direction === 'prevunique');\n"
"    i = pos + 1;\n"
"    while (i < list.length) {\n"
"      var e = list[i], ok;\n"
"      var ck = compareKeys(e.key, explicitKey);\n"
"      if (explicitPrimary !== undefined) {\n"
"        ok = reverse ? (ck < 0 || (ck === 0 && compareKeys(e.primary, explicitPrimary) <= 0))\n"
"                     : (ck > 0 || (ck === 0 && compareKeys(e.primary, explicitPrimary) >= 0));\n"
"      } else {\n"
"        ok = reverse ? ck <= 0 : ck >= 0;\n"
"      }\n"
"      if (ok) break;\n"
"      i++;\n"
"    }\n"
"  } else {\n"
"    i = pos + count;\n"
"  }\n"
"  if ((cur.direction === 'nextunique' || cur.direction === 'prevunique') && pos >= 0 && i < list.length) {\n"
"    while (i < list.length && compareKeys(list[i].key, list[pos].key) === 0) i++;\n"
"  }\n"
"  if (i < 0 || i >= list.length) return finishCursorExhausted(cur);\n"
"  return placeCursorAt(cur, list, i);\n"
"}\n"
"function makeCursor(sourceHandle, store, idx, range, direction, keyOnly, req) {\n"
"  var cur = Object.create(keyOnly ? CursorProto : CursorWithValueProto);\n"
"  cur.source = sourceHandle; cur.direction = direction;\n"
"  cur.key = undefined; cur.primaryKey = undefined;\n"
"  if (!keyOnly) cur.value = undefined;\n"
"  cur._store = store; cur._index = idx; cur._range = range; cur._keyOnly = keyOnly;\n"
"  cur._req = req; cur._gotValue = false; cur._done = false;\n"
"  return cur;\n"
"}\n"
"function openCursorGeneric(os, idx, sourceHandle, txn, query, direction, keyOnly) {\n"
"  checkTxnUsable(txn);\n"
"  direction = direction === undefined ? 'next' : String(direction);\n"
"  if (['next', 'nextunique', 'prev', 'prevunique'].indexOf(direction) < 0)\n"
"    throw new TypeError('unrecognised cursor direction: ' + direction);\n"
"  var range = normalizeQuery(query, false);\n"
"  var storeRec = idx ? idx._store : os._rec;\n"
"  var idxRec = idx ? idx._idx : null;\n"
"  var req = makeRequest(sourceHandle, txn);\n"
"  var cur = makeCursor(sourceHandle, storeRec, idxRec, range, direction, keyOnly, req);\n"
"  return scheduleSettle(req, txn, function () { return advanceCursorTo(cur, undefined, undefined, 1); });\n"
"}\n"
"function checkCursorGotValueOrActive(cur) {\n"
"  checkTxnUsable(cur._req.transaction);\n"
"  if (!cur._gotValue) throw derr('the cursor is exhausted or has not been positioned', 'InvalidStateError');\n"
"}\n"
"CursorProto.advance = named(function (count) {\n"
"  var cur = this;\n"
"  count = Number(count);\n"
"  if (!isFinite(count) || count < 1) throw new TypeError('advance requires a count of at least 1');\n"
"  checkCursorGotValueOrActive(cur);\n"
"  cur._gotValue = false; cur._req.readyState = 'pending';\n"
"  scheduleSettle(cur._req, cur._req.transaction, function () { return advanceCursorTo(cur, undefined, undefined, count | 0); });\n"
"}, 'advance', 1);\n"
"CursorProto.continue = named(function (key) {\n"
"  var cur = this;\n"
"  checkCursorGotValueOrActive(cur);\n"
"  if (key !== undefined) {\n"
"    key = normalizeKeyOrThrow(key);\n"
"    var c = compareKeys(key, cur.key);\n"
"    var reverse = (cur.direction === 'prev' || cur.direction === 'prevunique');\n"
"    if ((!reverse && c <= 0) || (reverse && c >= 0))\n"
"      throw derr('the given key is not after the current cursor position', 'DataError');\n"
"  }\n"
"  cur._gotValue = false; cur._req.readyState = 'pending';\n"
"  scheduleSettle(cur._req, cur._req.transaction, function () { return advanceCursorTo(cur, key, undefined, 1); });\n"
"}, 'continue', 0);\n"
"CursorProto.continuePrimaryKey = named(function (key, primaryKey) {\n"
"  var cur = this;\n"
"  if (!cur._index) throw derr('continuePrimaryKey requires an index cursor', 'InvalidAccessError');\n"
"  if (cur.direction !== 'next' && cur.direction !== 'prev') throw derr('continuePrimaryKey requires a next or prev cursor', 'InvalidAccessError');\n"
"  checkCursorGotValueOrActive(cur);\n"
"  key = normalizeKeyOrThrow(key); primaryKey = normalizeKeyOrThrow(primaryKey);\n"
"  cur._gotValue = false; cur._req.readyState = 'pending';\n"
"  scheduleSettle(cur._req, cur._req.transaction, function () { return advanceCursorTo(cur, key, primaryKey, 1); });\n"
"}, 'continuePrimaryKey', 2);\n"
"CursorProto.update = named(function (value) {\n"
"  var cur = this, txn = cur._req.transaction;\n"
"  checkWritable(txn);\n"
"  if (!cur._gotValue || cur._keyOnly) throw derr('the cursor has no current value to update', 'InvalidStateError');\n"
"  if (G.Blob && value instanceof G.Blob) throw derr('a Blob or File cannot be stored by this implementation', 'DataCloneError');\n"
"  var rec = cur._store, kp = rec.keyPath;\n"
"  if (kp !== null && kp !== undefined) {\n"
"    var kv = evalKeyPath(value, kp);\n"
"    if (kv === undefined || compareKeys(kv, cur.primaryKey) !== 0)\n"
"      throw derr('the updated value key path does not match the current key', 'DataError');\n"
"  }\n"
"  var cloned = G.structuredClone(value), pk = cur.primaryKey;\n"
"  var req = makeRequest(cur, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var existing = storeFindEntry(rec, pk);\n"
"    checkUniqueIndexes(rec, cloned, pk);\n"
"    txn._undo.push(existing ? { store: rec, key: pk, had: true, prev: existing.value } : { store: rec, key: pk, had: false });\n"
"    storePutRaw(rec, pk, cloned);\n"
"    return pk;\n"
"  });\n"
"}, 'update', 1);\n"
"CursorProto.delete = named(function () {\n"
"  var cur = this, txn = cur._req.transaction;\n"
"  checkWritable(txn);\n"
"  if (!cur._gotValue || cur._keyOnly) throw derr('the cursor has no current value to delete', 'InvalidStateError');\n"
"  var rec = cur._store, pk = cur.primaryKey;\n"
"  var req = makeRequest(cur, txn);\n"
"  return scheduleSettle(req, txn, function () {\n"
"    var existing = storeFindEntry(rec, pk);\n"
"    if (existing) { txn._undo.push({ store: rec, key: pk, had: true, prev: existing.value }); storeDeleteRaw(rec, pk); }\n"
"    return undefined;\n"
"  });\n"
"}, 'delete', 0);\n"
"\n"
/* ==== IDBDatabase ============================================================= */
"var DBProto = Object.create(G.EventTarget.prototype);\n"
"function mkStringList(arr) {\n"
"  var a = arr.slice();\n"
"  a.contains = function (x) { return a.indexOf(String(x)) >= 0; };\n"
"  a.item = function (i) { return (i >= 0 && i < a.length) ? a[i] : null; };\n"
"  return a;\n"
"}\n"
"function makeDatabaseHandle(rec) {\n"
"  var conn = Object.create(DBProto);\n"
"  conn._dbRecord = rec; conn._closed = false; conn._liveTxns = []; conn._versionchangeTxn = null;\n"
"  Object.defineProperty(conn, 'name', { enumerable: true, configurable: true, get: function () { return rec.name; } });\n"
"  Object.defineProperty(conn, 'version', { enumerable: true, configurable: true, get: function () { return rec.version; } });\n"
"  Object.defineProperty(conn, 'objectStoreNames', {\n"
"    enumerable: true, configurable: true,\n"
"    get: function () { return mkStringList(Array.from(rec.stores.keys()).sort()); }\n"
"  });\n"
"  return conn;\n"
"}\n"
"function currentVersionChangeTxn(conn) { return (conn._versionchangeTxn && !conn._versionchangeTxn._finished) ? conn._versionchangeTxn : null; }\n"
"DBProto.createObjectStore = named(function (name, options) {\n"
"  var conn = this, txn = currentVersionChangeTxn(conn);\n"
"  if (!txn) throw derr('createObjectStore is only valid during a versionchange transaction', 'InvalidStateError');\n"
"  name = String(name);\n"
"  var rec = conn._dbRecord;\n"
"  if (rec.stores.has(name)) throw derr('an object store of that name already exists', 'ConstraintError');\n"
"  var kp = (options && options.keyPath !== undefined) ? options.keyPath : null;\n"
"  if (Array.isArray(kp)) kp = kp.slice(); else if (kp !== null) kp = String(kp);\n"
"  var ai = !!(options && options.autoIncrement);\n"
"  if (ai && Array.isArray(kp)) throw derr('autoIncrement is not allowed with an array key path', 'InvalidAccessError');\n"
"  rec.stores.set(name, { name: name, keyPath: kp, autoIncrement: ai, nextKey: 1, records: [], indexes: new Map() });\n"
"  return makeStoreHandle(txn, name);\n"
"}, 'createObjectStore', 1);\n"
"DBProto.deleteObjectStore = named(function (name) {\n"
"  var conn = this, txn = currentVersionChangeTxn(conn);\n"
"  if (!txn) throw derr('deleteObjectStore is only valid during a versionchange transaction', 'InvalidStateError');\n"
"  name = String(name);\n"
"  if (!conn._dbRecord.stores.has(name)) throw derr('no object store of that name', 'NotFoundError');\n"
"  conn._dbRecord.stores.delete(name);\n"
"  txn._stores.delete(name);\n"
"}, 'deleteObjectStore', 1);\n"
"DBProto.transaction = named(function (storeNames, mode) {\n"
"  var conn = this;\n"
"  if (conn._closed) throw derr('the connection is closed', 'InvalidStateError');\n"
"  if (currentVersionChangeTxn(conn)) throw derr('a versionchange transaction is in progress', 'InvalidStateError');\n"
"  mode = mode === undefined ? 'readonly' : String(mode);\n"
"  if (mode !== 'readonly' && mode !== 'readwrite') throw new TypeError('mode must be readonly or readwrite, got ' + mode);\n"
"  var names = Array.isArray(storeNames) ? storeNames.map(String) : [String(storeNames)];\n"
"  if (!names.length) throw derr('no object store names were given', 'InvalidAccessError');\n"
"  var seen = {};\n"
"  names.forEach(function (n) {\n"
"    if (!conn._dbRecord.stores.has(n)) throw derr('no object store of that name', 'NotFoundError');\n"
"    seen[n] = 1;\n"
"  });\n"
"  return makeTransaction(conn, Object.keys(seen).sort(), mode);\n"
"}, 'transaction', 1);\n"
"DBProto.close = named(function () {\n"
"  var conn = this;\n"
"  if (conn._closed) return;\n"
"  conn._closed = true;\n"
"  removeOpenConn(conn._dbRecord, conn);\n"
"  dispatchAt(conn, mkEvent('close', false));\n"
"  checkWaitersForDb(conn._dbRecord);\n"
"}, 'close', 0);\n"
"defHandler(DBProto, 'versionchange', 'onversionchange');\n"
"defHandler(DBProto, 'close', 'onclose');\n"
"defHandler(DBProto, 'abort', 'onabort');\n"
"defHandler(DBProto, 'error', 'onerror');\n"
"\n"
/* ==== IDBFactory: open / deleteDatabase / cmp / databases ======================
 * Every branch below ends in exactly one of: a synchronous throw (a
 * programmer error -- bad version number, missing argument), or a call that
 * reaches finishOpenSuccess / finishOpenError / beginUpgrade -- and
 * beginUpgrade itself always reaches its own txn._finishHook via
 * finishTransaction, which always fires on this request. There is no branch
 * that returns without one of those. */
"var IDBFactoryProto = {};\n"
"function finishOpenSuccess(req, conn) {\n"
"  req.result = conn; req.readyState = 'done';\n"
"  dispatchAt(req, mkEvent('success', false));\n"
"}\n"
"function finishOpenError(req, err) {\n"
"  req.result = undefined; req.error = err; req.readyState = 'done';\n"
"  dispatchAt(req, mkEvent('error', true));\n"
"}\n"
"function beginUpgrade(req, rec, targetVersion) {\n"
"  var oldVersion = rec.version;\n"
"  var conn = makeDatabaseHandle(rec);\n"
"  var txn = makeTransaction(conn, Array.from(rec.stores.keys()).sort(), 'versionchange');\n"
"  conn._versionchangeTxn = txn;\n"
"  rec.version = targetVersion;\n"
"  req.result = conn; req.transaction = txn; req.readyState = 'done';\n"
"  txn._finishHook = function (ok, err) {\n"
"    conn._versionchangeTxn = null;\n"
"    if (ok) {\n"
"      addOpenConn(rec, conn);\n"
"      req.transaction = null;\n"
"      dispatchAt(req, mkEvent('success', false));\n"
"    } else {\n"
"      rec.version = oldVersion;\n"
"      req.result = undefined; req.error = err; req.transaction = null;\n"
"      dispatchAt(req, mkEvent('error', true));\n"
"    }\n"
"    checkWaitersForDb(rec);\n"
"  };\n"
"  dispatchAt(req, mkVCE('upgradeneeded', oldVersion, targetVersion));\n"
"}\n"
"function notifyBlockersAndWait(rec, targetVersion, onReady, onBlocked) {\n"
"  var blockers = liveConns(rec);\n"
"  if (!blockers.length) { onReady(); return; }\n"
"  blockers.forEach(function (c) {\n"
"    if (!c._versionchangeNotified) { c._versionchangeNotified = true; dispatchAt(c, mkVCE('versionchange', rec.version, targetVersion)); }\n"
"  });\n"
"  G.setTimeout(function () {\n"
"    if (liveConns(rec).length > 0) onBlocked(); else onReady();\n"
"  }, 0);\n"
"}\n"
"function openStep(req, name, reqVersion) {\n"
"  var rec = DBS.get(name);\n"
"  if (!rec) { rec = { name: name, version: 0, stores: new Map(), openConns: [], waiters: [] }; DBS.set(name, rec); }\n"
"  var targetVersion = reqVersion === undefined ? (rec.version || 1) : reqVersion;\n"
"  if (rec.version > 0 && targetVersion < rec.version) {\n"
"    finishOpenError(req, derr('the requested version is less than the existing database version', 'VersionError'));\n"
"    return;\n"
"  }\n"
"  if (targetVersion === rec.version) {\n"
"    var conn0 = makeDatabaseHandle(rec);\n"
"    addOpenConn(rec, conn0);\n"
"    finishOpenSuccess(req, conn0);\n"
"    return;\n"
"  }\n"
"  notifyBlockersAndWait(rec, targetVersion,\n"
"    function () { beginUpgrade(req, rec, targetVersion); },\n"
"    function () { dispatchAt(req, mkVCE('blocked', rec.version, targetVersion)); rec.waiters.push({ kind: 'open', req: req, targetVersion: targetVersion }); });\n"
"}\n"
"function performDelete(req, rec) {\n"
"  DBS.delete(rec.name);\n"
"  req.result = undefined; req.readyState = 'done';\n"
"  dispatchAt(req, mkEvent('success', false));\n"
"}\n"
"IDBFactoryProto.open = named(function (name, version) {\n"
"  if (arguments.length < 1) throw new TypeError('open requires at least 1 argument');\n"
"  name = String(name);\n"
"  var reqVersion;\n"
"  if (version !== undefined) {\n"
"    reqVersion = Math.floor(Number(version));\n"
"    if (!isFinite(reqVersion) || reqVersion < 1) throw new TypeError('the version provided must not be less than 1');\n"
"  }\n"
"  var req = makeOpenRequest();\n"
"  G.setTimeout(function () { openStep(req, name, reqVersion); }, 0);\n"
"  return req;\n"
"}, 'open', 1);\n"
"IDBFactoryProto.deleteDatabase = named(function (name) {\n"
"  if (arguments.length < 1) throw new TypeError('deleteDatabase requires 1 argument');\n"
"  name = String(name);\n"
"  var req = makeOpenRequest();\n"
"  G.setTimeout(function () {\n"
"    var rec = DBS.get(name);\n"
"    if (!rec) { req.result = undefined; req.readyState = 'done'; dispatchAt(req, mkEvent('success', false)); return; }\n"
"    notifyBlockersAndWait(rec, null,\n"
"      function () { performDelete(req, rec); },\n"
"      function () { dispatchAt(req, mkVCE('blocked', rec.version, null)); rec.waiters.push({ kind: 'delete', req: req }); });\n"
"  }, 0);\n"
"  return req;\n"
"}, 'deleteDatabase', 1);\n"
"IDBFactoryProto.cmp = named(function (a, b) {\n"
"  if (arguments.length < 2) throw new TypeError('cmp requires 2 arguments');\n"
"  return compareKeys(normalizeKeyOrThrow(a), normalizeKeyOrThrow(b));\n"
"}, 'cmp', 2);\n"
"IDBFactoryProto.databases = named(function () {\n"
"  return Promise.resolve().then(function () {\n"
"    var out = [];\n"
"    DBS.forEach(function (rec, n) { out.push({ name: n, version: rec.version }); });\n"
"    return out;\n"
"  });\n"
"}, 'databases', 0);\n"
"\n"
/* ==== wire up the global constructors and the one instance ==================== */
"function illegal(name) { return named(function () { throw new TypeError('illegal constructor: ' + name); }, name, 0); }\n"
"function installIface(name, proto) {\n"
"  var C = illegal(name);\n"
"  C.prototype = proto; proto.constructor = C;\n"
"  Object.defineProperty(G, name, { value: C, writable: true, configurable: true });\n"
"  return C;\n"
"}\n"
"installIface('IDBRequest', ReqProto);\n"
"installIface('IDBOpenDBRequest', OpenReqProto);\n"
"installIface('IDBTransaction', TxnProto);\n"
"installIface('IDBDatabase', DBProto);\n"
"installIface('IDBObjectStore', OSProto);\n"
"installIface('IDBIndex', IdxProto);\n"
"installIface('IDBCursor', CursorProto);\n"
"installIface('IDBCursorWithValue', CursorWithValueProto);\n"
"Object.defineProperty(G, 'IDBKeyRange', { value: KRCtor, writable: true, configurable: true });\n"
"Object.defineProperty(G, 'IDBVersionChangeEvent', { value: IVCE, writable: true, configurable: true });\n"
"var factory = Object.create(IDBFactoryProto);\n"
"named(IDBFactoryProto.constructor = illegal('IDBFactory'), 'IDBFactory', 0);\n"
"IDBFactoryProto.constructor.prototype = IDBFactoryProto;\n"
"Object.defineProperty(G, 'IDBFactory', { value: IDBFactoryProto.constructor, writable: true, configurable: true });\n"
"Object.defineProperty(G, 'indexedDB', { value: factory, writable: true, configurable: true, enumerable: true });\n"
"})(typeof globalThis !== 'undefined' ? globalThis : this);\n";

#ifdef JS_IDB_NEGCTL
/* THE CONTROL FOR THE TERMINATION BAR ITSELF, not for any one method. It
 * replaces IDBObjectStore.prototype.get with exactly the shape
 * js_platform.h's old comment warned about: a REAL IDBRequest -- same
 * prototype, `instanceof IDBRequest` is true, readyState starts 'pending' --
 * that is simply never handed a settle-task. Nothing else in this file
 * changes. tests/idb.mk's test-idb-negctl build links this in and the host
 * gate's own quiescence check (every request must reach readyState==='done'
 * within a bounded pump) must go RED on exactly the one request this breaks
 * and pass on everything else -- see tests/unit/webapi_idb_test.c. */
static const char *IDB_NEGCTL_JS =
"(function (G) {\n"
"  if (!G.IDBObjectStore || !G.IDBRequest) return;\n"
"  G.IDBObjectStore.prototype.get = function (query) {\n"
"    if (arguments.length < 1) throw new TypeError('get requires 1 argument');\n"
"    var req = Object.create(G.IDBRequest.prototype);\n"
"    req.readyState = 'pending'; req.result = undefined; req.error = null;\n"
"    req.source = this; req.transaction = this.transaction;\n"
/*  Deliberately no G.setTimeout call here -- this is the bug, not a fixture
 *  bug. Everything else in this file still schedules-before-running. */
"    return req;\n"
"  };\n"
"})(typeof globalThis !== 'undefined' ? globalThis : this);\n";
#endif

void js_idb_install(JSContext *ctx)
{
    if (!ctx) return;
    JSValue r = JS_Eval(ctx, IDB_JS, strlen(IDB_JS), "<js_idb>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(r)) {
        /* Loud, not silent -- the same rule js_events.c states: a prelude
         * that fails to install must not leave the page thinking it has no
         * indexedDB for an innocent reason. */
        JSValue e = JS_GetException(ctx);
        const char *s = JS_ToCString(ctx, e);
        fprintf(stderr, "js_idb: install failed: %s\n", s ? s : "(unprintable)");
        if (s) JS_FreeCString(ctx, s);
        JSValue st = JS_GetPropertyStr(ctx, e, "stack");
        if (!JS_IsUndefined(st)) {
            const char *ss = JS_ToCString(ctx, st);
            if (ss) { fprintf(stderr, "%s\n", ss); JS_FreeCString(ctx, ss); }
        }
        JS_FreeValue(ctx, st);
        JS_FreeValue(ctx, e);
    }
    JS_FreeValue(ctx, r);

#ifdef JS_IDB_NEGCTL
    {
        /* LOUD on failure to install, for the reason js_events.c gives for
         * the identical pattern: a control whose stub does not install is
         * byte-for-byte the real build, and it would then report the suite
         * it controls as meaningless-but-green -- the one verdict that is
         * not true. Abort rather than report a fiction. */
        JSValue n = JS_Eval(ctx, IDB_NEGCTL_JS, strlen(IDB_NEGCTL_JS),
                            "<js_idb_negctl>", JS_EVAL_TYPE_GLOBAL);
        if (JS_IsException(n)) {
            JSValue e = JS_GetException(ctx);
            const char *m = JS_ToCString(ctx, e);
            fprintf(stderr, "js_idb NEGCTL: stub did not install: %s\n", m ? m : "(unprintable)");
            fprintf(stderr, "js_idb NEGCTL: this build is identical to the real one -- its verdict is meaningless\n");
            if (m) JS_FreeCString(ctx, m);
            JS_FreeValue(ctx, e);
            exit(2);
        }
        JS_FreeValue(ctx, n);
    }
#endif
}
