#!/usr/bin/env python3
"""qmp_webaccel.py -- the open-time timeline, taken in the guest, one boot.

    python3 tests/qmp/qmp_webaccel.py --iso build-webaccel/logit.iso \
        --disk build-webaccel/disk.img --out /tmp/wa.json [--json-only]

WHY ANOTHER DRIVER (qmp_replay.py already boots a page)
=======================================================
qmp_replay REFUSES subresources -- every non-document path 404s -- because it
is a crash-diagnosis harness and its docstring argues (correctly, for its
purpose) that a fabricated 200 lets a missing subresource read as present.
A cache/perf gate needs the opposite: REAL subresource bytes, a known count,
known sizes. This driver serves the deterministic fixtures from
tests/fixtures/webaccel/ (regenerated by gen.py, seeded, byte-stable) from a
host-local HTTP server through slirp's 10.0.2.2. Nothing is faked -- the CSS,
JS and PNG bytes are real files the browser really parses, executes and
decodes; only their author is a generator instead of a site.

WHY THE NUMBERS ARE TRUSTWORTHY (the tools/perf contract, applied)
==================================================================
1. EVERY TIMESTAMP IS THE GUEST'S. The browser prints "[wa] t=<ms>" stamps
   (browser_rt.c, monotonic_ms) for the network phases; the page itself
   prints "WA-T0"/"WA-END" via performance.now() through console.log;
   engine-side lines are bracketed by the WM's "[wm] perf t=<ms>" (1 s
   resolution -- reported as such, never as exact).
2. BOTH NAVIGATIONS HAPPEN IN ONE BOOT, back to back. Five sibling agents
   load this host with QEMU, so cross-boot (and any host) wall clock is
   noise; first vs second visit is only comparable inside a single guest.
3. THE GATE IS A RATIO, NOT AN ABSOLUTE NUMBER. second_ms must beat
   first_ms by a factor the cache makes true (default 2x). An absolute
   ratchet would ratchet on host contention.
4. THE COUNT CROSS-CHECK. The gate also requires visit 2's dial count to be
   strictly below visit 1's -- a fast second visit that still dialled
   everything would be a timing fluke wearing the cache's clothes.

WHAT IT PRINTS: a phase table per visit (nav->docdone, docdone->css, css->
paint, paint->scripts fetched, scripts fetched->end), the "load done"
counter lines verbatim, and the first/second ratio.

Exit code 0 only if the gate's assertions hold (see GATE at the bottom);
--json-only skips the assertion (for baseline runs that must NOT gate).
"""
import argparse
import http.server
import json
import os
import re
import subprocess
import sys
import tempfile
import threading
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qmp_ui import Session       # noqa: E402

FIXDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "fixtures", "webaccel")
PARK = (40, 780)
BOOT_BUDGET = float(os.environ.get("WA_BOOT", 300))
LOAD_BUDGET = float(os.environ.get("WA_LOAD", 120))
SETTLE = float(os.environ.get("WA_SETTLE", 6))

# The ratchet: visit 2's end-to-end must be at most this fraction of visit 1's.
# 0.8, and the number is MEASURED, not chosen: with the cache on, this fixture
# lands at ~0.71 (visit 1 ~5.7 s, visit 2 ~4.1 s, same boot) because the local
# origin makes the network cheap and the engine (parse+layout+JS, no JIT)
# carries the rest; the bound sits one honest margin above the measurement and
# one below the no-cache control (~0.85+). 0.5 was the first guess and it was
# WRONG -- it assumed the network dominated, which is true on a real https
# origin and false on a loopback one.
RATIO_MAX = float(os.environ.get("WA_RATIO_MAX", "0.8"))

QEMU = os.environ.get("QEMU", "qemu-system-x86_64")


class Serve(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"      # keep-alive: the pool is under test

    def _send(self, body, ctype, code=200, extra=()):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        for k, v in extra:
            self.send_header(k, v)
        self.end_headers()
        try:
            if code != 304:
                self.wfile.write(body)
        except OSError:
            pass

    def do_GET(self):
        # Route on PATH ONLY (a query is location.search, not another file).
        path = self.path.split("?", 1)[0].lstrip("/")
        if not path or path.endswith("/"):
            path += "heavy.html"
        full = os.path.normpath(os.path.join(FIXDIR, path))
        # Path escape refusal: the fixture dir is the whole server.
        if not full.startswith(os.path.abspath(FIXDIR)) or not os.path.isfile(full):
            self._send(b"not here", "text/plain", 404)
            return
        ctype = "text/html; charset=utf-8" if full.endswith(".html") else (
            "text/css" if full.endswith(".css") else (
                "application/javascript" if full.endswith(".js") else "image/png"))
        with open(full, "rb") as fh:
            body = fh.read()
        # ---- the revalidation corner --------------------------------------
        # rv-* paths carry max-age=1 and a strong ETag, and an If-None-Match
        # that matches is answered 304. This is the only place the fixture
        # server sends cache directives at all: every other path is
        # deliberately headerless, which is what exercises the DOCUMENTED
        # heuristic (60 s) rather than an explicit policy.
        if path.startswith("rv-"):
            tag = '"rv-%d"' % len(body)
            inm = self.headers.get("If-None-Match")
            if inm and tag in inm:
                self._send(b"", ctype, 304,
                           extra=(("Cache-Control", "max-age=1"), ("ETag", tag)))
                return
            self._send(body, ctype, 200,
                       extra=(("Cache-Control", "max-age=1"), ("ETag", tag)))
            return
        self._send(body, ctype)

    def log_message(self, *_a):
        pass


# ---- serial-line parsing ------------------------------------------------------

# [wa] t=123456 (+12) nav            <- browser_rt.c's stamps (exact ms)
WA_RE = re.compile(r"\[wa\] t=(\d+) \(\+\d+\) (nav|docdone(?: status=\d+ len=\d+)?)")
WA_IDLE_RE = re.compile(r"\[wa\] t=(\d+) \(\+\d+\) idle reqs=(\d+) dials=(\d+) reuses=(\d+)")
WA_LOADEND_RE = re.compile(r"\[wa\] t=(\d+) loadend reqs=(\d+) dials=(\d+) reuses=(\d+) "
                           r"cache ents=(\d+) (\d+)K hits=(\d+) rvs=(\d+)")
# WA-T0 123456.7 / WA-END 234567.8   <- the page's own performance.now() stamps
T0_RE = re.compile(r"WA-T0 (\d+(?:\.\d+)?)")
END_RE = re.compile(r"WA-END (\d+(?:\.\d+)?)")
# [wm] perf t=123456 ...             <- the WM's 1 s-resolution guest clock
WM_RE = re.compile(r"\[wm\] perf t=(\d+)")
LOADDONE_RE = re.compile(r"\[browser\] load done: (\d+) requests, (\d+) connections "
                         r"dialled, (\d+) reused")
CSSDONE_RE = re.compile(r"css:.*sheets|css report|\[css\]", re.I)


def parse_visit(text):
    """One navigation's events, from its '[browser] load:' line to 'load done'."""
    ev = {"t_nav": None, "t_docdone": None, "t_t0": None, "t_end": None,
          "t_loadend": None, "loadend_counts": None,
          "idles": [], "loaddone": None, "wm": []}
    for ln in text.splitlines():
        m = WA_RE.search(ln)
        if m:
            if m.group(2) == "nav":
                ev["t_nav"] = int(m.group(1))
            else:
                ev["t_docdone"] = int(m.group(1))
            continue
        m = WA_IDLE_RE.search(ln)
        if m:
            ev["idles"].append((int(m.group(1)), int(m.group(2)),
                                int(m.group(3)), int(m.group(4))))
            continue
        m = WA_LOADEND_RE.search(ln)
        if m:
            ev["t_loadend"] = int(m.group(1))
            ev["loadend_counts"] = tuple(int(g) for g in m.groups()[1:])
            continue
        m = T0_RE.search(ln)
        if m and ev["t_t0"] is None:
            ev["t_t0"] = float(m.group(1))
            continue
        m = END_RE.search(ln)
        if m and ev["t_end"] is None:
            ev["t_end"] = float(m.group(1))
            continue
        m = WM_RE.search(ln)
        if m:
            ev["wm"].append(int(m.group(1)))
            continue
        m = LOADDONE_RE.search(ln)
        if m:
            ev["loaddone"] = tuple(int(g) for g in m.groups())
    return ev


def phase_table(v):
    """The per-visit phase table.

    Clocks, stated per row: [wa] rows are the guest's boot-relative monotonic
    ms (exact); WA-T0/WA-END rows are the PAGE's performance.now() clock,
    whose epoch is js_page_open (mid-load), so they are reported as their own
    segment (fetch-to-first-script, first-script-to-last-script) and NEVER
    subtracted from a [wa] stamp -- the first baseline run produced a
    NEGATIVE open time from exactly that mix-up.
    """
    rows = []
    prev = None
    for k, label in (("t_nav", "nav (address bar -> fetch armed)"),
                     ("t_docdone", "docdone (document settled)")):
        if v[k] is None:
            continue
        rows.append((label, v[k], (v[k] - prev) if prev is not None else None, "ms"))
        prev = v[k]
    for entry in v["idles"]:
        t = entry[0]
        rows.append(("idle (a subresource batch drained; reqs/dials/reuses "
                     "cumulative: %s)" % (entry[1:],), t, t - prev, "ms"))
        prev = t
    if v["t_t0"] is not None and v["t_end"] is not None:
        rows.append(("WA-T0..WA-END (first script ran -> last script ran; page "
                     "clock, own segment)", None, v["t_end"] - v["t_t0"], "page-ms"))
    if v["t_loadend"] is not None:
        rows.append(("loadend (bfetch_stats, one clock with nav)",
                     v["t_loadend"],
                     (v["t_loadend"] - v["t_nav"]) if v["t_nav"] is not None else None,
                     "ms"))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--iso", default="build-webaccel/logit.iso")
    ap.add_argument("--disk", default="build-webaccel/disk.img")
    ap.add_argument("--page", default="heavy.html")
    ap.add_argument("--control", default=None,
                    help="also measure this control page first (e.g. control.html)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--json-only", action="store_true",
                    help="measure and exit 0 without the gate assertions")
    ap.add_argument("--after", default=None,
                    help="navigate to this page AFTER the two visits and record "
                         "its serial (diagnosis probes; never gated, never "
                         "counted -- it runs after the measurement)")
    ap.add_argument("--expect-off", action="store_true",
                    help="NEGATIVE CONTROL MODE (tests/webaccel.mk builds the "
                         "browser with -DWACACHE_OFF and runs this): the cache "
                         "assertions MUST redden here. A green run in this mode "
                         "means the positive gate does not measure the cache; a "
                         "red run that is NOT the cache assertion (harness "
                         "failure) still fails, because a broken apparatus is "
                         "not evidence either way.")
    ap.add_argument("--rv", action="store_true",
                    help="also run the revalidation corner: rv.html twice with "
                         ">1 s between (its resources are max-age=1), gating "
                         "that visit 2 revalidated (304s, rvs>0) and still "
                         "rendered")
    args = ap.parse_args()

    for p, what in ((args.iso, "iso"), (args.disk, "disk")):
        if not os.path.exists(p) or os.path.getsize(p) == 0:
            print("HARNESS FAIL: the %s (%s) is missing or empty" % (what, p))
            sys.exit(2)

    srv = http.server.ThreadingHTTPServer(("0.0.0.0", 0), Serve)
    port = srv.server_port
    threading.Thread(target=srv.serve_forever, daemon=True).start()

    tmp = tempfile.mkdtemp(prefix="qmp_webaccel_")
    qmp_path = os.path.join(tmp, "qmp.sock")
    serial_path = os.path.join(tmp, "serial.log")

    rec = {"page": args.page, "visits": [], "control": None,
           "serial_log": os.path.join(tmp, "serial.log"),
           "gate": None, "started": time.strftime("%Y-%m-%dT%H:%M:%S")}

    cmd = [QEMU, "-cpu", os.environ.get("QEMU_CPU", "max"), "-cdrom", args.iso,
           "-drive", "file=%s,format=raw,if=none,id=hd0,file.locking=off" % args.disk,
           "-device", "virtio-blk-pci,drive=hd0", "-boot", "d",
           "-snapshot", "-m", "1G", "-smp", "4", "-accel", "tcg,thread=multi",
           "-vga", "none", "-device", "virtio-gpu-pci,xres=1280,yres=800",
           "-display", "none", "-no-reboot",
           "-netdev", "user,id=n0", "-device", "e1000,netdev=n0",
           "-serial", "file:" + serial_path,
           "-qmp", "unix:%s,server,nowait" % qmp_path]
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    def serial():
        try:
            with open(serial_path, "rb") as fh:
                return fh.read().decode("utf-8", "replace")
        except OSError:
            return ""

    def wait_for(needle, secs, frm=0):
        end = time.time() + secs
        while time.time() < end:
            if needle in serial()[frm:]:
                return True
            if proc.poll() is not None:
                return False
            time.sleep(0.4)
        return False

    def finish(code, why):
        rec["why"] = why
        rec["finished"] = time.strftime("%Y-%m-%dT%H:%M:%S")
        rec["serial_tail"] = serial()[-4000:]
        try:
            proc.kill()
        except OSError:
            pass
        srv.shutdown()
        with open(args.out, "w") as fh:
            json.dump(rec, fh, indent=1)
        print(json.dumps({"gate": rec.get("gate"), "why": why}, indent=1))
        sys.exit(code)

    def navigate_and_capture(page, label, settle=SETTLE):
        """Ctrl+L, type, Enter; return the serial slice for ONE load."""
        mark = len(serial())
        ui.key_mods(["ctrl"], "l")
        time.sleep(0.3)
        ui.typ("http://10.0.2.2:%d/%s" % (port, page))
        ui.key("ret")
        if not wait_for("[browser] load: ", 20.0, mark):
            finish(2, "%s: the address bar never took the URL" % label)
        if not wait_for("WA-END ", LOAD_BUDGET, mark):
            finish(2, "%s: the page never stamped WA-END (load did not finish)" % label)
        time.sleep(settle)
        return serial()[mark:]

    try:
        if not wait_for("LOGIT_BOOT_OK", BOOT_BUDGET):
            finish(2, "the kernel never printed LOGIT_BOOT_OK")
        if not wait_for("desktop live", 120):
            finish(2, "the window manager never brought the desktop up")
        time.sleep(3)
        ui = Session(qmp_path, serial=serial_path)
        try:
            ui.launch_app("browser")
        except AssertionError as e:
            finish(2, str(e))
        time.sleep(7)
        ui.goto(*PARK)

        if args.control:
            sl = navigate_and_capture(args.control, "control")
            rec["control"] = parse_visit(sl)

        # ---- visit 1, then visit 2, same boot, back to back ----
        v1 = parse_visit(navigate_and_capture(args.page, "visit 1"))
        v2 = parse_visit(navigate_and_capture(args.page, "visit 2"))
        rec["visits"] = [v1, v2]

        if args.after:
            sl = navigate_and_capture(args.after, "after-probe")
            rec["after"] = parse_visit(sl)
            rec["after_serial"] = sl[-6000:]

        # ---- the revalidation corner (--rv): max-age=1 twice, 1 s apart ----
        if args.rv:
            rv1 = parse_visit(navigate_and_capture("rv.html", "rv visit 1"))
            time.sleep(2.5)                      # past max-age=1: now STALE
            rv2 = parse_visit(navigate_and_capture("rv.html", "rv visit 2"))
            rec["rv"] = [rv1, rv2]

        for name, v in (("visit 1", v1), ("visit 2", v2)):
            print("== %s ==" % name)
            for label, t, d, note in phase_table(v):
                print("  %-58s t=%-10s +%s %s" % (label, t, d, note))
            if v["loaddone"]:
                print("  load done: %d requests, %d dialled, %d reused"
                      % v["loaddone"])
            if v["idles"]:
                print("  idle stamps: %s" % (v["idles"],))

        def span(v):
            if v["t_nav"] is None or v["t_loadend"] is None:
                return None
            return v["t_loadend"] - v["t_nav"]

        s1, s2 = span(v1), span(v2)
        rec["first_ms"], rec["second_ms"] = s1, s2
        if s1 is None or s2 is None:
            finish(2, "a visit is missing its nav or loadend stamp")

        dials1 = v1["loaddone"][1] if v1["loaddone"] else None
        dials2 = v2["loaddone"][1] if v2["loaddone"] else None
        # The cache's own accounting, read from visit 2's loadend line:
        # (reqs, dials, reuses, ents, KBytes, hits, revalidations).
        lc2 = v2["loadend_counts"]
        hits2 = lc2[5] if lc2 else None
        ratio = s2 / s1
        print("first=%d ms second=%d ms ratio=%.3f dials %s->%s hits2=%s"
              % (s1, s2, ratio, dials1, dials2, hits2))

        if args.json_only:
            finish(0, "measured, ungated (--json-only)")

        # ---- THE GATE ----
        # Two assertions, categorical first:
        #   1. visit 2 served from the cache: ZERO dials, and hits == the
        #      request count (every resource the page asked for came from
        #      memory, none touched the network). This is the part the
        #      negative control reddens hard -- WACACHE_OFF gives dials 2 and
        #      hits 0, and no clock is involved.
        #   2. the ratio ratchet, same-boot by construction. 0.8 rather than
        #      the 0.5 a first guess would pick: measured WITH the cache the
        #      ratio is ~0.71 on this fixture, because the network is local
        #      HTTP (fast) and the remaining open time is parse+css+layout+
        #      paint+JS on the ENGINE -- QuickJS has no JIT and layout runs
        #      on an emulated CPU. On a real https origin the dial count is
        #      what dominates (2345: 8 dials, each a TLS handshake) and the
        #      ratio would be far smaller; the bound is set by what the LOCAL
        #      fixture honestly shows, with the margin 0.71 -> 0.8.
        ok_ratio = ratio <= RATIO_MAX
        ok_cache = (dials2 == 0 and hits2 is not None and lc2 is not None
                    and hits2 == lc2[0])
        rec["gate"] = {"ratio": ratio, "ratio_max": RATIO_MAX,
                       "ok_ratio": ok_ratio, "dials1": dials1, "dials2": dials2,
                       "hits2": hits2, "ok_cache": ok_cache}
        if not ok_cache:
            if args.expect_off:
                finish(0, "NEGCTL RED AS EXPECTED: visit 2 dialled %s and "
                          "served %s/%s from cache -- compiled out is "
                          "indistinguishable from absent" % (dials2, hits2,
                                                             lc2[0] if lc2 else "?"))
            finish(1, "GATE RED: visit 2 dialled %s and served %s/%s from "
                      "cache -- the cache did not carry the revisit"
                      % (dials2, hits2, lc2[0] if lc2 else "?"))
        if args.expect_off:
            finish(1, "NEGCTL GREEN -- the positive gate does not measure the "
                      "cache (visit 2 served %s/%s from cache with the cache "
                      "COMPILED OUT)" % (hits2, lc2[0] if lc2 else "?"))
        if not ok_ratio:
            finish(1, "GATE RED: second visit %d ms is not <= %.0f%% of first "
                      "(%d ms)" % (s2, RATIO_MAX * 100, s1))

        # The revalidation corner, when asked for. Assertions:
        #   rv2 has revalidations armed (rvs>0) -- the STALE path ran;
        #   rv2 still dialled (dials>0) -- the conditional really went out
        #     (a "revalidation" that never asked the server is just a stale
        #     serve wearing the name);
        #   rv2 stamped WA-END -- the 304s produced a complete page.
        if args.rv:
            rv1, rv2 = rec["rv"]
            lc_rv2 = rv2["loadend_counts"]
            # loadend_counts = (reqs, dials, reuses, ents, K, hits, rvs)
            ok_rv = (rv2["t_end"] is not None and lc_rv2 is not None
                     and lc_rv2[6] > 0 and lc_rv2[1] > 0)
            rec["gate"]["ok_rv"] = ok_rv
            if not ok_rv:
                finish(1, "GATE RED: the revalidation corner failed -- rv "
                          "visit 2 counts %s (reqs,dials,reuses,ents,K,hits,"
                          "rvs), WA-END %s" % (lc_rv2, rv2["t_end"]))
            print("rv corner: visit 2 rvs=%d dials=%d (conditional 304s "
                  "answered from cache, page complete)"
                  % (lc_rv2[6], lc_rv2[1]))
        finish(0, "GATE GREEN: second visit %.1f%% of first, dials %s->0, "
                  "%d cache hits%s" % (ratio * 100, dials1, hits2,
                                       ", rv corner green" if args.rv else ""))
    finally:
        try:
            proc.kill()
        except OSError:
            pass


if __name__ == "__main__":
    main()
