// Test-only keys generated by Node WebCrypto/OpenSSL. Never user credentials.
globalThis.keyVectors=[
  {
    "alg": {
      "name": "Ed25519"
    },
    "op": {
      "name": "Ed25519"
    },
    "msg": "4c6f6769744f53207265616c206b657920636f6e73756d657220e2809420696e646570656e64656e74204f70656e53534c206f7261636c65",
    "pub": {
      "key_ops": [
        "verify"
      ],
      "ext": true,
      "alg": "Ed25519",
      "crv": "Ed25519",
      "x": "J5cmqaCx_iogHuGEeEXkw0ocWIQOnakyTGt0nEf14xc",
      "kty": "OKP"
    },
    "priv": {
      "key_ops": [
        "sign"
      ],
      "ext": true,
      "alg": "Ed25519",
      "crv": "Ed25519",
      "d": "PxxV5lQXJd0ljRt2F7ZrQfvD59h3CORodD7Oo4XsVrw",
      "x": "J5cmqaCx_iogHuGEeEXkw0ocWIQOnakyTGt0nEf14xc",
      "kty": "OKP"
    },
    "spki": "302a300506032b6570032100279726a9a0b1fe2a201ee1847845e4c34a1c58840e9da9324c6b749c47f5e317",
    "pkcs8": "302e020100300506032b6570042204203f1c55e6541725dd258d1b7617b66b41fbc3e7d87708e468743ecea385ec56bc",
    "signature": "73ab92d58414eaebf2a7fab39338156268f8b21aaae444dfc09d2b1bb71747c6345507c9673fce94a386f3c0962cd8a8d18e351270212c07390d684ead776102"
  },
  {
    "alg": {
      "name": "ECDSA",
      "namedCurve": "P-256"
    },
    "op": {
      "name": "ECDSA",
      "hash": "SHA-256"
    },
    "msg": "4c6f6769744f53207265616c206b657920636f6e73756d657220e2809420696e646570656e64656e74204f70656e53534c206f7261636c65",
    "pub": {
      "key_ops": [
        "verify"
      ],
      "ext": true,
      "kty": "EC",
      "x": "bznITTTWDh9dx_93lr9e0G_vl3BcA4qd7iz-eDGiY4w",
      "y": "mgkOpRnC5OYSjyOFprelrLfC1wbPBVQ1Rj6JjXuPDyc",
      "crv": "P-256"
    },
    "priv": {
      "key_ops": [
        "sign"
      ],
      "ext": true,
      "kty": "EC",
      "x": "bznITTTWDh9dx_93lr9e0G_vl3BcA4qd7iz-eDGiY4w",
      "y": "mgkOpRnC5OYSjyOFprelrLfC1wbPBVQ1Rj6JjXuPDyc",
      "crv": "P-256",
      "d": "zH_q-7gx21lFPK9xKqhtlQXvSr-duMiR-FhWIsf0iyY"
    },
    "spki": "3059301306072a8648ce3d020106082a8648ce3d030107034200046f39c84d34d60e1f5dc7ff7796bf5ed06fef97705c038a9dee2cfe7831a2638c9a090ea519c2e4e6128f2385a6b7a5acb7c2d706cf055435463e898d7b8f0f27",
    "pkcs8": "308187020100301306072a8648ce3d020106082a8648ce3d030107046d306b0201010420cc7feafbb831db59453caf712aa86d9505ef4abf9db8c891f8585622c7f48b26a144034200046f39c84d34d60e1f5dc7ff7796bf5ed06fef97705c038a9dee2cfe7831a2638c9a090ea519c2e4e6128f2385a6b7a5acb7c2d706cf055435463e898d7b8f0f27",
    "signature": "8a7b56729aa2eab91b536721907ae32a0cd35220b24cbc48f6107e8302538d3f36703af12ceb8ca5fc62c92f33c5336be148d87e5c75022a8f71261606bae60e"
  },
  {
    "alg": {
      "name": "ECDSA",
      "namedCurve": "P-384"
    },
    "op": {
      "name": "ECDSA",
      "hash": "SHA-384"
    },
    "msg": "4c6f6769744f53207265616c206b657920636f6e73756d657220e2809420696e646570656e64656e74204f70656e53534c206f7261636c65",
    "pub": {
      "key_ops": [
        "verify"
      ],
      "ext": true,
      "kty": "EC",
      "x": "3QtA_XqtQ-HShsUZQ6MjE1IBZLOLH45BetCLRkFhwkTS4ltJxhwT-Wd2cLXeHrDR",
      "y": "f_NKhjbAV9tFpLEME66hCx99we2ejo9sZZF7L2JiMRJDFPQCIswMQSdZGYc41Yt0",
      "crv": "P-384"
    },
    "priv": {
      "key_ops": [
        "sign"
      ],
      "ext": true,
      "kty": "EC",
      "x": "3QtA_XqtQ-HShsUZQ6MjE1IBZLOLH45BetCLRkFhwkTS4ltJxhwT-Wd2cLXeHrDR",
      "y": "f_NKhjbAV9tFpLEME66hCx99we2ejo9sZZF7L2JiMRJDFPQCIswMQSdZGYc41Yt0",
      "crv": "P-384",
      "d": "d6GZl4tEsNDHPLC8qmmJD7Kp5qp82YWTDXMi6t8RNp-Go8N1XO3nPTp1y_XG3DjV"
    },
    "spki": "3076301006072a8648ce3d020106052b8104002203620004dd0b40fd7aad43e1d286c51943a32313520164b38b1f8e417ad08b464161c244d2e25b49c61c13f9677670b5de1eb0d17ff34a8636c057db45a4b10c13aea10b1f7dc1ed9e8e8f6c65917b2f626231124314f40222cc0c412759198738d58b74",
    "pkcs8": "3081b6020100301006072a8648ce3d020106052b8104002204819e30819b020101043077a199978b44b0d0c73cb0bcaa69890fb2a9e6aa7cd985930d7322eadf11369f86a3c3755cede73d3a75cbf5c6dc38d5a16403620004dd0b40fd7aad43e1d286c51943a32313520164b38b1f8e417ad08b464161c244d2e25b49c61c13f9677670b5de1eb0d17ff34a8636c057db45a4b10c13aea10b1f7dc1ed9e8e8f6c65917b2f626231124314f40222cc0c412759198738d58b74",
    "signature": "02fc4be9a5445b2eacc6c1471ecac5ef265d287e22d7bb43e120b3cc306edd758285cfe1b15a0ee3132a5db46118445bd825f60ba1b37f0bc24f9c028f04472f23b405fe47834e37595930bad1bc6b738874822a986ae1fb8a804cad8d1bd832"
  },
  {
    "alg": {
      "name": "ECDSA",
      "namedCurve": "P-521"
    },
    "op": {
      "name": "ECDSA",
      "hash": "SHA-512"
    },
    "msg": "4c6f6769744f53207265616c206b657920636f6e73756d657220e2809420696e646570656e64656e74204f70656e53534c206f7261636c65",
    "pub": {
      "key_ops": [
        "verify"
      ],
      "ext": true,
      "kty": "EC",
      "x": "AAXGpKysSwgbT0VkztP4Ib5aWEQrs4-hfZPqDltNxUOTGDD_28bHZbw4xQY_LRTWDsej_WapAo_gDlYRTNSyJe_C",
      "y": "AFbXEw9IGADFo-hu3iemDadXcOvff5HJ5xn2P4MrZ0iIS6NP-R7CMZQ64Qccn5DtnrLpHMkgjjVravci98OYLWse",
      "crv": "P-521"
    },
    "priv": {
      "key_ops": [
        "sign"
      ],
      "ext": true,
      "kty": "EC",
      "x": "AAXGpKysSwgbT0VkztP4Ib5aWEQrs4-hfZPqDltNxUOTGDD_28bHZbw4xQY_LRTWDsej_WapAo_gDlYRTNSyJe_C",
      "y": "AFbXEw9IGADFo-hu3iemDadXcOvff5HJ5xn2P4MrZ0iIS6NP-R7CMZQ64Qccn5DtnrLpHMkgjjVravci98OYLWse",
      "crv": "P-521",
      "d": "AJO1vF23oWBVzTqBJ-vsVsIQs6-gjfthH3nicbDvnJbS2831dUQpWjhzNPb-DRR0f9_mMiIXkCVmLTh0cqXwF1zV"
    },
    "spki": "30819b301006072a8648ce3d020106052b8104002303818600040005c6a4acac4b081b4f4564ced3f821be5a58442bb38fa17d93ea0e5b4dc543931830ffdbc6c765bc38c5063f2d14d60ec7a3fd66a9028fe00e56114cd4b225efc20056d7130f481800c5a3e86ede27a60da75770ebdf7f91c9e719f63f832b6748884ba34ff91ec231943ae1071c9f90ed9eb2e91cc9208e356b6af722f7c3982d6b1e",
    "pkcs8": "3081ee020100301006072a8648ce3d020106052b810400230481d63081d302010104420093b5bc5db7a16055cd3a8127ebec56c210b3afa08dfb611f79e271b0ef9c96d2dbcdf57544295a387334f6fe0d14747fdfe63222179025662d387472a5f0175cd5a1818903818600040005c6a4acac4b081b4f4564ced3f821be5a58442bb38fa17d93ea0e5b4dc543931830ffdbc6c765bc38c5063f2d14d60ec7a3fd66a9028fe00e56114cd4b225efc20056d7130f481800c5a3e86ede27a60da75770ebdf7f91c9e719f63f832b6748884ba34ff91ec231943ae1071c9f90ed9eb2e91cc9208e356b6af722f7c3982d6b1e",
    "signature": "018d41d7a1b68aa8c79724fe8d170e78a4ec701f64941eb773e71d9531bcce58be39eb74326b6fcbf44410e1bcd172f24901abbcc542f6137248367b73d2e0be51af017d2955dcd758ddcfc3a46223bdff6b27656c6d384ae6f9678e15e37b4d63cfd03d0d610221bab85ac23ef7cb9b1f95c17a3838e52540e7c2ecd31b44baf93ab24a"
  },
  {
    "alg": {
      "name": "X25519"
    },
    "priv": {
      "key_ops": [
        "deriveKey",
        "deriveBits"
      ],
      "ext": true,
      "crv": "X25519",
      "d": "8JxuAw3TnS4aI0aHOph4L0101Ncb72Wig9zfb_QJ-Vo",
      "x": "V8BSzldQjMjwmPvLtQRmzIvUBeaheh2o8MG83e4b8mo",
      "kty": "OKP"
    },
    "pub": {
      "key_ops": [],
      "ext": true,
      "crv": "X25519",
      "x": "uIE89nz8-3EI8TVDKSf3FbO_Zw5H9nJsFjPHaF6vyzs",
      "kty": "OKP"
    },
    "shared": "3426d72c3ba9fce32fdbe1056ef8d521c6ce7c06dac92f15117d9bf1539ae836"
  },
  {
    "alg": {
      "name": "ECDH",
      "namedCurve": "P-256"
    },
    "priv": {
      "key_ops": [
        "deriveKey",
        "deriveBits"
      ],
      "ext": true,
      "kty": "EC",
      "x": "PCNEKPnYqSLLDYrFWq2mB4PR0VNerDAKaKIt-POILXY",
      "y": "EZC-dkD_HnaeIEglKy11ZnZzD-IhzCalimeEpoRJ6zY",
      "crv": "P-256",
      "d": "r6CNmv8NyilvKwSJt2pHF7aPMg3sVz7Ds5adRLNAlM4"
    },
    "pub": {
      "key_ops": [],
      "ext": true,
      "kty": "EC",
      "x": "09TVH9NG0bUY1SIKeeqnRbRYkAlxFcilyaz1m7LZKlY",
      "y": "5mJj_bSfhW0t830qfbRJwrVdtf2REJhOlLCYIlyJggE",
      "crv": "P-256"
    },
    "shared": "236dcb3be1da329ae910c24784196024d36d97a8002f214e5f3252b044c948c0"
  },
  {
    "alg": {
      "name": "ECDH",
      "namedCurve": "P-384"
    },
    "priv": {
      "key_ops": [
        "deriveKey",
        "deriveBits"
      ],
      "ext": true,
      "kty": "EC",
      "x": "qE8lu5PqIEg345ctbU854A2rbcsaNUHX1Q6qa1Y3-idGzg0-y23_E9E9oU8ZV6aW",
      "y": "ov-GnMGzRACnbCA_v5reFXt2kUklqK68Rf7tMLwE2pd51EgtE6Xc0KnS_qO042Ni",
      "crv": "P-384",
      "d": "qLyyPwhr5Ojp7NnF0lXdcXVOUv_Wl6cgP6lH4IDicYfGNgZv1OSM6FV1XwOdEO1t"
    },
    "pub": {
      "key_ops": [],
      "ext": true,
      "kty": "EC",
      "x": "XREEAWGLQVvA-OAOIEDwmmNSXFlKC-ffGPR7u6B49uQH1GMWQZATJeH3Qakbtael",
      "y": "fVKkVjOGlWAApgZvlZ_OldFxDzYlxx2M0o2IeJZV7nGw2MaTy9NQyfXakE_xkSs_",
      "crv": "P-384"
    },
    "shared": "fac5dabfe6a683fa56e4db050ec11336ba0ec7246b4f3ed27213758bc99f081dacdb8b2b112dbabd16a21479604b3f8f"
  },
  {
    "alg": {
      "name": "ECDH",
      "namedCurve": "P-521"
    },
    "priv": {
      "key_ops": [
        "deriveKey",
        "deriveBits"
      ],
      "ext": true,
      "kty": "EC",
      "x": "AHRWAQfjmt8aH6OCi33pUu7RHcwp4siQw9StRo-pKPK0KsQ3Ln6YPxY4mYOcIMD5tf5O62qBojmY_KJ88pp45bUT",
      "y": "ACyLnxzrbWX-WjSa6dO3U2X9BX2s0ewbIbOyVm7VjGM_PK2T1bQjWe7Qr3awanF2G35BlH6cGzPtH96y4pN9JoN1",
      "crv": "P-521",
      "d": "AV_ulyJYiddxzWHZJwXRLaIQpf0WuV3Rj24Y83nQH92XrKRhUv7QBU_Cfms0XRWQgtNaSrxMpRVhkv70pyLnEpNH"
    },
    "pub": {
      "key_ops": [],
      "ext": true,
      "kty": "EC",
      "x": "AdlFEE9CQtZh_BY3KKXPfaG-zJqDugX7LXzTQv2_8uXgnLN4dvAjJtpcQojhSABu-fWBEUSYhw_6K8YhWtO55d3y",
      "y": "AKNbER5Au6SMJqxSTWs-FXCP4ofU-kbSh8g21PQPfjmG6SlLLrRiqPQ3za6GCNdnGTirMc3crDB1LXNf6iL82cs2",
      "crv": "P-521"
    },
    "shared": "00c26cf39b91d6fa38092ee4de735a00124543cde44e17d6bf8f21d28712a33b400f8dc0b0d72774f52f3fec9e37ef3e31513221d84021e7b38d0b510198eb1be53f"
  }
];
