/* c/lib/video/mjpeg.h -- public API: Motion JPEG, decoded by REUSING
 * c/lib/image/jpeg.c (the existing baseline/progressive JPEG decoder) one
 * frame at a time. This file owns none of the JPEG format itself -- no
 * Huffman decode, no IDCT, no colour conversion, no dequantisation -- it
 * owns exactly the two things that are MOTION-JPEG-specific and not
 * JPEG-specific:
 *
 *   1. FRAMING. An MJPEG elementary stream is a concatenation of complete
 *      JPEG frames (SOI..EOI) with nothing between them. mjpeg_next_frame()
 *      finds where each one starts and ends -- honouring FF00 byte-stuffing
 *      and RSTn restart markers inside the entropy-coded data, the same way
 *      a real marker walk must -- so the caller can hand one whole frame at
 *      a time to mjpeg_decode_frame().
 *
 *   2. THE DEFAULT-TABLES CONVENTION. Many MJPEG encoders -- the AVI "MJPG"
 *      convention among them -- omit the DHT segment on every frame and
 *      rely on the decoder already knowing ITU-T.81 Annex K.3's four
 *      standard ("default") Huffman tables. c/lib/image/jpeg.c REQUIRES a
 *      DHT for every table a scan names (parse_sos:
 *      `if (wants_dc && !hdc[td].defined) return -1`) -- correctly, since a
 *      STILL JPEG with no DHT really is malformed -- so a frame missing DHT
 *      is rejected by jpeg.c exactly as it should be. mjpeg_decode_frame()
 *      detects that case (no DHT marker anywhere in the frame) and hands
 *      img_decode() a COPY of the frame with a synthetic DHT segment
 *      spliced in right after SOI, built from the tables in
 *      mjpeg_deftables.inc (generated by tools/gen_mjpeg_tables.py from two
 *      independent encoders, see that file). jpeg.c itself is never
 *      modified and never knows the tables did not arrive with the frame;
 *      a frame that DOES carry its own DHT is decoded completely
 *      unmodified, zero-copy.
 *
 * WHAT THIS FILE DOES NOT DO, BY NAME:
 *
 *   - AVI two-field interlaced MJPEG (two complete JPEGs packed into one
 *     video CHUNK, one per field) is NOT decoded. mjpeg_is_two_field() names
 *     it so a container-aware caller can detect and refuse it BEFORE ever
 *     calling mjpeg_decode_frame -- see that function's comment for why this
 *     has to be the chunk-aware caller's job and not this file's.
 *   - A stream whose SOF geometry changes mid-stream is not silently
 *     re-accommodated: see mjpeg_decode_frame's MJPEG_ERR_SIZE_CHANGE.
 *   - Anything jpeg.c itself does not do (12-bit precision, arithmetic
 *     coding, CMYK/4-component, extended-sequential SOF1) is rejected the
 *     same way jpeg.c rejects it: gracefully, via img_decode() returning
 *     nonzero, surfaced here as MJPEG_ERR_CORRUPT (jpeg.c has one failure
 *     code, not several, so this file cannot report a finer reason than
 *     "jpeg.c would not decode it").
 *
 * Usage (pull model, one whole MJPEG elementary stream buffer in):
 *   mjpegdec *d = mjpeg_open();
 *   int off = 0;
 *   while (off < len) {
 *       int start;
 *       int flen = mjpeg_next_frame(data + off, len - off, &start);
 *       if (flen == 0) break;            // no complete frame left in the buffer
 *       if (flen < 0) { ... MJPEG_ERR_* ...; break; }
 *       mjpegframe f;
 *       int rc = mjpeg_decode_frame(d, data + off + start, flen, &f);
 *       if (rc == MJPEG_OK) {
 *           // present f.width / f.height / f.rgba (valid until the next
 *           // mjpeg_decode_frame call on `d`, or mjpeg_close(d))
 *       }
 *       off += start + flen;
 *   }
 *   mjpeg_close(d);
 *
 * A container demuxer that hands out ONE CHUNK per call (rather than a whole
 * concatenated stream) calls mjpeg_is_two_field() on that chunk first; see
 * its comment.
 */
#ifndef LOGIT_MJPEG_H
#define LOGIT_MJPEG_H

#define MJPEG_OK               0
#define MJPEG_ERR_CORRUPT     -1   /* jpeg.c would not decode this frame */
#define MJPEG_ERR_OOM          -3
#define MJPEG_ERR_SIZE_CHANGE  -4  /* SOF geometry differs from the first frame */
#define MJPEG_ERR_TWO_FIELD    -5  /* AVI two-field interlaced MJPEG: unsupported */
#define MJPEG_ERR_NO_DHT        -6 /* DHT missing; default tables compiled out
                                     * (MJPEG_NO_DEFAULT_DHT) -- the negative
                                     * control, never set in a real build */

typedef struct mjpegdec mjpegdec;

typedef struct {
    int width, height;
    const unsigned char *rgba;  /* width*height*4, straight RGBA8. Owned by
                                  * `d`: allocated ONCE, at the first
                                  * successfully decoded frame, and reused
                                  * (overwritten in place) by every later
                                  * frame of the same size -- see
                                  * mjpeg_decode_frame. Valid until the next
                                  * call on the same `d`, or mjpeg_close(d). */
} mjpegframe;

mjpegdec *mjpeg_open(void);
void      mjpeg_close(mjpegdec *d);

/* Locate the next complete SOI..EOI frame in data[0..len).
 *
 * Returns:
 *   > 0   the frame's length in bytes (SOI through EOI inclusive);
 *         *frame_start is the byte offset of its SOI (0 unless leading
 *         junk precedes it -- real streams have none, but this does not
 *         assume it).
 *   0     no complete frame remains in the buffer (no SOI at all, or an SOI
 *         with nothing after it yet -- ask again once more bytes arrive).
 *   < 0   MJPEG_ERR_CORRUPT: an SOI was found but the marker structure runs
 *         off the end of the buffer before an EOI (a segment's declared
 *         length reaches past `len`, or the buffer simply ends mid-frame).
 *
 * The walk is marker-structure-aware, not a byte search for 0xFFD9: inside
 * entropy-coded data (after SOS) a literal 0xFF is always followed by a
 * stuffed 0x00 or an RSTn marker by a compliant encoder, and both are
 * skipped correctly here, the same way c/lib/image/jpeg.c's own bit reader
 * and next_marker() skip them -- this is a second, independent piece of
 * code that has to know the same rule, not a copy of jpeg.c's. */
int mjpeg_next_frame(const unsigned char *data, int len, int *frame_start);

/* 1 if data[0..len) -- meant to be exactly ONE demuxer-delivered video
 * CHUNK, not an arbitrary slice of a longer stream -- holds a second
 * complete SOI..EOI frame immediately after the first one ends (allowing up
 * to one 0x00 RIFF alignment pad byte between them, since AVI chunks are
 * word-aligned and that is the only padding the format can insert there).
 * That shape is the OpenDML AVI two-field interlaced MJPEG convention: one
 * chunk carries two whole JPEG-coded FIELDS of one interlaced video frame,
 * with nothing in the byte stream itself naming which is which or that a
 * second one follows -- there is no marker, no length prefix, nothing this
 * file could decode into a meaningful single picture. 0 if the chunk holds
 * one frame (the ordinary case) or the walk cannot even find one complete
 * frame (not this function's problem to report; mjpeg_next_frame already
 * covers that).
 *
 * THIS IS DELIBERATELY NOT FOLDED INTO mjpeg_next_frame/mjpeg_decode_frame.
 * Two SOI..EOI frames back to back is also exactly what an ORDINARY
 * multi-frame elementary stream looks like from a byte-structure point of
 * view -- mjpeg_next_frame's whole job is to peel exactly one off at a time
 * from such a stream, called in a loop, and a stream of N frames is nothing
 * but "two JPEGs, then another, then another" all the way down. The two
 * situations are visually identical in the bytes; what tells them apart is
 * a fact ONLY a container demuxer has -- whether the two JPEGs it is
 * looking at came from one chunk or two -- so only a container-aware caller
 * can call this meaningfully, once, on exactly the bytes of one chunk. A
 * future AVI integration in c/lib/media calls this before
 * mjpeg_decode_frame and treats 1 as MJPEG_ERR_TWO_FIELD; see the top-level
 * report for the exact call site this belongs at. */
int mjpeg_is_two_field(const unsigned char *data, int len);

/* Decode exactly one SOI..EOI frame, as located by mjpeg_next_frame (data/len
 * must be precisely one frame -- passing more or less is MJPEG_ERR_CORRUPT).
 *
 * Reuses c/lib/image/jpeg.c's img_decode() underneath; see the file comment
 * for the DHT splice. `out->rgba` is allocated ONCE on `d`, sized by the
 * FIRST successfully decoded frame's width/height, and REUSED (overwritten
 * in place, never reallocated or grown) for every later frame of that same
 * size -- this is the whole of requirement 2 in the task this file was
 * written against, and it is asserted by pointer identity in
 * tests/unit/mjpeg_test.c, not merely by the numbers still matching.
 *
 * A later frame whose SOF names a DIFFERENT width/height is refused with
 * MJPEG_ERR_SIZE_CHANGE. It is still decoded in full by jpeg.c first (this
 * file has no cheaper way to learn a frame's true geometry than jpeg.c's own
 * SOF parse, and duplicating that parse here -- to reject BEFORE the
 * entropy decode runs -- would be exactly the second decoder this file
 * exists not to be); only the copy into `d`'s persistent buffer is skipped,
 * so `d->rgba`/`out` are left holding the previous frame, untouched. */
int mjpeg_decode_frame(mjpegdec *d, const unsigned char *data, int len,
                       mjpegframe *out);

const char *mjpeg_strerror(int err);

#endif /* LOGIT_MJPEG_H */
