/* GENERATED by tools/gen_mpeg12_tables.py -- DO NOT EDIT.
 * Source: FFmpeg libavcodec mpeg12data.c, mpeg12.c, mpegvideodata.c, mathtables.c (ISO/IEC 13818-2 Annex B tables).
 * Regenerate with `python3 tools/gen_mpeg12_tables.py`;
 * `--check` fails if this file and the generator disagree.
 */

#ifndef LOGIT_MPEG12_TABLES_H
#define LOGIT_MPEG12_TABLES_H

#include <stdint.h>

/* Two-level VLC entry. len == 0: no such code (bitstream is corrupt).
 * sub == 0: leaf -- consume `len` bits, the symbol is `sym`.
 * sub == 1: node -- consume M12_VLC_BITS, then `len` more bits, and
 *           look at entry [sym + those bits] of the same array. */
typedef struct { int16_t sym; uint8_t len; uint8_t sub; } m12_vlc_e;

#define M12_VLC_BITS 9

/* symbols of m12_vlc_coef_*: 0..110 index m12_rl_run/m12_rl_level */
#define M12_COEF_ESCAPE 111
#define M12_COEF_EOB    112

/* symbols of m12_vlc_mbincr: 1..33 = increment, 34 = escape (+33),
 * 35 = macroblock_stuffing (no increment) */
#define M12_MBINCR_ESCAPE  34
#define M12_MBINCR_STUFF   35

/* macroblock_type flags, the symbols of m12_vlc_mb_ptype/btype */
#define M12_MB_INTRA   0x01
#define M12_MB_PATTERN 0x02
#define M12_MB_BACKWARD 0x04
#define M12_MB_FORWARD 0x08
#define M12_MB_QUANT   0x10

extern const uint8_t m12_scan_zigzag[64];
extern const uint8_t m12_scan_alternate[64];
extern const uint8_t m12_default_intra_matrix[64];
extern const uint8_t m12_default_non_intra_matrix[64];
extern const uint8_t m12_non_linear_qscale[32];
extern const m12_vlc_e m12_vlc_dc_lum[512];
extern const m12_vlc_e m12_vlc_dc_chroma[514];
extern const m12_vlc_e m12_vlc_mbincr[538];
extern const m12_vlc_e m12_vlc_cbp[512];
extern const m12_vlc_e m12_vlc_motion[518];
extern const m12_vlc_e m12_vlc_mb_ptype[512];
extern const m12_vlc_e m12_vlc_mb_btype[512];
extern const uint8_t m12_rl_run[111];
extern const uint8_t m12_rl_level[111];
extern const m12_vlc_e m12_vlc_coef_b14[680];
extern const m12_vlc_e m12_vlc_coef_b15[674];

#endif /* LOGIT_MPEG12_TABLES_H */
