/* c/lib/video/mpeg4_tables.h -- GENERATED by tools/genmpeg4_tables.py.
 *
 * DO NOT EDIT.  Regenerate with
 *     python3 tools/genmpeg4_tables.py --src <ffmpeg-src> -o c/lib/video/mpeg4_tables.h
 * and check it with
 *     python3 tools/genmpeg4_tables.py --src <ffmpeg-src> --check
 * which must reproduce this file byte for byte.
 *
 * Source: FFmpeg n7.1, libavcodec/{h263data.c,mpeg4data.h,mathtables.c,
 * mpegvideodata.c} -- the machine-readable copy of ISO/IEC 14496-2 Annex B and
 * ITU-T H.263 Tables 12-16.  Every prefix code below was checked for ambiguity
 * by the generator; every array's shape and CRC-32 are in the comment above it.
 */
#ifndef LOGIT_MPEG4_TABLES_H
#define LOGIT_MPEG4_TABLES_H

#include <stdint.h>

/* A prefix code, decoded one bit at a time with a binary search per length.
 * `off[l]`/`cnt[l]` bracket the entries whose codeword is `l` bits long, and
 * within that range `code[]` is ascending, so the search is exact. */
typedef struct {
    const uint16_t *code;
    const uint16_t *sym;
    const uint16_t *off;
    const uint16_t *cnt;
    int minlen, maxlen;
} m4_vlc;

/* A run-level VLC plus the escape-1/escape-2 helper tables (14496-2 7.4.1.3).
 * `esc` is the symbol number of the ESCAPE codeword; symbols below `last_index`
 * carry last=0 and the rest last=1. */
typedef struct {
    const m4_vlc *vlc;
    const uint8_t *run;
    const uint8_t *level;
    const uint8_t *max_level;   /* [2][65], flattened */
    const uint8_t *max_run;     /* [2][65], flattened */
    int n;                      /* symbol number of ESCAPE == n */
    int last_index;
} m4_rl;

/* m4_vlc_intra_mcbpc_code: 9 entries, crc32 446e6436 */
static const uint16_t m4_vlc_intra_mcbpc_code[9] = {
    0x0001, 0x0001, 0x0002, 0x0003, 0x0001, 0x0001, 0x0002, 0x0003, 0x0001
};

/* m4_vlc_intra_mcbpc_sym: 9 entries, crc32 d4e15634 */
static const uint16_t m4_vlc_intra_mcbpc_sym[9] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8
};

/* m4_vlc_intra_mcbpc_off: 11 entries, crc32 f902d5be */
static const uint16_t m4_vlc_intra_mcbpc_off[11] = {
    0, 0, 1, 1, 4, 5, 5, 8, 8, 8, 9
};

/* m4_vlc_intra_mcbpc_cnt: 11 entries, crc32 87c94cad */
static const uint16_t m4_vlc_intra_mcbpc_cnt[11] = {
    0, 1, 0, 3, 1, 0, 3, 0, 0, 1, 0
};

#define M4_VLC_INTRA_MCBPC_MINLEN 1
#define M4_VLC_INTRA_MCBPC_MAXLEN 9
static const m4_vlc m4_vlc_intra_mcbpc = { m4_vlc_intra_mcbpc_code, m4_vlc_intra_mcbpc_sym, m4_vlc_intra_mcbpc_off, m4_vlc_intra_mcbpc_cnt, 1, 9 };

/* m4_vlc_inter_mcbpc_code: 25 entries, crc32 628bb1e4 */
static const uint16_t m4_vlc_inter_mcbpc_code[25] = {
    0x0001, 0x0002, 0x0003, 0x0002, 0x0003, 0x0003, 0x0004, 0x0005, 0x0003,
    0x0004, 0x0005, 0x0006, 0x0007, 0x0003, 0x0004, 0x0005, 0x0001, 0x0002,
    0x0003, 0x0004, 0x0005, 0x0002, 0x000c, 0x000e, 0x000f
};

/* m4_vlc_inter_mcbpc_sym: 25 entries, crc32 c44a70ea */
static const uint16_t m4_vlc_inter_mcbpc_sym[25] = {
    0, 16, 8, 2, 1, 4, 12, 3, 7, 18, 17, 10, 9, 6, 5, 19, 20, 15, 14, 13, 11,
    24, 25, 26, 27
};

/* m4_vlc_inter_mcbpc_off: 15 entries, crc32 2d72ade4 */
static const uint16_t m4_vlc_inter_mcbpc_off[15] = {
    0, 0, 1, 1, 3, 5, 6, 8, 13, 16, 21, 21, 22, 22, 25
};

/* m4_vlc_inter_mcbpc_cnt: 15 entries, crc32 222a7b22 */
static const uint16_t m4_vlc_inter_mcbpc_cnt[15] = {
    0, 1, 0, 2, 2, 1, 2, 5, 3, 5, 0, 1, 0, 3, 0
};

#define M4_VLC_INTER_MCBPC_MINLEN 1
#define M4_VLC_INTER_MCBPC_MAXLEN 13
static const m4_vlc m4_vlc_inter_mcbpc = { m4_vlc_inter_mcbpc_code, m4_vlc_inter_mcbpc_sym, m4_vlc_inter_mcbpc_off, m4_vlc_inter_mcbpc_cnt, 1, 13 };

/* m4_vlc_cbpy_code: 16 entries, crc32 a29320d1 */
static const uint16_t m4_vlc_cbpy_code[16] = {
    0x0003, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007, 0x0008, 0x0009, 0x000a,
    0x000b, 0x0002, 0x0003, 0x0004, 0x0005, 0x0002, 0x0003
};

/* m4_vlc_cbpy_sym: 16 entries, crc32 308fdc21 */
static const uint16_t m4_vlc_cbpy_sym[16] = {
    15, 0, 12, 10, 14, 5, 13, 3, 11, 7, 8, 4, 2, 1, 6, 9
};

/* m4_vlc_cbpy_off: 8 entries, crc32 7da152b6 */
static const uint16_t m4_vlc_cbpy_off[8] = {
    0, 0, 0, 1, 1, 10, 14, 16
};

/* m4_vlc_cbpy_cnt: 8 entries, crc32 04770256 */
static const uint16_t m4_vlc_cbpy_cnt[8] = {
    0, 0, 1, 0, 9, 4, 2, 0
};

#define M4_VLC_CBPY_MINLEN 2
#define M4_VLC_CBPY_MAXLEN 6
static const m4_vlc m4_vlc_cbpy = { m4_vlc_cbpy_code, m4_vlc_cbpy_sym, m4_vlc_cbpy_off, m4_vlc_cbpy_cnt, 2, 6 };

/* m4_vlc_mvd_code: 33 entries, crc32 f54b06e4 */
static const uint16_t m4_vlc_mvd_code[33] = {
    0x0001, 0x0001, 0x0001, 0x0001, 0x0003, 0x0003, 0x0004, 0x0005, 0x0009,
    0x000a, 0x000b, 0x0004, 0x0005, 0x0006, 0x0007, 0x0008, 0x0009, 0x000a,
    0x000b, 0x000c, 0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0002, 0x0003,
    0x0004, 0x0005, 0x0006, 0x0007, 0x0002, 0x0003
};

/* m4_vlc_mvd_sym: 33 entries, crc32 95b1d1c8 */
static const uint16_t m4_vlc_mvd_sym[33] = {
    0, 1, 2, 3, 4, 7, 6, 5, 10, 9, 8, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
    14, 13, 12, 11, 30, 29, 28, 27, 26, 25, 32, 31
};

/* m4_vlc_mvd_off: 14 entries, crc32 e7843f0d */
static const uint16_t m4_vlc_mvd_off[14] = {
    0, 0, 1, 2, 3, 4, 4, 5, 8, 8, 11, 25, 31, 33
};

/* m4_vlc_mvd_cnt: 14 entries, crc32 d3ee04cc */
static const uint16_t m4_vlc_mvd_cnt[14] = {
    0, 1, 1, 1, 1, 0, 1, 3, 0, 3, 14, 6, 2, 0
};

#define M4_VLC_MVD_MINLEN 1
#define M4_VLC_MVD_MAXLEN 12
static const m4_vlc m4_vlc_mvd = { m4_vlc_mvd_code, m4_vlc_mvd_sym, m4_vlc_mvd_off, m4_vlc_mvd_cnt, 1, 12 };

/* m4_vlc_dc_lum_code: 13 entries, crc32 c7a6bf4e */
static const uint16_t m4_vlc_dc_lum_code[13] = {
    0x0002, 0x0003, 0x0001, 0x0002, 0x0003, 0x0001, 0x0001, 0x0001, 0x0001,
    0x0001, 0x0001, 0x0001, 0x0001
};

/* m4_vlc_dc_lum_sym: 13 entries, crc32 a9c0ff2c */
static const uint16_t m4_vlc_dc_lum_sym[13] = {
    2, 1, 4, 3, 0, 5, 6, 7, 8, 9, 10, 11, 12
};

/* m4_vlc_dc_lum_off: 13 entries, crc32 a3e047eb */
static const uint16_t m4_vlc_dc_lum_off[13] = {
    0, 0, 0, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13
};

/* m4_vlc_dc_lum_cnt: 13 entries, crc32 cafd60df */
static const uint16_t m4_vlc_dc_lum_cnt[13] = {
    0, 0, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0
};

#define M4_VLC_DC_LUM_MINLEN 2
#define M4_VLC_DC_LUM_MAXLEN 11
static const m4_vlc m4_vlc_dc_lum = { m4_vlc_dc_lum_code, m4_vlc_dc_lum_sym, m4_vlc_dc_lum_off, m4_vlc_dc_lum_cnt, 2, 11 };

/* m4_vlc_dc_chrom_code: 13 entries, crc32 cf3e38a2 */
static const uint16_t m4_vlc_dc_chrom_code[13] = {
    0x0001, 0x0002, 0x0003, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
    0x0001, 0x0001, 0x0001, 0x0001
};

/* m4_vlc_dc_chrom_sym: 13 entries, crc32 39304633 */
static const uint16_t m4_vlc_dc_chrom_sym[13] = {
    2, 1, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
};

/* m4_vlc_dc_chrom_off: 14 entries, crc32 9702c4a4 */
static const uint16_t m4_vlc_dc_chrom_off[14] = {
    0, 0, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
};

/* m4_vlc_dc_chrom_cnt: 14 entries, crc32 684c952b */
static const uint16_t m4_vlc_dc_chrom_cnt[14] = {
    0, 0, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0
};

#define M4_VLC_DC_CHROM_MINLEN 2
#define M4_VLC_DC_CHROM_MAXLEN 12
static const m4_vlc m4_vlc_dc_chrom = { m4_vlc_dc_chrom_code, m4_vlc_dc_chrom_sym, m4_vlc_dc_chrom_off, m4_vlc_dc_chrom_cnt, 2, 12 };

/* m4_vlc_mb_type_b_code: 4 entries, crc32 ad60f150 */
static const uint16_t m4_vlc_mb_type_b_code[4] = {
    0x0001, 0x0001, 0x0001, 0x0001
};

/* m4_vlc_mb_type_b_sym: 4 entries, crc32 278eafa9 */
static const uint16_t m4_vlc_mb_type_b_sym[4] = {
    0, 1, 2, 3
};

/* m4_vlc_mb_type_b_off: 6 entries, crc32 e07f559a */
static const uint16_t m4_vlc_mb_type_b_off[6] = {
    0, 0, 1, 2, 3, 4
};

/* m4_vlc_mb_type_b_cnt: 6 entries, crc32 3fc12c06 */
static const uint16_t m4_vlc_mb_type_b_cnt[6] = {
    0, 1, 1, 1, 1, 0
};

#define M4_VLC_MB_TYPE_B_MINLEN 1
#define M4_VLC_MB_TYPE_B_MAXLEN 4
static const m4_vlc m4_vlc_mb_type_b = { m4_vlc_mb_type_b_code, m4_vlc_mb_type_b_sym, m4_vlc_mb_type_b_off, m4_vlc_mb_type_b_cnt, 1, 4 };

/* m4_rl_intra_aic_vlc_code: 103 entries, crc32 327e3255 */
static const uint16_t m4_rl_intra_aic_vlc_code[103] = {
    0x0002, 0x0006, 0x0007, 0x000e, 0x000f, 0x000b, 0x000c, 0x000d, 0x000c,
    0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015,
    0x0003, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017,
    0x0013, 0x0014, 0x0015, 0x0016, 0x0017, 0x0018, 0x0019, 0x001a, 0x001b,
    0x001c, 0x001d, 0x001e, 0x001f, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015,
    0x0016, 0x0017, 0x0018, 0x0019, 0x001a, 0x001b, 0x001c, 0x001d, 0x001e,
    0x001f, 0x0020, 0x0021, 0x0022, 0x0023, 0x0024, 0x0025, 0x0004, 0x0005,
    0x0006, 0x0007, 0x0008, 0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x000e,
    0x000f, 0x0020, 0x0021, 0x0004, 0x0005, 0x0006, 0x0007, 0x0020, 0x0021,
    0x0022, 0x0023, 0x0024, 0x0025, 0x0026, 0x0027, 0x0050, 0x0051, 0x0052,
    0x0053, 0x0054, 0x0055, 0x0056, 0x0057, 0x0058, 0x0059, 0x005a, 0x005b,
    0x005c, 0x005d, 0x005e, 0x005f
};

/* m4_rl_intra_aic_vlc_sym: 103 entries, crc32 e5a1bba4 */
static const uint16_t m4_rl_intra_aic_vlc_sym[103] = {
    0, 1, 58, 2, 25, 32, 3, 4, 59, 75, 72, 68, 5, 6, 7, 40, 26, 36, 102, 60,
    78, 82, 80, 27, 33, 8, 43, 61, 84, 86, 91, 90, 89, 88, 87, 9, 46, 37, 28,
    48, 62, 63, 69, 73, 93, 94, 96, 95, 92, 12, 13, 14, 15, 16, 17, 10, 11,
    44, 41, 52, 50, 64, 70, 76, 79, 56, 35, 51, 49, 47, 38, 34, 29, 55, 54,
    97, 98, 53, 42, 57, 30, 19, 18, 74, 71, 66, 65, 31, 39, 45, 24, 23, 22,
    21, 20, 99, 100, 101, 85, 83, 81, 77, 67
};

/* m4_rl_intra_aic_vlc_off: 14 entries, crc32 18f6616b */
static const uint16_t m4_rl_intra_aic_vlc_off[14] = {
    0, 0, 0, 1, 2, 5, 8, 18, 27, 40, 61, 75, 87, 103
};

/* m4_rl_intra_aic_vlc_cnt: 14 entries, crc32 f597a0c8 */
static const uint16_t m4_rl_intra_aic_vlc_cnt[14] = {
    0, 0, 1, 1, 3, 3, 10, 9, 13, 21, 14, 12, 16, 0
};

#define M4_RL_INTRA_AIC_VLC_MINLEN 2
#define M4_RL_INTRA_AIC_VLC_MAXLEN 12
static const m4_vlc m4_rl_intra_aic_vlc = { m4_rl_intra_aic_vlc_code, m4_rl_intra_aic_vlc_sym, m4_rl_intra_aic_vlc_off, m4_rl_intra_aic_vlc_cnt, 2, 12 };

/* m4_rl_intra_aic_run: 102 entries, crc32 f737168d */
static const uint8_t m4_rl_intra_aic_run[102] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7,
    8, 8, 9, 9, 10, 11, 12, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2,
    2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23
};

/* m4_rl_intra_aic_level: 102 entries, crc32 e4701583 */
static const uint8_t m4_rl_intra_aic_level[102] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 1,
    2, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1
};

/* m4_rl_intra_aic_maxlevel: 130 entries, crc32 f995b67b */
static const uint8_t m4_rl_intra_aic_maxlevel[130] = {
    25, 7, 4, 4, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 4, 3, 3, 2, 2, 2, 2,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0
};

/* m4_rl_intra_aic_maxrun: 130 entries, crc32 c9009a3e */
static const uint8_t m4_rl_intra_aic_maxrun[130] = {
    0, 13, 9, 5, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 7, 3, 1, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0
};

static const m4_rl m4_rl_intra_aic = { &m4_rl_intra_aic_vlc, m4_rl_intra_aic_run, m4_rl_intra_aic_level, m4_rl_intra_aic_maxlevel, m4_rl_intra_aic_maxrun, 102, 58 };

/* m4_rl_h263_inter_vlc_code: 103 entries, crc32 327e3255 */
static const uint16_t m4_rl_h263_inter_vlc_code[103] = {
    0x0002, 0x0006, 0x0007, 0x000e, 0x000f, 0x000b, 0x000c, 0x000d, 0x000c,
    0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015,
    0x0003, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017,
    0x0013, 0x0014, 0x0015, 0x0016, 0x0017, 0x0018, 0x0019, 0x001a, 0x001b,
    0x001c, 0x001d, 0x001e, 0x001f, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015,
    0x0016, 0x0017, 0x0018, 0x0019, 0x001a, 0x001b, 0x001c, 0x001d, 0x001e,
    0x001f, 0x0020, 0x0021, 0x0022, 0x0023, 0x0024, 0x0025, 0x0004, 0x0005,
    0x0006, 0x0007, 0x0008, 0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x000e,
    0x000f, 0x0020, 0x0021, 0x0004, 0x0005, 0x0006, 0x0007, 0x0020, 0x0021,
    0x0022, 0x0023, 0x0024, 0x0025, 0x0026, 0x0027, 0x0050, 0x0051, 0x0052,
    0x0053, 0x0054, 0x0055, 0x0056, 0x0057, 0x0058, 0x0059, 0x005a, 0x005b,
    0x005c, 0x005d, 0x005e, 0x005f
};

/* m4_rl_h263_inter_vlc_sym: 103 entries, crc32 5a0338cf */
static const uint16_t m4_rl_h263_inter_vlc_sym[103] = {
    0, 12, 58, 18, 1, 28, 25, 22, 65, 64, 63, 61, 38, 36, 34, 31, 13, 2, 102,
    69, 68, 67, 66, 43, 42, 40, 3, 77, 76, 75, 74, 73, 72, 71, 70, 45, 44, 19,
    14, 4, 85, 84, 83, 82, 81, 80, 79, 78, 59, 53, 52, 51, 50, 49, 48, 47, 46,
    26, 23, 6, 5, 89, 88, 87, 86, 39, 37, 35, 32, 29, 24, 20, 15, 8, 7, 62,
    60, 10, 9, 11, 16, 54, 55, 90, 91, 92, 93, 17, 21, 27, 30, 33, 41, 56, 57,
    94, 95, 96, 97, 98, 99, 100, 101
};

/* m4_rl_h263_inter_vlc_off: 14 entries, crc32 18f6616b */
static const uint16_t m4_rl_h263_inter_vlc_off[14] = {
    0, 0, 0, 1, 2, 5, 8, 18, 27, 40, 61, 75, 87, 103
};

/* m4_rl_h263_inter_vlc_cnt: 14 entries, crc32 f597a0c8 */
static const uint16_t m4_rl_h263_inter_vlc_cnt[14] = {
    0, 0, 1, 1, 3, 3, 10, 9, 13, 21, 14, 12, 16, 0
};

#define M4_RL_H263_INTER_VLC_MINLEN 2
#define M4_RL_H263_INTER_VLC_MAXLEN 12
static const m4_vlc m4_rl_h263_inter_vlc = { m4_rl_h263_inter_vlc_code, m4_rl_h263_inter_vlc_sym, m4_rl_h263_inter_vlc_off, m4_rl_h263_inter_vlc_cnt, 2, 12 };

/* m4_rl_h263_inter_run: 102 entries, crc32 b0f9daf9 */
static const uint8_t m4_rl_h263_inter_run[102] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3,
    4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 0, 0, 0, 1, 1, 2, 3, 4, 5, 6,
    7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40
};

/* m4_rl_h263_inter_level: 102 entries, crc32 71903edd */
static const uint8_t m4_rl_h263_inter_level[102] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 1, 2,
    3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1
};

/* m4_rl_h263_inter_maxlevel: 130 entries, crc32 16692a97 */
static const uint8_t m4_rl_h263_inter_maxlevel[130] = {
    12, 6, 4, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

/* m4_rl_h263_inter_maxrun: 130 entries, crc32 4e076bb8 */
static const uint8_t m4_rl_h263_inter_maxrun[130] = {
    0, 26, 10, 6, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0
};

static const m4_rl m4_rl_h263_inter = { &m4_rl_h263_inter_vlc, m4_rl_h263_inter_run, m4_rl_h263_inter_level, m4_rl_h263_inter_maxlevel, m4_rl_h263_inter_maxrun, 102, 58 };

/* m4_rl_mpeg4_intra_vlc_code: 103 entries, crc32 327e3255 */
static const uint16_t m4_rl_mpeg4_intra_vlc_code[103] = {
    0x0002, 0x0006, 0x0007, 0x000e, 0x000f, 0x000b, 0x000c, 0x000d, 0x000c,
    0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015,
    0x0003, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017,
    0x0013, 0x0014, 0x0015, 0x0016, 0x0017, 0x0018, 0x0019, 0x001a, 0x001b,
    0x001c, 0x001d, 0x001e, 0x001f, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015,
    0x0016, 0x0017, 0x0018, 0x0019, 0x001a, 0x001b, 0x001c, 0x001d, 0x001e,
    0x001f, 0x0020, 0x0021, 0x0022, 0x0023, 0x0024, 0x0025, 0x0004, 0x0005,
    0x0006, 0x0007, 0x0008, 0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x000e,
    0x000f, 0x0020, 0x0021, 0x0004, 0x0005, 0x0006, 0x0007, 0x0020, 0x0021,
    0x0022, 0x0023, 0x0024, 0x0025, 0x0026, 0x0027, 0x0050, 0x0051, 0x0052,
    0x0053, 0x0054, 0x0055, 0x0056, 0x0057, 0x0058, 0x0059, 0x005a, 0x005b,
    0x005c, 0x005d, 0x005e, 0x005f
};

/* m4_rl_mpeg4_intra_vlc_sym: 103 entries, crc32 c55fd422 */
static const uint16_t m4_rl_mpeg4_intra_vlc_sym[103] = {
    0, 1, 67, 27, 2, 37, 4, 3, 68, 49, 78, 75, 46, 42, 7, 6, 28, 5, 102, 82,
    80, 52, 84, 55, 38, 29, 8, 89, 88, 86, 69, 62, 60, 58, 90, 43, 30, 11, 10,
    9, 95, 94, 93, 92, 91, 76, 70, 64, 63, 56, 53, 50, 44, 39, 32, 31, 15, 47,
    14, 13, 12, 79, 77, 71, 65, 51, 59, 48, 45, 40, 33, 19, 18, 17, 16, 73,
    72, 21, 20, 22, 23, 34, 61, 81, 83, 96, 97, 24, 25, 26, 35, 54, 36, 41,
    57, 66, 74, 85, 87, 98, 99, 100, 101
};

/* m4_rl_mpeg4_intra_vlc_off: 14 entries, crc32 18f6616b */
static const uint16_t m4_rl_mpeg4_intra_vlc_off[14] = {
    0, 0, 0, 1, 2, 5, 8, 18, 27, 40, 61, 75, 87, 103
};

/* m4_rl_mpeg4_intra_vlc_cnt: 14 entries, crc32 f597a0c8 */
static const uint16_t m4_rl_mpeg4_intra_vlc_cnt[14] = {
    0, 0, 1, 1, 3, 3, 10, 9, 13, 21, 14, 12, 16, 0
};

#define M4_RL_MPEG4_INTRA_VLC_MINLEN 2
#define M4_RL_MPEG4_INTRA_VLC_MAXLEN 12
static const m4_vlc m4_rl_mpeg4_intra_vlc = { m4_rl_mpeg4_intra_vlc_code, m4_rl_mpeg4_intra_vlc_sym, m4_rl_mpeg4_intra_vlc_off, m4_rl_mpeg4_intra_vlc_cnt, 2, 12 };

/* m4_rl_mpeg4_intra_run: 102 entries, crc32 01b0e5ed */
static const uint8_t m4_rl_mpeg4_intra_run[102] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5,
    5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 9, 9, 10, 11, 12, 13, 14, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20
};

/* m4_rl_mpeg4_intra_level: 102 entries, crc32 d556c579 */
static const uint8_t m4_rl_mpeg4_intra_level[102] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 26, 27, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 1,
    2, 3, 4, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
    2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1
};

/* m4_rl_mpeg4_intra_maxlevel: 130 entries, crc32 85b6f4ee */
static const uint8_t m4_rl_mpeg4_intra_maxlevel[130] = {
    27, 10, 5, 4, 3, 3, 3, 3, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 3, 2, 2, 2, 2, 2, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

/* m4_rl_mpeg4_intra_maxrun: 130 entries, crc32 8534aab2 */
static const uint8_t m4_rl_mpeg4_intra_maxrun[130] = {
    0, 14, 9, 7, 3, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 6, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0
};

static const m4_rl m4_rl_mpeg4_intra = { &m4_rl_mpeg4_intra_vlc, m4_rl_mpeg4_intra_run, m4_rl_mpeg4_intra_level, m4_rl_mpeg4_intra_maxlevel, m4_rl_mpeg4_intra_maxrun, 102, 67 };

/* m4_rl_rvlc_inter_vlc_code: 170 entries, crc32 7f8555d8 */
static const uint16_t m4_rl_rvlc_inter_vlc_code[170] = {
    0x0006, 0x0007, 0x0000, 0x0001, 0x000a, 0x000b, 0x0004, 0x0005, 0x0008,
    0x0009, 0x0012, 0x0013, 0x000c, 0x000d, 0x0014, 0x0015, 0x0018, 0x0019,
    0x0022, 0x0023, 0x001c, 0x001d, 0x002c, 0x002d, 0x0034, 0x0035, 0x0038,
    0x0039, 0x0042, 0x0043, 0x003c, 0x003d, 0x005c, 0x005d, 0x006c, 0x006d,
    0x0074, 0x0075, 0x0078, 0x0079, 0x0082, 0x0083, 0x007c, 0x007d, 0x00bc,
    0x00bd, 0x00dc, 0x00dd, 0x00ec, 0x00ed, 0x00f4, 0x00f5, 0x00f8, 0x00f9,
    0x0102, 0x0103, 0x00fc, 0x00fd, 0x017c, 0x017d, 0x01bc, 0x01bd, 0x01dc,
    0x01dd, 0x01ec, 0x01ed, 0x01f4, 0x01f5, 0x01f8, 0x01f9, 0x0202, 0x0203,
    0x01fc, 0x01fd, 0x02fc, 0x02fd, 0x037c, 0x037d, 0x03bc, 0x03bd, 0x03dc,
    0x03dd, 0x03ec, 0x03ed, 0x03f4, 0x03f5, 0x03f8, 0x03f9, 0x0402, 0x0403,
    0x03fc, 0x03fd, 0x05fc, 0x05fd, 0x06fc, 0x06fd, 0x077c, 0x077d, 0x07bc,
    0x07bd, 0x07dc, 0x07dd, 0x07ec, 0x07ed, 0x07f4, 0x07f5, 0x07f8, 0x07f9,
    0x0802, 0x0803, 0x07fc, 0x07fd, 0x0bfc, 0x0bfd, 0x0dfc, 0x0dfd, 0x0efc,
    0x0efd, 0x0f7c, 0x0f7d, 0x0fbc, 0x0fbd, 0x0fdc, 0x0fdd, 0x0fec, 0x0fed,
    0x0ff4, 0x0ff5, 0x0ff8, 0x0ff9, 0x1002, 0x1003, 0x0ffc, 0x0ffd, 0x17fc,
    0x17fd, 0x1bfc, 0x1bfd, 0x1dfc, 0x1dfd, 0x1efc, 0x1efd, 0x1f7c, 0x1f7d,
    0x1fbc, 0x1fbd, 0x1fdc, 0x1fdd, 0x1fec, 0x1fed, 0x1ff4, 0x1ff5, 0x1ff8,
    0x1ff9, 0x2002, 0x2003, 0x1ffc, 0x1ffd, 0x2ffc, 0x2ffd, 0x37fc, 0x37fd,
    0x3bfc, 0x3bfd, 0x3dfc, 0x3dfd, 0x3efc, 0x3efd, 0x3f7c, 0x3f7d
};

/* m4_rl_rvlc_inter_vlc_sym: 170 entries, crc32 bfb2904b */
static const uint16_t m4_rl_rvlc_inter_vlc_sym[170] = {
    0, 19, 169, 1, 29, 103, 2, 36, 43, 48, 108, 113, 20, 52, 56, 60, 116, 118,
    120, 122, 3, 30, 63, 66, 68, 124, 126, 128, 130, 132, 4, 5, 21, 37, 44,
    70, 72, 74, 104, 134, 136, 138, 6, 22, 31, 49, 76, 78, 80, 109, 139, 140,
    141, 142, 143, 144, 7, 8, 23, 38, 53, 57, 61, 64, 82, 83, 84, 145, 146,
    147, 148, 149, 9, 10, 24, 32, 45, 50, 67, 85, 86, 87, 88, 89, 90, 105,
    114, 150, 151, 152, 11, 25, 33, 39, 54, 58, 69, 91, 92, 93, 110, 117, 119,
    153, 154, 155, 156, 157, 158, 159, 12, 13, 14, 15, 26, 40, 46, 51, 62, 71,
    94, 95, 96, 97, 106, 121, 123, 125, 127, 129, 160, 161, 16, 17, 27, 28,
    34, 35, 41, 55, 65, 73, 75, 77, 79, 98, 99, 100, 107, 111, 131, 133, 135,
    162, 163, 164, 18, 42, 47, 59, 81, 101, 102, 112, 115, 137, 165, 166, 167,
    168
};

/* m4_rl_rvlc_inter_vlc_off: 17 entries, crc32 8710d868 */
static const uint16_t m4_rl_rvlc_inter_vlc_off[17] = {
    0, 0, 0, 0, 2, 6, 12, 20, 30, 42, 56, 72, 90, 110, 132, 156, 170
};

/* m4_rl_rvlc_inter_vlc_cnt: 17 entries, crc32 f40785d9 */
static const uint16_t m4_rl_rvlc_inter_vlc_cnt[17] = {
    0, 0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 14, 0
};

#define M4_RL_RVLC_INTER_VLC_MINLEN 3
#define M4_RL_RVLC_INTER_VLC_MAXLEN 15
static const m4_vlc m4_rl_rvlc_inter_vlc = { m4_rl_rvlc_inter_vlc_code, m4_rl_rvlc_inter_vlc_sym, m4_rl_rvlc_inter_vlc_off, m4_rl_rvlc_inter_vlc_cnt, 3, 15 };

/* m4_rl_rvlc_inter_run: 169 entries, crc32 e6ad4169 */
static const uint8_t m4_rl_rvlc_inter_run[169] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
    5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 11, 11, 12, 12,
    13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 0, 0, 0, 0, 0, 1, 1,
    1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11,
    11, 12, 12, 13, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
    27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44
};

/* m4_rl_rvlc_inter_level: 169 entries, crc32 b7a8cf5b */
static const uint8_t m4_rl_rvlc_inter_level[169] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 1, 2,
    3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2,
    3, 4, 5, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 1, 2, 1, 2,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 1, 2, 1, 2,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
};

/* m4_rl_rvlc_inter_maxlevel: 130 entries, crc32 5bdd9f80 */
static const uint8_t m4_rl_rvlc_inter_maxlevel[130] = {
    19, 10, 7, 7, 5, 4, 4, 4, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 3, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

/* m4_rl_rvlc_inter_maxrun: 130 entries, crc32 655b2002 */
static const uint8_t m4_rl_rvlc_inter_maxrun[130] = {
    0, 38, 17, 9, 7, 4, 3, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44, 13, 2, 1, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0
};

static const m4_rl m4_rl_rvlc_inter = { &m4_rl_rvlc_inter_vlc, m4_rl_rvlc_inter_run, m4_rl_rvlc_inter_level, m4_rl_rvlc_inter_maxlevel, m4_rl_rvlc_inter_maxrun, 169, 103 };

/* m4_rl_rvlc_intra_vlc_code: 170 entries, crc32 7f8555d8 */
static const uint16_t m4_rl_rvlc_intra_vlc_code[170] = {
    0x0006, 0x0007, 0x0000, 0x0001, 0x000a, 0x000b, 0x0004, 0x0005, 0x0008,
    0x0009, 0x0012, 0x0013, 0x000c, 0x000d, 0x0014, 0x0015, 0x0018, 0x0019,
    0x0022, 0x0023, 0x001c, 0x001d, 0x002c, 0x002d, 0x0034, 0x0035, 0x0038,
    0x0039, 0x0042, 0x0043, 0x003c, 0x003d, 0x005c, 0x005d, 0x006c, 0x006d,
    0x0074, 0x0075, 0x0078, 0x0079, 0x0082, 0x0083, 0x007c, 0x007d, 0x00bc,
    0x00bd, 0x00dc, 0x00dd, 0x00ec, 0x00ed, 0x00f4, 0x00f5, 0x00f8, 0x00f9,
    0x0102, 0x0103, 0x00fc, 0x00fd, 0x017c, 0x017d, 0x01bc, 0x01bd, 0x01dc,
    0x01dd, 0x01ec, 0x01ed, 0x01f4, 0x01f5, 0x01f8, 0x01f9, 0x0202, 0x0203,
    0x01fc, 0x01fd, 0x02fc, 0x02fd, 0x037c, 0x037d, 0x03bc, 0x03bd, 0x03dc,
    0x03dd, 0x03ec, 0x03ed, 0x03f4, 0x03f5, 0x03f8, 0x03f9, 0x0402, 0x0403,
    0x03fc, 0x03fd, 0x05fc, 0x05fd, 0x06fc, 0x06fd, 0x077c, 0x077d, 0x07bc,
    0x07bd, 0x07dc, 0x07dd, 0x07ec, 0x07ed, 0x07f4, 0x07f5, 0x07f8, 0x07f9,
    0x0802, 0x0803, 0x07fc, 0x07fd, 0x0bfc, 0x0bfd, 0x0dfc, 0x0dfd, 0x0efc,
    0x0efd, 0x0f7c, 0x0f7d, 0x0fbc, 0x0fbd, 0x0fdc, 0x0fdd, 0x0fec, 0x0fed,
    0x0ff4, 0x0ff5, 0x0ff8, 0x0ff9, 0x1002, 0x1003, 0x0ffc, 0x0ffd, 0x17fc,
    0x17fd, 0x1bfc, 0x1bfd, 0x1dfc, 0x1dfd, 0x1efc, 0x1efd, 0x1f7c, 0x1f7d,
    0x1fbc, 0x1fbd, 0x1fdc, 0x1fdd, 0x1fec, 0x1fed, 0x1ff4, 0x1ff5, 0x1ff8,
    0x1ff9, 0x2002, 0x2003, 0x1ffc, 0x1ffd, 0x2ffc, 0x2ffd, 0x37fc, 0x37fd,
    0x3bfc, 0x3bfd, 0x3dfc, 0x3dfd, 0x3efc, 0x3efd, 0x3f7c, 0x3f7d
};

/* m4_rl_rvlc_intra_vlc_sym: 170 entries, crc32 29b6533e */
static const uint16_t m4_rl_rvlc_intra_vlc_sym[170] = {
    0, 1, 169, 27, 2, 103, 40, 51, 28, 3, 108, 113, 60, 66, 4, 5, 116, 118,
    120, 122, 72, 77, 41, 29, 6, 124, 126, 128, 130, 132, 82, 86, 52, 61, 30,
    31, 7, 8, 104, 134, 136, 138, 90, 67, 42, 53, 32, 9, 10, 109, 139, 140,
    141, 142, 143, 144, 92, 94, 73, 78, 83, 62, 43, 33, 11, 12, 13, 145, 146,
    147, 148, 149, 96, 87, 68, 74, 79, 54, 44, 45, 34, 35, 14, 15, 16, 105,
    114, 150, 151, 152, 91, 63, 69, 75, 55, 64, 36, 17, 18, 21, 110, 117, 119,
    153, 154, 155, 156, 157, 158, 159, 97, 98, 93, 84, 88, 80, 56, 46, 47, 48,
    37, 19, 20, 22, 106, 121, 123, 125, 127, 129, 160, 161, 99, 100, 101, 85,
    70, 65, 71, 57, 58, 49, 50, 38, 39, 23, 24, 25, 107, 111, 131, 133, 135,
    162, 163, 164, 26, 59, 76, 81, 89, 95, 102, 112, 115, 137, 165, 166, 167,
    168
};

/* m4_rl_rvlc_intra_vlc_off: 17 entries, crc32 8710d868 */
static const uint16_t m4_rl_rvlc_intra_vlc_off[17] = {
    0, 0, 0, 0, 2, 6, 12, 20, 30, 42, 56, 72, 90, 110, 132, 156, 170
};

/* m4_rl_rvlc_intra_vlc_cnt: 17 entries, crc32 f40785d9 */
static const uint16_t m4_rl_rvlc_intra_vlc_cnt[17] = {
    0, 0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 14, 0
};

#define M4_RL_RVLC_INTRA_VLC_MINLEN 3
#define M4_RL_RVLC_INTRA_VLC_MAXLEN 15
static const m4_vlc m4_rl_rvlc_intra_vlc = { m4_rl_rvlc_intra_vlc_code, m4_rl_rvlc_intra_vlc_sym, m4_rl_rvlc_intra_vlc_off, m4_rl_rvlc_intra_vlc_cnt, 3, 15 };

/* m4_rl_rvlc_intra_run: 169 entries, crc32 b24cff3a */
static const uint8_t m4_rl_rvlc_intra_run[169] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6,
    6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 11, 11, 12, 12, 13,
    14, 15, 16, 17, 18, 19, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4,
    5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
    35, 36, 37, 38, 39, 40, 41, 42, 43, 44
};

/* m4_rl_rvlc_intra_level: 169 entries, crc32 bbe87693 */
static const uint8_t m4_rl_rvlc_intra_level[169] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 26, 27, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2,
    3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6,
    1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 1, 2, 3, 4, 1,
    2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1
};

/* m4_rl_rvlc_intra_maxlevel: 130 entries, crc32 8ebddbd1 */
static const uint8_t m4_rl_rvlc_intra_maxlevel[130] = {
    27, 13, 11, 9, 6, 6, 5, 5, 4, 4, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 3, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0
};

/* m4_rl_rvlc_intra_maxrun: 130 entries, crc32 f946d6a8 */
static const uint8_t m4_rl_rvlc_intra_maxrun[130] = {
    0, 19, 12, 9, 9, 7, 5, 3, 3, 3, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44, 13, 2, 1, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0
};

static const m4_rl m4_rl_rvlc_intra = { &m4_rl_rvlc_intra_vlc, m4_rl_rvlc_intra_run, m4_rl_rvlc_intra_level, m4_rl_rvlc_intra_maxlevel, m4_rl_rvlc_intra_maxrun, 169, 103 };

/* m4_zigzag: 64 entries, crc32 34f6a43f */
static const uint8_t m4_zigzag[64] = {
    0, 1, 8, 16, 9, 2, 3, 10, 17, 24, 32, 25, 18, 11, 4, 5, 12, 19, 26, 33,
    40, 48, 41, 34, 27, 20, 13, 6, 7, 14, 21, 28, 35, 42, 49, 56, 57, 50, 43,
    36, 29, 22, 15, 23, 30, 37, 44, 51, 58, 59, 52, 45, 38, 31, 39, 46, 53,
    60, 61, 54, 47, 55, 62, 63
};

/* m4_scan_alt_h: 64 entries, crc32 febb8646 */
static const uint8_t m4_scan_alt_h[64] = {
    0, 1, 2, 3, 8, 9, 16, 17, 10, 11, 4, 5, 6, 7, 15, 14, 13, 12, 19, 18, 24,
    25, 32, 33, 26, 27, 20, 21, 22, 23, 28, 29, 30, 31, 34, 35, 40, 41, 48,
    49, 42, 43, 36, 37, 38, 39, 44, 45, 46, 47, 50, 51, 56, 57, 58, 59, 52,
    53, 54, 55, 60, 61, 62, 63
};

/* m4_scan_alt_v: 64 entries, crc32 14fbeb79 */
static const uint8_t m4_scan_alt_v[64] = {
    0, 8, 16, 24, 1, 9, 2, 10, 17, 25, 32, 40, 48, 56, 57, 49, 41, 33, 26, 18,
    3, 11, 4, 12, 19, 27, 34, 42, 50, 58, 35, 43, 51, 59, 20, 28, 5, 13, 6,
    14, 21, 29, 36, 44, 52, 60, 37, 45, 53, 61, 22, 30, 7, 15, 23, 31, 38, 46,
    54, 62, 39, 47, 55, 63
};

/* m4_y_dc_scale: 32 entries, crc32 52f00a2f */
static const uint8_t m4_y_dc_scale[32] = {
    0, 8, 8, 8, 8, 10, 12, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 29, 30, 31, 32, 34, 36, 38, 40, 42, 44, 46
};

/* m4_c_dc_scale: 32 entries, crc32 7c011f60 */
static const uint8_t m4_c_dc_scale[32] = {
    0, 8, 8, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16,
    16, 17, 17, 18, 18, 19, 20, 21, 22, 23, 24, 25
};

/* m4_dc_threshold: 8 entries, crc32 de9169fd */
static const uint8_t m4_dc_threshold[8] = {
    99, 13, 15, 17, 19, 21, 23, 0
};

/* m4_identity_qscale: 32 entries, crc32 c4edd0b0 */
static const uint8_t m4_identity_qscale[32] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31
};

/* m4_h263_chroma_qscale: 32 entries, crc32 38bb6a04 */
static const uint8_t m4_h263_chroma_qscale[32] = {
    0, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 9, 10, 10, 11, 11, 12, 12, 12, 13, 13,
    13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15
};

/* m4_modified_quant: 64 entries, crc32 2d719e46 */
static const uint8_t m4_modified_quant[64] = {
    0, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30,
    31, 31, 31, 26
};

/* m4_mba_max: 6 entries, crc32 d9ecc283 */
static const uint16_t m4_mba_max[6] = {
    47, 98, 395, 1583, 6335, 9215
};

/* m4_mba_length: 7 entries, crc32 7d49ec76 */
static const uint8_t m4_mba_length[7] = {
    6, 7, 9, 11, 13, 14, 14
};

/* m4_aic_dc_scale: 32 entries, crc32 ce22aec7 */
static const uint8_t m4_aic_dc_scale[32] = {
    0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
    40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62
};

/* m4_default_intra_matrix: 64 entries, crc32 f81cbeb1 */
static const uint16_t m4_default_intra_matrix[64] = {
    8, 17, 18, 19, 21, 23, 25, 27, 17, 18, 19, 21, 23, 25, 27, 28, 20, 21, 22,
    23, 24, 26, 28, 30, 21, 22, 23, 24, 26, 28, 30, 32, 22, 23, 24, 26, 28,
    30, 32, 35, 23, 24, 26, 28, 30, 32, 35, 38, 25, 26, 28, 30, 32, 35, 38,
    41, 27, 28, 30, 32, 35, 38, 41, 45
};

/* m4_default_inter_matrix: 64 entries, crc32 32a3e578 */
static const uint16_t m4_default_inter_matrix[64] = {
    16, 17, 18, 19, 20, 21, 22, 23, 17, 18, 19, 20, 21, 22, 23, 24, 18, 19,
    20, 21, 22, 23, 24, 25, 19, 20, 21, 22, 23, 24, 26, 27, 20, 21, 22, 23,
    25, 26, 27, 28, 21, 22, 23, 24, 26, 27, 28, 30, 22, 23, 24, 26, 27, 28,
    30, 31, 23, 24, 25, 27, 28, 30, 31, 33
};

/* m4_h263_format: 16 entries, crc32 5e9e891a */
static const uint16_t m4_h263_format[16] = {
    0, 0, 128, 96, 176, 144, 352, 288, 704, 576, 1408, 1152, 0, 0, 0, 0
};

/* m4_h263_loop_strength: 32 entries, crc32 86006796 */
static const uint8_t m4_h263_loop_strength[32] = {
    0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10,
    10, 10, 11, 11, 11, 12, 12, 12
};

/* m4_chroma_roundtab: 16 entries, crc32 45fa6aac */
static const uint8_t m4_chroma_roundtab[16] = {
    0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1
};


#endif /* LOGIT_MPEG4_TABLES_H */

