/*
 * Pinyin Dictionary Binary Format - c/lib/ime/pinyin_fmt.h
 *
 * This header defines the binary format for the Pinyin dictionary used by the
 * input method engine. The dictionary is built once at boot from jieba and
 * pypinyin data, then loaded and searched using binary search by key.
 *
 * FORMAT (little-endian):
 *   Header (12 bytes):
 *     magic[4]    0x50594e00  ("PYN\0")
 *     version     uint32_t = 1
 *     key_count   uint32_t  (number of pinyin syllable keys)
 *
 *   Key entries (one per sorted key):
 *     key_str     null-terminated UTF-8 string (ASCII pinyin, toneless)
 *     candidates  uint16_t  (number of candidate characters/phrases)
 *     For each candidate:
 *       length    uint16_t  (UTF-8 bytes in this candidate)
 *       data      UTF-8 encoded character or phrase
 *
 * EXAMPLE: To find candidates for "nihao" (你好):
 *   1. Binary search for key "nihao" in the key entries
 *   2. Read candidates count
 *   3. Read each candidate (length + UTF-8 data)
 *
 * PROPERTIES:
 *   - All keys are sorted lexicographically for binary search
 *   - Candidates within each key are sorted by frequency (most common first)
 *   - All characters in candidates are guaranteed to be in the font's cmap
 *   - The dictionary is read-only and can be mmap'd
 *   - No allocator required - binary format is self-describing
 *
 * SOURCE:
 *   Generated by tools/mkpinyin.py from:
 *   - pypinyin 0.55.0 (MIT) - character readings and phrase dictionary
 *   - jieba 0.42.1 (MIT) - word list and frequencies
 *   - Font cmap from fsroot/fonts/ui.ttf - available characters (6763 CJK)
 *
 * LICENSE: The dictionary data combines:
 *   - pypinyin-0.55.0: MIT (C:\Python314\Lib\site-packages\pypinyin-0.55.0.dist-info\licenses\LICENSE.txt)
 *   - jieba-0.42.1: MIT (verified in METADATA: License :: OSI Approved :: MIT License)
 *   - jieba's dict.txt: MIT (included in jieba package)
 */

#ifndef C_LIB_IME_PINYIN_FMT_H_
#define C_LIB_IME_PINYIN_FMT_H_

#include <stdint.h>

typedef struct {
	uint8_t magic[4];    // Must be 'P', 'Y', 'N', '\0'
	uint32_t version;    // Must be 1
	uint32_t key_count;  // Number of pinyin keys in dictionary
} pinyin_dict_header_t;

#define PINYIN_MAGIC 0x4e5950  // "PYN" in little-endian (0x50594e00 with null)
#define PINYIN_VERSION 1

#endif // C_LIB_IME_PINYIN_FMT_H_
