#!/usr/bin/env python3
"""bin2inc.py IN OUT SYMBOL -- turn a binary file into a C array include.

Emits `static const unsigned char SYMBOL[] = {...};` plus `SYMBOL_len`.
`static` on purpose: the only consumer is the single .c file that #includes
this, and a non-static array would put 40 KB of bytecode in the global symbol
table of every binary that links it.

Used for exactly one thing today: embedding build/asboot.la (the compiled
bridge module, c/apps/as/asboot.as) into /bin/as. See the header of
c/apps/as/asboot.as for why the bridge exists at all.

Deterministic: the output is a pure function of the input bytes, so a
rebuild with an unchanged input produces a byte-identical header and does not
cascade a rebuild of everything downstream.
"""
import sys


def main(argv):
    if len(argv) != 4:
        sys.stderr.write("usage: bin2inc.py IN OUT SYMBOL\n")
        return 2
    src, dst, sym = argv[1], argv[2], argv[3]
    with open(src, "rb") as f:
        data = f.read()
    if not data:
        sys.stderr.write("bin2inc.py: %s is empty -- refusing to emit an empty array\n" % src)
        return 1
    out = []
    out.append("/* Generated by tools/bin2inc.py from %s -- do not edit. */\n" % src)
    out.append("static const unsigned char %s[] = {\n" % sym)
    for i in range(0, len(data), 16):
        row = ", ".join("0x%02x" % b for b in data[i:i + 16])
        out.append("    %s,\n" % row)
    out.append("};\n")
    out.append("static const unsigned int %s_len = %du;\n" % (sym, len(data)))
    text = "".join(out)
    # Write only on change: the .inc is a prerequisite of as.c's object, and
    # rewriting an identical file would rebuild it on every make.
    try:
        with open(dst, "r") as f:
            if f.read() == text:
                return 0
    except OSError:
        pass
    with open(dst, "w") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
