#!/usr/bin/env python3
"""Emit the NASM view of include/abi/logit_boot.h.

The BIOS loader is assembly and cannot include a C header, so every offset and
constant in the native boot protocol exists twice: once as a `#define` the C
side compiles and `_Static_assert`s, and once as a `%define` nasm consumes.
This script is the single door between them.

WHY IT IS A SCRIPT AND NOT AN awk LINE IN A RECIPE, which is what it replaced:
there were two such lines, one in the root Makefile and one in
tests/bootself.mk, each with its own regular expression for the same fact. They
agreed on the day they were written. On 2026-09-15 the product ISO stopped
building because one of them had produced a 21-constant include while the other
produced 50 from the same header, and the product rule did not list its own
recipe as an input, so make reported a stale file as up to date. One jar, two
doors, and the doors disagreed -- which is the failure CLAUDE.md's third rule
names and the one the boot-contract gate exists to catch.

Anything that consumes this output must depend on THIS FILE as well as on the
header, or the same silence returns the next time the extraction changes.

Refused rather than guessed: a #define whose value is not a plain integer
literal (an expression, a cast, a sizeof, another macro) is skipped, because
nasm's %define is textual and would paste C syntax into an instruction stream
and fail somewhere unrelated. If a constant you need is missing from the output,
give it a literal value in the header rather than loosening the filter here.
"""

import argparse
import re
import sys

# `#define NAME 0x1234` or `#define NAME 42`, nothing else. The trailing
# comment is allowed because the header uses them and they carry the reasons.
DEFINE = re.compile(
    r"^#define\s+(LOGIT_BOOT_[A-Z0-9_]+)\s+"
    r"(0[xX][0-9a-fA-F]+|[0-9]+)\s*(?:/\*.*\*/|//.*)?\s*$"
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("header")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument(
        "--min-defines",
        type=int,
        default=20,
        help="fail if fewer than this many constants are extracted; a "
        "generator that silently emits nothing is how the 21-vs-50 "
        "incident happened",
    )
    args = ap.parse_args()

    out, names = [], set()
    with open(args.header, "r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            m = DEFINE.match(line.rstrip("\n"))
            if not m:
                continue
            name, value = m.group(1), m.group(2)
            if name in names:
                print(
                    f"{args.header}:{lineno}: {name} defined twice",
                    file=sys.stderr,
                )
                return 1
            names.add(name)
            out.append(f"%define {name} {value}")

    # FAIL CLOSED. An extraction that matches nothing must not produce an empty
    # include that assembles into a loader full of zero offsets.
    if len(out) < args.min_defines:
        print(
            f"gen_boot_inc: extracted {len(out)} constants from {args.header}, "
            f"expected at least {args.min_defines}. Either the header changed "
            f"shape or this script's pattern did; do not lower the floor to "
            f"make this pass.",
            file=sys.stderr,
        )
        return 1

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write("; GENERATED by tools/gen_boot_inc.py from " + args.header + "\n")
        fh.write("; DO NOT EDIT. Change the header; this file follows it.\n")
        fh.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
