#!/usr/bin/env python3
"""Generate c/apps/browser/encoding_tables.inc from the WHATWG Encoding data.

WHERE THE DATA COMES FROM, because it decides whether the encoding tests are
measuring anything.  Two files, both of which say in their own first line that
they are copies of a normative WHATWG artefact:

    third_party/wpt/encoding/resources/encodings.js
        "// Straight from https://encoding.spec.whatwg.org/encodings.json"
        -- the label -> encoding-name table.
    third_party/wpt/encoding/resources/single-byte-decoder.js
        "// https://encoding.spec.whatwg.org/indexes.json"
        -- index i -> code point, for each legacy single-byte encoding.

These are DATA, in the html5lib-tests sense: the same normative table every
browser compiles in, not the WPT assertions restated.  The distinction matters
and it is not free of cost -- see the honesty note below.

WHAT IS AND IS NOT MEASURED AFTER THIS.  encoding/textdecoder-labels.any.js and
encoding/textdecoder-fatal-single-byte.any.js consume the SAME two upstream
files this generator reads.  So for the pure-lookup part of those tests -- "is
label X the name Y", "is byte B in encoding E the code point C" -- our answer
and the test's answer have a common ancestor, and agreement is close to
tautological.  What is NOT tautological, and is what those tests actually break
on today, is the algorithm around the table: ASCII case-folding, the leading and
trailing whitespace strip (space/tab/LF/FF/CR only -- not \\v, which is the
usual bug), the RangeError on an unknown label, `encoding` reporting the
lowercased canonical name rather than the label the caller passed, and the fatal
flag turning an unmapped byte into a TypeError instead of U+FFFD.  Read any
"labels" number in the report with that split in mind; it is stated again there.

Regenerate:  python3 tools/gen_encoding_tables.py
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RES = os.path.join(ROOT, "third_party", "wpt", "encoding", "resources")
OUT = os.path.join(ROOT, "c", "apps", "browser", "encoding_tables.inc")


def js_array_literal(text, start_marker):
    """Pull the first bracketed literal following `start_marker` out of a JS file."""
    i = text.index(start_marker) + len(start_marker)
    while text[i] in " \t\r\n=":
        i += 1
    assert text[i] in "[{", text[i]
    open_ch, close_ch = ("[", "]") if text[i] == "[" else ("{", "}")
    depth, j, in_str = 0, i, None
    while j < len(text):
        c = text[j]
        if in_str:
            if c == "\\":
                j += 2
                continue
            if c == in_str:
                in_str = None
        elif c in "\"'":
            in_str = c
        elif c == open_ch:
            depth += 1
        elif c == close_ch:
            depth -= 1
            if depth == 0:
                return text[i:j + 1]
        j += 1
    raise ValueError("unterminated literal after " + start_marker)


def main():
    if not os.path.isdir(RES):
        sys.stderr.write("gen_encoding_tables: no corpus at %s -- nothing to do\n" % RES)
        return 1

    enc_js = open(os.path.join(RES, "encodings.js"), encoding="utf-8").read()
    table = json.loads(js_array_literal(enc_js, "encodings_table"))

    sb_js = open(os.path.join(RES, "single-byte-decoder.js"), encoding="utf-8").read()
    indexes = json.loads(js_array_literal(sb_js, "singleByteIndexes"))

    # label -> canonical name, lowercased as TextDecoder.encoding reports it.
    labels = []
    names = []
    for section in table:
        for enc in section["encodings"]:
            name = enc["name"]
            names.append((name, name.lower(), section["heading"]))
            for lab in enc["labels"]:
                labels.append((lab.lower(), name.lower()))
    labels.sort()
    dupes = [l for i, (l, _) in enumerate(labels[1:], 1) if l == labels[i - 1][0]]
    assert not dupes, "duplicate labels: %r" % dupes

    lines = []
    w = lines.append
    w("/* GENERATED by tools/gen_encoding_tables.py -- do not edit.")
    w(" * Source: the WHATWG Encoding Standard's encodings.json and indexes.json,")
    w(" * as vendored by WPT under third_party/wpt/encoding/resources/.")
    w(" * %d labels over %d encodings; %d single-byte index tables." %
      (len(labels), len(names), len(indexes)))
    w(" * See the generator's docstring for what this does and does not make")
    w(" * the encoding/ WPT numbers mean. */")
    w("")
    w("struct enc_label { const char *label; const char *name; };")
    w("static const struct enc_label ENC_LABELS[] = {")
    for lab, name in labels:
        w('    { "%s", "%s" },' % (lab, name))
    w("};")
    w("#define ENC_LABEL_COUNT %d" % len(labels))
    w("")

    # Single-byte index tables: 128 entries each, index 0 == byte 0x80.
    # A hole (unmapped byte) is 0 -- U+0000 is never a legitimate target here,
    # so zero is an unambiguous "no mapping" and needs no parallel bitmap.
    w("/* Byte 0x80+i -> code point, or 0 for \"no mapping\" (fatal: TypeError,")
    w(" * otherwise U+FFFD). U+0000 is never a target in these indexes, so 0 is")
    w(" * a safe hole marker; asserted by the generator. */")
    sb_names = sorted(indexes.keys())
    for enc_name in sb_names:
        arr = indexes[enc_name]
        assert len(arr) == 128, (enc_name, len(arr))
        assert 0 not in arr, enc_name
        ident = re.sub(r"[^A-Za-z0-9]", "_", enc_name).upper()
        w("static const unsigned short ENC_SB_%s[128] = {" % ident)
        cells = [("0" if v is None else str(v)) for v in arr]
        for k in range(0, 128, 16):
            w("    " + ",".join("%5s" % c for c in cells[k:k + 16]) + ",")
        w("};")
    w("")
    # ISO-8859-8-I is a single-byte ENCODING with no index of its own: it is
    # ISO-8859-8's table under a second name, the two differing only in the
    # bidi directionality the bytes imply, which a decoder does not represent.
    # Left out, `new TextDecoder('iso-8859-8-i')` finds no index and silently
    # falls back -- encoding/textdecoder-mistakes.any.js has a case named
    # exactly "iso-8859-8-i decodes bytes the same way as iso-8859-8". So the
    # aliasing is derived, not hardcoded: any name in the single-byte section
    # without its own index is matched to the name it is a suffixed variant of,
    # and the assert below refuses to emit a table that leaves one uncovered.
    sb_section = [e["name"] for sec in table if "single-byte" in sec["heading"]
                  for e in sec["encodings"]]
    entries = [(n.lower(), n) for n in sb_names]
    have = {n.lower() for n in sb_names}
    for name in sb_section:
        low = name.lower()
        if low in have:
            continue
        base = re.sub(r"-[a-z]$", "", low)
        assert base in have, "no index for single-byte encoding %r" % name
        entries.append((low, dict((k.lower(), k) for k in sb_names)[base]))
        have.add(low)
    missing = [n for n in sb_section if n.lower() not in have]
    assert not missing, "single-byte encodings with no table: %r" % missing
    entries.sort()

    w("struct enc_sb { const char *name; const unsigned short *idx; };")
    w("static const struct enc_sb ENC_SINGLE_BYTE[] = {")
    for low, src_name in entries:
        ident = re.sub(r"[^A-Za-z0-9]", "_", src_name).upper()
        w('    { "%s", ENC_SB_%s },' % (low, ident))
    w("};")
    w("#define ENC_SINGLE_BYTE_COUNT %d" % len(entries))
    w("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    sys.stderr.write("gen_encoding_tables: wrote %s (%d labels, %d single-byte tables)\n"
                     % (OUT, len(labels), len(sb_names)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
