#!/usr/bin/env python3
"""Generate c/lib/ime/pinyin_syllables.inc -- the legal Mandarin Pinyin
syllable table used by the IME segmenter (c/lib/ime/pinyin.c) to decide
where a typed buffer may be cut into syllables.

METHOD: for every codepoint U+4E00..U+9FFF, ask pypinyin for EVERY
pronunciation of that character (heteronym=True, not just the first), strip
tone marks via NFD decomposition + drop combining marks (category Mn), and
lowercase. The union across all ~20,000 CJK codepoints is the REAL, REALIZED
syllable inventory of Mandarin -- every syllable at least one actual
character uses -- rather than a hand-derived initial x final combinability
grid that would need its own correctness argument.

This is the SAME pypinyin (0.55.0, MIT) data tools/mkpinyin.py already uses
for the dictionary itself (fsroot/ime/pinyin.dat): no new dependency, no new
licence to track beyond the row THIRD_PARTY.md already carries for pypinyin.

Five entries are removed from the raw scan on purpose: m, hm, n, ng, hng --
the nasal-interjection readings of 呣/嗯/哼 and kin. They are genuine
pypinyin output and remain ordinary DICTIONARY KEYS ('n' has 1 candidate,
嗯, reachable by a direct whole-buffer lookup), but they are excluded from
this SEGMENTATION table because they do not compose: admitting bare 'n' as
a legal segment would let the segmenter parse "nhao" as n+hao and
manufacture a candidate for a buffer the gate requires to come back with
zero candidates (verified: without this removal, tests/unit/ime_test.c's
nhao case fails).

Idempotent: run against unmodified pypinyin/CJK-block data it reproduces
c/lib/ime/pinyin_syllables.inc byte for byte -- check that first if this
script is ever touched.
"""

import sys
import unicodedata

from pypinyin import pinyin, NORMAL

OUTPUT = "c/lib/ime/pinyin_syllables.inc"
FILLERS = {"m", "hm", "n", "ng", "hng"}


def toneless(py):
    d = unicodedata.normalize("NFD", py)
    out = ""
    for c in d:
        if unicodedata.category(c) == "Mn":
            continue
        if ord(c) <= 127:
            out += c.lower()
    return out


def build_syllables():
    syl = set()
    for cp in range(0x4E00, 0x9FFF + 1):
        ch = chr(cp)
        try:
            results = pinyin(ch, style=NORMAL, heteronym=True)
        except Exception:
            continue
        if not results:
            continue
        for variant in results[0]:
            t = toneless(variant)
            if t:
                syl.add(t)
    raw_count = len(syl)
    syl -= FILLERS
    print(
        f"raw pypinyin scan: {raw_count} distinct toneless syllables; "
        f"removed {len(FILLERS)} fillers {sorted(FILLERS)}; "
        f"final table: {len(syl)}",
        file=sys.stderr,
    )
    return sorted(syl)


def write_header(syl, path):
    assert all(1 <= len(s) <= 6 for s in syl)
    assert all(s.isalpha() and s.isascii() and s == s.lower() for s in syl)

    lines = []
    lines.append(
        "/* c/lib/ime/pinyin_syllables.inc -- the legal Mandarin Pinyin syllable table."
    )
    lines.append(" *")
    lines.append(
        " * GENERATED by tools/gen_pinyin_syllables.py -- read that file's docstring"
    )
    lines.append(
        " * for the method and for why five syllables (m, hm, n, ng, hng) are removed"
    )
    lines.append(" * from the raw pypinyin scan. Do not hand-edit this file.")
    lines.append(" *")
    lines.append(f" * {len(syl)} entries, sorted, min length 1 max length 6. */")
    lines.append("")
    lines.append(f"#define PINYIN_SYLLABLE_COUNT {len(syl)}")
    lines.append("")
    lines.append(
        "static const char *const g_pinyin_syllables[PINYIN_SYLLABLE_COUNT] = {"
    )
    for i in range(0, len(syl), 8):
        row = syl[i : i + 8]
        lines.append("    " + " ".join(f'"{s}",' for s in row))
    lines.append("};")
    lines.append("")

    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path} ({len(syl)} syllables)", file=sys.stderr)


if __name__ == "__main__":
    syllables = build_syllables()
    write_header(syllables, OUTPUT)
