#!/usr/bin/env python3
"""gen_html_tables.py -- generate the HTML tokenizer's static tables.

Emits two committed .inc files next to the tokenizer, the same convention as
tools/genroots.py -> c/crypto/trust/roots_bundle.inc:

  c/apps/browser/html_entities.inc   the full WHATWG named character reference
                                     table (2231 entries), name-sorted
  c/apps/browser/html_tags.inc       a uint16_t id for every tag name the tree
                                     builder has to special-case

WHY GENERATE THE ENTITY TABLE INSTEAD OF VENDORING ONE
-----------------------------------------------------
CPython's stdlib `html.entities.html5` *is* the WHATWG table -- it is generated
from the same spec source and updated with the spec.  Vendoring a copied .h
means auditing 2231 lines by hand and re-auditing them whenever the spec moves;
reading it out of the stdlib means the table is right by construction, and the
diff of a regenerate is reviewable.  The historical no-semicolon forms (`&amp`,
`&notin` ... 106 of them) are in that dict too, and they matter: real pages in
the wild still contain `&copy` and `&nbsp` unterminated, and the spec's
longest-prefix match is what makes `&notit;` tokenize as `¬it;`.

WHY A SORTED ARRAY AND NOT A HASH / TRIE
----------------------------------------
The match the spec asks for is *longest prefix*, not exact lookup -- a hash
table cannot answer it without probing every prefix length.  A byte-sorted array
answers it in one narrowing scan (see html_ref_lookup in html_tokenizer.c),
needs no construction at startup, and lands in .rodata, which matters because
this runs in a ring-3 app with a 24 MiB arena.

Usage:  python3 tools/gen_html_tables.py [outdir]      (default c/apps/browser)
"""

import html.entities
import os
import sys

# ---------------------------------------------------------------- tags -----
# Every tag name the tree builder needs to recognise by identity rather than by
# strcmp: the spec's "special" set, the active-formatting-elements set, the
# scope sets, the foreign-content integration points, and the handful of others
# the insertion modes name explicitly.  0 is reserved for "unknown/custom", so
# an unrecognised tag (a web component, say) is simply HTAG_UNKNOWN and falls
# through every set test at once.
TAGS = """
a abbr address annotation-xml applet area article aside audio
b base basefont bdi bdo bgsound big blockquote body br button
canvas caption center cite code col colgroup
data datalist dd del desc details dfn dialog dir div dl dt
em embed
fieldset figcaption figure font footer foreignobject form frame frameset
h1 h2 h3 h4 h5 h6 head header hgroup hr html
i iframe image img input ins isindex
kbd keygen
label legend li link listing main malignmark marquee math menu menuitem meta
meter mglyph mi mn mo ms mtext
nav nobr noembed noframes noscript
object ol optgroup option output
p param picture plaintext pre progress
q
rb rp rt rtc ruby
s samp script search section select slot small source span strike strong style
sub summary sup svg
table tbody td template textarea tfoot th thead time title tr track tt
u ul
var video
wbr
xmp
"""


def c_string(b: bytes) -> str:
    """A C string literal for arbitrary bytes -- always \\xNN for anything
    outside printable ASCII so no locale or encoding can reinterpret it."""
    out = []
    for i, ch in enumerate(b):
        if ch == 0x22:
            out.append('\\"')
        elif ch == 0x5C:
            out.append("\\\\")
        elif 0x20 <= ch < 0x7F:
            # A hex escape swallows following hex digits, so re-quote after one.
            if out and out[-1].startswith("\\x") and chr(ch) in "0123456789abcdefABCDEF":
                out.append('" "')
            out.append(chr(ch))
        else:
            out.append("\\x%02x" % ch)
    return '"' + "".join(out) + '"'


def gen_entities(path):
    tbl = html.entities.html5
    rows = []
    for name, val in tbl.items():
        cps = [ord(c) for c in val]
        assert 1 <= len(cps) <= 2, (name, cps)
        rows.append((name.encode("ascii"), cps))
    # Byte order.  A name that is a prefix of another sorts first, which is what
    # the narrowing search in html_ref_lookup relies on to spot exact matches.
    rows.sort(key=lambda r: r[0])

    maxlen = max(len(n) for n, _ in rows)
    with open(path, "w", newline="\n") as f:
        f.write("/* html_entities.inc -- GENERATED by tools/gen_html_tables.py."
                "  Do not edit.\n"
                " *\n"
                " * The WHATWG named character reference table, read out of"
                " CPython's\n"
                " * html.entities.html5 (which is that table).  Sorted by name"
                " bytes; a\n"
                " * name that is a prefix of another comes first, so the"
                " narrowing search\n"
                " * in html_ref_lookup() sees an exact match as the low end of"
                " its range.\n"
                " *\n"
                " * Names carry their own trailing ';' when they have one --"
                " the %d legacy\n"
                " * forms that do not are the reason matching is"
                " longest-prefix.\n"
                " */\n" % sum(1 for n, _ in rows if not n.endswith(b";")))
        f.write("#define HTML_ENT_COUNT  %d\n" % len(rows))
        f.write("#define HTML_ENT_MAXLEN %d\n\n" % maxlen)
        f.write("static const struct html_ent {\n"
                "    const char *name;\n"
                "    unsigned char len;\n"
                "    unsigned int cp1, cp2;   /* cp2 == 0 -> single code point */\n"
                "} html_ents[HTML_ENT_COUNT] = {\n")
        for name, cps in rows:
            cp2 = cps[1] if len(cps) > 1 else 0
            f.write('    { %-34s %2d, 0x%05X, 0x%05X },\n'
                    % (c_string(name) + ",", len(name), cps[0], cp2))
        f.write("};\n")
    return len(rows), maxlen


def gen_tags(path):
    names = sorted(set(TAGS.split()))
    ids = ["HTAG_" + n.upper().replace("-", "_") for n in names]

    with open(path, "w", newline="\n") as f:
        f.write("/* html_tags.inc -- GENERATED by tools/gen_html_tables.py."
                "  Do not edit.\n"
                " *\n"
                " * A uint16_t identity for the tag names the tree builder has"
                " to test by\n"
                " * name: the spec's \"special\" set, the formatting set, the"
                " scope sets, the\n"
                " * MathML/SVG integration points.  Written as strcmp chains"
                " those tests are\n"
                " * both unreadable and O(n) per element; as ids they are a"
                " switch or a\n"
                " * bitset.  HTAG_UNKNOWN (0) is every tag not listed -- custom"
                " elements\n"
                " * fall out of every set at once, which is exactly the spec's"
                " behaviour.\n"
                " *\n"
                " * Include once for the enum; #define HTML_TAGS_TABLE before a"
                " second\n"
                " * include to also pull in the (static) lookup table.\n"
                " */\n")
        f.write("#ifndef HTML_TAGS_ENUM_\n#define HTML_TAGS_ENUM_\n")
        f.write("enum html_tag {\n    HTAG_UNKNOWN = 0,\n")
        for i, ident in enumerate(ids):
            f.write("    %-22s = %d,\n" % (ident, i + 1))
        f.write("    HTAG__COUNT\n};\n")
        f.write("#endif /* HTML_TAGS_ENUM_ */\n\n")

        f.write("#ifdef HTML_TAGS_TABLE\n")
        f.write("#define HTML_TAG_COUNT  %d\n" % len(names))
        f.write("#define HTML_TAG_MAXLEN %d\n\n" % max(len(n) for n in names))
        f.write("static const struct html_tag_ent {\n"
                "    const char *name;\n"
                "    unsigned char len;\n"
                "    unsigned short id;\n"
                "} html_tag_ents[HTML_TAG_COUNT] = {   /* sorted by name bytes */\n")
        for n, ident in zip(names, ids):
            f.write('    { %-20s %2d, %s },\n'
                    % ('"%s",' % n, len(n), ident))
        f.write("};\n#endif /* HTML_TAGS_TABLE */\n")
    return len(names)


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join("c", "apps", "browser")
    n, m = gen_entities(os.path.join(outdir, "html_entities.inc"))
    t = gen_tags(os.path.join(outdir, "html_tags.inc"))
    print("gen_html_tables: %d named entities (max name %d bytes), %d tag ids"
          % (n, m, t))


if __name__ == "__main__":
    main()
