#!/usr/bin/env python3
"""Rasterize DejaVu Sans Mono (permissive license, bundled with matplotlib)
into an 8x16 1-bpp bitmap font header for the kernel.

font8x16[c][row] is a byte; bit 7 (0x80) is the leftmost pixel."""
import os
from PIL import Image, ImageFont, ImageDraw
import matplotlib

TTF = os.path.join(os.path.dirname(matplotlib.__file__),
                   "mpl-data/fonts/ttf/DejaVuSansMono.ttf")
CELL_W, CELL_H = 8, 16
THRESHOLD = 110


def pick_size():
    sample = "".join(chr(c) for c in range(0x20, 0x7F))
    for size in range(CELL_H, 6, -1):
        f = ImageFont.truetype(TTF, size)
        asc, desc = f.getmetrics()
        if asc + desc > CELL_H:
            continue
        widest = 0
        for ch in sample:
            box = f.getbbox(ch)
            if box:
                widest = max(widest, box[2] - box[0])
        if widest <= CELL_W:
            return size, f
    return 8, ImageFont.truetype(TTF, 8)


def main():
    size, font = pick_size()
    asc, desc = font.getmetrics()
    yoff = max(0, (CELL_H - (asc + desc)) // 2)

    glyphs = []
    for c in range(128):
        rows = [0] * CELL_H
        if 0x20 <= c < 0x7F and c != 0x20:
            img = Image.new("L", (CELL_W, CELL_H), 0)
            ImageDraw.Draw(img).text((0, yoff), chr(c), fill=255, font=font)
            px = img.load()
            for y in range(CELL_H):
                b = 0
                for x in range(CELL_W):
                    if px[x, y] > THRESHOLD:
                        b |= 1 << (7 - x)
                rows[y] = b
        glyphs.append(rows)

    with open("include/font8x16.h", "w") as fh:
        fh.write("#ifndef AQUA_FONT8X16_H\n#define AQUA_FONT8X16_H\n")
        fh.write("/* Generated by tools/genfont.py from DejaVu Sans Mono. */\n")
        fh.write("#include <stdint.h>\n")
        fh.write(f"#define FONT_W {CELL_W}\n#define FONT_H {CELL_H}\n")
        fh.write("static const uint8_t font8x16[128][16] = {\n")
        for rows in glyphs:
            fh.write("  {" + ",".join("0x%02x" % b for b in rows) + "},\n")
        fh.write("};\n#endif\n")
    print(f"genfont: size={size} -> include/font8x16.h")


if __name__ == "__main__":
    main()
