#!/usr/bin/env python3
"""tools/pkgroots/*.pub  ->  c/crypto/trust/pkgroots.inc

The signer keys this machine trusts for .lpk packages, compiled into the kernel
image. See c/crypto/trust/pkgsig.h for WHY they are compiled in rather than read
from /etc/trust: a file on a filesystem with no enforced, reboot-surviving
ownership is writable by exactly the code the signature is meant to constrain.

Input format, one file per signer, named <signer>.pub:

    # optional comment lines
    <64 hex characters>          the raw Ed25519 public key, 32 bytes

That is the whole format. It is deliberately NOT DER/SPKI: the only thing that
can go in here is 32 bytes, so a parser is a place for a bug and not a place for
a feature. To convert an openssl-generated key:

    openssl genpkey -algorithm ED25519 -out signer.pem
    openssl pkey -in signer.pem -pubout -outform DER | tail -c 32 | xxd -p | tr -d '\\n'

(the raw key is the last 32 bytes of the 44-byte DER SPKI -- 12 bytes of
prefix -- which is why `tail -c 32` is exact and not a heuristic.)

    python3 tools/genpkgroots.py tools/pkgroots c/crypto/trust/pkgroots.inc

Refuses on: a bad length, a non-hex character, a duplicate key under two names.
The duplicate check matters -- two names for one key means revoking one of them
does nothing, and it is invisible in a directory listing.
"""

import os
import sys


def load(path):
    key = None
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if key is not None:
            raise SystemExit("%s: more than one key in one file" % path)
        if len(line) != 64:
            raise SystemExit("%s: expected 64 hex characters, got %d" % (path, len(line)))
        try:
            key = bytes.fromhex(line)
        except ValueError:
            raise SystemExit("%s: not hexadecimal" % path)
    if key is None:
        raise SystemExit("%s: no key" % path)
    return key


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: genpkgroots.py <pkgroots-dir> <out.inc>")
    src, out = sys.argv[1], sys.argv[2]

    entries = []
    seen = {}
    names = sorted(f for f in os.listdir(src) if f.endswith(".pub")) if os.path.isdir(src) else []
    for fn in names:
        name = fn[:-4]
        key = load(os.path.join(src, fn))
        if key in seen:
            raise SystemExit("%s and %s are the SAME key under two names -- "
                             "revoking one would do nothing" % (seen[key], name))
        seen[key] = name
        entries.append((name, key))

    lines = []
    lines.append("/* GENERATED by tools/genpkgroots.py from tools/pkgroots/<name>.pub.")
    lines.append(" * Do not edit. Re-run the generator; the Makefile makes pkgsig.o depend")
    lines.append(" * on this file, so a stale copy is a build failure and not a silent")
    lines.append(" * downgrade of the trust set. */")
    lines.append("struct pkg_root { const char *name; uint8_t key[32]; };")
    lines.append("#define PKG_ROOT_N %d" % len(entries))
    if entries:
        lines.append("static const struct pkg_root PKG_ROOTS[PKG_ROOT_N] = {")
        for name, key in entries:
            body = ",".join("0x%02x" % b for b in key)
            lines.append('    { "%s", { %s } },' % (name, body))
        lines.append("};")
    else:
        # An empty array is not valid C. An empty trust set is a legitimate
        # state (a build with no signer configured), and it must mean "trust
        # nothing", not "fail to compile" and not "trust anything".
        lines.append("static const struct pkg_root PKG_ROOTS[1] = { { \"\", { 0 } } };")
    text = "\n".join(lines) + "\n"

    old = None
    if os.path.exists(out):
        old = open(out, encoding="utf-8", newline="").read()
    if old != text:
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    print("pkgroots: %d signer%s -> %s" % (len(entries), "" if len(entries) == 1 else "s", out))
    for name, key in entries:
        print("  %-24s %s" % (name, key.hex()))


if __name__ == "__main__":
    main()
