#!/usr/bin/env python3
"""Generate the UAX #14 line-breaking tables used by c/apps/browser/layout_text.c.

This is the CSS Text line's table, and it is deliberately separate from
c/lib/text/bidi_data.inc (UAX #9, generated by tests/unit/bidi_gen.py): that one
is a kernel-side shaping/bidi table, this one is compiled into the ring-3
browser and carries only what line breaking needs.

Sources (Unicode Character Database, installed on the host as /usr/share/unicode):

    LineBreak.txt                        Line_Break         -> the class trie
    extracted/DerivedGeneralCategory.txt General_Category   -> Pi/Pf, and the
                                                               Mn/Mc test that
                                                               resolves SA
    EastAsianWidth.txt                   East_Asian_Width   -> the F/W/H flag
                                                               LB19a and LB30
                                                               are conditioned on
    emoji/emoji-data.txt                 Extended_Pictographic -> LB30b's second
                                                               clause
    UnicodeData.txt                      Simple_{Upper,Lower,Title}case_Mapping
    SpecialCasing.txt                    the unconditional FULL uppercase
                                         mappings (ß -> SS, ﬁ -> FI): both are
                                         `text-transform`, not line breaking,
                                         but they are the same kind of thing --
                                         a Unicode table that must be generated
                                         rather than hand-typed -- and putting
                                         them in a second .inc would mean a
                                         second generator over the same UCD.

The output is c/apps/browser/linebreak_data.inc: two deduplicated two-stage
tries (class, flags) plus the class enum itself, so layout_text.c cannot drift
out of order with the generator -- the enum is emitted here, not written by
hand there.

WHAT IS RESOLVED HERE AND WHAT IS NOT.  UAX #14 LB1 folds six classes into
others.  Two of those foldings are fixed facts about a code point and are done
here, once, at generation time:

    SG -> AL      (surrogates never appear in decoded text at all)
    SA -> CM if General_Category is Mn or Mc, else AL

The other four are *tailorings* -- CSS chooses them, and CSS can choose
differently per element -- so the raw class survives into the table and
lb_resolve() in layout_text.c applies them:

    AI -> AL (default) or ID
    CJ -> NS (`line-break: strict`/normal) or ID (`line-break: loose`)
    XX -> AL
    CB stays CB and is handled by rules LB20/LB31.

Usage: linebreak_gen.py [--ucd /usr/share/unicode] [--out c/apps/browser]
"""
import argparse
import os
import sys

# ------------------------------------------------------------------ classes --

# Every Line_Break value in the UCD, minus the two resolved above (SA, SG).
# The order IS the enum order emitted into the .inc; nothing else depends on it.
CLASSES = [
    "XX",                                  # 0 -- the default, so a zeroed
                                           #      table entry is the safe value
    "AI", "AK", "AL", "AP", "AS", "B2", "BA", "BB", "BK", "CB", "CJ", "CL",
    "CM", "CP", "CR", "EB", "EM", "EX", "GL", "H2", "H3", "HL", "HY", "ID",
    "IN", "IS", "JL", "JT", "JV", "LF", "NL", "NS", "NU", "OP", "PO", "PR",
    "QU", "RI", "SP", "SY", "VF", "VI", "WJ", "ZW", "ZWJ",
]

# Per-code-point flags. These are the conditions UAX #14 states as character
# properties rather than as line-break classes, so they cannot live in the class
# trie: a QU that is also Pi behaves differently from one that is not.
FLAGS = [
    ("LBF_PI", 1, "General_Category = Pi   -- LB15a, LB19"),
    ("LBF_PF", 2, "General_Category = Pf   -- LB15b, LB19"),
    ("LBF_EA", 4, "East_Asian_Width in F/W/H -- LB19a, LB30"),
    ("LBF_EXTPICT_CN", 8, "Extended_Pictographic and unassigned -- LB30b"),
]

# ------------------------------------------------------------------ parsing --

def parse_ranges(path, defaults=None):
    """Yield (first, last, value) from a UCD @-style property file."""
    out = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("# @missing:") and defaults is not None:
                body = line.split(":", 1)[1].strip()
                rng, val = body.split(";")[0].strip(), body.split(";")[1].strip()
                lo, hi = (rng.split("..") + [rng])[:2]
                defaults.append((int(lo, 16), int(hi, 16), val))
                continue
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = [p.strip() for p in line.split(";")]
            rng = parts[0]
            lo, hi = (rng.split("..") + [rng])[:2]
            out.append((int(lo, 16), int(hi, 16), parts[1]))
    return out


def flatten(ranges, defaults, fallback):
    """Flatten (lo, hi, value) ranges over the whole code space."""
    arr = [fallback] * 0x110000
    for lo, hi, val in defaults or []:
        for cp in range(lo, min(hi, 0x10FFFF) + 1):
            arr[cp] = val
    for lo, hi, val in ranges:
        for cp in range(lo, min(hi, 0x10FFFF) + 1):
            arr[cp] = val
    return arr


# -------------------------------------------------------------------- tries --

BLOCK = 256


def make_trie(arr):
    stage2, seen, stage1 = [], {}, []
    for base in range(0, 0x110000, BLOCK):
        blk = tuple(arr[base:base + BLOCK])
        i = seen.get(blk)
        if i is None:
            i = len(stage2) // BLOCK
            seen[blk] = i
            stage2.extend(blk)
        stage1.append(i)
    return stage1, stage2


def emit_trie(fh, name, stage1, stage2):
    assert max(stage1) < 65536, "stage1 overflowed uint16"
    assert max(stage2) < 256, "stage2 overflowed uint8"
    fh.write("static const uint16_t %s_s1[%d] = {\n" % (name, len(stage1)))
    for i in range(0, len(stage1), 16):
        fh.write("    " + ",".join(str(v) for v in stage1[i:i + 16]) + ",\n")
    fh.write("};\n")
    fh.write("static const uint8_t %s_s2[%d] = {\n" % (name, len(stage2)))
    for i in range(0, len(stage2), 32):
        fh.write("    " + ",".join(str(v) for v in stage2[i:i + 32]) + ",\n")
    fh.write("};\n\n")


def trie_bytes(s1, s2):
    return len(s1) * 2 + len(s2)


# ------------------------------------------------------------------- output --

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ucd", default="/usr/share/unicode")
    ap.add_argument("--out", default="c/apps/browser")
    a = ap.parse_args()
    if not os.path.isdir(a.ucd):
        sys.exit("no UCD at %s" % a.ucd)

    # --- General_Category first: SA's resolution and Pi/Pf both need it.
    gcd = []
    gc = flatten(parse_ranges(os.path.join(a.ucd, "extracted",
                                           "DerivedGeneralCategory.txt"), gcd),
                 gcd, "Cn")

    # --- Line_Break, with LB1's two non-tailorable foldings applied.
    lbd = []
    lb = flatten(parse_ranges(os.path.join(a.ucd, "LineBreak.txt"), lbd),
                 lbd, "XX")
    idx = {n: i for i, n in enumerate(CLASSES)}
    cls = [0] * 0x110000
    nsa = nsg = 0
    for cp in range(0x110000):
        v = lb[cp]
        if v == "SA":
            v = "CM" if gc[cp] in ("Mn", "Mc") else "AL"
            nsa += 1
        elif v == "SG":
            v = "AL"
            nsg += 1
        cls[cp] = idx[v]

    # --- flags.
    ea = flatten(parse_ranges(os.path.join(a.ucd, "EastAsianWidth.txt")), [], "N")
    extpict = set()
    with open(os.path.join(a.ucd, "emoji", "emoji-data.txt"), encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            rng, prop = [p.strip() for p in line.split(";")[:2]]
            if prop != "Extended_Pictographic":
                continue
            lo, hi = (rng.split("..") + [rng])[:2]
            extpict.update(range(int(lo, 16), int(hi, 16) + 1))

    flags = [0] * 0x110000
    for cp in range(0x110000):
        f = 0
        if gc[cp] == "Pi":
            f |= 1
        elif gc[cp] == "Pf":
            f |= 2
        if ea[cp] in ("F", "W", "H"):
            f |= 4
        if cp in extpict and gc[cp] == "Cn":
            f |= 8
        flags[cp] = f

    cs1, cs2 = make_trie(cls)
    fs1, fs2 = make_trie(flags)

    # --- case mappings, for text-transform.
    simple = {"up": [], "lo": [], "ti": []}
    with open(os.path.join(a.ucd, "UnicodeData.txt"), encoding="utf-8") as fh:
        for line in fh:
            f = [p.strip() for p in line.split(";")]
            if len(f) < 15:
                continue
            cp = int(f[0], 16)
            for key, col in (("up", 12), ("lo", 13), ("ti", 14)):
                if f[col]:
                    m = int(f[col], 16)
                    if m != cp:
                        simple[key].append((cp, m))
    # Titlecase differs from uppercase for only ~30 code points (the Latin
    # digraphs Ǆ/ǅ/ǆ and friends); emit only the difference so `capitalize`
    # can fall back to the uppercase table.
    upmap = dict(simple["up"])
    simple["ti"] = [(c, m) for c, m in simple["ti"] if upmap.get(c) != m]

    # SpecialCasing's UNCONDITIONAL full uppercase mappings only. A line with a
    # 5th field is conditional (locale or context) -- Turkish dotless i and
    # Lithuanian's retained dot live there, and both need a language we do not
    # have, so they are skipped here and said out loud in layout_text.h.
    full_up = []
    with open(os.path.join(a.ucd, "SpecialCasing.txt"), encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            f = [p.strip() for p in line.split(";")]
            if len(f) > 4 and f[4]:
                continue                    # conditional -- not ours
            cp = int(f[0], 16)
            up = [int(x, 16) for x in f[3].split()] if f[3] else []
            if len(up) > 1:
                full_up.append((cp, up[:3]))
    full_up.sort()

    path = os.path.join(a.out, "linebreak_data.inc")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("/* GENERATED by tools/linebreak_gen.py -- do not edit.\n"
                 " * Line_Break (UAX #14) with LB1's SA/SG foldings applied, plus the\n"
                 " * Pi/Pf/East_Asian_Width/Extended_Pictographic flags the rules test\n"
                 " * separately from the class.  Unicode %s. */\n\n"
                 % ucd_version(a.ucd))
        fh.write("enum {\n")
        for i, n in enumerate(CLASSES):
            fh.write("    LB_%s = %d,\n" % (n, i))
        fh.write("    LB_COUNT = %d\n};\n\n" % len(CLASSES))
        for name, bit, why in FLAGS:
            fh.write("#define %-16s %du  /* %s */\n" % (name, bit, why))
        fh.write("\n")
        fh.write("static const char *const lb_class_names[LB_COUNT] = {\n    ")
        fh.write(", ".join('"%s"' % n for n in CLASSES))
        fh.write("\n};\n\n")
        emit_trie(fh, "lb_cls", cs1, cs2)
        emit_trie(fh, "lb_flg", fs1, fs2)
        fh.write("/* Simple case mappings (UnicodeData.txt fields 12/13/14),\n"
                 " * sorted by code point for binary search. `title` holds only\n"
                 " * the entries where titlecase differs from uppercase. */\n")
        fh.write("struct lb_casemap { uint32_t cp, to; };\n")
        for key, name in (("up", "lb_upper"), ("lo", "lb_lower"),
                          ("ti", "lb_title")):
            ents = sorted(simple[key])
            fh.write("static const struct lb_casemap %s[%d] = {\n"
                     % (name, len(ents)))
            for i in range(0, len(ents), 4):
                fh.write("    " + " ".join("{0x%X,0x%X}," % e
                                           for e in ents[i:i + 4]) + "\n")
            fh.write("};\n")
        fh.write("\n/* Unconditional full uppercase mappings (SpecialCasing.txt):\n"
                 " * one code point becomes two or three. */\n")
        fh.write("struct lb_fullcase { uint32_t cp; uint32_t to[3]; };\n")
        fh.write("static const struct lb_fullcase lb_upper_full[%d] = {\n"
                 % len(full_up))
        for cp, up in full_up:
            up = up + [0] * (3 - len(up))
            fh.write("    {0x%X,{0x%X,0x%X,0x%X}},\n"
                     % (cp, up[0], up[1], up[2]))
        fh.write("};\n")
    print("linebreak_data.inc: class trie %d bytes, flag trie %d bytes, "
          "%d/%d/%d simple case maps, %d full uppercase maps "
          "(%d SA and %d SG folded at generation time)"
          % (trie_bytes(cs1, cs2), trie_bytes(fs1, fs2),
             len(simple["up"]), len(simple["lo"]), len(simple["ti"]),
             len(full_up), nsa, nsg))


def ucd_version(ucd):
    """The UCD's own version string, read from LineBreak.txt's first line."""
    with open(os.path.join(ucd, "LineBreak.txt"), encoding="utf-8") as fh:
        first = fh.readline().strip()
    # "# LineBreak-16.0.0.txt"
    if "-" in first and first.endswith(".txt"):
        return first.split("-", 1)[1][:-4]
    return "unknown"


if __name__ == "__main__":
    main()
