#!/usr/bin/env python3
"""tools/lmcorpus.py -- build the LOGITLM training corpus out of c/.

    python3 tools/lmcorpus.py --out build/corpus-c.txt

Writes ONE byte stream plus a manifest (`<out>.manifest`) naming every file
that went into it and the exact byte range it occupies.  Nothing here is
random and nothing depends on the filesystem, so the corpus is a function of
the repository: two clones on two machines produce byte-identical output, and
when somebody questions a bits/byte number six months from now the bytes it
was measured on are recoverable by re-running this.

WHY A TOOL AND NOT A `cat`.  A blob somebody made once cannot be audited.  The
number this corpus produces is compared against gzip on a named byte range,
and "the tail of the file I had" is not a byte range anybody else can
reconstruct.

---------------------------------------------------------------------------
THE FOUR DECISIONS, and each one changes the number:

(1) FILE ORDER IS SORTED, BY POSIX PATH.  `os.walk` hands back directory
    entries in whatever order the filesystem stored them, so concatenating in
    walk order makes the corpus -- and therefore the train/val split, and
    therefore every bits/byte in the report -- a property of the disk.  Sorted
    on the UTF-8 bytes of the '/'-joined relative path, not the locale (a
    locale-aware sort orders '_' against letters differently on two machines).
    The ONE exception is the held-out subsystem, moved to the end; see (4).

(2) EACH FILE GETS A ONE-LINE PATH HEADER, "==== c/fs/logitfs.c ====".
    Argued both ways, and it is IN:
      FOR -- it is a document boundary the model can see.  Without it, the
        last line of c/crypto/rsa.c is followed by the first line of
        c/drivers/block/ahci.c and the model is charged full price for a topic
        switch that nothing in its input announced.  It also makes the model
        promptable BY PATH, which is a genuinely useful thing to be able to do
        with a model trained on one repository.
      AGAINST -- it is 632 instances of a pattern the model learns almost
        perfectly, and near-zero-loss bytes pull the average down.
      THE COST IS MEASURED, NOT ARGUED: the tool prints header bytes as a
        fraction of the corpus.  632 headers averaging ~34 B is ~21 KB of
        9.9 MB = 0.22%, and inside the held-out block it is 23 headers of
        284 KB = 0.28%.  Even if every header byte were free that is worth
        about 0.006 bits/byte, two orders below the gap being measured.  And
        gzip is handed the identical bytes, headers included, so it gets the
        same gift.

(3) EXCLUSIONS.  Three rules, and the tool reports every file each one drops:
      - `third_party/`, pruned from the walk.  Not our code.  (There is none
        under c/ today; the rule is here so that adding a vendored directory
        under c/ does not silently start training the model on somebody
        else's style.)
      - `*.inc`.  Every one of them in this tree was written by a generator
        (roots_bundle.inc, html_entities.inc, linebreak_data.inc, the libcss
        codegen).  This falls out of taking only *.c and *.h, and is stated
        rather than left implicit because "we only take .c and .h" and "we
        exclude generated tables" are different rules that happen to agree.
      - GENERATED TABLES THAT ARE NAMED .c OR .h.  Detected two independent
        ways, because either alone is wrong:
          (a) a SELF-DECLARATION in the first 400 bytes: a generator word
              (GENERATED / generated by / auto-generated) AND either "do not
              edit" or the file's own basename.  Both halves are load-bearing
              and the second was added after the first shipped a wrong answer.
              A whole-file grep for the generator word alone matches four
              files that merely MENTION a generator in a comment about
              something else (js_cssom.c, fb.c, script.h, x509.c); restricting
              it to the first 400 bytes still matched three more that describe
              a generated file OTHER than themselves -- as_native.c ("the
              generated fsroot/as/lib/abi.as"), pkgsig.c and roots.c (both
              name the .inc they include).  Those three are 30 KB of the best
              hand-written prose in the tree and dropping them would have been
              a silent 0.3% mis-sample.  Requiring the file to say the words
              ABOUT ITSELF separates all of them: the two real table headers
              open with "<basename> -- GENERATED by ... Do not edit by hand".
          (b) digit-and-comma density >= 0.50 over non-whitespace bytes.
              Measured on this tree the distribution is bimodal with nothing
              in the gap: the four table files score 0.886 / 0.805 / 0.620 /
              0.542 and the next file down is sha384.c at 0.281, which is a
              hash's round constants inside real code.  (b) is what catches
              h264_cabac_tables.h, whose marker sits at line 30.
    A model that reproduces a machine-generated table has learned nothing, and
    near-zero loss on 149 KB of digits would flatter every number below.

(4) THE HELD-OUT SET IS A WHOLE SUBSYSTEM, MOVED TO THE TAIL.  Default `c/fs`
    -- 23 files, 283,689 B, 2.8% of the corpus.  A random slice would put the
    validation bytes between two files the model trained on, so a model that
    had merely interpolated between its neighbours would score well; holding
    out c/fs asks whether it generalises to code it has never seen.  c/fs is
    the right subsystem for it: it is complete on its own (logitfs + vfs +
    fsck + bcache + ramfs), it is ordinary C in this tree's house style rather
    than a table-heavy or vendored-shaped corner, and its identifiers
    (`logitfs_`, `bcache_`, `lfs_`) barely occur outside it.
    The tail is CONTIGUOUS and its byte range is printed, so `dd` cuts exactly
    those bytes back out and hands them to gzip -- which is the only way the
    model and the compressor are known to be scored on the same bytes.

---------------------------------------------------------------------------
LINE ENDINGS ARE NORMALISED TO LF, and that is not tidiness.  This repository
sets core.autocrlf=true, so what is on the disk depends on the checkout: on
this machine 12 of the 632 files carry CRLF and 620 carry LF, and which 12
depends on which files an editor last saved.  A corpus built from raw bytes is
therefore not reproducible from the repository -- and worse, it teaches a byte
model a coin flip it cannot win (is this line ending CRLF or LF?) while
handing gzip a free byte per line on the CRLF files.  CRLF -> LF; a bare CR is
left alone (there is none).
"""

import argparse
import os
import re
import sys

GEN_WORD = re.compile(rb'GENERATED|generated by|auto-?generated', re.IGNORECASE)
SELF_DECL = re.compile(rb'do not edit', re.IGNORECASE)
HEAD_BYTES = 400
DENSITY_BAR = 0.50

WS = (0x20, 0x09, 0x0a, 0x0d, 0x0b, 0x0c)


def table_density(data):
    """digits+commas as a fraction of non-whitespace bytes."""
    nw = 0
    hits = 0
    for b in data:
        if b in WS:
            continue
        nw += 1
        if 0x30 <= b <= 0x39 or b == 0x2c:
            hits += 1
    return (hits / nw) if nw else 0.0


def collect(root, exts):
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        dirnames[:] = [d for d in dirnames if d != 'third_party']
        for fn in sorted(filenames):
            if fn.endswith(exts):
                out.append(os.path.join(dirpath, fn).replace(os.sep, '/'))
    out.sort(key=lambda s: s.encode('utf-8'))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default='c', help='tree to walk (default c)')
    ap.add_argument('--out', default='build/corpus-c.txt')
    ap.add_argument('--holdout', default='c/fs',
                    help='path prefix moved to the tail and held out '
                         '(default c/fs); pass "" for no holdout')
    ap.add_argument('--also', action='append', default=[],
                    help='an extra tree folded in BEFORE the code, as '
                         'ROOT:EXT -- e.g. --also .:.md for every in-tree '
                         'markdown file. Repeatable.')
    ap.add_argument('--no-headers', action='store_true',
                    help='omit the ==== path ==== lines (see decision 2)')
    args = ap.parse_args()

    files = collect(args.root, ('.c', '.h'))

    dropped = []
    kept = []
    for p in files:
        data = open(p, 'rb').read()
        head = data[:HEAD_BYTES]
        base = os.path.basename(p).encode('utf-8')
        why = None
        if GEN_WORD.search(head) and (SELF_DECL.search(head) or base in head):
            why = 'declares itself generated in first %d B' % HEAD_BYTES
        else:
            d = table_density(data)
            if d >= DENSITY_BAR:
                why = 'digit/comma density %.3f >= %.2f' % (d, DENSITY_BAR)
        (dropped.append((p, len(data), why)) if why else kept.append(p))

    extra = []
    for spec in args.also:
        r, _, e = spec.partition(':')
        for p in collect(r or '.', (e or '.md',)):
            # third_party is pruned by collect(); skip anything already taken
            # from --root so a file cannot be counted twice.
            if p.startswith(args.root.rstrip('/') + '/'):
                continue
            extra.append(p)

    hold = args.holdout.rstrip('/')

    def held(p):
        return bool(hold) and (p == hold or p.startswith(hold + '/'))

    main_files = [p for p in kept if not held(p)]
    tail_files = [p for p in kept if held(p)]
    if hold and not tail_files:
        sys.stderr.write('lmcorpus: --holdout %s matched no file\n' % hold)
        return 2

    order = extra + main_files + tail_files

    d = os.path.dirname(args.out)
    if d:
        os.makedirs(d, exist_ok=True)
    man = []
    hdr_bytes = 0
    pos = 0
    with open(args.out, 'wb') as f:
        for p in order:
            data = open(p, 'rb').read().replace(b'\r\n', b'\n')
            if data and not data.endswith(b'\n'):
                data += b'\n'
            if args.no_headers:
                blob = data
            else:
                h = b'\n==== ' + p.encode('utf-8') + b' ====\n'
                hdr_bytes += len(h)
                blob = h + data
            f.write(blob)
            man.append((p, pos, len(blob)))
            pos += len(blob)

    total = pos
    tail_set = set(tail_files)
    tail_lo = next((off for p, off, n in man if p in tail_set), None)
    tail_hi = total if tail_lo is not None else None

    with open(args.out + '.manifest', 'w', encoding='utf-8', newline='\n') as mf:
        mf.write('# lmcorpus manifest for %s\n' % args.out)
        mf.write('# total %d bytes, %d files, headers %s\n'
                 % (total, len(order), 'off' if args.no_headers else 'on'))
        if tail_lo is not None:
            mf.write('# HELDOUT %s bytes [%d, %d) = %d\n'
                     % (hold, tail_lo, tail_hi, tail_hi - tail_lo))
        mf.write('# offset       length     path\n')
        for p, off, n in man:
            mf.write('%-12d %-10d %s%s\n'
                     % (off, n, p, '  HELDOUT' if p in tail_set else ''))
        for p, n, why in dropped:
            mf.write('# DROPPED %-10d %s  (%s)\n' % (n, p, why))

    print('lmcorpus: %s' % args.out)
    print('  %d files, %d bytes' % (len(order), total))
    if not args.no_headers:
        print('  path headers: %d bytes (%.2f%% of the corpus)'
              % (hdr_bytes, 100.0 * hdr_bytes / total))
    if extra:
        print('  folded in first: %d extra file(s)' % len(extra))
    print('  dropped %d generated file(s), %d bytes:'
          % (len(dropped), sum(n for _, n, _ in dropped)))
    for p, n, why in dropped:
        print('    %-40s %8d  %s' % (p, n, why))
    if tail_lo is not None:
        print('  HELD OUT: %s, %d files, bytes [%d, %d) = %d (%.2f%%)'
              % (hold, len(tail_files), tail_lo, tail_hi,
                 tail_hi - tail_lo, 100.0 * (tail_hi - tail_lo) / total))
        print('  train range is [0, %d)' % tail_lo)
        print('  cut the held-out bytes back out with:')
        print('    tail -c +%d %s > heldout.bin' % (tail_lo + 1, args.out))
    print('  manifest: %s.manifest' % args.out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
