#!/usr/bin/env python3
"""Subset a CJK + a monospace font down to GB2312 + Latin for the Aqua disk.

Output is plain TrueType (glyf outlines) so kernel/ttf.c can parse it. Source
fonts default to ones bundled with macOS (Heiti SC = sans-serif Simplified
Chinese, Menlo = monospace); both have glyf outlines. These are Apple-
proprietary, so the generated .ttf is .gitignored and regenerated by the build;
for redistribution, point --ui at an SIL-OFL font such as Noto Sans SC (TTF).

Usage: mkfont.py <out_ui.ttf> <out_mono.ttf>
"""
import sys
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options

UI_SRC,   UI_FACE   = "/System/Library/Fonts/STHeiti Medium.ttc", 1   # Heiti SC Medium
MONO_SRC, MONO_FACE = "/System/Library/Fonts/Menlo.ttc",          0   # Menlo Regular

def gb2312_unicodes():
    cps = set()
    for hi in range(0xA1, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                cps.add(ord(bytes([hi, lo]).decode("gb2312")))
            except Exception:
                pass
    return cps

def latin_punct():
    cps = set(range(0x20, 0x7F))                 # ASCII printable
    cps |= set(range(0x3000, 0x3040))            # CJK symbols & punctuation
    cps |= set(range(0xFF00, 0xFFF0))            # fullwidth forms
    cps |= {0x00A0, 0x00B7, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026, 0x2022}
    return cps

def subset(src, face, unicodes, out):
    f = TTFont(src, fontNumber=face)
    opt = Options()
    opt.glyph_names = False
    opt.recalc_bounds = True
    opt.drop_tables += ["GSUB", "GPOS", "GDEF", "morx", "kerx", "feat", "DSIG"]
    opt.name_IDs = []
    ss = Subsetter(options=opt)
    ss.populate(unicodes=sorted(unicodes))
    ss.subset(f)
    if "glyf" not in f:
        sys.exit(f"ERROR: {src} face {face} is not glyf-based (CFF/OTF unsupported)")
    f.save(out)
    return out

def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    out_ui, out_mono = sys.argv[1], sys.argv[2]
    ui_set = gb2312_unicodes() | latin_punct()
    subset(UI_SRC, UI_FACE, ui_set, out_ui)
    subset(MONO_SRC, MONO_FACE, set(range(0x20, 0x7F)) | {0x00A0}, out_mono)
    import os
    print(f"ui:   {out_ui}  {os.path.getsize(out_ui)//1024} KiB  ({len(ui_set)} codepoints)",
          file=sys.stderr)
    print(f"mono: {out_mono}  {os.path.getsize(out_mono)//1024} KiB", file=sys.stderr)

if __name__ == "__main__":
    main()
