#!/usr/bin/env python3
"""Regenerate tests/unit/wasm_js_modules.inc from tests/fixtures/wasmjs/*.wat.

WHY THE BYTES ARE CHECKED IN AT ALL, given that the .wat next to them is the
real source.  CLAUDE.md rule 5, applied to a gate rather than to a control: a
property whose only witness is a fetched toolchain stops being tested the day
the fetch fails, quietly, with the gate still green.  wat2wasm comes from the
optional wabt download, so `make test-wasm-js` would silently become a no-op on
a machine that never ran `make wasm-fetch`.  Embedding the assembled bytes
makes the JavaScript API gate run with no downloads at all.

AND THAT IS ONLY SAFE BECAUSE THE PAIR IS CHECKED.  A checked-in binary blob
whose stated source nobody re-derives is a comment, not a fact.  `--check`
re-assembles every .wat and compares byte for byte, so an edit to a .wat that
was not regenerated -- or a hand edit of the .inc -- is a failure rather than a
divergence nobody notices.  It is the same shape as tools/gen_as_opcodes.py.

    tools/wasm_js_modules.py --write   regenerate the .inc
    tools/wasm_js_modules.py --check   re-derive and diff; nonzero on a mismatch

Both need wat2wasm; without it --check SKIPS LOUDLY (naming the command that
would settle it) rather than passing, because a check that cannot run is not a
check that passed.
"""
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FIX = os.path.join(ROOT, "tests", "fixtures", "wasmjs")
OUT = os.path.join(ROOT, "tests", "unit", "wasm_js_modules.inc")

CANDIDATES = [
    os.path.join(ROOT, "build", "wasm", "wabt", "bin", "wat2wasm"),
    "/opt/homebrew/opt/wabt/bin/wat2wasm",
    "/usr/local/opt/wabt/bin/wat2wasm",
]


def find_wat2wasm():
    env = os.environ.get("WAT2WASM")
    if env and os.path.exists(env):
        return env
    for c in CANDIDATES:
        if os.path.exists(c) and os.access(c, os.X_OK):
            return c
    return None


def render(w2w):
    out = []
    out.append("/* GENERATED by tools/wasm_js_modules.py from "
               "tests/fixtures/wasmjs/*.wat.")
    out.append(" *")
    out.append(" * DO NOT EDIT.  The .wat files are the source; these bytes are")
    out.append(" * checked in so that the JavaScript API gate runs with no wabt")
    out.append(" * download, and `tools/wasm_js_modules.py --check` re-derives")
    out.append(" * them so that the pair cannot drift in silence. */")
    for path in sorted(glob.glob(os.path.join(FIX, "*.wat"))):
        name = os.path.basename(path)[:-4]
        wasm = path[:-4] + ".wasm.tmp"
        r = subprocess.run([w2w, path, "-o", wasm],
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write("wasm_js_modules: wat2wasm failed on %s:\n%s\n"
                             % (path, r.stderr))
            return None
        with open(wasm, "rb") as fh:
            b = fh.read()
        os.unlink(wasm)
        with open(path) as fh:
            wat = fh.read().strip()
        out.append("")
        out.append("/* %s.wat:" % name)
        for line in wat.splitlines():
            out.append("   " + line)
        out.append(" */")
        out.append("static const unsigned char W_%s[] = {" % name[2:])
        for i in range(0, len(b), 12):
            out.append("\t" + ", ".join("0x%02x" % c for c in b[i:i + 12]) + ",")
        out.append("};")
    return "\n".join(out) + "\n"


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    w2w = find_wat2wasm()
    if not w2w:
        print("wasm_js_modules: SKIPPED -- no wat2wasm.")
        print("  The embedded bytes in tests/unit/wasm_js_modules.inc cannot be")
        print("  re-derived without it, so this check did NOT run.  Settle it")
        print("  with:   make wasm-fetch      (or: brew install wabt)")
        return 0
    text = render(w2w)
    if text is None:
        return 1
    if mode == "--write":
        with open(OUT, "w") as fh:
            fh.write(text)
        print("wasm_js_modules: wrote %s (%d bytes)" % (OUT, len(text)))
        return 0
    try:
        with open(OUT) as fh:
            have = fh.read()
    except OSError:
        print("wasm_js_modules: %s is absent -- run --write" % OUT)
        return 1
    if have != text:
        print("wasm_js_modules: MISMATCH -- tests/unit/wasm_js_modules.inc does")
        print("  not match tests/fixtures/wasmjs/*.wat reassembled.  Either a")
        print("  .wat changed without regenerating, or the .inc was hand-edited.")
        print("  Settle it with:   tools/wasm_js_modules.py --write")
        return 1
    print("wasm_js_modules: .inc matches the .wat sources reassembled")
    return 0


if __name__ == "__main__":
    sys.exit(main())
