# GENERATED by tools/gen_abi.py from include/abi/logit_abi.h -- DO NOT EDIT.
#
# The kernel's structs, as AetherScript layouts. `t = Time()` allocates one the
# collector owns; `addr(t)` is exactly the pointer a syscall expects; `t.hour`
# reads the field at the offset below.
#
# These offsets are not this file's opinion of the layout. Each one is also
# emitted as a _Static_assert in c/apps/as/abi_layout.inc, which as_native.c
# includes -- so the compiler that builds /bin/as checks every number here
# against the real struct, and a kernel that reorders a field breaks the build
# instead of leaving a script reading the wrong bytes.
#
# The call wrappers below come from include/abi/logit_calls.abi, which is the one
# place the calling convention is written: the same field positions generate the
# kernel-side unpack macros in include/abi/logit_pack.h. `(x << 16) | y` used to
# live in a header comment, in gui.as, and in wm.c -- three copies of a rule
# nothing checked.
#
# Regenerate:  python3 tools/gen_abi.py --write
# Verify:      make check-abi


Event = layout("logit_event", 24, [
    ["type", 0, 4, "i"],
    ["a", 4, 4, "i"],
    ["b", 8, 4, "i"],
    ["mods", 12, 4, "i"],
    ["button", 16, 4, "i"],
    ["wheel", 20, 4, "i"]
])

Time = layout("logit_time", 28, [
    ["year", 0, 4, "i"],
    ["month", 4, 4, "i"],
    ["day", 8, 4, "i"],
    ["hour", 12, 4, "i"],
    ["minute", 16, 4, "i"],
    ["second", 20, 4, "i"],
    ["weekday", 24, 4, "i"]
])

Netinfo = layout("logit_netinfo", 20, [
    ["ip", 0, 4, "u"],
    ["mask", 4, 4, "u"],
    ["gw", 8, 4, "u"],
    ["mac", 12, 6, "s"]
])

Run = layout("logit_run", 40, [
    ["x", 0, 4, "i"],
    ["y", 4, 4, "i"],
    ["px", 8, 4, "i"],
    ["mono", 12, 4, "i"],
    ["color", 16, 4, "u"],
    ["s", 24, 8, "p"],
    ["len", 32, 4, "i"]
])

Blit = layout("logit_blit", 32, [
    ["x", 0, 4, "i"],
    ["y", 4, 4, "i"],
    ["w", 8, 4, "i"],
    ["h", 12, 4, "i"],
    ["rgba", 16, 8, "p"],
    ["sw", 24, 4, "i"],
    ["sh", 28, 4, "i"]
])

Imgreq = layout("logit_imgreq", 32, [
    ["path", 0, 8, "p"],
    ["rgba", 8, 8, "p"],
    ["max", 16, 4, "i"],
    ["w", 20, 4, "i"],
    ["h", 24, 4, "i"]
])

Timespec = layout("logit_timespec", 16, [
    ["tv_sec", 0, 8, "i"],
    ["tv_nsec", 8, 8, "i"]
])

Clockinfo = layout("logit_clockinfo", 104, [
    ["source", 0, 4, "i"],
    ["nsources", 4, 4, "i"],
    ["hz", 8, 8, "u"],
    ["res_ns", 16, 8, "u"],
    ["mono_ns", 24, 8, "u"],
    ["real_ns", 32, 8, "u"],
    ["reads", 40, 8, "u"],
    ["backsteps", 48, 8, "u"],
    ["backstep_max_ns", 56, 8, "u"],
    ["timers_queued", 64, 8, "u"],
    ["timers_fired", 72, 8, "u"],
    ["cores_seen", 80, 4, "u"],
    ["name", 84, 16, "s"]
])

Sndfmt = layout("logit_sndfmt", 16, [
    ["rate", 0, 4, "u"],
    ["channels", 4, 2, "u"],
    ["format", 6, 2, "u"],
    ["buffer_ms", 8, 4, "u"],
    ["flags", 12, 4, "u"]
])

Sndinfo = layout("logit_sndinfo", 80, [
    ["driver", 0, 16, "s"],
    ["codec", 16, 32, "s"],
    ["rate", 48, 4, "u"],
    ["channels", 52, 2, "u"],
    ["format", 54, 2, "u"],
    ["period_bytes", 56, 4, "u"],
    ["periods", 60, 4, "u"],
    ["streams_max", 64, 4, "u"],
    ["streams_open", 68, 4, "u"],
    ["underruns", 72, 4, "u"],
    ["irq_mode", 76, 4, "u"]
])

Sndstate = layout("logit_sndstate", 32, [
    ["frames_written", 0, 8, "u"],
    ["frames_played", 8, 8, "u"],
    ["avail_bytes", 16, 4, "u"],
    ["ring_bytes", 20, 4, "u"],
    ["underruns", 24, 4, "u"],
    ["state", 28, 4, "u"]
])

Meminfo = layout("logit_meminfo", 104, [
    ["frame_bytes", 0, 8, "u"],
    ["frames_total", 8, 8, "u"],
    ["frames_free", 16, 8, "u"],
    ["frames_used", 24, 8, "u"],
    ["frames_shared", 32, 8, "u"],
    ["refs_total", 40, 8, "u"],
    ["frames_pinned", 48, 8, "u"],
    ["cow_pages", 56, 8, "u"],
    ["cow_faults", 64, 8, "u"],
    ["cow_reuse", 72, 8, "u"],
    ["anon_faults", 80, 8, "u"],
    ["mm_bugs", 88, 8, "u"],
    ["mmap_reserved", 96, 8, "u"]
])

# ---- calls (include/abi/logit_calls.abi) ----

def gui_create(title, w, h):
    return syscall(SYS_GUI_CREATE, addr(title), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)))

def gui_clear(color):
    return syscall(SYS_GUI_CLEAR, color)

def gui_rect(x, y, w, h, color):
    return syscall(SYS_GUI_RECT, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)), color)

def gui_text(x, y, color, s):
    return syscall(SYS_GUI_TEXT, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), color, addr(s))

def gui_text_mono(x, y, cell, color, s):
    return syscall(SYS_GUI_TEXT_MONO, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((cell & 0xFF) << 24) | ((color & 0xFFFFFF)), addr(s))

def gui_icon(x, y, id, px, color):
    return syscall(SYS_GUI_ICON, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((id & 0xFFFF) << 16) | ((px & 0xFFFF)), color)

def gui_rrect(x, y, w, h, radius, color):
    return syscall(SYS_GUI_RRECT, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)), ((radius & 0xFF) << 24) | ((color & 0xFFFFFF)))

def gui_glass(x, y, w, h, radius, tr, tg, tb, ta):
    return syscall(SYS_GUI_GLASS, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)), ((radius & 0xFF) << 32) | ((tr & 0xFF) << 24) | ((tg & 0xFF) << 16) | ((tb & 0xFF) << 8) | ((ta & 0xFF)))

def gui_clip(x, y, w, h):
    return syscall(SYS_GUI_CLIP, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)))

def gui_flush():
    return syscall(SYS_GUI_FLUSH)

def gui_win_min(w, h):
    return syscall(SYS_GUI_WIN_MIN, ((w & 0xFFFF) << 16) | ((h & 0xFFFF)))

def gui_win_state(what, arg):
    return syscall(SYS_GUI_WIN_STATE, what, arg)

def gui_poll_event(ev):
    return syscall(SYS_POLL_EVENT, addr(ev))

def ui_dark_query():
    return syscall(SYS_UI_DARK, -1)

def ui_dark_set(on):
    return syscall(SYS_UI_DARK, on)

def sys_yield():
    return syscall(SYS_YIELD)

def get_time(t):
    return syscall(SYS_GET_TIME, addr(t))

def monotonic_ms():
    return syscall(SYS_MONOTONIC_MS)

def io_write(fd, b, len):
    return syscall(SYS_WRITE, fd, addr(b), len)

def proc_exit(code):
    return syscall(SYS_EXIT, code)

def get_arg(b, max):
    return syscall(SYS_GET_ARG, addr(b), max)

def sysinfo(b, max):
    return syscall(SYS_SYSINFO, addr(b), max)

def file_read(path, b, max):
    return syscall(SYS_READ_FILE, addr(path), addr(b), max)

def file_count():
    return syscall(SYS_FILE_COUNT)

def file_name(i, b, max):
    return syscall(SYS_FILE_NAME, i, addr(b), max)

def file_write(path, b, size):
    return syscall(SYS_WRITE_FILE, addr(path), addr(b), size)

def file_delete(path):
    return syscall(SYS_DELETE_FILE, addr(path))

def file_rename(old, new):
    return syscall(SYS_RENAME, addr(old), addr(new))

def dir_make(path):
    return syscall(SYS_MKDIR, addr(path))

def dir_count(dir):
    return syscall(SYS_DIR_COUNT, addr(dir))

def dir_name(dir, i, b):
    return syscall(SYS_DIR_NAME, addr(dir), i, addr(b))

def getcwd(b, max):
    return syscall(SYS_GETCWD, addr(b), max)

def chdir(path):
    return syscall(SYS_CHDIR, addr(path))

def proc_fork():
    return syscall(SYS_FORK)

def proc_execve(path, argv, envp):
    return syscall(SYS_EXECVE, addr(path), addr(argv), envp)

def proc_waitpid(pid, st, opts):
    return syscall(SYS_WAITPID, pid, addr(st), opts)

def proc_pid():
    return syscall(SYS_GETPID)

def proc_spawn(path, argv):
    return syscall(SYS_SPAWN, addr(path), addr(argv))

def fd_open(path, flags):
    return syscall(SYS_OPEN, addr(path), flags)

def fd_close(fd):
    return syscall(SYS_CLOSE, fd)

def fd_read(fd, b, len):
    return syscall(SYS_READ, fd, addr(b), len)

def fd_lseek(fd, off, whence):
    return syscall(SYS_LSEEK, fd, off, whence)

def fd_dup(fd):
    return syscall(SYS_DUP, fd)

def fd_dup2(oldfd, newfd):
    return syscall(SYS_DUP2, oldfd, newfd)

def fd_pipe(fds):
    return syscall(SYS_PIPE, addr(fds))

def fd_setnb(fd):
    return syscall(SYS_SETNB, fd)

def fd_fsync(fd):
    return syscall(SYS_FSYNC, fd)

def open_path(path):
    return syscall(SYS_OPEN_PATH, addr(path))

def net_info(ni):
    return syscall(SYS_NET_INFO, addr(ni))

def sock_open(host, port, flags):
    return syscall(SYS_SOCK_OPEN, addr(host), ((port & 0xFFFF) << 16) | ((flags & 0xFFFF)))

def sock_poll(fd):
    return syscall(SYS_SOCK_POLL, fd)

def sock_send(fd, b, len):
    return syscall(SYS_SOCK_SEND, fd, addr(b), len)

def sock_recv(fd, b, max):
    return syscall(SYS_SOCK_RECV, fd, addr(b), max)

def sock_alpn(fd, b, max):
    return syscall(SYS_SOCK_ALPN, fd, addr(b), max)

def sock_close(fd):
    return syscall(SYS_SOCK_CLOSE, fd)

def http_body(b, max):
    return syscall(SYS_HTTP_BODY, addr(b), max)

def res_fetch(src, b, max):
    return syscall(SYS_RES_FETCH, addr(src), addr(b), max)

def text_measure(s, len, px, mono):
    return syscall(SYS_TEXT_MEASURE, addr(s), len, ((px & 0x7FFFFFFF) << 1) | ((mono & 0x1)))

def gui_text_run(run):
    return syscall(SYS_GUI_TEXT_RUN, addr(run))

def gui_blit(blit):
    return syscall(SYS_GUI_BLIT, addr(blit))

def img_decode(req):
    return syscall(SYS_IMG_DECODE, addr(req))

def cpu_index():
    return syscall(SYS_CPU_INDEX)

def kheap_stress(iters, size, seed):
    return syscall(SYS_KHEAP_STRESS, iters, size, seed)

# ---- waiting ----
# Logit exposes these as start + poll: there is no in-kernel wait queue for them,
# so the caller spins and yields. Each call site used to write that loop itself,
# with its own retry count, and answer the same value for "failed" and "gave up".

_wait_t = Time()

# Seconds since midnight, off the RTC -- the WALL clock, hence the midnight
# wrap fixup below. monotonic_ms() exists now and is the better clock for an
# interval, but this loop deliberately stays on the wall clock: the host test
# (make test-as) runs the real abi.as with syscalls stubbed to -1, where a
# monotonic reading is a CONSTANT -1 and "now - start" never reaches the
# timeout -- the wait would hang instead of failing. A timeout loop has to
# still terminate when its clock is broken.
def now_s():
    get_time(_wait_t)
    return (_wait_t.hour * 60 + _wait_t.minute) * 60 + _wait_t.second

# The deadline is real seconds, not a retry count -- a count means a different
# amount of time on every machine and every load. The three outcomes stay
# distinct: a value is returned, a failure raises, a timeout raises something
# else. Conflating the last two is what made sys.dns() answer 0 both when a name
# did not resolve and when the loop simply ran out.
def await_(poll, pending_neg, pending_val, has_fail, fail_neg, fail_val, timeout_s, label):
    start = now_s()
    while true:
        v = poll()
        pending = v < 0 if pending_neg else v == pending_val
        if not pending:
            failed = false
            if has_fail:
                failed = v < 0 if fail_neg else v == fail_val
            if failed:
                raise label + ": failed"
            return v
        now = now_s()
        if now < start:
            now = now + 86400            # the RTC clock wrapped past midnight
        if now - start >= timeout_s:
            raise label + ": timed out after " + str(timeout_s) + "s"
        sys_yield()

def dns_start(name):
    return syscall(SYS_NET_DNS, addr(name))

def dns_poll():
    return syscall(SYS_NET_DNS_RESULT)

def wait_dns(name, timeout_s):
    if dns_start(name) < 0:
        raise "dns: cannot start"
    return await_(dns_poll, false, 0, true, false, 4294967295, timeout_s, "dns")

def ping_start(ip):
    return syscall(SYS_NET_PING, ip)

def ping_poll():
    return syscall(SYS_NET_PING_RTT)

def wait_ping(ip, timeout_s):
    if ping_start(ip) < 0:
        raise "ping: cannot start"
    return await_(ping_poll, true, 0, false, false, 0, timeout_s, "ping")

def http_start(url):
    return syscall(SYS_HTTP_GET, addr(url))

def http_poll():
    return syscall(SYS_HTTP_STATUS)

def wait_http(url, timeout_s):
    if http_start(url) < 0:
        raise "http: cannot start"
    return await_(http_poll, false, 1, true, true, 0, timeout_s, "http")
