# aether: 3.0
# GENERATED by tools/gen_abi.py from include/abi/logit_abi.h -- DO NOT EDIT.
#
# The kernel's structs, as AetherScript layouts. `t = Time()` allocates one the
# collector owns; `addr(t)` is exactly the pointer a syscall expects; `t.hour`
# reads the field at the offset below.
#
# Native correction: fixed fields carry static widths; s fields return Bytes.
# Wrappers validate byte extents and writable storage, and copy str arguments
# with a trailing NUL. Raw pointer fields/argv pointees retain explicit lifetime
# obligations. This module requires LogitOS plus the actual kernel capabilities.
#
# These offsets are not this file's opinion of the layout. Each one is also
# emitted as a _Static_assert in c/apps/as/sema/abi_layout.inc, which sema/constants.c
# includes -- so the compiler that builds /bin/as checks every number here
# against the real struct, and a kernel that reorders a field breaks the build
# instead of leaving a script reading the wrong bytes.
#
# The call wrappers below come from include/abi/logit_calls.abi, which is the one
# place the calling convention is written: the same field positions generate the
# kernel-side unpack macros in include/abi/logit_pack.h. `(x << 16) | y` used to
# live in a header comment, in gui.as, and in wm.c -- three copies of a rule
# nothing checked.
#
# Regenerate:  python3 tools/gen_abi.py --write
# Verify:      make check-abi


Event = layout("logit_event", 24, [
    ["type", 0, 4, "i"],
    ["a", 4, 4, "i"],
    ["b", 8, 4, "i"],
    ["mods", 12, 4, "i"],
    ["button", 16, 4, "i"],
    ["wheel", 20, 4, "i"]
])

Time = layout("logit_time", 28, [
    ["year", 0, 4, "i"],
    ["month", 4, 4, "i"],
    ["day", 8, 4, "i"],
    ["hour", 12, 4, "i"],
    ["minute", 16, 4, "i"],
    ["second", 20, 4, "i"],
    ["weekday", 24, 4, "i"]
])

Netinfo = layout("logit_netinfo", 20, [
    ["ip", 0, 4, "u"],
    ["mask", 4, 4, "u"],
    ["gw", 8, 4, "u"],
    ["mac", 12, 6, "s"]
])

Run = layout("logit_run", 40, [
    ["x", 0, 4, "i"],
    ["y", 4, 4, "i"],
    ["px", 8, 4, "i"],
    ["mono", 12, 4, "i"],
    ["color", 16, 4, "u"],
    ["s", 24, 8, "p"],
    ["len", 32, 4, "i"],
    ["bold", 36, 4, "i"]
])

Text_metrics = layout("logit_text_metrics", 44, [
    ["scale_percent", 0, 4, "i"],
    ["advance", 4, 4, "i"],
    ["baseline", 8, 4, "i"],
    ["ascent", 12, 4, "i"],
    ["descent", 16, 4, "i"],
    ["line_gap", 20, 4, "i"],
    ["has_ink", 24, 4, "i"],
    ["ink_left", 28, 4, "i"],
    ["ink_top", 32, 4, "i"],
    ["ink_right", 36, 4, "i"],
    ["ink_bottom", 40, 4, "i"]
])

Text_metrics_query = layout("logit_text_metrics_query", 40, [
    ["size", 0, 4, "u"],
    ["version", 4, 4, "u"],
    ["s", 8, 8, "p"],
    ["len", 16, 4, "i"],
    ["px", 20, 4, "i"],
    ["face", 24, 4, "i"],
    ["flags", 28, 4, "i"],
    ["out", 32, 8, "p"]
])

Blit = layout("logit_blit", 32, [
    ["x", 0, 4, "i"],
    ["y", 4, 4, "i"],
    ["w", 8, 4, "i"],
    ["h", 12, 4, "i"],
    ["rgba", 16, 8, "p"],
    ["sw", 24, 4, "i"],
    ["sh", 28, 4, "i"]
])

Imgreq = layout("logit_imgreq", 32, [
    ["path", 0, 8, "p"],
    ["rgba", 8, 8, "p"],
    ["max", 16, 4, "i"],
    ["w", 20, 4, "i"],
    ["h", 24, 4, "i"]
])

Timespec = layout("logit_timespec", 16, [
    ["tv_sec", 0, 8, "i"],
    ["tv_nsec", 8, 8, "i"]
])

Clockinfo = layout("logit_clockinfo", 104, [
    ["source", 0, 4, "i"],
    ["nsources", 4, 4, "i"],
    ["hz", 8, 8, "u"],
    ["res_ns", 16, 8, "u"],
    ["mono_ns", 24, 8, "u"],
    ["real_ns", 32, 8, "u"],
    ["reads", 40, 8, "u"],
    ["backsteps", 48, 8, "u"],
    ["backstep_max_ns", 56, 8, "u"],
    ["timers_queued", 64, 8, "u"],
    ["timers_fired", 72, 8, "u"],
    ["cores_seen", 80, 4, "u"],
    ["name", 84, 16, "s"]
])

Sndfmt = layout("logit_sndfmt", 16, [
    ["rate", 0, 4, "u"],
    ["channels", 4, 2, "u"],
    ["format", 6, 2, "u"],
    ["buffer_ms", 8, 4, "u"],
    ["flags", 12, 4, "u"]
])

Sndinfo = layout("logit_sndinfo", 80, [
    ["driver", 0, 16, "s"],
    ["codec", 16, 32, "s"],
    ["rate", 48, 4, "u"],
    ["channels", 52, 2, "u"],
    ["format", 54, 2, "u"],
    ["period_bytes", 56, 4, "u"],
    ["periods", 60, 4, "u"],
    ["streams_max", 64, 4, "u"],
    ["streams_open", 68, 4, "u"],
    ["underruns", 72, 4, "u"],
    ["irq_mode", 76, 4, "u"]
])

Sndstate = layout("logit_sndstate", 32, [
    ["frames_written", 0, 8, "u"],
    ["frames_played", 8, 8, "u"],
    ["avail_bytes", 16, 4, "u"],
    ["ring_bytes", 20, 4, "u"],
    ["underruns", 24, 4, "u"],
    ["state", 28, 4, "u"]
])

Meminfo = layout("logit_meminfo", 104, [
    ["frame_bytes", 0, 8, "u"],
    ["frames_total", 8, 8, "u"],
    ["frames_free", 16, 8, "u"],
    ["frames_used", 24, 8, "u"],
    ["frames_shared", 32, 8, "u"],
    ["refs_total", 40, 8, "u"],
    ["frames_pinned", 48, 8, "u"],
    ["cow_pages", 56, 8, "u"],
    ["cow_faults", 64, 8, "u"],
    ["cow_reuse", 72, 8, "u"],
    ["anon_faults", 80, 8, "u"],
    ["mm_bugs", 88, 8, "u"],
    ["mmap_reserved", 96, 8, "u"]
])

Mmap_file_req = layout("logit_mmap_file_req", 32, [
    ["hint", 0, 8, "u"],
    ["len", 8, 8, "u"],
    ["off", 16, 8, "u"],
    ["fd", 24, 4, "i"],
    ["prot", 28, 4, "i"]
])

Procinfo = layout("logit_procinfo", 184, [
    ["pid", 0, 4, "i"],
    ["ppid", 4, 4, "i"],
    ["state", 8, 4, "i"],
    ["tid", 12, 4, "i"],
    ["flags", 16, 4, "i"],
    ["nfds", 20, 4, "i"],
    ["name", 24, 32, "s"],
    ["cwd", 56, 128, "s"]
])

Setting = layout("logit_setting", 264, [
    ["key", 0, 48, "s"],
    ["label", 48, 40, "s"],
    ["value", 88, 80, "s"],
    ["dflt", 168, 80, "s"],
    ["type", 248, 4, "i"],
    ["group", 252, 4, "i"],
    ["lo", 256, 4, "i"],
    ["hi", 260, 4, "i"]
])

Thread_spec = layout("logit_thread_spec", 48, [
    ["entry", 0, 8, "u"],
    ["stack_top", 8, 8, "u"],
    ["stack_base", 16, 8, "u"],
    ["stack_len", 24, 8, "u"],
    ["tls", 32, 8, "u"],
    ["arg", 40, 8, "u"]
])

Stat = layout("logit_stat", 120, [
    ["len", 0, 4, "u"],
    ["version", 4, 4, "u"],
    ["mode", 8, 4, "u"],
    ["attr", 12, 4, "u"],
    ["uid", 16, 4, "u"],
    ["gid", 20, 4, "u"],
    ["nlink", 24, 4, "u"],
    ["blksize", 28, 4, "u"],
    ["ino", 32, 8, "u"],
    ["dev", 40, 8, "u"],
    ["size", 48, 8, "u"],
    ["blocks", 56, 8, "u"],
    ["atime", 64, 8, "i"],
    ["mtime", 72, 8, "i"],
    ["ctime", 80, 8, "i"],
    ["volume_0", 88, 8, "u"],
    ["volume_1", 96, 8, "u"],
    ["object_id", 104, 8, "u"],
    ["revision", 112, 8, "u"]
])

Dirent = layout("logit_dirent", 280, [
    ["reclen", 0, 4, "u"],
    ["type", 4, 4, "u"],
    ["ino", 8, 8, "u"],
    ["size", 16, 8, "u"],
    ["name", 24, 256, "s"]
])

Dirreq = layout("logit_dirreq", 32, [
    ["path", 0, 8, "p"],
    ["buf", 8, 8, "p"],
    ["max", 16, 4, "i"],
    ["cursor", 20, 4, "i"],
    ["count", 24, 4, "i"],
    ["pad", 28, 4, "i"]
])

Sigaction = layout("logit_sigaction", 32, [
    ["handler", 0, 8, "u"],
    ["mask", 8, 8, "u"],
    ["flags", 16, 8, "u"],
    ["restorer", 24, 8, "u"]
])

Sigctx = layout("logit_sigctx", 192, [
    ["r15", 0, 8, "u"],
    ["r14", 8, 8, "u"],
    ["r13", 16, 8, "u"],
    ["r12", 24, 8, "u"],
    ["r11", 32, 8, "u"],
    ["r10", 40, 8, "u"],
    ["r9", 48, 8, "u"],
    ["r8", 56, 8, "u"],
    ["rbp", 64, 8, "u"],
    ["rdi", 72, 8, "u"],
    ["rsi", 80, 8, "u"],
    ["rdx", 88, 8, "u"],
    ["rcx", 96, 8, "u"],
    ["rbx", 104, 8, "u"],
    ["rax", 112, 8, "u"],
    ["rip", 120, 8, "u"],
    ["rflags", 128, 8, "u"],
    ["rsp", 136, 8, "u"],
    ["oldmask", 144, 8, "u"],
    ["signo", 152, 8, "u"],
    ["err", 160, 8, "u"],
    ["trapno", 168, 8, "u"],
    ["cr2", 176, 8, "u"],
    ["fpstate", 184, 8, "u"]
])

Sockaddr_un = layout("logit_sockaddr_un", 110, [
    ["family", 0, 2, "u"],
    ["path", 2, 108, "s"]
])

Sockaddr = layout("logit_sockaddr", 8, [
    ["family", 0, 2, "u"],
    ["port", 2, 2, "u"],
    ["addr", 4, 4, "u"]
])

Dgram = layout("logit_dgram", 24, [
    ["buf", 0, 8, "p"],
    ["len", 8, 4, "i"],
    ["flags", 12, 4, "i"],
    ["family", 16, 2, "u"],
    ["port", 18, 2, "u"],
    ["addr", 20, 4, "u"]
])

Capreq = layout("logit_capreq", 72, [
    ["caps", 0, 8, "u"],
    ["prefix", 8, 64, "s"]
])

Ptrace_word = layout("logit_ptrace_word", 16, [
    ["addr", 0, 8, "u"],
    ["data", 8, 8, "u"]
])

Modinfo = layout("logit_modinfo", 48, [
    ["id", 0, 4, "i"],
    ["name", 4, 32, "s"],
    ["size", 36, 4, "u"],
    ["ndrivers", 40, 4, "i"],
    ["nbound", 44, 4, "i"]
])

Pollfd = layout("logit_pollfd", 8, [
    ["fd", 0, 4, "i"],
    ["events", 4, 2, "i"],
    ["revents", 6, 2, "i"]
])

Itimer = layout("logit_itimer", 16, [
    ["value_ms", 0, 8, "i"],
    ["interval_ms", 8, 8, "i"]
])

# ---- native argument ownership ----
# A3 str may be an interior view with no trailing NUL. A named Bytes temporary
# keeps each marshalled argument rooted across later argument allocations.
def _c_string(value: str) -> Bytes:
    if chr(0) in value:
        raise ValueError("C string contains an embedded NUL")
    return Bytes(value + chr(0))

def _check_size[B: ByteStorage](data: B, count: i64) -> None:
    if count < 0 or count > len(data):
        raise ValueError("ABI byte count exceeds backing storage")

def _check_text_size(value: str, count: i64) -> None:
    if count < 0 or count > len(value):
        raise ValueError("ABI byte count exceeds source text")

# argv contains raw addresses. Check its own termination without dereferencing
# those addresses; their pointees must remain live until the kernel has copied
# them. Neither this check nor a p layout field creates hidden GC ownership.
def _check_argv[B: ByteStorage](data: B) -> None:
    if len(data) < 8 or len(data) % 8 != 0:
        raise ValueError("argv requires complete pointer words and a terminator")
    for offset in range(0, len(data), 8):
        zero = true
        for byte in range(8):
            if data[offset + byte] != 0:
                zero = false
        if zero:
            return
    raise ValueError("argv has no NULL terminator")

# ---- calls (include/abi/logit_calls.abi) ----

def gui_create(title: str, w: i64, h: i64) -> i64:
    _c_title = _c_string(title)
    unsafe:
        return syscall(SYS_GUI_CREATE, addr(_c_title), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)))

def gui_clear(color: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_CLEAR, color)

def gui_rect(x: i64, y: i64, w: i64, h: i64, color: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_RECT, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)), color)

def gui_text(x: i64, y: i64, color: i64, s: str) -> i64:
    _c_s = _c_string(s)
    unsafe:
        return syscall(SYS_GUI_TEXT, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), color, addr(_c_s))

def gui_text_mono(x: i64, y: i64, cell: i64, color: i64, s: str) -> i64:
    _c_s = _c_string(s)
    unsafe:
        return syscall(SYS_GUI_TEXT_MONO, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((cell & 0xFF) << 24) | ((color & 0xFFFFFF)), addr(_c_s))

def gui_icon(x: i64, y: i64, id: i64, px: i64, color: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_ICON, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((id & 0xFFFF) << 16) | ((px & 0xFFFF)), color)

def gui_rrect(x: i64, y: i64, w: i64, h: i64, radius: i64, color: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_RRECT, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)), ((radius & 0xFF) << 24) | ((color & 0xFFFFFF)))

def gui_glass(x: i64, y: i64, w: i64, h: i64, radius: i64, tr: i64, tg: i64, tb: i64, ta: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_GLASS, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)), ((radius & 0xFF) << 32) | ((tr & 0xFF) << 24) | ((tg & 0xFF) << 16) | ((tb & 0xFF) << 8) | ((ta & 0xFF)))

def gui_clip(x: i64, y: i64, w: i64, h: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_CLIP, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)))

def gui_flush() -> i64:
    unsafe:
        return syscall(SYS_GUI_FLUSH)

def gui_flush_rect(x: i64, y: i64, w: i64, h: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_FLUSH_RECT, ((x & 0xFFFF) << 16) | ((y & 0xFFFF)), ((w & 0xFFFF) << 16) | ((h & 0xFFFF)))

def gui_win_min(w: i64, h: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_WIN_MIN, ((w & 0xFFFF) << 16) | ((h & 0xFFFF)))

def gui_win_state(what: i64, arg: i64) -> i64:
    unsafe:
        return syscall(SYS_GUI_WIN_STATE, what, arg)

def gui_poll_event(ev: Event) -> i64:
    unsafe:
        return syscall(SYS_POLL_EVENT, addr(ev))

def gui_wait_event(ev: Event, ms: i64) -> i64:
    unsafe:
        return syscall(SYS_WAIT_EVENT, addr(ev), ms)

def ui_dark_query() -> i64:
    unsafe:
        return syscall(SYS_UI_DARK, -1)

def ui_dark_set(on: i64) -> i64:
    unsafe:
        return syscall(SYS_UI_DARK, on)

def sys_yield() -> i64:
    unsafe:
        return syscall(SYS_YIELD)

def get_time(t: Time) -> i64:
    unsafe:
        return syscall(SYS_GET_TIME, addr(t))

def monotonic_ms() -> i64:
    unsafe:
        return syscall(SYS_MONOTONIC_MS)

def io_write[B0: ByteStorage](fd: i64, b: B0, len: i64) -> i64:
    _check_size(b, len)
    unsafe:
        return syscall(SYS_WRITE, fd, addr(b), len)

def proc_exit(code: i64) -> i64:
    unsafe:
        return syscall(SYS_EXIT, code)

def get_arg[B0: MutableByteStorage](b: B0, max: i64) -> i64:
    _check_size(b, max)
    unsafe:
        return syscall(SYS_GET_ARG, addr(b), max)

def sysinfo[B0: MutableByteStorage](b: B0, max: i64) -> i64:
    _check_size(b, max)
    unsafe:
        return syscall(SYS_SYSINFO, addr(b), max)

def file_read[B0: MutableByteStorage](path: str, b: B0, max: i64) -> i64:
    _c_path = _c_string(path)
    _check_size(b, max)
    unsafe:
        return syscall(SYS_READ_FILE, addr(_c_path), addr(b), max)

def file_count() -> i64:
    unsafe:
        return syscall(SYS_FILE_COUNT)

def file_name[B0: MutableByteStorage](i: i64, b: B0, max: i64) -> i64:
    _check_size(b, max)
    unsafe:
        return syscall(SYS_FILE_NAME, i, addr(b), max)

def file_write[B0: ByteStorage](path: str, b: B0, size: i64) -> i64:
    _c_path = _c_string(path)
    _check_size(b, size)
    unsafe:
        return syscall(SYS_WRITE_FILE, addr(_c_path), addr(b), size)

def file_delete(path: str) -> i64:
    _c_path = _c_string(path)
    unsafe:
        return syscall(SYS_DELETE_FILE, addr(_c_path))

def file_rename(old: str, new: str) -> i64:
    _c_old = _c_string(old)
    _c_new = _c_string(new)
    unsafe:
        return syscall(SYS_RENAME, addr(_c_old), addr(_c_new))

def dir_make(path: str) -> i64:
    _c_path = _c_string(path)
    unsafe:
        return syscall(SYS_MKDIR, addr(_c_path))

def dir_count(dir: str) -> i64:
    _c_dir = _c_string(dir)
    unsafe:
        return syscall(SYS_DIR_COUNT, addr(_c_dir))

def dir_name[B0: MutableByteStorage](dir: str, i: i64, b: B0) -> i64:
    _c_dir = _c_string(dir)
    _check_size(b, 64)
    unsafe:
        return syscall(SYS_DIR_NAME, addr(_c_dir), i, addr(b))

def getcwd[B0: MutableByteStorage](b: B0, max: i64) -> i64:
    _check_size(b, max)
    unsafe:
        return syscall(SYS_GETCWD, addr(b), max)

def chdir(path: str) -> i64:
    _c_path = _c_string(path)
    unsafe:
        return syscall(SYS_CHDIR, addr(_c_path))

def stat(path: str, st: Stat, stlen: i64) -> i64:
    _c_path = _c_string(path)
    _check_size(st, stlen)
    unsafe:
        return syscall(SYS_STAT, addr(_c_path), addr(st), stlen)

def proc_fork() -> i64:
    unsafe:
        return syscall(SYS_FORK)

def proc_execve[B0: ByteStorage](path: str, argv: B0, envp: i64) -> i64:
    _c_path = _c_string(path)
    _check_argv(argv)
    unsafe:
        return syscall(SYS_EXECVE, addr(_c_path), addr(argv), envp)

def proc_waitpid[B0: MutableByteStorage](pid: i64, st: B0, opts: i64) -> i64:
    _check_size(st, 4)
    unsafe:
        return syscall(SYS_WAITPID, pid, addr(st), opts)

def proc_pid() -> i64:
    unsafe:
        return syscall(SYS_GETPID)

def proc_spawn[B0: ByteStorage](path: str, argv: B0) -> i64:
    _c_path = _c_string(path)
    _check_argv(argv)
    unsafe:
        return syscall(SYS_SPAWN, addr(_c_path), addr(argv))

def fd_open(path: str, flags: i64) -> i64:
    _c_path = _c_string(path)
    unsafe:
        return syscall(SYS_OPEN, addr(_c_path), flags)

def fd_close(fd: i64) -> i64:
    unsafe:
        return syscall(SYS_CLOSE, fd)

def fd_read[B0: MutableByteStorage](fd: i64, b: B0, len: i64) -> i64:
    _check_size(b, len)
    unsafe:
        return syscall(SYS_READ, fd, addr(b), len)

def fd_lseek(fd: i64, off: i64, whence: i64) -> i64:
    unsafe:
        return syscall(SYS_LSEEK, fd, off, whence)

def fd_dup(fd: i64) -> i64:
    unsafe:
        return syscall(SYS_DUP, fd)

def fd_dup2(oldfd: i64, newfd: i64) -> i64:
    unsafe:
        return syscall(SYS_DUP2, oldfd, newfd)

def fd_pipe[B0: MutableByteStorage](fds: B0) -> i64:
    _check_size(fds, 8)
    unsafe:
        return syscall(SYS_PIPE, addr(fds))

def fd_setnb(fd: i64) -> i64:
    unsafe:
        return syscall(SYS_SETNB, fd)

def fd_fsync(fd: i64) -> i64:
    unsafe:
        return syscall(SYS_FSYNC, fd)

def fd_ftruncate(fd: i64, len: i64) -> i64:
    unsafe:
        return syscall(SYS_FTRUNCATE, fd, len)

def open_path(path: str) -> i64:
    _c_path = _c_string(path)
    unsafe:
        return syscall(SYS_OPEN_PATH, addr(_c_path))

def net_info(ni: Netinfo) -> i64:
    unsafe:
        return syscall(SYS_NET_INFO, addr(ni))

def sock_open(host: str, port: i64, flags: i64) -> i64:
    _c_host = _c_string(host)
    unsafe:
        return syscall(SYS_SOCK_OPEN, addr(_c_host), ((port & 0xFFFF) << 16) | ((flags & 0xFFFF)))

def sock_poll(fd: i64) -> i64:
    unsafe:
        return syscall(SYS_SOCK_POLL, fd)

def sock_send[B0: ByteStorage](fd: i64, b: B0, len: i64) -> i64:
    _check_size(b, len)
    unsafe:
        return syscall(SYS_SOCK_SEND, fd, addr(b), len)

def sock_recv[B0: MutableByteStorage](fd: i64, b: B0, max: i64) -> i64:
    _check_size(b, max)
    unsafe:
        return syscall(SYS_SOCK_RECV, fd, addr(b), max)

def sock_alpn[B0: MutableByteStorage](fd: i64, b: B0, max: i64) -> i64:
    _check_size(b, max)
    unsafe:
        return syscall(SYS_SOCK_ALPN, fd, addr(b), max)

def sock_close(fd: i64) -> i64:
    unsafe:
        return syscall(SYS_SOCK_CLOSE, fd)

def http_body[B0: MutableByteStorage](b: B0, max: i64) -> i64:
    _check_size(b, max)
    unsafe:
        return syscall(SYS_HTTP_BODY, addr(b), max)

def res_fetch[B0: MutableByteStorage](src: str, b: B0, max: i64) -> i64:
    _c_src = _c_string(src)
    _check_size(b, max)
    unsafe:
        return syscall(SYS_RES_FETCH, addr(_c_src), addr(b), max)

def text_measure(s: str, len: i64, px: i64, mono: i64) -> i64:
    _check_text_size(s, len)
    _c_s = _c_string(s)
    unsafe:
        return syscall(SYS_TEXT_MEASURE, addr(_c_s), len, ((px & 0x3FFFFFFF) << 2) | ((mono & 0x3)))

def gui_text_run(run: Run) -> i64:
    unsafe:
        return syscall(SYS_GUI_TEXT_RUN, addr(run))

def gui_blit(blit: Blit) -> i64:
    unsafe:
        return syscall(SYS_GUI_BLIT, addr(blit))

def img_decode(req: Imgreq) -> i64:
    unsafe:
        return syscall(SYS_IMG_DECODE, addr(req))

def cpu_index() -> i64:
    unsafe:
        return syscall(SYS_CPU_INDEX)

def kheap_stress(iters: i64, size: i64, seed: i64) -> i64:
    unsafe:
        return syscall(SYS_KHEAP_STRESS, iters, size, seed)

def thread_create(spec: Thread_spec) -> i64:
    unsafe:
        return syscall(SYS_THREAD_CREATE, addr(spec))

def thread_exit(retval: i64) -> i64:
    unsafe:
        return syscall(SYS_THREAD_EXIT, retval)

def thread_join[B0: MutableByteStorage](tid: i64, retval: B0) -> i64:
    _check_size(retval, 8)
    unsafe:
        return syscall(SYS_THREAD_JOIN, tid, addr(retval))

def thread_detach(tid: i64) -> i64:
    unsafe:
        return syscall(SYS_THREAD_DETACH, tid)

def thread_self() -> i64:
    unsafe:
        return syscall(SYS_THREAD_SELF)

def set_tls(fsbase: i64) -> i64:
    unsafe:
        return syscall(SYS_SET_TLS, fsbase)

def futex[B0: MutableByteStorage](word: B0, timeout: i64, val: i64, op: i64) -> i64:
    _check_size(word, 4)
    unsafe:
        return syscall(SYS_FUTEX, addr(word), (wrapping_shl((timeout & 0xFFFFFFFF), 32)) | ((val & 0xFFFFFFFF)), op)

def thread_info(what: i64) -> i64:
    unsafe:
        return syscall(SYS_THREAD_INFO, what)

def getrandom[B0: MutableByteStorage](b: B0, len: i64, flags: i64) -> i64:
    _check_size(b, len)
    unsafe:
        return syscall(SYS_GETRANDOM, addr(b), len, flags)

# ---- waiting ----
# The A2 loop used RTC seconds and a midnight fixup to accommodate a host VM
# stub. Native host syscalls now fail explicitly. Real waits use the monotonic
# clock; a failed/backwards reading raises instead of masquerading as elapsed
# time. Kernel failure and timeout remain distinct typed exceptions.
def now_s() -> i64:
    clock = Time()
    if get_time(clock) < 0:
        raise IOError("wall clock unavailable")
    return (i64(clock.hour) * 60 + i64(clock.minute)) * 60 + i64(clock.second)

def await_(poll: Callable[[], i64], pending_neg: bool, pending_val: i64,
           has_fail: bool, fail_neg: bool, fail_val: i64,
           timeout_s: i64, label: str) -> i64:
    if timeout_s < 0:
        raise ValueError("timeout must be nonnegative")
    duration = timeout_s * 1000
    start = monotonic_ms()
    if start < 0:
        raise IOError("monotonic clock unavailable")
    while true:
        value = poll()
        pending = value < 0 if pending_neg else value == pending_val
        if not pending:
            failed = false
            if has_fail:
                failed = value < 0 if fail_neg else value == fail_val
            if failed:
                raise IOError(label + ": failed")
            return value
        now = monotonic_ms()
        if now < start:
            raise IOError("monotonic clock failed or moved backwards")
        if now - start >= duration:
            raise RuntimeError(label + ": timed out after " + str(timeout_s) + "s")
        sys_yield()
    # The current checker conservatively treats loop exits as reachable.
    raise RuntimeError("polling loop terminated unexpectedly")

def dns_start(name: str) -> i64:
    _c_name = _c_string(name)
    unsafe:
        return syscall(SYS_NET_DNS, addr(_c_name))

def dns_poll() -> i64:
    unsafe:
        return syscall(SYS_NET_DNS_RESULT)

def wait_dns(name: str, timeout_s: i64) -> i64:
    if dns_start(name) < 0:
        raise IOError("dns: cannot start")
    return await_(dns_poll, false, 0, true, false, 4294967295, timeout_s, "dns")

def ping_start(ip: i64) -> i64:
    unsafe:
        return syscall(SYS_NET_PING, ip)

def ping_poll() -> i64:
    unsafe:
        return syscall(SYS_NET_PING_RTT)

def wait_ping(ip: i64, timeout_s: i64) -> i64:
    if ping_start(ip) < 0:
        raise IOError("ping: cannot start")
    return await_(ping_poll, true, 0, false, false, 0, timeout_s, "ping")

def http_start(url: str) -> i64:
    _c_url = _c_string(url)
    unsafe:
        return syscall(SYS_HTTP_GET, addr(_c_url))

def http_poll() -> i64:
    unsafe:
        return syscall(SYS_HTTP_STATUS)

def wait_http(url: str, timeout_s: i64) -> i64:
    if http_start(url) < 0:
        raise IOError("http: cannot start")
    return await_(http_poll, false, 1, true, true, 0, timeout_s, "http")
