# GENERATED by tools/gen_abi.py from include/abi/logit_abi.h -- DO NOT EDIT.
#
# The kernel's structs, as AetherScript layouts. `t = Time()` allocates one the
# collector owns; `addr(t)` is exactly the pointer a syscall expects; `t.hour`
# reads the field at the offset below.
#
# These offsets are not this file's opinion of the layout. Each one is also
# emitted as a _Static_assert in c/apps/as/abi_layout.inc, which as_native.c
# includes -- so the compiler that builds /bin/as checks every number here
# against the real struct, and a kernel that reorders a field breaks the build
# instead of leaving a script reading the wrong bytes.
#
# Regenerate:  python3 tools/gen_abi.py --write
# Verify:      make check-abi


Event = layout("logit_event", 12, [
    ["type", 0, 4, "i"],
    ["a", 4, 4, "i"],
    ["b", 8, 4, "i"]
])

Time = layout("logit_time", 28, [
    ["year", 0, 4, "i"],
    ["month", 4, 4, "i"],
    ["day", 8, 4, "i"],
    ["hour", 12, 4, "i"],
    ["minute", 16, 4, "i"],
    ["second", 20, 4, "i"],
    ["weekday", 24, 4, "i"]
])

Netinfo = layout("logit_netinfo", 20, [
    ["ip", 0, 4, "u"],
    ["mask", 4, 4, "u"],
    ["gw", 8, 4, "u"],
    ["mac", 12, 6, "s"]
])

Run = layout("logit_run", 40, [
    ["x", 0, 4, "i"],
    ["y", 4, 4, "i"],
    ["px", 8, 4, "i"],
    ["mono", 12, 4, "i"],
    ["color", 16, 4, "u"],
    ["s", 24, 8, "p"],
    ["len", 32, 4, "i"]
])

Blit = layout("logit_blit", 32, [
    ["x", 0, 4, "i"],
    ["y", 4, 4, "i"],
    ["w", 8, 4, "i"],
    ["h", 12, 4, "i"],
    ["rgba", 16, 8, "p"],
    ["sw", 24, 4, "i"],
    ["sh", 28, 4, "i"]
])

Imgreq = layout("logit_imgreq", 32, [
    ["path", 0, 8, "p"],
    ["rgba", 8, 8, "p"],
    ["max", 16, 4, "i"],
    ["w", 20, 4, "i"],
    ["h", 24, 4, "i"]
])
