/* AES-GCM-SIV (RFC 8452) known-answer test.
 *
 * Vectors: tests/unit/aes_gcm_siv_vectors.inc, generated by
 * tests/unit/aes_gcm_siv_gen.py directly from the RFC's own text -- see that
 * script's header for why it parses the RFC rather than a hand-transcription.
 * 50 AEAD vectors: RFC 8452 C.1 (AES-128, 24 cases spanning plaintext 0..64
 * bytes with and without AAD), C.2 (AES-256, the same 24 cases), C.3 (the two
 * counter-wrap cases, which exist specifically to catch a 32-bit-boundary
 * increment bug). Plus the standalone POLYVAL worked example from section 7,
 * which exercises this file's field arithmetic (dot, and the a*b it is built
 * from) independently of the AEAD construction on top of it.
 *
 * This is a self-test in the narrow sense that it links this tree's own
 * aes_gcm_siv.c -- but the ANSWERS are RFC 8452's, not generated by that same
 * code, so it is exactly the "reference instead of a hand-written
 * expectation" the mini-libc gate argues for (CLAUDE.md, "Porting real
 * software"). See aes_gcm_siv.c's header for the negative control that makes
 * this gate watchably red: -DSIV_CTL_NO_TAG_MASK.
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "aes_gcm_siv.h"

#include "aes_gcm_siv_vectors.inc"

static int hex2bin(const char *hex, uint8_t *out, int maxout)
{
    int n = 0;
    while (hex[0] && hex[1]) {
        unsigned v;
        if (sscanf(hex, "%2x", &v) != 1) return -1;
        if (n >= maxout) return -1;
        out[n++] = (uint8_t)v;
        hex += 2;
    }
    return n;
}

static void bin2hex(const uint8_t *b, int n, char *out)
{
    static const char *H = "0123456789abcdef";
    for (int i = 0; i < n; i++) { out[2*i] = H[b[i]>>4]; out[2*i+1] = H[b[i]&15]; }
    out[2*n] = 0;
}

static int pass, fail;
static void ok(const char *what)  { pass++; }
static void bad(const char *what) { fail++; fprintf(stderr, "  FAIL: %s\n", what); }

int main(void)
{
    /* --- RFC 8452 section 7: the standalone POLYVAL worked example ---
     * polyval(H=b, X_1=a, nblocks=1) computes S_1 = dot(S_0+X_1, H) =
     * dot(0+a, b) = dot(a,b) -- the one-block case of the general iteration
     * IS this worked example, so no separate "dot" entry point is needed
     * (see aes_gcm_siv.h). This is checked BEFORE any AEAD vector: if the
     * field arithmetic is wrong, every AEAD vector below would also fail,
     * and this isolates the failure to the primitive rather than the
     * construction. */
    {
        uint8_t a[16], b[16], want[16], got[16];
        hex2bin(POLYVAL_EX_A, a, 16);
        hex2bin(POLYVAL_EX_B, b, 16);
        hex2bin(POLYVAL_EX_DOT, want, 16);
        polyval(b, a, 1, got);
        if (memcmp(got, want, 16) == 0) ok("polyval section-7 dot(a,b)");
        else {
            char gh[33], wh[33]; bin2hex(got,16,gh); bin2hex(want,16,wh);
            bad("polyval section-7 dot(a,b)");
            fprintf(stderr, "    got  %s\n    want %s\n", gh, wh);
        }
    }

    /* --- RFC 8452 Appendix C: the 50 AEAD vectors --- */
    for (int i = 0; i < SIV_NVECTORS; i++) {
        const struct siv_vec *v = &SIV_VECTORS[i];
        uint8_t key[32], nonce[12], aad[64], pt[80], want_res[96];
        int keylen = v->keylen;
        int noncelen = hex2bin(v->nonce, nonce, sizeof nonce);
        int aadlen = hex2bin(v->aad, aad, sizeof aad);
        int ptlen = hex2bin(v->pt, pt, sizeof pt);
        int reslen = hex2bin(v->result, want_res, sizeof want_res);
        hex2bin(v->key, key, sizeof key);
        if (noncelen != 12 || reslen != ptlen + 16) {
            bad("vector shape (bad .inc?)"); continue;
        }

        uint8_t ct[80], tag[16];
        if (keylen == 16) aes128_gcm_siv_seal(key, nonce, aad, aadlen, pt, ptlen, ct, tag);
        else               aes256_gcm_siv_seal(key, nonce, aad, aadlen, pt, ptlen, ct, tag);

        int seal_ok = (memcmp(ct, want_res, (size_t)ptlen) == 0) &&
                      (memcmp(tag, want_res + ptlen, 16) == 0);
        if (seal_ok) ok("seal");
        else {
            uint8_t got_res[96];
            memcpy(got_res, ct, (size_t)ptlen); memcpy(got_res + ptlen, tag, 16);
            char gh[193], wh[193];
            bin2hex(got_res, reslen, gh); bin2hex(want_res, reslen, wh);
            bad("seal");
            fprintf(stderr, "    vec %d (%s, pt=%dB aad=%dB)\n    got  %s\n    want %s\n",
                    i, keylen==16?"AES-128":"AES-256", ptlen, aadlen, gh, wh);
        }

        /* Round trip: open() must recover the exact plaintext and report
         * success. This also exercises the decrypt-then-recompute-then-
         * compare path (aes_gcm_siv.c's siv_open) independently of seal(). */
        uint8_t recovered[80];
        int rc = (keylen == 16)
            ? aes128_gcm_siv_open(key, nonce, aad, aadlen, want_res, ptlen, want_res + ptlen, recovered)
            : aes256_gcm_siv_open(key, nonce, aad, aadlen, want_res, ptlen, want_res + ptlen, recovered);
        if (rc == 0 && memcmp(recovered, pt, (size_t)ptlen) == 0) ok("open");
        else bad("open (round trip)");

        /* A corrupted tag must be refused -- the one negative check every
         * vector gets for free, distinct from the -D control below (which
         * targets the CONSTRUCTION, not just "does verification exist at
         * all"). */
        uint8_t bad_tag[16]; memcpy(bad_tag, want_res + ptlen, 16); bad_tag[0] ^= 0x01;
        int rc2 = (keylen == 16)
            ? aes128_gcm_siv_open(key, nonce, aad, aadlen, want_res, ptlen, bad_tag, recovered)
            : aes256_gcm_siv_open(key, nonce, aad, aadlen, want_res, ptlen, bad_tag, recovered);
        if (rc2 != 0) ok("corrupted tag refused");
        else bad("corrupted tag WAS ACCEPTED");
    }

    printf("AES-GCM-SIV: %d passed, %d failed (%d RFC 8452 vectors + polyval)\n",
           pass, fail, SIV_NVECTORS);
    return fail ? 1 : 0;
}
