#!/usr/bin/env python3
"""Native durcheck parity: exact binary bytes, failure exits and real file I/O.

Only SYS_DELETE_FILE's host transport is adapted to unlink. Generation, reads,
writes, comparisons and command parsing execute the actual A3 source/runtime.
"""
import argparse
import os
from pathlib import Path
import tempfile

from as_abi_test import probe_runtime
from as_managed_test import ROOT, emit_ir, invoke, sanitized

SOURCE = ROOT / "fsroot/as/examples/durcheck.as"
SIZES = {"tiny": 100, "small": 30000, "mid": 120000, "big": 400000, "huge": 4400000}
PROBE = r'''#include "abi/logit_abi.h"
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static unsigned deletions;

int64_t abi_probe(int64_t number, uint64_t a, uint64_t b, uint64_t c)
{
    assert(number == SYS_DELETE_FILE && a && !b && !c);
    const char *path = (const char *)(uintptr_t)a;
    const char *root = getenv("DURABILITY_ROOT");
    assert(root && !strncmp(path, root, strlen(root)) && path[strlen(root)] == '/');
    deletions++;
    if (getenv("DURABILITY_DELETE_FAIL")) {
        return -1;
    }
    return unlink(path);
}

__attribute__((destructor)) static void verify_deletions(void)
{
    const char *count = getenv("DURABILITY_DELETIONS");
    assert(deletions == (count ? strtoul(count, NULL, 10) : 0));
}
'''


def pattern(size):
    # Independent whole-offset oracle, including the wrap at byte 65536.
    cycle = bytes(((position // 256) * 251 + (position % 256) * 37 +
                   ((position % 256) ** 2) % 97) % 256 for position in range(65536))
    return (cycle * (size // len(cycle) + 1))[:size]


def run(binary, work, arguments, status, output=None, deletions=0, delete_fail=False):
    environment = dict(os.environ, ASAN_OPTIONS="detect_leaks=0:halt_on_error=1",
                       UBSAN_OPTIONS="halt_on_error=1", DURABILITY_ROOT=str(work),
                       DURABILITY_DELETIONS=str(deletions))
    environment.pop("DURABILITY_DELETE_FAIL", None)
    if delete_fail:
        environment["DURABILITY_DELETE_FAIL"] = "1"
    result = invoke([binary, *arguments], env=environment)
    assert result.returncode == status, (arguments, result)
    if output is not None:
        assert result.stdout == output, (arguments, result)
    return result


def commands(binary, work):
    for arguments in ([], ["write"], ["unknown", str(work / "unknown")]):
        run(binary, work, arguments, 2)
    for name, size in SIZES.items():
        path = work / (name + ".bin")
        expected = pattern(size)
        run(binary, work, ["write", path, name], 0,
            f"durcheck write {path} {size} -> {size}\n")
        assert path.read_bytes() == expected, (name, "generated bytes differ from A2 formula")
        run(binary, work, ["verify", path, name], 0, f"DURCHECK-OK {path} {size}\n")

        # Keep the same length: a length-only checker must fail these controls.
        for offset in sorted({min(size - 1, n) for n in (0, 255, 256, 65535, 65536, size - 1)}):
            damaged = bytearray(expected)
            damaged[offset] ^= 0xff
            path.write_bytes(damaged)
            run(binary, work, ["verify", path, name], 1,
                f"DURCHECK-FAIL {path} first bad byte {offset} "
                f"got {damaged[offset]} want {expected[offset]}\n")
        path.write_bytes(expected[:-1])
        run(binary, work, ["verify", path, name], 1,
            f"DURCHECK-FAIL {path} length {size - 1} expected {size}\n")
        path.write_bytes(expected)

    absent = work / "absent"
    run(binary, work, ["verify", absent, "tiny"], 1, f"DURCHECK-FAIL {absent} unreadable\n")
    unwritable = absent / "file"
    run(binary, work, ["write", unwritable, "tiny"], 1,
        f"DURCHECK-FAIL {unwritable} write\n")
    fallback = work / "default.bin"
    run(binary, work, ["write", fallback, "unspecified"], 0)
    assert fallback.read_bytes() == pattern(SIZES["mid"])
    run(binary, work, ["verify", fallback], 0,
        f"DURCHECK-OK {fallback} {SIZES['mid']}\n")

    run(binary, work, ["churn", work], 0, "DURCHECK-CHURN-DONE\n", deletions=12)
    assert not (work / "churn.tmp").exists()
    assert fallback.read_bytes() == pattern(SIZES["mid"]), "churn changed bystander"
    failed = run(binary, work, ["churn", work], 1, "", deletions=1, delete_fail=True)
    assert "IOError" in failed.stderr and (work / "churn.tmp").exists(), failed

    victim = work / "victim.bin"
    output = "CRASH-WRITE-ARMED\n" + "".join(
        f"CRASH-WRITE-ROUND {n}\n" for n in range(0, 300, 10)) + "CRASH-WRITE-DONE\n"
    run(binary, work, ["crashwrite", victim], 0, output, deletions=300)
    assert not victim.exists()
    assert Path(str(victim) + ".b").read_bytes() == pattern(SIZES["big"])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("compiler", type=Path)
    parser.add_argument("--negative-control", action="store_true")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="a3-durability-") as temporary:
        work = Path(temporary).resolve()
        runtime = probe_runtime(work, PROBE)
        ir = work / "durability.ll"
        emit_ir(args.compiler.resolve(), SOURCE, ir)
        for optimization in ("-O0", "-O2"):
            binary = work / ("durability" + optimization)
            assert sanitized(ir, runtime, binary, optimization).returncode == 2
            commands(binary, work)
        if args.negative_control:
            text = SOURCE.read_text()
            anchor = "if data != want:"
            assert text.count(anchor) == 1
            source = work / "length_only.as"
            source.write_text(text.replace(anchor, "if false:"))
            emit_ir(args.compiler.resolve(), source, ir)
            binary = work / "length_only"
            assert sanitized(ir, runtime, binary, "-O0").returncode == 2
            damaged = work / "negative.bin"
            data = bytearray(pattern(100))
            data[42] ^= 0xff
            damaged.write_bytes(data)
            result = run(binary, work, ["verify", damaged, "tiny"], 0)
            assert "DURCHECK-OK" in result.stdout, result
            try:
                run(binary, work, ["verify", damaged, "tiny"], 1)
            except AssertionError:
                print("PASS negative control: length-only verifier observed accepting corruption")
            else:
                raise AssertionError("same-length corruption control did not detect missing comparison")
    print("PASS native durcheck: five sizes, exact bytes, failures, churn and 300 rounds; O0/O2 ASan/UBSan")


if __name__ == "__main__":
    main()
