/* Host known-answer + negative tests for the P-256 / P-384 ECDHE added to
 * c/crypto/pubkey/ecdsa.c (the fallback groups that make a server which refuses
 * x25519 reachable at all).
 *
 * Provenance of the vectors: generated by an independent pure-Python curve
 * implementation (the same arithmetic tests/unit/crypto_vec_gen.py uses) and
 * then cross-checked, every one of them and in both directions, against
 * `openssl pkeyutl -derive` (OpenSSL 3.5.5). A vector is only in this file if
 * Python and OpenSSL agreed on it first. Generator:
 * scratch script recorded in the M27 TLS notes; regenerate with any ECDH tool
 * -- the numbers are plain SEC1 scalars/points, nothing LogitOS-specific.
 *
 * Build: see the `test-crypto` rule in the Makefile. */
#include <stdio.h>
#include <stdint.h>
#include <string.h>

int ecdh_keygen(int curve, const uint8_t *priv, uint32_t blind, uint8_t *pub);
int ecdh_shared(int curve, const uint8_t *priv, uint32_t blind,
                const uint8_t *peer, int peerlen, uint8_t *out);

static int fails, checks;

static int hb(const char *h, uint8_t *o)
{
    int n = 0;
    while (h[2*n]) { unsigned v; sscanf(h + 2*n, "%2x", &v); o[n++] = (uint8_t)v; }
    return n;
}

static void ok(const char *what, int cond)
{
    checks++;
    if (cond) printf("ok   %s\n", what);
    else { printf("FAIL %s\n", what); fails++; }
}

/* A deliberately varied set of blinding factors: 0 and 0xffffffff exercise the
 * clamp in blind_scalar() (which forces bit 30 and clears bit 31), the rest are
 * arbitrary. Every one must produce the *same* answer -- that is the whole
 * point of blinding: it changes the ladder's work, never its result. */
static const uint32_t BLINDS[] = { 0u, 1u, 0x40000000u, 0x7fffffffu, 0xffffffffu,
                                   0xdeadbeefu, 0x12345678u, 0xa5a5a5a5u };
#define NBLIND ((int)(sizeof BLINDS / sizeof BLINDS[0]))

static void V(int curve, const char *dah, const char *apubh,
              const char *dbh, const char *bpubh, const char *zh)
{
    int nb = curve / 8;
    uint8_t da[48], db[48], apub[97], bpub[97], z[48];
    uint8_t got[97], gz[48];
    char name[64];

    hb(dah, da); hb(dbh, db); hb(zh, z);
    int apl = hb(apubh, apub), bpl = hb(bpubh, bpub);

    /* public share must reproduce exactly, for every blinding factor */
    int allsame = 1;
    for (int i = 0; i < NBLIND; i++) {
        memset(got, 0xAA, sizeof got);
        if (ecdh_keygen(curve, da, BLINDS[i], got) != 0 || memcmp(got, apub, apl)) allsame = 0;
        if (ecdh_keygen(curve, db, BLINDS[i], got) != 0 || memcmp(got, bpub, bpl)) allsame = 0;
    }
    snprintf(name, sizeof name, "P-%d keygen (x%d blinds)", curve, NBLIND);
    ok(name, allsame);

    /* both directions of the agreement must land on the same X coordinate */
    allsame = 1;
    for (int i = 0; i < NBLIND; i++) {
        memset(gz, 0xAA, sizeof gz);
        if (ecdh_shared(curve, da, BLINDS[i], bpub, bpl, gz) != 0 || memcmp(gz, z, nb)) allsame = 0;
        memset(gz, 0xAA, sizeof gz);
        if (ecdh_shared(curve, db, BLINDS[i], apub, apl, gz) != 0 || memcmp(gz, z, nb)) allsame = 0;
    }
    snprintf(name, sizeof name, "P-%d shared A<->B (x%d blinds)", curve, NBLIND);
    ok(name, allsame);
}

/* Group order n, needed for the out-of-range scalar rejections. */
static const char *N256 = "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551";
static const char *N384 = "ffffffffffffffffffffffffffffffffffffffffffffffff"
                          "c7634d81f4372ddf581a0db248b0a77aecec196accc52973";
static const char *P256P = "ffffffff00000001000000000000000000000000ffffffffffffffffffffffff";

static void negatives(int curve, const char *nh, const char *goodpubh)
{
    int nb = curve / 8;
    uint8_t n[48], d[48], pub[97], out[97];
    char name[80];
    int pl = hb(goodpubh, pub);
    hb(nh, n);

    /* scalar 0 and scalar == n are both outside [1, n-1]. Reducing them instead
     * of rejecting would bias the private key, so both calls must refuse and
     * make the caller re-randomise. */
    memset(d, 0, nb);
    snprintf(name, sizeof name, "P-%d rejects scalar 0", curve);
    ok(name, ecdh_keygen(curve, d, 1, out) != 0 && ecdh_shared(curve, d, 1, pub, pl, out) != 0);

    memcpy(d, n, nb);
    snprintf(name, sizeof name, "P-%d rejects scalar == n", curve);
    ok(name, ecdh_keygen(curve, d, 1, out) != 0 && ecdh_shared(curve, d, 1, pub, pl, out) != 0);

    memcpy(d, n, nb); d[nb-1] = 0xff;                 /* > n (n ends ...51 / ...73) */
    snprintf(name, sizeof name, "P-%d rejects scalar > n", curve);
    ok(name, ecdh_keygen(curve, d, 1, out) != 0);

    /* --- peer-point validation. These are the checks that stop an
     * invalid-curve attack: with cofactor 1, "on the curve and not infinity"
     * is exactly "in the prime-order group". --- */
    memset(d, 0, nb); d[nb-1] = 7;                    /* any valid small scalar */

    uint8_t bad[97];
    memcpy(bad, pub, pl); bad[pl-1] ^= 1;             /* perturb Y -> off curve */
    snprintf(name, sizeof name, "P-%d rejects off-curve peer point", curve);
    ok(name, ecdh_shared(curve, d, 1, bad, pl, out) != 0);

    memcpy(bad, pub, pl); bad[1] ^= 0x80;             /* perturb X -> off curve */
    snprintf(name, sizeof name, "P-%d rejects off-curve peer point (X twisted)", curve);
    ok(name, ecdh_shared(curve, d, 1, bad, pl, out) != 0);

    memcpy(bad, pub, pl); bad[0] = 0x02;              /* compressed form */
    snprintf(name, sizeof name, "P-%d rejects compressed peer point", curve);
    ok(name, ecdh_shared(curve, d, 1, bad, pl, out) != 0);

    memcpy(bad, pub, pl);
    snprintf(name, sizeof name, "P-%d rejects wrong-length peer point", curve);
    ok(name, ecdh_shared(curve, d, 1, bad, pl - 1, out) != 0 &&
             ecdh_shared(curve, d, 1, bad, pl + 1, out) != 0);

    memset(bad, 0, pl); bad[0] = 0x04;                /* (0,0) */
    snprintf(name, sizeof name, "P-%d rejects (0,0)", curve);
    ok(name, ecdh_shared(curve, d, 1, bad, pl, out) != 0);
}

int main(void)
{
    /* --- known answers, Python reference == OpenSSL == us --- */
    V(256, "6c0eaf074b41c9b7fa8de03c57bff50392edff299a09f1735f90c2b1a7bedecb",
           "04f3b10d25b14f93d0a14e377c88be79fa064f3ec52bea19dda9c673f4d22789ce"
           "c0b40c58642c3ea15f7faca8adadad73a8a4487ed25f117deabe48f3b1ab9e53",
           "880954cfc38fa91ffccabb9fc18d7f90e6fc820d50286ec38d013c3644eb43d1",
           "04c9d855ed6a292888056ed6534a0326caa12c421e8f480b48920dab99cd650edc"
           "9cd32fb951da47ae58843a72efb6e7c314d58efcd3afd79110a4c1e1e25e224f",
           "27f0a41020ad7b252eaf212c066a5f8319071febc2ef01285dd7562e451ff344");
    V(256, "ee702b8dfe4f1b46a44c16883bd7fe82c129e49132ef5e181b6f3f612e039eb7",
           "04dad5b01f357d949bd6f0128309156d549e6f2bcc184693bb0f4835772c572b8b"
           "068d37b07b8f706d30c857ffcf52349c6799175a7a69de6bd08cf545b1a921b0",
           "e80eaf7e9b76bc1e34dfe1c1fe724726780a6f6300e86899ca78a9c0fd595e94",
           "04079775fc1dfa422906c30eb2d530a1ab7bbac805ebbdcfcff60769cf9a911a13"
           "873d56d2bb3bfb84f512915bfb3e5949f21971669560fcd3e7ce4e250bb4d11d",
           "c21f2a502ca314af52ade65cd404c56625788d0f6956d7abdc54691e48761768");
    V(256, "10ab36b30cdf69acb00d18353c280245dbe245100a3b85282c97212a6c19418c",
           "0491bb46f3372fc2c149735ec06c8867b54737b7db50b860f53b9d81bf55636afc"
           "a8007b6563c479387cea195927a6a0716ec8b73e2ca9bc1f9250ef4ab96503c2",
           "204b2f2cf223cf6e0d167d2176d7981b0055f2cf9a227100e4c18d7a8c406249",
           "0476d2d0f36bfd8d87afda6172a526ddb94b42a9ee1226e915f594240f5537fce5"
           "2661e714cce091e1cb438b71726269bedea606cde01fe82672f02c68186e45b5",
           "06bda61d6c1c225a7118dca34b95deced2f3183299cb68f97d5ecbd575293e8a");
    V(256, "d588af85d5455b184846f45fa747094cc311ffd9bc1599fc9bfa65795a73d721",
           "042486256619b72786a5b124773427da5ec67c732628dc1f77723b9d4644c70fe2"
           "d5753833cc52419a549f64d385c1495cbf2617096b30e8adb1be51bf6319712a",
           "66588169399b974703f9d0cebe3e3835493ac12951b841de2b59e600fb3e133c",
           "04b28b3b0e8d56cf605ebaf963fdb52b66796a0cdc39f7c546e97d0754ef51991d"
           "679c5ebf3905b50a97c3660b8b31dc68f847fb0d3261c64c256d87127c0f7a30",
           "fbf1d95363ee604e40e9fb4dced22869ab8ae20df0cf6f7c0b3450cd66676d0b");

    V(384, "078378e4b824c8c5e9cfc5143906d0b8eb4e11d877c66030ec23ea8df3fd7a5b"
           "586ffcce53db0e45da1aa4100253457a",
           "04762f6ca3f10b625c505b9705bcb9e55f279c956c29a8756508678cebb9658ba5"
           "9e65ebb1f843fbe0d179fdc1b9ce0a5b24e5f43bf877d5f4f23e4ef57450a78387"
           "c0b1e9d2984e2d2ab3f37f88aba5590e44353dc4d5609c96d0b338b76886fc",
           "19cd936862c200f04bb559f512d93d6b16f3e53b021e4e0defcebfc52de52faa"
           "c444152743418699b040983788f623be",
           "044bed1c5617dc32d2562b6699b4a56b9856472da4627523d6932d41dadd8e4d61"
           "f22b27a93403182f1193c993581143e1cf50b0e8c25f89829816ae88406fcc04f0"
           "65a0d92f23039451845b97399810af95d34ed90061de7b240b0bf11486d160",
           "b1507e910b4563aa3a9033bf1232b633f9aae052b86a83681a0cecea06a6bf44"
           "fef474baf7073490ee2db36dbcfae792");
    V(384, "f0f10bc0f6ae93adfe46a7729609f0a9e6df2a5828cef066c3f1a136dcc21c9f"
           "83f0d6fb97e052f6b3f20a2892b2491e",
           "041d9901ecf66425e263cce9643c0e4771952a07f8c396add6009cf7500d365487"
           "4c9a7d982908704263e7b16ca728496171407f7370cd88a469f0c85f0e8d110177"
           "72b7db9513e7743c6ee2c714c84617290f849f26056c375c92530cbfd11b4f",
           "f4f46e8e06a384325fbc195043b74c92d10af7e33ce254a90c281138eef70870"
           "b7cd51d80ff1cb0bfa08531b049886e9",
           "045132ba35eefdc758bdc41e9b0a22dfb8c07df98d7a8dfe16b6f63a56e3f28fa2"
           "812ed5da742980fe37fbc602af5821277043e32e4ed9bea79c12289d9b8a0c85a7"
           "127bf29250d0e1c9692b8d665ddc75e4e4cfc5e5f2a216ed387a9c58838d47",
           "196971e621e68acb0580c471075466928ea7fba79644c1c96bc12c21d87a86dd"
           "69d3474d86b86107bc7f3a7e71d78808");
    V(384, "eac810ee43ede6df350d958d6b93e72a34cf6c9d62a5f54eade4141c8e4bfa98"
           "57524e29da1d7522929f60f7622d0976",
           "04a753b6a96c22e9ee6e65a40036aea596e3a1afae8e03833bf7b9a4bf47915725"
           "c62057a62411417741cd1812dda4fc410ab59894c7b00fb195580227ac04d4afa5"
           "076d07d592e9b7c3b889d9d0d0db4dcf11678df8b8361e1404f7bd5cd0aa93",
           "4e185557742f83ed6c6dfd7a43242d4c720bf308fbf243925b3e0945e8a450e7"
           "3ada8d378d4391c393a5efa291eed40e",
           "044079edb1a889090d9b53ad78fc898ce39ac04c74b5ebf59b6164d0e20d508bd6"
           "8ebd2e8d6378d7816168dde2f78f655f466f1917436a904b9361ec1476fb0894ea"
           "4dc42122547e2dde91bd7801c287c2fa1601453738d8d77069186c83854def",
           "ddf8a54bd4c43798063a0bf94ef9d5fa8844526e4ff3d14d5feae6379e7805f1"
           "13403dc922ff68ac527182b50c251417");
    V(384, "ef91d109fca1651cde826deb0200fabcbfb3ac813918012642af2ee981e20767"
           "4432bb824ab01313006630b3e968c5fc",
           "048bdbeae5a12b9504ed034c0b14fe004ff6f0f737a64bc89efe9ad1c765e2e879"
           "ad3eab6a86d7ad02bf5fc3fe090d1b140ecfb357d0e3ab5fe997115c3b63e4f070"
           "08f6de1f442a9c2f49f2337ff69deaea73758b99da1b55247fc8f673d7bb68",
           "55576857ad8f55c2e2096601e2bd7077b9654c91ae56456eb8ae1be64efc7a50"
           "6e0f86e3a48a22a188b106db2cae0975",
           "04d22c77f5957895db996a98cf49ee176f2560f3bb8b5ffee31b6e373b110c8cd2"
           "3eb2a67a34b6a2d9a699e26a77d828751b6d2cca22772d9c35b251dd1df4119aae"
           "c1513403b1edc5a8e327a49b4b1d597de72b28855a307ea389f397527a26f9",
           "552e64e44ecea994a48b21876cea89e465f6f11b7b52044c7c99a6507c5c68af"
           "7838dc1183fc9bfb860c6c80252fde77");

    /* --- rejections --- */
    negatives(256, N256,
              "04f3b10d25b14f93d0a14e377c88be79fa064f3ec52bea19dda9c673f4d22789ce"
              "c0b40c58642c3ea15f7faca8adadad73a8a4487ed25f117deabe48f3b1ab9e53");
    negatives(384, N384,
              "04762f6ca3f10b625c505b9705bcb9e55f279c956c29a8756508678cebb9658ba5"
              "9e65ebb1f843fbe0d179fdc1b9ce0a5b24e5f43bf877d5f4f23e4ef57450a78387"
              "c0b1e9d2984e2d2ab3f37f88aba5590e44353dc4d5609c96d0b338b76886fc");

    /* An X coordinate >= p must be refused before it reaches Barrett reduction,
     * which assumes reduced inputs -- feeding it an unreduced value would not
     * merely be wrong, it would be arithmetic outside the implementation's
     * stated domain. */
    {
        uint8_t bad[97], d[32], out[32];
        uint8_t p[32]; hb(P256P, p);
        bad[0] = 0x04; memcpy(bad + 1, p, 32); memset(bad + 33, 0, 32);
        memset(d, 0, 32); d[31] = 7;
        ok("P-256 rejects peer X >= p", ecdh_shared(256, d, 1, bad, 65, out) != 0);
    }
    /* An unknown curve id is not silently treated as P-256. */
    {
        uint8_t d[32] = {0}, out[97]; d[31] = 5;
        ok("unknown curve id refused", ecdh_keygen(521, d, 1, out) != 0);
    }

    printf("\n%d checks, %d failed\n", checks, fails);
    printf(fails ? "ECDH FAILED\n" : "ECDH ALL PASS\n");
    return fails ? 1 : 0;
}
