#!/usr/bin/env python3
"""Converts the official Wycheproof ECDSA/secp256k1/SHA-256 test vectors into
the flat line format tests/unit/secp256k1_test.c reads on stdin.

SOURCE (fetched 2026-08-28, verified reachable):
  https://raw.githubusercontent.com/C2SP/wycheproof/main/testvectors_v1/ecdsa_secp256k1_sha256_test.json
  318933 bytes, sha256 43db761c0a2eae71fb0755d355d5130e28ce64a5b07846cf27e7072082597a81
  algorithm=ECDSA, 109 test groups, 476 individual cases, all sha=SHA-256.

There are no NIST CAVP vectors for secp256k1 -- it is a SECG/Certicom curve,
not a NIST one -- which is why this file exists instead of a committed .inc
in the CAVP style ecdsa.c's P-256/P-384/P-521 tests use. Wycheproof is the
closest thing this curve has to an official, multi-implementation-tested
corpus: it is maintained by Google's crypto team specifically to catch the
class of bug a round-trip self-test cannot (wrong-curve points, ASN.1 DER
edge cases, small/degenerate r and s, boundary hashes).

This script does NOT parse the DER signature or hash the message -- both of
those are exactly what tests/unit/secp256k1_test.c exercises in the C code
under test (der_parse_sig via secp256k1_verify_der, sha256() via crypto.h).
Pre-parsing them here would silently narrow the vector set to "cases whose
encoding this script's parser also accepts", which is the opposite of the
point: many Wycheproof cases exist SPECIFICALLY to probe non-canonical DER
(BER lengths, redundant sign-guard zero bytes, negative encodings) and the
C parser must see the raw bytes to be tested at all.

Output line format (space-separated, one case per line):
  tcid  result(1|0)  wx_hex(64)  wy_hex(64)  msg_hex_or_-  sig_der_hex

`result` is 1 for Wycheproof's "valid", 0 for "invalid". This vector set has
NO "acceptable" cases (verified: no test in this file carries that result --
see secp256k1.h's LOW-S note for what that means for this gate), so no
label needs a policy decision to reduce it to a bit.

Usage: python3 gen_secp256k1_vectors.py <path-to-wycheproof-json> > secp256k1_wycheproof.inc
"""
import json
import sys


def pad64(h):
    h = h.strip()
    if len(h) > 64:
        h = h[-64:]          # Wycheproof left-pads some coordinates with an
                              # extra 0x00 sign-guard byte for DER purposes;
                              # only the low 32 bytes are the coordinate.
    return h.rjust(64, "0")


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_secp256k1_vectors.py <wycheproof.json>")
    with open(sys.argv[1]) as f:
        d = json.load(f)

    assert d["algorithm"] == "ECDSA"
    n = 0
    print("# generated by tests/unit/gen_secp256k1_vectors.py -- DO NOT EDIT BY HAND")
    print("# source: ecdsa_secp256k1_sha256_test.json, sha256 "
          "43db761c0a2eae71fb0755d355d5130e28ce64a5b07846cf27e7072082597a81")
    for g in d["testGroups"]:
        assert g["sha"] == "SHA-256", g["sha"]
        wx = pad64(g["publicKey"]["wx"])
        wy = pad64(g["publicKey"]["wy"])
        for t in g["tests"]:
            res = t["result"]
            if res == "acceptable":
                sys.exit(f"tcId {t['tcId']}: unexpected 'acceptable' result -- "
                         "the header comment above claims this file has none; "
                         "re-check secp256k1.h's LOW-S note before proceeding")
            want = 1 if res == "valid" else 0
            msg = t["msg"] if t["msg"] else "-"
            sig = t["sig"] if t["sig"] else "-"   # tcId 21 ("removing sequence
                                                   # [r, s]") is a genuinely
                                                   # empty DER blob
            print(f"{t['tcId']} {want} {wx} {wy} {msg} {sig}")
            n += 1
    print(f"# {n} cases", file=sys.stderr)


if __name__ == "__main__":
    main()
