/* Exact positioned constraints through DOM -> real LibCSS -> layout. The
 * percentage and margin negative binaries independently restore each old
 * path; a fix to one must not hide a dead test for the other. */
#define main intrinsic_original_main
#include "intrinsic_test.c"
#undef main
static int xpos(const char *id){int x,y,w,h;CHECK(layout_node_box(ID(id),&x,&y,&w,&h),"x box exists");return x;}
static int ypos(const char *id){int x,y,w,h;CHECK(layout_node_box(ID(id),&x,&y,&w,&h),"y box exists");return y;}
int main(void){
 css_init();css_viewport(1126,562);
 page("<style>body{margin:0}#box{top:20%;left:0;right:0;position:fixed;width:900px;height:52px;margin:auto;z-index:3}form{display:flex;align-items:center;width:100%;height:100%;background:white}input{width:838px;height:28px;padding:0;border:0}#nav{position:fixed;top:0;left:182px;height:39px;width:26px;z-index:4}</style><div id='box'><form><input id='query'></form></div><nav id='nav'>NAV</nav>",1126);
 EQ(ypos("query"),124,"fixed percentage top separates search control from navigation");EQ(xpos("query"),113,"opposing fixed insets distribute horizontal auto margins");EQ(ypos("nav"),0,"fixed navigation remains at zero");
 css_viewport(1000,800);layout_page(g_root,1000);EQ(ypos("query"),172,"viewport resize recomputes percentage top");EQ(xpos("query"),50,"viewport resize recomputes auto margins");
 css_viewport(400,300);
 page("<style>body{margin:0}#cb{position:relative;width:300px;height:200px;padding:10px;border:2px solid}#a{position:absolute;left:25%;top:10%;width:20px;height:20px}#b{position:absolute;right:10%;bottom:25%;width:20px;height:20px}#f{position:fixed;left:25%;top:10%;width:20px;height:20px}</style><div id='cb'><div><div id='a'></div><div id='b'></div><div id='f'></div></div></div>",400);
 EQ(xpos("a"),82,"absolute left percent uses containing padding width");EQ(ypos("a"),24,"absolute top percent uses containing padding height");EQ(xpos("b"),270,"absolute right percentage solves far edge");EQ(ypos("b"),147,"absolute bottom percentage solves far edge");EQ(xpos("f"),100,"nested fixed skips positioned ancestor width");EQ(ypos("f"),30,"nested fixed skips positioned ancestor height");
 page("<style>body{margin:0}#cb{position:relative;padding:10px;border:2px solid}#a{position:absolute;top:50%;width:20px;height:20px}</style><div id='cb'><div style='height:100px'></div><div id='a'></div></div>",400);EQ(ypos("a"),62,"absolute percent uses auto containing block used padding height");
 page("<style>body{margin:0}.f{position:fixed;width:20px;height:20px}#zero{top:0%;left:0%}#negative{top:-10%;left:-12.5%}#bottom{bottom:10%;right:12.5%}#auto{top:20%;top:auto;left:0}#px{top:20%;top:7px;left:0}#calc{top:9px;top:calc(20% + 3px);left:0}</style><div style='height:37px'></div><div id='zero' class='f'></div><div id='negative' class='f'></div><div id='bottom' class='f'></div><div id='auto' class='f'></div><div id='px' class='f'></div><div id='calc' class='f'></div>",400);
 EQ(ypos("zero"),0,"zero percentage remains specified not static auto");EQ(xpos("negative"),-50,"negative fractional left percentage retained");EQ(ypos("negative"),-30,"negative top percentage retained");EQ(xpos("bottom"),330,"fixed right fraction uses viewport width");EQ(ypos("bottom"),250,"fixed bottom fraction uses viewport height");EQ(ypos("auto"),37,"auto cascade clears previous percentage");EQ(ypos("px"),7,"pixel cascade clears previous percentage");EQ(ypos("calc"),9,"unsupported calc inset preserves prior cascaded length without fabricated value");
 page("<style>body{margin:0}.box{position:fixed;left:10px;right:30px;top:20px;bottom:40px;width:100px;height:20px;margin:auto}#overflow{width:500px;height:400px}#one{margin:7px 7px 7px auto}#max{width:auto;max-width:100px}#rtl{direction:rtl}</style><div id='center' class='box'></div><div id='overflow' class='box'></div><div id='one' class='box'></div><div id='max' class='box'></div>",400);
 EQ(xpos("center"),140,"both horizontal auto margins share positive free space");EQ(ypos("center"),130,"both vertical auto margins share positive free space");EQ(xpos("overflow"),10,"negative horizontal free space goes to LTR end margin");EQ(ypos("overflow"),-60,"negative vertical free space is split equally");EQ(xpos("one"),263,"single auto margin absorbs all remaining width");EQ(xpos("max"),140,"max width is applied before auto margin distribution");
 page("<style>html{direction:rtl}body{margin:0}#a{position:fixed;left:10px;right:30px;width:500px;height:20px;margin:0 auto;direction:ltr}#b{position:fixed;left:10px;right:30px;width:100px;height:20px;direction:ltr}</style><div id='a'></div><div id='b'></div>",400);EQ(xpos("a"),-130,"RTL containing block puts negative free space in left auto margin");EQ(xpos("b"),270,"RTL overconstraint ignores left inset even with LTR child");
 page("<style>body{margin:0}#a{position:fixed;left:10%;right:20%;top:10%;bottom:20%}#a>div{height:500px}</style><div id='a'><div></div></div>",400);EQ(width("a"),280,"opposing percent insets solve auto width");EQ(height("a"),210,"opposing percent insets solve auto height despite overflowing child");
 page("<style>body{margin:0}#cb{height:200px}#a{position:relative;left:10%;top:25%;height:20px}#next{height:10px}</style><div id='cb'><div id='a'></div><div id='next'></div></div>",400);EQ(xpos("a"),40,"relative percent uses normal containing width");EQ(ypos("a"),50,"relative percent uses definite normal containing height");EQ(ypos("next"),20,"relative offset does not move following flow");
 page("<style>body{margin:0}#a{position:relative;top:25%;height:20px}#b{position:fixed;top:25%;inset-block-start:8px;width:20px;height:20px}</style><div><div id='a'></div></div><div id='b'></div>",400);EQ(ypos("a"),0,"relative percentage against auto height stays auto");EQ(ypos("b"),8,"logical pixel inset clears earlier physical percentage");
 printf("positioned-insets: %d checks, %d failures\n",checks,fails);return fails?1:0;
}
