/* PBKDF2 (c/crypto/kdf/pbkdf2.c) and the password-record format on top of it.
 *
 * VECTOR SOURCES, and one honest note about RFC 6070.
 * ---------------------------------------------------
 * RFC 6070 is the canonical PBKDF2 vector set and it is PBKDF2-HMAC-**SHA-1**
 * only. There is no SHA-1 in this tree and there is not going to be, so those
 * vectors cannot be run here -- quoting them would be quoting numbers this code
 * can never produce. The published SHA-256 equivalents are:
 *
 *   RFC 7914 section 11 -- two IETF-published PBKDF2-HMAC-SHA256 vectors
 *                          (c=1 and c=80000, dkLen=64). Compiled in below.
 *   openssl             -- `openssl kdf -kdfopt ...` over random inputs,
 *                          generated by tests/unit/pbkdf2_gen.sh. Covers
 *                          SHA-384, which has no published vector at all, and
 *                          the dkLen boundaries (hlen-1, hlen, hlen+1).
 *
 * Plus the rejections and the record round trip. */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include "crypto.h"

static int checks, failed;
static void ok(int cond, const char *what)
{
    checks++;
    if (cond) printf("ok   %s\n", what);
    else { printf("FAIL %s\n", what); failed++; }
}

static int hexval(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}
static int unhex(uint8_t *out, int max, const char *h)
{
    int n = 0;
    while (h[0] && h[1]) {
        int a = hexval(h[0]), b = hexval(h[1]);
        if (a < 0 || b < 0) return -1;
        if (n >= max) return -1;
        out[n++] = (uint8_t)((a << 4) | b);
        h += 2;
    }
    return h[0] ? -1 : n;
}

/* ---- RFC 7914 section 11: PBKDF2-HMAC-SHA256 ------------------------------ */
struct pbvec { const char *name, *pw, *salt; uint32_t c; int dklen; const char *dk; };
static const struct pbvec RFC7914[] = {
{ "RFC7914 s11 #1 (passwd/salt, c=1, dkLen=64)", "passwd", "salt", 1, 64,
  "55ac046e56e3089fec1691c22544b605f94185216dde0465e68b9d57c20dacbc"
  "49ca9cccf179b64599166 4b39d77ef317c71b845b1e30bd509112041d3a19783" },
{ "RFC7914 s11 #2 (Password/NaCl, c=80000, dkLen=64)", "Password", "NaCl", 80000, 64,
  "4ddcd8f60b98be21830cee5ef22701f9641a4418d04c0414aeff08876b34ab56"
  "a1d425a1225833549adb841b51c9b3176a272bdebba1d078478f62b397f33c8d" },
};

/* ---- openssl-generated: hlen pw_hex salt_hex iters dklen dk_hex ----------- */
static void run_openssl_file(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) { ok(0, "opening the openssl vector file"); return; }
    char line[4096];
    int n = 0;
    while (fgets(line, sizeof line, f)) {
        int hlen, iters, dklen;
        char pwh[512], salth[512], dkh[512];
        if (sscanf(line, "%d %511s %511s %d %d %511s",
                   &hlen, pwh, salth, &iters, &dklen, dkh) != 6) continue;
        uint8_t pw[256], salt[256], want[256], got[256];
        int pl = unhex(pw, sizeof pw, pwh);
        int sl = unhex(salt, sizeof salt, salth);
        int wl = unhex(want, sizeof want, dkh);
        if (pl < 0 || sl < 0 || wl != dklen || dklen > (int)sizeof got) continue;
        pbkdf2(hlen, pw, pl, salt, sl, (uint32_t)iters, got, dklen);
        char what[128];
        snprintf(what, sizeof what, "openssl case %d (hlen=%d c=%d dkLen=%d)", n, hlen, iters, dklen);
        ok(memcmp(got, want, (size_t)dklen) == 0, what);
        n++;
    }
    fclose(f);
    ok(n >= 8, "openssl generated at least 8 pbkdf2 cases");
}

/* deterministic salt source for the record tests */
static uint64_t frs = 0xfeedfacecafebeefULL;
static void fakerand(uint8_t *b, int n)
{ for (int i=0;i<n;i++){ frs^=frs<<13; frs^=frs>>7; frs^=frs<<17; b[i]=(uint8_t)frs; } }

int main(int argc, char **argv)
{
    for (unsigned v = 0; v < sizeof RFC7914 / sizeof RFC7914[0]; v++) {
        const struct pbvec *t = &RFC7914[v];
        uint8_t want[128], got[128];
        /* strip spaces the RFC's wrapping puts in the hex */
        char clean[512]; int cn = 0;
        for (const char *p = t->dk; *p; p++) if (*p != ' ') clean[cn++] = *p;
        clean[cn] = 0;
        int wl = unhex(want, sizeof want, clean);
        if (wl != t->dklen) { ok(0, t->name); continue; }
        pbkdf2(32, (const uint8_t *)t->pw, (int)strlen(t->pw),
               (const uint8_t *)t->salt, (int)strlen(t->salt), t->c, got, t->dklen);
        ok(memcmp(got, want, (size_t)t->dklen) == 0, t->name);
    }

    /* --- the rejections: a KDF that ignores a parameter is the bug ---------- */
    {
        uint8_t a[32], b[32];
        const uint8_t pw[] = "password", s1[] = "saltsalt", s2[] = "saltsalu";
        pbkdf2(32, pw, 8, s1, 8, 100, a, 32);
        pbkdf2(32, pw, 8, s2, 8, 100, b, 32);
        ok(memcmp(a, b, 32) != 0, "REJECT: a one-byte salt change changes the key");
        pbkdf2(32, pw, 8, s1, 8, 101, b, 32);
        ok(memcmp(a, b, 32) != 0, "REJECT: one more iteration changes the key");
        pbkdf2(48, pw, 8, s1, 8, 100, b, 32);
        ok(memcmp(a, b, 32) != 0, "REJECT: a different PRF changes the key");
        const uint8_t pw2[] = "passworE";
        pbkdf2(32, pw2, 8, s1, 8, 100, b, 32);
        ok(memcmp(a, b, 32) != 0, "REJECT: a one-byte password change changes the key");

        /* dkLen straddling the hash length: block 2 must really be block 2 */
        uint8_t big[96], first[32];
        pbkdf2(32, pw, 8, s1, 8, 100, big, 96);
        pbkdf2(32, pw, 8, s1, 8, 100, first, 32);
        ok(memcmp(big, first, 32) == 0, "dkLen>hlen: the first block is unchanged");
        ok(memcmp(big + 32, big, 32) != 0, "dkLen>hlen: block 2 differs from block 1");
        ok(memcmp(big + 64, big + 32, 32) != 0, "dkLen>hlen: block 3 differs from block 2");

        /* refusals: the function must write nothing rather than something wrong */
        uint8_t canary[32]; memset(canary, 0xA5, 32);
        pbkdf2(31, pw, 8, s1, 8, 100, canary, 32);
        int untouched = 1; for (int i=0;i<32;i++) if (canary[i] != 0xA5) untouched = 0;
        ok(untouched, "REJECT: an unsupported PRF length writes nothing");
        pbkdf2(32, pw, 8, s1, 8, 0, canary, 32);
        untouched = 1; for (int i=0;i<32;i++) if (canary[i] != 0xA5) untouched = 0;
        ok(untouched, "REJECT: iters == 0 writes nothing");
    }

    /* --- the account record ------------------------------------------------ */
    {
        char rec[256], rec2[256];
        int n = pwhash_make(rec, sizeof rec, "correct horse battery staple", 4096, fakerand);
        ok(n > 0 && n < (int)sizeof rec, "pwhash_make produced a record");
        rec[n] = 0;
        printf("     record: %s\n", rec);
        ok(pwhash_check(rec, "correct horse battery staple") == 1, "the right password checks out");
        ok(pwhash_check(rec, "correct horse battery stapl") == 0, "REJECT: truncated password");
        ok(pwhash_check(rec, "Correct horse battery staple") == 0, "REJECT: wrong case");
        ok(pwhash_check(rec, "") == 0, "REJECT: empty password");

        int n2 = pwhash_make(rec2, sizeof rec2, "correct horse battery staple", 4096, fakerand);
        rec2[n2] = 0;
        ok(strcmp(rec, rec2) != 0, "the same password twice gives different records (salt)");
        ok(pwhash_check(rec2, "correct horse battery staple") == 1, "the second record also checks out");

        /* the iteration count really is honoured, not decoration */
        char slow[256];
        int ns = pwhash_make(slow, sizeof slow, "p", 8192, fakerand); slow[ns] = 0;
        ok(pwhash_check(slow, "p") == 1, "a record with a different cost still checks out");

        /* tampering with the record */
        char bad[256];
        strcpy(bad, rec); bad[strlen(bad)-1] ^= 1;
        /* flipping a base64 char may or may not change the decoded bytes; flip
         * a whole character to a different one that is certain to. */
        bad[strlen(bad)-1] = (rec[strlen(rec)-1] == 'A') ? 'B' : 'A';
        ok(pwhash_check(bad, "correct horse battery staple") == 0,
           "REJECT: record with a tampered digest");
        strcpy(bad, rec); bad[1] = 'X';
        ok(pwhash_check(bad, "correct horse battery staple") == 0,
           "REJECT: record with a tampered prefix");
        ok(pwhash_check("$argon2id$v=19$m=65536,t=3,p=4$c2FsdA$aGFzaA", "x") == 0,
           "REJECT: a record naming an algorithm we do not implement");
        ok(pwhash_check("$pbkdf2-sha256$$c2FsdA$aGFzaA", "x") == 0,
           "REJECT: record with no iteration count");
        ok(pwhash_check("$pbkdf2-sha256$4096$c2FsdA", "x") == 0,
           "REJECT: record with no digest field");
        ok(pwhash_check("", "x") == 0, "REJECT: empty record");
        ok(pwhash_check(rec, NULL) == 0 && pwhash_check(NULL, "x") == 0,
           "REJECT: NULL arguments");

        /* the record's own iteration count must be what verification uses: a
         * record whose count is rewritten must stop verifying. */
        char re[256]; strcpy(re, rec);
        char *dollar = strchr(re + 1, '$');            /* end of "pbkdf2-sha256" */
        ok(dollar != NULL, "record is shaped as expected");
        if (dollar) {
            /* "4096" -> "4097" */
            char *it = dollar + 1;
            while (*it && *it != '$') it++;
            it--;
            *it = (char)(*it == '6' ? '7' : '6');
            ok(pwhash_check(re, "correct horse battery staple") == 0,
               "REJECT: record whose iteration count was rewritten");
        }
    }

    if (argc > 1) run_openssl_file(argv[1]);
    else printf("(no openssl vector file given -- RFC 7914 vectors only)\n");

    printf("\n%d checks, %d failed\n", checks, failed);
    if (!failed) printf("PWHASH ALL PASS\n");
    return failed ? 1 : 0;
}
