/* secp256k1: SEC 2 domain-parameter pinning + a Wycheproof known-answer
 * differential + a round-trip sanity check. No official CAVP vectors exist
 * for this curve (see secp256k1.h and gen_secp256k1_vectors.py) -- Wycheproof
 * is what stands in for one.
 *
 * THREE INDEPENDENT CHECKS, each catching a different bug shape:
 *
 *   1. DOMAIN PARAMETERS, pinned against SEC 2 v2.0 2.4.1 directly (not
 *      Wycheproof, which never states p/n/G explicitly): G must be on the
 *      curve, 1*G must equal G exactly, 2*G must equal the well-known value
 *      every secp256k1 implementation publishes. This is what would have
 *      caught the transcription bug this file's own history has: an earlier
 *      draft of secp256k1.c had a 2-hex-digit-short `p` (a typo, not a
 *      reasoning error), and every check below this one would have stayed
 *      GREEN with it -- Wycheproof's public keys are on secp256k1's real
 *      curve, so verifying a real signature against a truncated p mostly
 *      just fails "invalid" tests for the wrong reason, which reads as
 *      correct. Only pinning G itself catches a wrong modulus directly.
 *
 *   2. WYCHEPROOF, read on stdin from tests/unit/secp256k1_wycheproof.inc
 *      (generated by gen_secp256k1_vectors.py from the upstream JSON --
 *      run that script and diff before suspecting this file). Exercises
 *      secp256k1_verify_der end to end: DER parsing (many cases exist only
 *      to probe BER/non-minimal encodings), sha256(), and the verify math,
 *      against 476 cases whose expected result Google's crypto team
 *      determined, not us.
 *
 *   3. ROUND TRIP, our own keygen+sign+verify+tamper. This is explicitly
 *      NOT an oracle -- secp256k1.h's own header explains why a wrong-curve
 *      bug can still pass a round trip in general (this file's
 *      point_on_curve check happens to catch the specific bug that was
 *      found here, but that is not a property the round trip itself
 *      provides). It is here for the properties Wycheproof, being verify-
 *      only, cannot see at all: that secp256k1_sign and secp256k1_keygen
 *      exist, produce range-valid output, and that a tampered hash or
 *      pubkey is rejected.
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include "crypto.h"
#include "secp256k1.h"

static int pass, fail;
static void check(const char *what, int ok)
{
    if (ok) pass++;
    else { fail++; printf("FAIL %s\n", what); }
}

static int hex2bin(const char *h, uint8_t *o, int max)
{
    int n = 0;
    while (h[2*n] && h[2*n+1] && n < max) {
        int hi = h[2*n], lo = h[2*n+1];
        #define HX(c) ((c) <= '9' ? (c)-'0' : ((c)|32)-'a'+10)
        o[n] = (uint8_t)((HX(hi) << 4) | HX(lo));
        #undef HX
        n++;
    }
    return n;
}
static void hexout(const uint8_t *b, int n) { for (int i = 0; i < n; i++) printf("%02x", b[i]); }

/* -------------------------------------------- 1. domain-parameter pinning */

static void test_domain_params(void)
{
    /* SEC 2 v2.0 2.4.1: G itself. priv=1 must produce exactly G. */
    uint8_t one[32]; memset(one, 0, 32); one[31] = 1;
    uint8_t pub[65];
    check("keygen(1) succeeds", secp256k1_keygen(one, 0, pub) == 0);
    uint8_t want_g[65];
    hex2bin("04"
            "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            "483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8",
            want_g, 65);
    check("keygen(1) == G (SEC 2 2.4.1)", memcmp(pub, want_g, 65) == 0);

    /* 2*G, the second most-published constant for this curve -- catches a
     * doubling bug that happens to fix up 1*G (e.g. only the addition path
     * is exercised by priv=1's all-zero-then-one bit pattern) but not
     * doubling itself. */
    uint8_t two[32]; memset(two, 0, 32); two[31] = 2;
    uint8_t pub2[65];
    check("keygen(2) succeeds", secp256k1_keygen(two, 0, pub2) == 0);
    uint8_t want_2g[65];
    hex2bin("04"
            "c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5"
            "1ae168fea63dc339a3c58419466ceaeef7f632653266d0e1236431a950cfe52a",
            want_2g, 65);
    check("keygen(2) == 2G", memcmp(pub2, want_2g, 65) == 0);

    /* priv == n (the group order) is out of range and must be refused --
     * this is the r/s-vs-n distinction secp256k1.h's "fourth trap" warns
     * about: n and p are close but not equal, so this only catches a
     * mixed-up modulus if the two differ in a place this specific value
     * exercises, which is why it is a supplement to the vectors, not a
     * replacement. */
    uint8_t n_bytes[32];
    hex2bin("fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141", n_bytes, 32);
    uint8_t pubn[65];
    check("keygen(n) rejected (out of range)", secp256k1_keygen(n_bytes, 0, pubn) == -1);
}

/* -------------------------------------------------- 2. Wycheproof vectors */

/* Wycheproof's IntegerOverflow cases (RangeCheck / IntegerOverflow flags)
 * carry a DER length field that CLAIMS thousands of bytes -- the point of
 * the case is that a parser must reject the claim, not that a real
 * signature is ever this long. The longest `sig` field in the vector file
 * is 8344 hex chars (4172 bytes); these buffers are sized with headroom
 * above that rather than trimmed to fit exactly, so a future Wycheproof
 * revision with a slightly larger adversarial case does not silently
 * truncate into a "malformed vector line" false FAIL. */
static void run_wycheproof(void)
{
    static char line[16384];
    int n = 0, wpass = 0, wfail = 0;
    while (fgets(line, sizeof line, stdin)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        int tcid, want;
        static char wx[128], wy[128], msg[2048], sig[9000];
        if (sscanf(line, "%d %d %127s %127s %2047s %8999s", &tcid, &want, wx, wy, msg, sig) != 6) {
            printf("FAIL malformed vector line (len %zu): %.80s...\n", strlen(line), line); fail++; continue;
        }
        uint8_t pub[65]; pub[0] = 0x04;
        if (hex2bin(wx, pub+1, 32) != 32 || hex2bin(wy, pub+1+32, 32) != 32) {
            printf("FAIL tcId %d: bad wx/wy in vector file\n", tcid); fail++; continue;
        }
        static uint8_t msgbuf[1024]; int msglen = 0;
        if (strcmp(msg, "-") != 0) msglen = hex2bin(msg, msgbuf, sizeof msgbuf);
        uint8_t hash[32]; sha256(msgbuf, (size_t)msglen, hash);
        static uint8_t sigbuf[4500]; int siglen = 0;
        if (strcmp(sig, "-") != 0) siglen = hex2bin(sig, sigbuf, sizeof sigbuf);

        int got = secp256k1_verify_der(pub, sigbuf, siglen, hash, 32);
        n++;
        if ((got != 0) == (want != 0)) wpass++;
        else {
            wfail++;
            printf("FAIL tcId %d: got %s want %s\n", tcid, got ? "valid" : "invalid", want ? "valid" : "invalid");
        }
    }
    printf("wycheproof secp256k1/SHA-256: %d/%d agree\n", wpass, n);
    pass += wpass; fail += wfail;
    check("wycheproof ran at least 400 cases (sanity on the vector file itself)", n >= 400);
}

/* --------------------------------------------------------- 3. round trip */

static void test_round_trip(void)
{
    uint8_t priv[32];
    for (int i = 0; i < 32; i++) priv[i] = (uint8_t)(i * 37 + 11);
    uint8_t pub[65];
    check("round-trip keygen", secp256k1_keygen(priv, 0xa5a5a5a5u, pub) == 0);
    check("round-trip pubkey on curve (04 prefix)", pub[0] == 0x04);

    uint8_t hash[32];
    for (int i = 0; i < 32; i++) hash[i] = (uint8_t)(i * 19 + 7);
    uint8_t k[32];
    for (int i = 0; i < 32; i++) k[i] = (uint8_t)(251 - i * 3);
    uint8_t sig[64];
    check("round-trip sign", secp256k1_sign(priv, hash, 32, k, 0x5a5a5a5au, sig) == 0);
    check("round-trip verify", secp256k1_verify(pub, sig, hash, 32) == 1);

    uint8_t bad_hash[32]; memcpy(bad_hash, hash, 32); bad_hash[0] ^= 0x01;
    check("round-trip rejects tampered hash", secp256k1_verify(pub, sig, bad_hash, 32) == 0);

    uint8_t bad_pub[65]; memcpy(bad_pub, pub, 65); bad_pub[1] ^= 0x01;
    check("round-trip rejects tampered pubkey", secp256k1_verify(bad_pub, sig, hash, 32) == 0);

    uint8_t bad_sig[64]; memcpy(bad_sig, sig, 64); bad_sig[63] ^= 0x01;
    check("round-trip rejects tampered signature", secp256k1_verify(pub, bad_sig, hash, 32) == 0);

    /* k out of range must be refused, not silently reduced -- a silently
     * reduced k is a k the caller did not choose, which is exactly the
     * repeated/predictable-k failure mode secp256k1.h warns about. */
    uint8_t zero_k[32]; memset(zero_k, 0, 32);
    check("sign rejects k=0", secp256k1_sign(priv, hash, 32, zero_k, 0, sig) == -1);
    uint8_t n_bytes[32];
    hex2bin("fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141", n_bytes, 32);
    check("sign rejects k=n", secp256k1_sign(priv, hash, 32, n_bytes, 0, sig) == -1);
    check("keygen rejects priv=0", secp256k1_keygen(zero_k, 0, pub) == -1);
}

int main(void)
{
    printf("== secp256k1 domain-parameter pinning (SEC 2 v2.0 2.4.1) ==\n");
    test_domain_params();
    printf("== secp256k1 vs Wycheproof (ecdsa_secp256k1_sha256_test.json) ==\n");
    run_wycheproof();
    printf("== secp256k1 round trip (keygen/sign/verify, our own oracle) ==\n");
    test_round_trip();

    printf("\n%d checks, %d failed -- %s\n", pass + fail, fail, fail ? "FAILED" : "ALL PASS");
    (void)hexout;
    return fail ? 1 : 0;
}
