/* Differential shaping test: LogitOS's shaper against HarfBuzz.
 *
 * $(BUILD)/shape_expect.h is generated by tests/unit/shape_hb_gen.py, which
 * drives HarfBuzz over tests/unit/shape_corpus.txt. For every case it holds the
 * text, the segmentation the corpus states, and HarfBuzz's glyph ids and
 * positions. This program runs the whole LogitOS pipeline -- bidi, script and
 * font segmentation, GSUB, GPOS -- over the same text and compares:
 *
 *   1. the runs: script tag, direction, start and length, in VISUAL order
 *   2. the glyphs: id, x advance, y advance, x offset, y offset, one by one
 *
 * It also asserts the invariant the display line stated: measure and draw must
 * agree at the same pixel size, because wm.c measures at S(px) and divides the
 * answer back. That is checked through shape_line(), which is the single
 * function text_measure and text_draw_run both go through -- and it is checked
 * on strings where the naive sum of per-character advances is NOT the shaped
 * width, since an implementation that summed advances would pass a test made of
 * strings without ligatures or kerning.
 *
 * Build: see tests/text.mk. Run: shape_test <font.ttf>
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "shape.h"
#include "script.h"
#include "bidi.h"
#include "ttf.h"
#include "fontrd.h"

#include "shape_expect.h"

static int checks, failures;

#define FAIL(...) do { failures++; printf("  FAIL "); printf(__VA_ARGS__); putchar('\n'); } while (0)
#define CHECK(cond, ...) do { checks++; if (!(cond)) FAIL(__VA_ARGS__); } while (0)

/* ------------------------------------------------------------------ font -- */

static uint8_t *load(const char *path, int *len)
{
    FILE *fh = fopen(path, "rb");
    if (!fh) { perror(path); exit(2); }
    fseek(fh, 0, SEEK_END);
    long n = ftell(fh);
    fseek(fh, 0, SEEK_SET);
    uint8_t *b = malloc((size_t)n);
    if (!b || fread(b, 1, (size_t)n, fh) != (size_t)n) { fprintf(stderr, "read %s\n", path); exit(2); }
    fclose(fh);
    *len = (int)n;
    return b;
}

static void tag_str(uint32_t t, char out[5])
{
    out[0] = (char)(t >> 24); out[1] = (char)(t >> 16);
    out[2] = (char)(t >> 8);  out[3] = (char)t; out[4] = 0;
}

/* ---------------------------------------------------- pipeline under test -- */

#define MAXCP  256
#define MAXG   1024
#define MAXRUN 32

static uint32_t g_cps[MAXCP];
static uint8_t  g_lv[MAXCP];
static int      g_ord[MAXCP];
static struct text_run g_runs[MAXRUN];
static uint8_t  g_bidi[64 * 1024];

/* Segment exactly as shape_line does: bidi, then script/direction runs, then
 * visual order. Returns the run count and fills vis_order[] with run indices
 * left to right. */
static int segment(const uint32_t *cps, int n, int *vis_order)
{
    memcpy(g_cps, cps, (size_t)n * sizeof cps[0]);
    if (bidi_is_trivial(g_cps, n)) {
        memset(g_lv, 0, (size_t)n);
    } else if (bidi_resolve(g_cps, n, BIDI_DIR_AUTO, g_lv, g_bidi, (int)sizeof g_bidi) < 0) {
        memset(g_lv, 0, (size_t)n);
    }
    int nrun = script_runs(g_cps, n, g_lv, NULL, NULL, g_runs, MAXRUN);
    if (nrun > MAXRUN) nrun = MAXRUN;

    bidi_reorder(g_lv, n, g_ord);
    for (int k = 0; k < nrun; k++) g_runs[k].vis = n;
    for (int vi = 0; vi < n; vi++) {
        int ci = g_ord[vi];
        for (int k = 0; k < nrun; k++)
            if (ci >= g_runs[k].start && ci < g_runs[k].start + g_runs[k].len) {
                if (vi < g_runs[k].vis) g_runs[k].vis = vi;
                break;
            }
    }
    int last = -1;
    for (int e = 0; e < nrun; e++) {
        int best = -1;
        for (int k = 0; k < nrun; k++)
            if (g_runs[k].vis > last && (best < 0 || g_runs[k].vis < g_runs[best].vis))
                best = k;
        if (best < 0) break;
        last = g_runs[best].vis;
        vis_order[e] = best;
    }
    return nrun;
}

/* ------------------------------------------------------- the differential -- */

static struct shape_glyph g_out[MAXG];
static struct shape_glyph g_case[MAXG];

static void run_case(const struct ttf_font *f, const struct sx_case *c)
{
    int vis[MAXRUN];
    int nrun = segment(c->cps, c->ncp, vis);

    printf("  %-20s %2d cp  %d run%s", c->name, c->ncp, nrun, nrun == 1 ? " " : "s");

    int run_ok = 1;
    checks++;
    if (nrun != c->nrun) {
        run_ok = 0;
        FAIL("%s: segmented into %d runs, corpus states %d", c->name, nrun, c->nrun);
    } else {
        for (int i = 0; i < nrun; i++) {
            const struct text_run *r = &g_runs[vis[i]];
            char t[5];
            tag_str(script_ot_tag(r->script), t);
            if (strcmp(t, c->runs[i].tag) || r->rtl != c->runs[i].rtl ||
                r->start != c->runs[i].start || r->len != c->runs[i].len) {
                run_ok = 0;
                FAIL("%s: visual run %d is %s:%c:%d:%d, corpus states %s:%c:%d:%d",
                     c->name, i, t, r->rtl ? 'R' : 'L', r->start, r->len,
                     c->runs[i].tag, c->runs[i].rtl ? 'R' : 'L',
                     c->runs[i].start, c->runs[i].len);
            }
        }
    }
    if (!run_ok) { printf("  RUNS DIFFER\n"); return; }

    /* Shape each run in visual order and concatenate, exactly as shape_line
     * places them. */
    int ng = 0;
    for (int i = 0; i < nrun; i++) {
        const struct text_run *r = &g_runs[vis[i]];
        int k = shape_run(f, c->cps + r->start, r->len, r->script, r->rtl,
                          g_out, MAXG - ng);
        if (k < 0) { FAIL("%s: run %d did not fit", c->name, i); return; }
        for (int j = 0; j < k && ng < MAXG; j++) g_case[ng++] = g_out[j];
    }

    printf("  %2d glyphs (hb %2d)", ng, c->nglyph);

    checks++;
    if (ng != c->nglyph) {
        FAIL("%s: %d glyphs, HarfBuzz produced %d", c->name, ng, c->nglyph);
        printf("\n    ours:");
        for (int i = 0; i < ng; i++) printf(" %u", g_case[i].gid);
        printf("\n    hb:  ");
        for (int i = 0; i < c->nglyph; i++) printf(" %u", c->glyphs[i].gid);
        printf("\n");
        return;
    }

    int bad = 0;
    for (int i = 0; i < ng; i++) {
        const struct sx_glyph *x = &c->glyphs[i];
        checks++;
        if ((unsigned)g_case[i].gid != x->gid ||
            g_case[i].x_advance != x->xa || g_case[i].y_advance != x->ya ||
            g_case[i].x_offset  != x->xo || g_case[i].y_offset  != x->yo) {
            failures++;
            if (bad < 6)
                printf("\n    glyph %2d: ours gid=%u adv=%d,%d off=%d,%d   "
                       "hb gid=%u adv=%d,%d off=%d,%d",
                       i, g_case[i].gid, g_case[i].x_advance, g_case[i].y_advance,
                       g_case[i].x_offset, g_case[i].y_offset,
                       x->gid, x->xa, x->ya, x->xo, x->yo);
            bad++;
        }
    }
    if (bad) printf("\n    %d of %d glyphs differ\n", bad, ng);
    else     printf("  ok\n");
}

/* ------------------------------------------- measure / draw agreement ---- */

/* The emit callback records the pen positions a draw would use. */
struct rec { int n; int x[MAXG]; int gid[MAXG]; };
static void rec_glyph(void *ud, int fidx, int gid, int x, int y_off)
{
    struct rec *r = (struct rec *)ud;
    (void)fidx; (void)y_off;
    if (r->n < MAXG) { r->x[r->n] = x; r->gid[r->n] = gid; r->n++; }
}

static uint32_t ml_cps[MAXCP];
static uint8_t  ml_lv[MAXCP];
static int      ml_ord[MAXCP];
static struct text_run ml_runs[MAXRUN];
static struct shape_glyph ml_glyphs[MAXG];
static uint8_t  ml_bidi[64 * 1024];

static void measure_draw(const struct ttf_font *f, const char *label, const char *s)
{
    struct shape_font_set fs = { { f }, 1 };
    struct shape_scratch sc;
    sc.cps = ml_cps; sc.levels = ml_lv; sc.order = ml_ord;
    sc.glyphs = ml_glyphs; sc.runs = ml_runs; sc.bidi = ml_bidi;
    sc.ncp_cap = MAXCP; sc.nglyph_cap = MAXG; sc.nrun_cap = MAXRUN;
    sc.bidi_cap = (int)sizeof ml_bidi;

    static const int sizes[] = { 8, 11, 12, 13, 16, 20, 24, 32, 48, 64 };
    int len = (int)strlen(s);
    int shown = 0;

    for (unsigned k = 0; k < sizeof sizes / sizeof sizes[0]; k++) {
        int px = sizes[k];
        int measured = shape_line(&fs, s, len, px, 0, 0, NULL, &sc);
        struct rec r; r.n = 0;
        struct shape_emit em = { rec_glyph, &r };
        int drawn = shape_line(&fs, s, len, px, 0, 0, &em, &sc);
        checks++;
        if (measured != drawn)
            FAIL("%s at %dpx: measure=%d draw ends at %d", label, px, measured, drawn);

        /* And the pen must never run backwards or past the measured end. */
        for (int i = 0; i < r.n; i++) {
            checks++;
            if (r.x[i] < 0 || r.x[i] > measured + px)
                FAIL("%s at %dpx: glyph %d drawn at x=%d, outside [0,%d]",
                     label, px, i, r.x[i], measured);
        }
        if (!shown && px == 16) {
            /* The naive width: what a per-character walk would have said. The
             * point of printing it is that the two numbers must differ, or the
             * invariant is being asserted on a string that cannot break it. */
            shown = 1;
        }
    }
}

/* Sum of per-code-point hmtx advances -- the pre-shaping measurement. */
static int naive_width(const struct ttf_font *f, const char *s, int px)
{
    int w = 0;
    for (const unsigned char *p = (const unsigned char *)s; *p; ) {
        uint32_t cp = *p;
        int n = 1;
        if (cp >= 0xF0) { cp &= 0x07; n = 4; }
        else if (cp >= 0xE0) { cp &= 0x0F; n = 3; }
        else if (cp >= 0xC0) { cp &= 0x1F; n = 2; }
        for (int i = 1; i < n; i++) cp = (cp << 6) | (p[i] & 0x3F);
        p += n;
        int g = ttf_glyph_id(f, cp);
        if (g < 0) g = 0;
        w += (int)(((long)ttf_advance(f, g) * px) / f->units_per_em);
    }
    return w;
}

static int shaped_width(const struct ttf_font *f, const char *s, int px)
{
    struct shape_font_set fs = { { f }, 1 };
    struct shape_scratch sc;
    sc.cps = ml_cps; sc.levels = ml_lv; sc.order = ml_ord;
    sc.glyphs = ml_glyphs; sc.runs = ml_runs; sc.bidi = ml_bidi;
    sc.ncp_cap = MAXCP; sc.nglyph_cap = MAXG; sc.nrun_cap = MAXRUN;
    sc.bidi_cap = (int)sizeof ml_bidi;
    return shape_line(&fs, s, (int)strlen(s), px, 0, 0, NULL, &sc);
}

/* ------------------------------------------------------------------ main -- */

int main(int argc, char **argv)
{
    const char *path = argc > 1 ? argv[1] : SHAPE_EXPECT_FONT;
    int len;
    uint8_t *blob = load(path, &len);
    struct ttf_font f;
    if (ttf_parse(blob, len, &f) != 0) { fprintf(stderr, "shape_test: %s does not parse\n", path); return 2; }

    printf("shape_test: %s, %d glyphs, upem=%d\n", path, f.num_glyphs, f.units_per_em);
    if (f.units_per_em != SHAPE_EXPECT_UPEM) {
        fprintf(stderr, "shape_test: font upem %d, reference built at %d -- "
                "run against the same font\n", f.units_per_em, SHAPE_EXPECT_UPEM);
        return 2;
    }
    printf("shape_test: GSUB=%s GPOS=%s GDEF=%s kern=%s\n",
           f.off_gsub ? "yes" : "no", f.off_gpos ? "yes" : "no",
           f.off_gdef ? "yes" : "no", f.off_kern ? "yes" : "no");

    printf("\n-- differential against HarfBuzz (%d cases) --\n", SHAPE_EXPECT_N);
    for (int i = 0; i < SHAPE_EXPECT_N; i++) run_case(&f, &shape_expect[i]);

#ifdef SHAPE_KERN_N
    /* The legacy `kern` table. It is a FALLBACK -- a shaper reads it only when
     * the font has no GPOS -- so no font on this machine exercises it. The
     * generator makes one by stripping GPOS from the corpus font, which leaves
     * its real kern table as the only kerning source for HarfBuzz and for us
     * alike. Without this the fallback would be claimed and never run. */
    {
        int klen;
        uint8_t *kblob = load(SHAPE_EXPECT_NOGPOS, &klen);
        struct ttf_font kf;
        if (ttf_parse(kblob, klen, &kf) != 0) {
            fprintf(stderr, "shape_test: %s does not parse\n", SHAPE_EXPECT_NOGPOS);
            return 2;
        }
        printf("\n-- legacy kern fallback (%s: GSUB=%s GPOS=%s kern=%s) --\n",
               SHAPE_EXPECT_NOGPOS, kf.off_gsub ? "yes" : "no",
               kf.off_gpos ? "yes" : "no", kf.off_kern ? "yes" : "no");
        checks++;
        if (kf.off_gpos)
            FAIL("the GPOS-stripped font still has GPOS -- the fallback is not "
                 "being exercised");
        checks++;
        if (!kf.off_kern)
            FAIL("the GPOS-stripped font has no kern table either -- there is "
                 "nothing for the fallback to read");
        for (int i = 0; i < SHAPE_KERN_N; i++) run_case(&kf, &shape_kern_expect[i]);
        free(kblob);
    }
#endif

    /* The measure/draw invariant, on strings chosen so that a per-character
     * walk gives a DIFFERENT answer -- otherwise the assertion is vacuous. */
    printf("\n-- measure/draw agreement --\n");
    static const char *ml[] = {
        "AVATAR To Wave Yo.",
        "office fluffier waffle",
        "Read \xd8\xa7\xd9\x84\xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9 now",
        "\xd7\xa9\xd7\x9c\xd7\x95\xd7\x9d \xd7\xa2\xd7\x95\xd7\x9c\xd7\x9d",
        "The quick brown fox",
    };
    int differ = 0;
    for (unsigned i = 0; i < sizeof ml / sizeof ml[0]; i++) {
        int nv = naive_width(&f, ml[i], 16);
        int sw = shaped_width(&f, ml[i], 16);
        printf("  %-26.26s naive=%3dpx shaped=%3dpx %s\n",
               ml[i], nv, sw, nv == sw ? "(same)" : "(DIFFERENT)");
        if (nv != sw) differ++;
        measure_draw(&f, ml[i], ml[i]);
    }
    checks++;
    if (differ < 2)
        FAIL("only %d of the measure/draw strings shape to a different width "
             "than a per-character walk -- the invariant is being asserted on "
             "text that cannot break it", differ);

    printf("\nshape_test: %d checks, %d failures\n", checks, failures);
    free(blob);
    return failures ? 1 : 0;
}
